### ISSUE TITLE
Consolidate ComputeGeodesicDistanceToLandmark

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1004]
File: Libs/Mesh/ComputeGeodesicDistanceToLandmark.cxx
After consolidation, add:

1. Python binding
2. MeshTest
3. shapeworksTest
4. PythonTest

**Comment by sheryjoe** [comment]
this tool should use libigl for geodesic computation.

**Comment by akenmorris** [comment]
Should we move this to 6.3?

**Comment by sheryjoe** [comment]
@archanasri how far are you on this issue?
