### ISSUE TITLE
Consolidate GenerateFidsFiles

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1010]
File: Libs/Mesh/GenerateFidsFiles.cxx
After consolidation, add:

1. Python binding
2. MeshTest
3. shapeworksTest
4. PythonTest

**Comment by sheryjoe** [comment]
See my comment on #1011

**Comment by cchriste** [comment]
We are currently working on #810. Are these executables used or can we remove them now?

**Comment by cchriste** [comment]
> We are currently working on #810. Are these executables used or can we remove them now?

Ah... I think I get it: we're adding the functionality these executables currently provide.

**Comment by cchriste** [comment]
@sheryjoe Can you confirm that the Fids executables are no longer needed? (#1010 #1011 #1020)

**Comment by sheryjoe** [comment]
Closing the issue. FIDs are computationally expensive and was originally implemented to convert meshes to accurate distance transforms for optimization. No longer needed now given that we can optimize particles directly on meshes.
