### ISSUE TITLE
Consolidate GenerateFidsFilesFromMeshes

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1011]
File: Libs/Mesh/GenerateFidsFilesFromMeshes.cxx
After consolidation, add:

1. Python binding
2. MeshTest
3. shapeworksTest
4. PythonTest

**Comment by sheryjoe** [comment]
@archanasri this is related to computing signed distance transforms from meshes. Fids is computationally expensive and users would need to have access to computational servers to process their data. Consolidating this becomes irrelevant if we can come up with a more efficient alternative. Also, fids is developed on top of trimesh2, which we are now replacing with vtk. I am moving this issue to backlog accordingly.

**Comment by cchriste** [comment]
Related to #810, which will hopefully consolidate FIDS altogether.

**Comment by cchriste** [comment]
@sheryjoe Can you confirm that the Fids executables are no longer needed? #1010 #1011 #1020

**Comment by sheryjoe** [comment]
Closing the issue. FIDs are computationally expensive and was originally implemented to convert meshes to accurate distance transforms for optimization. No longer needed now given that we can optimize particles directly on meshes.
