### ISSUE TITLE
Consolidate GenerateNormalFeaFiles

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1012]
File: Libs/Mesh/GenerateNormalFeaFiles.cxx
After consolidation, add:

1. Python binding
2. MeshTest
3. shapeworksTest
4. PythonTest

**Comment by sheryjoe** [comment]
@archanasri is this generating features as a scalar field on meshes? If this is the case, we can have a function in the mesh class to compute surface normals and use write-mesh to save the normals as feature scales on the mesh.

**Comment by sheryjoe** [comment]
@akenmorris @medakk when normals are used for correspondence, aren't the normals computed on the fly?

**Comment by medakk** [comment]
Normals(and their gradient) are computed at the start of `shapeworks optimize` at all points on the mesh/image. They are not read from a file

**Comment by archanasri** [comment]
This executable uses trimesh::orient then exactly does the same function as #1015 which is linearly interpolating a vector image.

**Comment by cchriste** [comment]
> Normals(and their gradient) are computed at the start of `shapeworks optimize` at all points on the mesh/image. They are not read from a file

We have a `generate_normal` branch that is doing exactly this for a mesh, so...
- [ ] call this new function at the beginning of optimize (presuming optimize even uses shapeworks, i.e., vtk, meshes)

**Comment by cchriste** [comment]
> This executable uses trimesh::orient then exactly does the same function as #1015 which is linearly interpolating a vector image.

`Mesh::generateNormals` uses the `vtkPolyDataNormals` filter to [re-]compute the normals for the vertices and cells of a mesh. 
It uses `AutoOrientNormalsOn()` which may more elegantly address the same issues as the heavy-handed `trimesh::orient`.
