### ISSUE TITLE
Consolidate GetFeatureVolume

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1013]
File: Libs/Mesh/GetFeatureVolume.cxx
After consolidation, add:

1. Python binding
2. MeshTest
3. shapeworksTest
4. PythonTest

**Comment by sheryjoe** [comment]
@akenmorris @medakk I don't think this tool is relevant anymore. This tool used to generate a volumetric image given a mesh with a scalar field as a feature for correspondence optimization, so the tool propagates the feature values (via interpolation) within a narrow band around the surface. As I recall, Praful (with the mesh-based general entropy ... class) removed that need for this conversion step by loading meshes with scalar fields (or features) and using mesh-based interpolation to probe feature values and the gradients at particle positions. Can you confirm this?

**Comment by medakk** [comment]
Regarding the mesh-based general entropy class using feature values, I've never seen a working example of this. I contacted Praful for an example use case demonstrating this but never heard back.
