### ISSUE TITLE
Consolidate GradientTesting

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1014]
File: Libs/Mesh/GradientTesting.cxx
After consolidation, add:

1. Python binding
2. MeshTest
3. shapeworksTest
4. PythonTest

**Comment by sheryjoe** [comment]
@archanasri What is this command doing? For the naming, it seems to be a debugging code.

**Comment by archanasri** [comment]
This executable uses a vtkGradientFilter to compute gradients and store the results in a mesh as field value.
