### ISSUE TITLE
Consolidate ProbeNormals

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1015]
File: Libs/Mesh/ProbeNormals.cxx
After consolidation, add:

1. Python binding
2. MeshTest
3. shapeworksTest
4. PythonTest

**Comment by cchriste** [comment]
Two parts: 
1. compute a vector field (vector image, which we don't have) from a scalar field (the Image class we already have).
2. interpolates that field for a set of points, just need a function to interpolate for one point (like #1005)

**Comment by archanasri** [comment]
This seems to be similar to #1012.

**Comment by akenmorris** [comment]
@sheryjoe, where is this used?
