### ISSUE TITLE
Consolidate ReconstructSamplesAlongPCAModes

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1018]
File: Libs/Mesh/ReconstructSamplesAlongPCAModes.cxx
After consolidation, add:

1. Python binding
2. ParticlesTest
3. PythonTest

**Comment by sheryjoe** [comment]
@archanasri  Similar comment to #1019 
One thing to consider here is the computation of PCA and movement along PCA modes, this command already implements it but I think we should consider using the particles statistics class implemented in the ParticleSystem (i.e., use the same code that Studio uses for animating PCA modes). This way, Studio and commandline (and python) produce reproducible results and we should be able to reduce sources for bugs  ... @akenmorris

**Comment by archanasri** [comment]
@sheryjoe Can we move this to 6.3? We can focus on consolidation of particle-based executables for the next release

**Comment by archanasri** [comment]
Relevant to #109
