### ISSUE TITLE
Consolidate ReconstructSurface

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1019]
File: Libs/Mesh/ReconstructSurface.cxx
After consolidation, add:

1. Python binding
2. ParticlesTest
3. PythonTest

**Comment by sheryjoe** [comment]
@archanasri This tool warp a template mesh given particles. We could have an option to either do the warping using @riddhishb warp or the current ITK-based warp.

**Comment by archanasri** [comment]
@sheryjoe Can we move this to 6.3? We can focus on consolidation of particle-based executables for the next release

**Comment by archanasri** [comment]
Relevent to #109
