### ISSUE TITLE
Consolidate RemoveFidsDTLeakage

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1020]
File: Libs/Mesh/RemoveFidsDTLeakage.cxx
After consolidation, add:

1. Python binding
2. MeshTest
3. shapeworksTest
4. PythonTest

**Comment by sheryjoe** [comment]
@archanasri Moving this to backlog till we decide if we need the compute fids command line (which is computationally expensive). A better and more accurate tool to compute signed distance transforms directly from meshes would be a better route here.

**Comment by cchriste** [comment]
Related to #810, which will hopefully consolidate FIDS altogether.

**Comment by sheryjoe** [comment]
Closing the issue. FIDs are computationally expensive and was originally implemented to convert meshes to accurate distance transforms for optimization. No longer needed now given that we can optimize particles directly on meshes.
