### ISSUE TITLE
Consolidate WriteFeatureGradientAsText

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1021]
File: Libs/Mesh/WriteFeatureGradientAsText.cxx
After consolidation, add:

1. Python binding
2. MeshTest
3. shapeworksTest
4. PythonTest

**Comment by sheryjoe** [comment]
we should use gradient computation from ligigl.

**Comment by archanasri** [comment]
> we should use gradient computation from ligigl.

This executable does not do any gradient computation.
