### ISSUE TITLE
Specify a target number of vertices in mesh-fix (formerly PreviewCmd) 

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1023]
As discussed in the SW-Ortho meeting on 2/17/2021, functionality for specifying a target number of faces should be included in the MeshFix toolbox. @sheryjoe

**Comment by sheryjoe** [comment]
@archanasri @akenmorris 
When integrating this into Studio, it would be nice to expose individual functionalities/steps (with their parameters) of the mesh fix (smooth, decimate, and fix winding) as users might want to enable/disable specific steps depending on the data.

**Comment by cchriste** [comment]
Frozen until re-meshing feature added to Studio, after which desired APIs will be noted here and/or in #938.

**Comment by sheryjoe** [comment]
mmgtools will replace PreviewCmd
