### ISSUE TITLE
GitHub Action for Windows runs low on disk space

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1024]
We're ending with only about 135MB free on the 14GB D: SSD.  I think there might be a slower C:\ that we can write some things to.  I tried installing Qt there but it didn't work.  Needs some more investigation.

I temporarily added a step to delete the bin directory at the end so that the cache actions can create the tarballs.  Otherwise we have no dependency cache and must rebuild the dependencies on each run.

**Comment by cchriste** [comment]
Is this still an issue?

**Comment by akenmorris** [comment]
No, I switched it to build the dependencies on the non-SSD drive.
