### ISSUE TITLE
Studio: Parameter ranges in Studio seem to be too constrained

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1031]
Based on parameters previously used for our hip models, the parameter ranges in Studio are too constraining. Additionally, I wonder if the inclusion of decimals on most parameters is non-intuitive for new users.

- Initial relative weighting - can this have three decimals? We have used 0.001 previously.
- Relative weighting - does this need a decimal point? I don't know that I've ever used <1
- Starting regularization - max is 99,999 while we have used 1e9 previously; does this need a decimal point?
- Normals strength - do you expect users to use decimal values or can this be integers?

**Comment by akenmorris** [comment]
> Initial relative weighting - can this have three decimals? We have used 0.001 previously.

Sure, we can set to three decimals

> Relative weighting - does this need a decimal point? I don't know that I've ever used <1

It's probably unlikely to need less than one, but 1.5, 2.5, etc may be reasonable

> Starting regularization - max is 99,999 while we have used 1e9 previously; does this need a decimal point?

Wow, that's huge

> Normals strength - do you expect users to use decimal values or can this be integers?

They might need to, it kind of needs to scale with the range of the data.

**Comment by sheryjoe** [comment]
Is this resolved? close issue?

**Comment by akenmorris** [comment]
Resolved in #1034
