### ISSUE TITLE
Ellipsoid tiny test no long works (on windows at least)

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1039]
Not sure about other platforms.

```
Traceback (most recent call last):
  File "RunUseCase.py", line 94, in <module>
    module.Run_Pipeline(args)
  File "C:\Users\amorris\Desktop\Examples\Python\ellipsoid.py", line 38, in Run_Pipeline
    CommonUtils.download_subset(args.use_case,datasetName, outputDirectory)
  File "C:\Users\amorris\Desktop\Examples\Python\CommonUtils.py", line 54, in download_subset
    DatasetUtils.downloadDataset(datasetName,destinationPath=outputDirectory,fileList = segFilesList)
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\DatasetUtils\__init__.py", line 31, in downloadDataset
    GirderConnector.downloadDatasetZip(accessToken, datasetName, destinationPath)
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\DatasetUtils\GirderConnector.py", line 160, in downloadDatasetZip
    GirderAPI.downloadFolder(serverAddress, accessToken, path=destinationPath, folderInfo=datasetFolder)
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\DatasetUtils\GirderAPI.py", line 197, in downloadFolder
    with open(filename, "wb") as filehandle:
FileNotFoundError: [Errno 2] No such file or directory: 'Output/ellipsoid/ellipsoid-v1//ellipsoid-v1.zip'
```

**Comment by iyerkrithika21** [comment]
I checked Linux, the use case tiny test works fine.

**Comment by iyerkrithika21** [comment]
None of the GirderAPI code was changed for subset download.
@akenmorris does the use case work without tiny test on windows? And is the ellipsoid tiny test the only use case that is failing on windows?

**Comment by archanasri** [comment]
Works on Mac as well.

**Comment by akenmorris** [comment]
This was caused by an out of date DataSetUtils installed via pip.   (Do we have any way to ensure things are kept in sync?  What exactly is the advantage of "installing" DataSetUtils and not GroomUtils/OptimizeUtils, etc?)

**Comment by iyerkrithika21** [comment]
> 
> 
> This was caused by an out of date DataSetUtils installed via pip. (Do we have any way to ensure things are kept in sync? What exactly is the advantage of "installing" DataSetUtils and not GroomUtils/OptimizeUtils, etc?)

@akenmorris how did you install DatasetUtils if the pip one was out of date?

**Comment by akenmorris** [comment]
I just ran:

`pip install Python/DatasetUtilsPackage`

**Comment by sheryjoe** [comment]
> I just ran:
> 
> `pip install Python/DatasetUtilsPackage`
> 
> From C:\Program Files\ShapeWorks

Shouldn't that be part of conda installs?

**Comment by akenmorris** [comment]
It is.
