### ISSUE TITLE
Mesh Domain leaks memory in optimizer

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1044]
It seems the MeshDomain class doesn't fully implement the ITK smark pointer interface from its parent classes.

**Comment by sheryjoe** [comment]
is this fully resolved? close issue?

**Comment by medakk** [comment]
> is this fully resolved?

Yes

>  close issue?

It hasn't been merged to master yet, its on the release branch.

**Comment by akenmorris** [comment]
Release branch or master.
