### ISSUE TITLE
Mesh warp returns mesh with nan's in some cases

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1046]
I'm not sure what's special about this mesh or particles, but the mesh returned has lots of NaNs:

```
# vtk DataFile Version 4.2
vtk output
ASCII
DATASET POLYDATA
POINTS 13022 float
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
37.314 -3.02839 -19.6524 nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan
```

Attached are the data and studio xlsx file:

[warp_mesh_problem.zip](https://github.com/SCIInstitute/ShapeWorks/files/6030137/warp_mesh_problem.zip)

**Comment by riddhishb** [comment]
@akenmorris I cannot immediatly think of why this would be the case :/ I will take a look at the mesh and find out more

**Comment by akenmorris** [comment]
Here is another example, this time just simple ellipsoids:

[warp_mesh_problem2.zip](https://github.com/SCIInstitute/ShapeWorks/files/6237559/warp_mesh_problem2.zip)

**Comment by akenmorris** [comment]
For the femur one, if run in debug, we are halted at this assert:

    assert(is_symmetric(Auu,1.0) &&
      "Auu should be symmetric if positive definite");



__pthread_kill 0x00007fff6f3f833a
pthread_kill 0x00007fff6f4b4e60
abort 0x00007fff6f37f808
__assert_rtn 0x00007fff6f37eac6
bool igl::min_quad_with_fixed_precompute<double, itkeigen::Matrix<int, -1, 1, 0, -1, 1> >(itkeigen::SparseMatrix<double, 0, int> const&, itkeigen::MatrixBase<itkeigen::Matrix<int, -1, 1, 0, -1, 1> > const&, itkeigen::SparseMatrix<double, 0, int> const&, bool, igl::min_quad_with_fixed_data<double>&) min_quad_with_fixed.cpp:124
bool igl::min_quad_with_fixed<double, itkeigen::Matrix<int, -1, 1, 0, -1, 1>, itkeigen::Matrix<double, -1, 1, 0, -1, 1>, itkeigen::Matrix<double, -1, -1, 0, -1, -1>, itkeigen::Matrix<double, -1, 1, 0, -1, 1>, itkeigen::Matrix<double, -1, -1, 0, -1, -1> >(itkeigen::SparseMatrix<double, 0, int> const&, itkeigen::MatrixBase<itkeigen::Matrix<double, -1, 1, 0, -1, 1> > const&, itkeigen::MatrixBase<itkeigen::Matrix<int, -1, 1, 0, -1, 1> > const&, itkeigen::MatrixBase<itkeigen::Matrix<double, -1, -1, 0, -1, -1> > const&, itkeigen::SparseMatrix<double, 0, int> const&, itkeigen::MatrixBase<itkeigen::Matrix<double, -1, 1, 0, -1, 1> > const&, bool, itkeigen::PlainObjectBase<itkeigen::Matrix<double, -1, -1, 0, -1, -1> >&) min_quad_with_fixed.cpp:581
bool igl::biharmonic_coordinates<itkeigen::Matrix<double, -1, -1, 0, -1, -1>, itkeigen::Matrix<int, -1, -1, 0, -1, -1>, int, itkeigen::Matrix<double, -1, -1, 0, -1, -1> >(itkeigen::MatrixBase<itkeigen::Matrix<double, -1, -1, 0, -1, -1> > const&, itkeigen::MatrixBase<itkeigen::Matrix<int, -1, -1, 0, -1, -1> > const&, std::__1::vector<std::__1::vector<int, std::__1::allocator<int> >, std::__1::allocator<std::__1::vector<int, std::__1::allocator<int> > > > const&, int, itkeigen::PlainObjectBase<itkeigen::Matrix<double, -1, -1, 0, -1, -1> >&) biharmonic_coordinates.cpp:200
shapeworks::MeshUtils::generateWarpMatrix(itkeigen::Matrix<double, -1, -1, 0, -1, -1>, itkeigen::Matrix<int, -1, -1, 0, -1, -1>, itkeigen::Matrix<double, -1, -1, 0, -1, -1>) MeshUtils.cpp:120

**Comment by akenmorris** [comment]
In these two cases, I think it's an issue with the mesh and not the particles.
