### ISSUE TITLE
more general versions of Mesh::reflect and Image::reflect

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1049]
`Mesh::reflect` and `Image::reflect` should reflect across any plane, not only xy, xz, yz.

To make it general, add rotations (R and R'):
1. translate to the origin (just like we’re doing)
2. rotate the plane’s normal into one of the main axes
3. reflect across that axis
4. rotate back
5. translate back

i.e., **T R S R' T'**

**Comment by sheryjoe** [comment]
> `Mesh::reflect` and `Image::reflect` should reflect across any plane, not only xy, xz, yz.
> 
> To make it general, add rotations (R and R'):
> 
> 1. translate to the origin (just like we’re doing)
> 2. rotate the plane’s normal into one of the main axes
> 3. reflect across that axis
> 4. rotate back
> 5. translate back
> 
> i.e., **T R S R' T'**

Reflection is different from rotation. The reflect command/API should only do reflection and we can add another API for rotation.

<img width="178" alt="image" src="https://user-images.githubusercontent.com/3253036/108880239-54646100-75bf-11eb-8c8f-4cb00bb09a50.png">
