### ISSUE TITLE
cleanup Windows compiler warnings

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#105]
This will make identifying issues during compilation one ga-ba-zillion times easier than it is right now. There are issues related to updated C++ standards such as using the word `override` when defining overloaded functions, as well as old code explicitly marked as deprecated which will eventually be eliminated altogether.

**Comment by cchriste** [comment]
We're most of the way there [on OSX], just a few left in Studio. Assigning @akenmorris, who can close this as "won't fix" if he wants. Fewer bugs makes happier devs.

**Comment by akenmorris** [comment]
Are you referring to warnings like this?

`Note: No relevant classes found. No output generated.`

Or are you using -Wall -Wextra?  (I get millions with these)

**Comment by cchriste** [comment]
> Are you referring to warnings like this?
> 
> `Note: No relevant classes found. No output generated.`

Mostly. Sounds like they can't be removed. 

> Or are you using -Wall -Wextra? (I get millions with these)

Modern corporal punishment. 

I did have the dubious pleasure of compiling on Windows yesterday. Now _there's_ a platform with LOTS of warnings.
Examples:
```
32>cl : command line warning D9002: ignoring unknown option '-fPIC'
32>ShapeWorks\Libs\Utils\Utils.h(19,1): warning C4005: '_USE_MATH_DEFINES': macro redefinition (compiling source file C:\Users\cam\code\ShapeWorks\Studio\src\Application\Data\MeshGenerator.cpp)
32>ShapeWorks\Studio\src\Application\Utils\WindowsCrashHandler.cpp(144,6): warning C4313: 'sprintf_s': '%X' in format string conflicts with argument 3 of type 'PVOID'
```

These are worth addressing similarly to the lack of being able to build Debug on Windows (since when do linked libraries also need to be Debug?) #665

**Comment by akenmorris** [comment]
>>    Note: No relevant classes found. No output generated.

> Mostly. Sounds like they can't be removed.

I think they can.

**Comment by akenmorris** [comment]
Warnings have been mostly cleaned up.
