### ISSUE TITLE
Generalize Image class to handle vector-valued voxels

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#1053]
Related to:
#1012 
#1015

Example use cases:
- volumetric correspondences (e.g. diffusion images, multiple clinically-relevant metrics - cortical thickness, bone density ... etc) - related to Andy's project

**Comment by cchriste** [comment]
The very limited skeleton of VectorImage that was just added has an "evaluate" function. Perhaps we should add a similar function to our current Image class to get the weighted scalar value of a given location in space.

**Comment by cchriste** [comment]
Closing as duplicate of #1080.

**Comment by cchriste** [comment]
Is this a duplicate of #1080? If not, can we be more specific about what is being requested? Thanks!

**Comment by akenmorris** [comment]
Duplicate of #1080
