### ISSUE TITLE
PCA Python API

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1054]
Need python API support for performing all PCA operations for correspondence model currently present in Studio.
The API should calculate the following:
1. Eigenvalues 
2. Eigenvectors 
3. PCA Loading 
4. PCA Component Scores / Variance

All these quantities should be saved as numpy arrays.

**Comment by iyerkrithika21** [comment]
Related to #995

**Comment by iyerkrithika21** [comment]
@akenmorris: Currently, which library does Studio use to perform the principal component analysis? 
@sheryjoe Should we use the same library for the API or use python libraries like sklearn to perform the PCA analysis?
If we want to use python libraries, following the same suite of `ShapeCohortGenPackage`/`DataAugmentationsPackage` I can start working on `PCAPackage` in the python library.

**Comment by akenmorris** [comment]
Studio uses the ParticleShapeStatistics class:

https://github.com/SCIInstitute/ShapeWorks/blob/master/Libs/Particles/ParticleShapeStatistics.h

In general, my recommendation is to use a single library for both.  This keeps results and behavior consistent across tools.  I worry that having multiple implementations is a step backward into a disjoint set of tools that we've been trying to consolidate over time.

FYI, there are some different plans for the future of statistical analysis including using R.

**Comment by archanasri** [comment]
Are we planning on creating a pybind wrapper of ParticleShapeStatistics?

**Comment by sheryjoe** [comment]
> Are we planning on creating a pybind wrapper of ParticleShapeStatistics?

Yes, as part of the shapeworks python library.

**Comment by cchriste** [comment]
#830 #1172

**Comment by cchriste** [comment]
It’ll be 1000x easier to get this feature out by simply exporting Eigen::Matrix that already has all these functions.
