### ISSUE TITLE
Jupyter notebooks refer to non-existent datasets

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1057]
getting-started-with-segentations.ipynb instructs the user to download `ellipsoid-v2` from `use-case-data-v2`, however no such dataset exists on the data portal.

<img width="604" alt="image" src="https://user-images.githubusercontent.com/1693349/109194560-c8853d00-7756-11eb-8349-c1c9a79dabea.png">

The notebook also assumes that `ellipsoid-v2` exists, but there is no way for the user to get it.

Additionally, the notebook assumes the dataset has been unzipped to the correct location, but there is no instruction to the user that they need to decompress the zip file.

**Comment by iyerkrithika21** [comment]
All segmentations notebooks use v-2, will change it to v-1, and add instructions for unzipping

**Comment by akenmorris** [comment]
Resolved in #1058
