### ISSUE TITLE
integrate contents of mkdocs branch into docs folder

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1059]
Currently devs have to check out an entirely different branch just to update docs for something, so it's no surprise we have trouble keeping up with documentation.
- [ ] Let's find a way to use the docs folder in the main tree and have the mkdocs branch clone and produce the github.io website for docs directly from this. 
- [ ] For bonus, the script that does this can also exist in the main branch so devs can not only "update as they go" but also ensure what they've done looks right. 
- [ ] This will enable features/fixes and their associated documentation to be consolidated into a single pull request to master.

**Comment by sheryjoe** [comment]
The purpose of mkdocs branch was to add documentation and then merge it to master. The merit is to focus work on the documentation to a single branch where PRs are easier to review and merge. The mkdocs branch should not produce the github.io documentation as this is meant to be under-review till a PR from it is merged.

(@archanasri et al, you should submit a PR when you finish updating the docs.)

**Comment by cchriste** [comment]
As a developer one cannot find or review or update docs as one is working without switching branches. Therefore they have to commit or stash what they’re doing, switch branches, update or review docs, commit or stash that, rinse and repeat. Any way you slice it this is painstaking, involving too many commits or popping stashes that aren’t at the top, or (most likely) lack of attention, lack of addition, or mistakes in documentation that finally gets merged.

I stand by the advantages noted earlier, though I acknowledge there may be things I don’t know about. Maybe we can have a developers meeting to discuss this in more detail.

**Comment by sheryjoe** [comment]
@cchriste @akenmorris per to our discussion last week, do we still need this issue?

**Comment by cchriste** [comment]
> @cchriste @akenmorris per to our discussion last week, do we still need this issue?

nope. closing.
