### ISSUE TITLE
Update SCI ShapeWorks site

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1072]
A google search for ShapeWorks always pulls up this site, which doesn't even have a link to our current site from which users would download and install and documentation. 
https://www.sci.utah.edu/software/shapeworks.html

Maybe we can have the current SCI webmaster do this.

**Comment by cchriste** [comment]
Btw, every time I try to install ShapeWorks I run into this. I guess I'm just a simple user at heart.

**Comment by sheryjoe** [comment]
@cchriste et al ...

check out [http://shapeworks.sci.utah.edu](http://shapeworks.sci.utah.edu) or https://www.sci.utah.edu/software/shapeworks.html --- we are on our way to resolve this issue.

**Comment by sheryjoe** [comment]
Done. We will update the page with the Release 6 tour video once we announce the release (sometime soon, I hope!).
