### ISSUE TITLE
ShapeWorks 6.0 testing

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1073]
Please edit and add a ✅ indicating success and ❌ indicating failure or 🕒 for a test in progress with your username when you complete a task for a given platform. When a test fails, please add a github issue and link it (* the issue when it's fixed and ready to test again).  Also, go ahead and add new tasks that might not already be on here.

Please use the most recent release candidate for all testing (be careful which `shapeworks` is in your `$PATH`).  The most recent is found here:

https://github.com/SCIInstitute/ShapeWorks/releases/tag/v6.0.0-rc10

Example:

|                               | Windows                                 | Mac                | Linux                 |  
|------------------|-----------------------------|--------------|----------------|
| Notebooks | | 🕒 (@archanasri) | | 
| Usecase: Ellipsoid | ✅  (@akenmorris ) |  |  | 
| Usecase: All tiny-test   | ❌ (#1073) | ✅  (@cchriste) | | 

Ok, now the real thing!

|                               | Windows                                 | Mac                | Linux                 |  
|------------------|-----------------------------|--------------|----------------|
| Clean installation | ✅  (@cchriste) (#1097, #1098) |✅ (@akenmorris RC10) | | 
| Notebooks: getting-started-with-jupyter-notebooks | ✅  (@cchriste) | ✅ (@akenmorris RC10) |  ✅ (@jadie1, @riddhishb)  | 
| Notebooks: setting-up-shapeworks-environment | ✅  (@cchriste)  | ✅ (@akenmorris RC10) |  ✅ (@jadie1, @riddhishb)| 
| Notebooks: getting-started-with-segmentations | ✅  (@cchriste) (#1113) | ✅ (@akenmorris RC10) |  ✅ (@jadie1 RC10)  | 
| Notebooks: getting-started-with-exploring-segmentations | ✅  (@cchriste)  (#1113)| ✅ (@akenmorris RC10) |  ✅ (@jadie1 RC10)  | 
| Notebooks: getting-started-with-meshes |  ✅  (@cchriste) (#1142)  | ✅(@akenmorris RC10) |  ✅ (@jadie1 RC10)  | 
| Notebooks: getting-started-with-data-augmentation | ✅  (@cchriste) | ✅(@akenmorris) |  ✅ (@jadie1)  | 
| Notebooks: getting-started-with-shape-cohort-generation | ✅ (@cchriste)  (#1113) | ✅ (@akenmorris) |  ✅ (@jadie1 RC10)  | 
| Usecase: ellipsoid | ✅ (@akenmorris RC10)  | ✅ (@akenmorris) |✅ (@jadie1 RC10) | 
| Usecase: ellipsoid --tiny_test   | ✅ (@akenmorris)  | ✅ (@archanasri) | ✅ (@jadie1, @riddhishb)| 
| Usecase: ellipsoid_cut |  ✅ (@akenmorris RC10) | ✅ (@akenmorris) | (✅ @jadie1 RC10) | 
| Usecase: ellipsoid_cut --tiny_test   |✅ (@akenmorris)  | ✅ (@archanasri) | ✅ (@jadie1) | 
| Usecase: ellipsoid_evaluate   | ✅ (@akenmorris) (RC6)  | ✅ (@akenmorris) (RC6) | ✅ (@iyerkrithika21)| 
| Usecase: ellipsoid_fd   | ✅  (@cchriste) | ✅ (@akenmorris) | ✅ (@jadie1 RC10, @riddhishb)| 
| Usecase: ellipsoid_mesh | ✅ (@iyerkrithika21, @cchriste) | ✅ (@archanasri) | ✅ (@medakk)  (@jadie1 RC10) | 
| Usecase: ellipsoid_mesh --tiny-test | ✅ (@iyerkrithika21) | ✅ (@archanasri) | ✅ (@medakk) | 
| Usecase: femur | ✅  (@cchriste) | ✅ (@akenmorris RC10) | ✅ (@jadie1) |
| Usecase: femur --tiny-test   | ✅ (@iyerkrithika21) | ✅ (@archanasri) | ✅ (@jadie1) | 
| Usecase: femur --groom_images |  ✅ (@cchriste) | ✅ (@akenmorris) | ✅ (@jadie1)  | 
| Usecase: femur --groom_images --tiny-test |✅ (@iyerkrithika21)  | ✅ (@archanasri)  | ✅ (@jadie1) | 
| Usecase: femur_mesh | ✅  (@cchriste) | ✅ (@archanasri) | ✅ (@jadie1)  | 
| Usecase: femur_mesh --tiny-test |  ✅ (@iyerkrithika21)| ✅ (@archanasri) | ✅ (@jadie1)  | 
| Usecase: femur_cut | ✅  (@cchriste) | ✅ (akenmorris) | ✅ (@jadie1) | 
| Usecase: femur_cut --tiny-test | ✅ (@iyerkrithika21)  | ✅ (@archanasri) | ✅ (@jadie1) | 
| Usecase: femur_cut --tiny-test (anisotropic)| ✅ (@akenmorris) | ✅ (@akenmorris) |  ✅ (@jadie1) | 
| Usecase: left_atrium |✅ (@akenmorris, @cchriste)  | ✅ (@akenmorris) | ✅ (@jadie1) | 
| Usecase: left_atrium --tiny-test |✅ (@akenmorris)  | ✅ (@archanasri) | ✅ (@jadie1) | 
| Usecase: lumps | ✅ (@iyerkrithika21, @cchriste) | ✅ (@akenmorris) | ✅ (@jadie1) | 
| Usecase: lumps --tiny-test |✅ (@iyerkrithika21)  |  ✅ (@archanasri) | ✅ (@jadie1) | 
| Usecase: deep_ssm --tiny-test |  ✅  (@cchriste)  | ✅ (@akenmorris RC10) | ✅ (@jadie1) | 
| Usecase: deep_ssm |  ✅  (@cchriste)  | ✅ (@akenmorris RC10) |  ✅ (@jadie1) |  
| Studio: Ellipsoid Example  | ✅ (@akenmorris) | ✅ (@akenmorris) | ✅ (@medakk) | 
| Studio: Feature Map Example  | ✅ (@akenmorris) | ✅ (@akenmorris) | ✅ (@medakk) | 
| ... | | | | 

Please keep comments on this issue to a minimum.  Let's try to keep the status in the table and not in the comments.

**Comment by archanasri** [comment]
Working on testing use cases and notebooks on Mac

**Comment by cchriste** [comment]
> Working on testing use cases and notebooks on Mac

No need to add comments about what you're testing. Just update the table at the top when you have completed a test. If something fails, create an issue referenced in your comment.

**Comment by archanasri** [comment]
> > Working on testing use cases and notebooks on Mac
> 
> No need to add comments about what you're testing. Just update the table at the top when you have completed a test. If something fails, create an issue referenced in your comment (see the example above).

Added the comment so that we don't end up duplicating the effort.

**Comment by sheryjoe** [comment]
@akenmorris very nice issue template for testing releases!

**Comment by cchriste** [comment]
Do we have instructions anywhere for how to test (say) notebooks? Just open and run them?

**Comment by akenmorris** [comment]
> @akenmorris very nice issue template for testing releases!

It's a work in progress.  @cchriste and I are still refining.

**Comment by akenmorris** [comment]
> Do we have instructions anywhere for how to test (say) notebooks? Just open and run them?

I think so.  There are instructions in them for the most part.  They typically require that you go download data and put it in the right place.  You can't just blindly open and run everything.

**Comment by cchriste** [comment]
Let's delete unnecessary comments (including this one). Try to keep it super short and sweet.

**Comment by akenmorris** [comment]
Agreed.  And this one too.

**Comment by cchriste** [comment]
Can someone please provide a key to this `--use_case` flag and the list of cases in the table above? 
```bash
ellipsoid,ellipsoid_evaluate,ellipsoid_mesh,ellipsoid_fd,ellipsoid_cut,lumps,left_atrium,femur,femur_mesh,femur_cut,deep_ssm,data_augmentation
```

**Comment by cchriste** [comment]
FYI: femur_cut seemed to have been moving along (it was >24 hrs running), but then the machine wouldn't respond so I rebooted it. It does this periodically even when nothing is running. There was not yet an `analyze.xml` and the most recent files had been written at about 7pm, so I think it was still running. I guess I'll start it over. 😞

**Comment by cchriste** [comment]
> FYI: femur_cut seemed to have been moving along (it was >24 hrs running), but then the machine wouldn't respond so I rebooted it. It does this periodically even when nothing is running. There was not yet an `analyze.xml` and the most recent files had been written at about 7pm, so I think it was still running. I guess I'll start it over. 😞

Or at least I'll try to run it again. But now shapeworks (and it's python module, see #1099) isn't in the path. Did the install .exe do something magic for me? Because I just opened Anaconda terminals, activated the conda environment, and it all worked before rebooting.

**Comment by cchriste** [comment]
Regarding #1102, should the answer be yes or no? 
The currently running test was answered yes (use isotropic spacing for mesh rasterization).

**Comment by jadie1** [comment]
> Regarding #1102, should the answer be yes or no?
> The currently running test was answered yes (use isotropic spacing for mesh rasterization).

For testing? It should work either way, testing with both yes and no on the tiny test only should be sufficient though. No need to test the entire use case with both.

**Comment by cchriste** [comment]
> > FYI: femur_cut seemed to have been moving along (it was >24 hrs running), but then the machine wouldn't respond so I rebooted it. It does this periodically even when nothing is running. There was not yet an `analyze.xml` and the most recent files had been written at about 7pm, so I think it was still running. I guess I'll start it over. 😞
> 
> Or at least I'll try to run it again. But now shapeworks (and it's python module, see #1099) isn't in the path. Did the install .exe do something magic for me? Because I just opened Anaconda terminals, activated the conda environment, and it all worked before rebooting.

I started to create an issue for this and found the problem was due to multiple shortcuts to Anaconda Prompt, one coming from an old installation (with a different path). 

On a potentially related note, the path is anaconda3, not miniconda3, so maybe the windows installer is going big on that?? I thought we already confirmed it installs miniconda, so it could be because this system already had it installed. And related to _that_, I've never had a problem just re-running conda_installs.bat, an infamous issue amongst developers here. But then again, I haven't had a  successful build of shapeworks on Windows in ages.

**Comment by cchriste** [comment]
> FYI: femur_cut seemed to have been moving along (it was >24 hrs running), but then the machine wouldn't respond so I rebooted it. It does this periodically even when nothing is running. There was not yet an `analyze.xml` and the most recent files had been written at about 7pm, so I think it was still running. I guess I'll start it over. 😞

The reason it seems to have taken so long to run is that my system entered sleep state. I've disabled that now, but is there some way we can tell Windows to stay awake when shapeworks is running?

**Comment by akenmorris** [comment]
> On a potentially related note, the path is anaconda3, not miniconda3, so maybe the windows installer is going big on that?? I thought we already confirmed it installs miniconda, so it could be because this system already had it installed.

I believe our older instructions from a previous release pointed the user to anaconda.  Now they point to miniconda.  It's quite possible you had a previous installation.

**Comment by akenmorris** [comment]
> I've disabled that now, but is there some way we can tell Windows to stay awake when shapeworks is running?

I would recommend disabling sleep in power options until you're finished testing shapeworks.

**Comment by cchriste** [comment]
> femur_cut (rc5) status update: it just now "Finished initialization!!!"

```bash
Done.
writing Output/femur_cut/shape_models//1024//transform ...Done.
Writing cutting plane points...
Writing ...Done.
Done.
Finished initialization!!!
------------------------------
*** AddAdaptivity Step
------------------------------
------------------------------
*** Optimize Step
------------------------------
Writing point files...
```

**Comment by cchriste** [comment]
Hi @akenmorris, I noticed RC6 is built, but pull requests still exist for some of these issues. When things are ready to be tested again please let us know.

**Comment by akenmorris** [comment]
Building RC7 now.  Will probably take a few hours.

**Comment by akenmorris** [comment]
I ran the `deep_ssm` use case with RC8 on windows.  This is what it ended with.  Is this what's expected?

![Screenshot (28)](https://user-images.githubusercontent.com/1693349/110275748-ea6c9400-7f8e-11eb-801c-c769b97584ac.png)

**Comment by sheryjoe** [comment]
@jadie1 didn't we add the violin plots for data augmentation viz?

**Comment by jadie1** [comment]
> @jadie1 didn't we add the violin plots for data augmentation viz?

Yes and it is used in the data augmentation notebook. I didn't change the DeepSSM use case to use it, I can if you'd like.

**Comment by akenmorris** [comment]
@jadie1 , should this be considered success?  Can we close the issue and mark it as successful above?

**Comment by jadie1** [comment]
> @jadie1 , should this be considered success? Can we close the issue and mark it as successful above?

Yes, if on windows or no GPU that is the expected output.

**Comment by sheryjoe** [comment]
> > @jadie1 didn't we add the violin plots for data augmentation viz?
> 
> Yes and it is used in the data augmentation notebook. I didn't change the DeepSSM use case to use it, I can if you'd like.

@jadie1 for consistency, let's add the violin plots to the deep ssm use case. it is also a better viz to convey the augmentation results.

**Comment by cchriste** [comment]
Just wanted to verify this result looks good for the full femur_cut. The run took 2-3 days. I marked it as successful above, but wanted to be sure. Thanks!

<img width="1740" alt="Screen Shot 2021-03-10 at 8 05 05 AM" src="https://user-images.githubusercontent.com/1260945/110650868-2747af00-8178-11eb-9207-df54bbb913ca.png">

**Comment by akenmorris** [comment]
@cchriste , looks good to me.

**Comment by cchriste** [comment]
> > @jadie1 , should this be considered success? Can we close the issue and mark it as successful above?
> 
> Yes, if on windows or no GPU that is the expected output.

Is there a github issue to enable utilization of the GPU(s) on Windows? This box has two of them and they're _really_ bored.

**Comment by jadie1** [comment]
> > > @jadie1 , should this be considered success? Can we close the issue and mark it as successful above?
> > 
> > 
> > Yes, if on windows or no GPU that is the expected output.
> 
> Is there a github issue to enable utilization of the GPU(s) on Windows? This box has two of them and they're _really_ bored.

It will work on windows if the user installs the correct version of Pytorch themselves to the ShapeWorks environment following this doc: [PyTorch GPU Support for ShapeWorks](http://sciinstitute.github.io/ShapeWorks/deep-learning/pytorch-gpu.html). It seems there is no reliable way to automatically detect CUDA version on Windows which is why we don't have conda_installs.bat install it with GPU support. We can make an issue but I am not sure if there is currently a solution.

**Comment by cchriste** [comment]
> > > > @jadie1 , should this be considered success? Can we close the issue and mark it as successful above?
> > > 
> > > 
> > > Yes, if on windows or no GPU that is the expected output.
> > 
> > 
> > Is there a github issue to enable utilization of the GPU(s) on Windows? This box has two of them and they're _really_ bored.
> 
> It will work on windows if the user installs the correct version of Pytorch themselves to the ShapeWorks environment following this doc: [PyTorch GPU Support for ShapeWorks](http://sciinstitute.github.io/ShapeWorks/deep-learning/pytorch-gpu.html). It seems there is no reliable way to automatically detect CUDA version on Windows which is why we don't have conda_installs.bat install it with GPU support. We can make an issue but I am not sure if there is currently a solution.

Unfortunately those instructions don't provide any method for determining the CUDA version available on Windows. I will look into it more when I have a chance.

**Comment by cchriste** [comment]
I think we're down to just the two ellipsoid use cases for this release. Might anyone have ideas for things we just haven't thought to test yet? Anything in particular we should be sure to run again on any particular platform?

**Comment by jadie1** [comment]
The ellipsoid use case and notebook are working on the one_mode_ellipsoid branch (issue #1133). The only thing we are waiting on is the parameters need to be tuned for the ellipsoid_cut use case because the correspondence is still not great (issue #1104). @HeavenlyBerserker an @akenmorris Should I make a PR now for the one_mode_ellipsoid branch? Or wait in case the ellipsoid_cut params get updated?

**Comment by jadie1** [comment]
I did not find any issues with RC10 on Linux!

**Comment by akenmorris** [comment]
Done!
