### ISSUE TITLE
Studio Examples: Wrong path

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#1075]
Examples/Studio/ellipsoid crashes with 
![image](https://user-images.githubusercontent.com/10536745/109703281-82631b80-7b52-11eb-9a3c-225007a2afe0.png)

**Comment by akenmorris** [comment]
Is this with the most recent RC?  I thought I fixed this.

**Comment by medakk** [comment]
Yes, the paths are wrong. Will you fix it or shall I do it?

**Comment by akenmorris** [comment]
Where are they wrong?

https://github.com/SCIInstitute/ShapeWorks/blob/release_v6.0/Examples/Studio/Ellipsoid/ellipsoid.xlsx

**Comment by medakk** [comment]
Oops, sorry. I was using the release binaries but an old XLSX file.
