### ISSUE TITLE
Studio Example: Feature maps sliding of particles

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#1076]
![Peek 2021-03-02 12-29](https://user-images.githubusercontent.com/10536745/109703773-1af99b80-7b53-11eb-9945-ed55102b53c1.gif)

Has there been any change to the image domain recently that could cause this? (normals are disable here, so its not related to gradient of normals)
I guess the hyperparameters need to be adjusted.

**Comment by akenmorris** [comment]
Check the newer XLSX file for this one as well.

**Comment by medakk** [comment]
Indeed, my bad.
