### ISSUE TITLE
Add equivalent of VectorImage::evaluate for the Image and Mesh classes

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1080]
`VectorImage::evaluate` takes a point in space and returns the value of the image at that point by interpolating nearby values.
- [x] add function to Image
- [x] add similar function to Mesh to interpolate a given field at any point _on the mesh_ (use Mesh::closestPoint) to get the point to interpolate)

Incidentally, but not necessary for this issue, these two classes (Image and VectorImage) are extremely similar. Their functionality is specific to the type of data stored in their voxels, and they aren't both (currently) expected to work in the same places. We might be able to consolidate them using polymorphism or templates, or to make one utilize the other, or leave them separate, but still try to reduce the amount of copied code between the two. Note that they currently differ somewhat in interface and offered functionality, but for the most part may be similar enough to combine.

**Comment by cchriste** [comment]
Closed #1053 as duplicate. Some example use cases noted there include:

volumetric correspondences (e.g. diffusion images, multiple clinically-relevant metrics - cortical thickness, bone density ... etc) - related to Andy's project

These notably encourage combining the classes. One interface to rule them all!

**Comment by cchriste** [comment]
> Closed #1053 as duplicate. Some example use cases noted there include:

Actually leaving that issue open since it is more general. Currently tagged as won't fix/consolidation/would be nice.

**Comment by archanasri** [comment]
We already have it for mesh as Mesh::probeVolume()

**Comment by cchriste** [comment]
Look at the inheritance hierarchy here:
https://itk.org/Doxygen/html/classitk_1_1InterpolateImageFunction.html

There are several ways to interpolate the image such as Linear, NearestNeighbor, and Gaussian.
We can provide a simple version or an enum allowing the user to specify their preference. 

What will this be used for? My suggestion is Linear as the simplest intermediate value unless there is a specific use case needing to be resolved more delicately.

**Comment by cchriste** [comment]
We have decided to use linear interpolation, same as used by VectorImage. 
We can add an enum in order to support other types of interpolation in the future.

**Comment by akenmorris** [comment]
@sheryjoe , why do we need this?

**Comment by sheryjoe** [comment]
@akenmorris mainly for volumetric correspondences and sampling/probing imaging data at particles locations (Andy's project).

**Comment by akenmorris** [comment]
Done.
