### ISSUE TITLE
ensure all python examples can be run simultaneously

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1081]
At the least, this means unzipping data into its own directory for each example.

**Comment by iyerkrithika21** [comment]
Currently, the data is unzipped in its own directory, ie in `Output/use_case_name/unzipped_data`

**Comment by cchriste** [comment]
At least `data_augmentation` and `deep_ssm` use same directory (deep_ssm). Are they dependent?

**Comment by iyerkrithika21** [comment]
Yes, they are related. The data augmentation process is for the deep_ssm training. @jadie1 correct me here.

**Comment by jadie1** [comment]
Yes the deep_ssm use case runs data augmentation then DeepSSM.  
I believe all of the use cases can be run at the same time currently. I've never run into any issues with that.

**Comment by jadie1** [comment]
@cchriste Can this be closed?

**Comment by jadie1** [comment]
@cchriste I just realized what you were saying about the data_augmentation use case using the same folder as deep_ssm. I will change that.
