### ISSUE TITLE
Debug statement "STUCK" prints during optimization of ellipsoid_cut

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1084]
When the optimization begins the code prints "STUCK" in a loop.
![image](https://user-images.githubusercontent.com/11266258/109749385-ba408200-7b97-11eb-8c71-59f259e0718a.png)

**Comment by sheryjoe** [comment]
@HeavenlyBerserker does this look familiar to you?!!

**Comment by HeavenlyBerserker** [comment]
Yeah, I'll remove it before noon.

**Comment by sheryjoe** [comment]
ok, but is it really stuck?

**Comment by HeavenlyBerserker** [comment]
It's not, it just prints that

**Comment by iyerkrithika21** [comment]
fixed with #1087
