### ISSUE TITLE
Refactor InputParams for ParticleBasedSurfaceReconstruction

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#109]
- base param class for all tools to include common params for all tools
- a derived params class for every cmd tool that includes tool-specific params
- clean up unnecessary params for each tool
- example xml file for each tool

**Comment by cchriste** [comment]
#177 references this and there's a file in Libs/Mesh called `ParticleBasedSurfaceReconstruction_InputParams.h`. No idea if it's been changed at all.

**Comment by sheryjoe** [comment]
@akenmorris @archanasri didn't we consolidate surface reconstruction commands (ReconstructSurface, ... etc ... commands that used the Reconstruction class)? I think consolidated commands are not using xml files.

**Comment by akenmorris** [comment]
The only surface reconstruction I know of in the shapeworks command is the mesh based stuff. I don’t think the distance transform based approach as been consolidated.

**Comment by archanasri** [comment]
@sheryjoe These executables have not been consolidated
