### ISSUE TITLE
Crossing Points in Scapula Model

### ISSUE THREAD

**Issue by elevendavis** [SCIInstitute/ShapeWorks#1090]
[Scapula_v2.zip](https://github.com/SCIInstitute/ShapeWorks/files/6079745/Scapula_v2.zip)

As discussed in the ShapeWorks meeting today (3/3) I have observed point crossing eachother in the model. I did try running it with higher iterations (1000 vs. 500) and lowering the procrustes interval from 10 to 5 and it seemed to resolve the issue, but I am still sending you the files in case you want to investigate further and see if the same changes work to resolve the issue on your end.

![crossingpoints](https://user-images.githubusercontent.com/53015538/109885235-66877480-7c3b-11eb-805a-7e0112a663a8.jpg)

Cheers,
Evan Davis

**Comment by medakk** [comment]
Thanks for sharing this example, @elevendavis 

While it may not fully explain the issue, here is something I noticed. Early on in the optimization, particles may split wildly inconsistently across domains:
![image](https://user-images.githubusercontent.com/10536745/110383360-61e70580-8019-11eb-8623-cd7a485461ec.png)

I have some initial work on splitting particles with a more consistent vector, but this won't entirely solve the problem.

**Comment by akenmorris** [comment]
Can we close this?  @sheryjoe , @medakk ?

**Comment by elevendavis** [comment]
Yes geodesics has resolved this issue for the scapula models
