### ISSUE TITLE
RunUseCase needs path to shapeworks module before it can tell user how to set that path

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1099]
A "chicken and egg" problem: when shapeworks module isn't in path, RunUseCase.py fails with the following error:
```bash
Traceback (most recent call last):
  File "./RunUseCase.py", line 17, in <module>
    from CommonUtils import robustifyShapeworksPaths,dataset_exists_check
  File "/Users/cam/code/ShapeWorks/ShapeWorks/Examples/Python/CommonUtils.py", line 23, in <module>
    import GroomUtils
  File "/Users/cam/code/ShapeWorks/ShapeWorks/Examples/Python/GroomUtils.py", line 14, in <module>
    from shapeworks import *
ModuleNotFoundError: No module named 'shapeworks'
```

**Comment by akenmorris** [comment]
Is this on the master branch or release branch?  I'm pretty sure I already fixed this in the release branch.

**Comment by cchriste** [comment]
> Is this on the master branch or release branch? I'm pretty sure I already fixed this in the release branch.
> 
> See #1033

I discovered the error using the RC5 downloadable release.

**Comment by akenmorris** [comment]
`"/Users/cam/code/ShapeWorks/ShapeWorks/Examples/Python/CommonUtils.py"`

This file is from the RC5 downloadable?

**Comment by cchriste** [comment]
> `"/Users/cam/code/ShapeWorks/ShapeWorks/Examples/Python/CommonUtils.py"`
> 
> This file is from the RC5 downloadable?

Touché. If this is resolved we can close the issue. And... I just checked on the [Windows] downloadable release. It's resolved. Thanks!
