### ISSUE TITLE
Provide users' details for use cases

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1103]
Please provide a key to RunUseCase'py's `--use_case` flag and the list of cases (e.g., in the table in #1073)? 
This can be in the documentation and the `--help` can direct the user with a link (if they can get --help, see #1099)
```bash
ellipsoid,
ellipsoid_evaluate,
ellipsoid_mesh,
ellipsoid_fd,
ellipsoid_cut,
lumps,
left_atrium,
femur,
femur_mesh,
femur_cut,
deep_ssm,
data_augmentation
```
Note: this use case documentation should also probably explain the --groom_imagers flag and for which cases it can be used.

**Comment by cchriste** [comment]
If I understand what I was suggesting: some explanation of each use case could be added to our documentation, maybe on this page: http://sciinstitute.github.io/ShapeWorks/use-cases/use-cases.html. 

Also see #1341

**Comment by cchriste** [comment]
Pushing this to 6.2 since it's a lot of details and at least we have some of the use cases in the docs TOC and the list of all use cases with `python RunUseCase.py --help`.

**Comment by iyerkrithika21** [comment]
Related to  #1347
