### ISSUE TITLE
ellipsoid_cut model shows poor correspondence

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1104]
Here's what I see at the end of ellipsoid_cut.  Notice there are swapped particles, etc.

<img width="1152" alt="ellipsoid_cut" src="https://user-images.githubusercontent.com/1693349/109993000-135c0300-7cc9-11eb-9cb8-f9903c44e2d9.png">

https://user-images.githubusercontent.com/1693349/109993135-35ee1c00-7cc9-11eb-9b34-6817d70a3c68.mp4

**Comment by jadie1** [comment]
Will be fixed for release via issue #1133

**Comment by jadie1** [comment]
@HeavenlyBerserker After updating the ellipsoid data to only have one mode of variation I am still seeing bad correspondence. The shape model correctly predicts only one mode of variation but some of the particles are crossing over each other. 
Can you look at the optimization parameters? The new dataset is called "ellipsoid_1mode_aligned". I have changed the ellipsoid_cut use case to use it on the "one_mode_ellipsoid" branch.

**Comment by HeavenlyBerserker** [comment]
@jadie1 I'll look at it on Thursday. Thanks for the note.

**Comment by sheryjoe** [comment]
@HeavenlyBerserker @jadie1 is this issue resolved?

**Comment by HeavenlyBerserker** [comment]
To the best of my knowledge, yes.

**Comment by jadie1** [comment]
That was with 128 particles though. I will test with the new params on the one_mode_ellipsoid branch which uses the new data. If that looks good then we can close this

**Comment by jadie1** [comment]
![image](https://user-images.githubusercontent.com/54382613/111656553-407fd980-87d0-11eb-9d60-a3a4656ccadb.png)
Looks good, packing isn't super uniform but no particles are switching. Closing this now.
