### ISSUE TITLE
Add transform to DeepSSM

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1106]
Need to add capability of DeepSSM to predict the transformation matrix between world and local particles to account for when procrustes is used in training ground truth correspondence model.

**Comment by akenmorris** [comment]
@jadie1, what's the status on this issue?

**Comment by jadie1** [comment]
@sheryjoe Is this something we are still planning to include in ShapeWorks, or will @j-void work replace it?

**Comment by sheryjoe** [comment]
@j-void 's work should replace this.

**Comment by jadie1** [comment]
@j-void @sheryjoe Should we remove or rewrite this issue?

**Comment by sheryjoe** [comment]
@jadie1  Let's close this and have another issue to add anatomy localizer to DeepSSM and assign it to @j-void
