### ISSUE TITLE
Consolidate Studio and Libs versions of itkParticleShapeStatistics  and itkParticlePositionWriter/Reader classes

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#111]
itkParticleShapeStatistics.h/.txx are found in Run, Studio and View2 (probably identical copies). This should be consolidated into one class in the ParticleSystem library.

**Comment by sheryjoe** [comment]
Run and View2 are identical. Studio version bears some differences (related to group differences). It is worth considering having a separate lib for particle system utilities (see Run/Utilities).

**Comment by sheryjoe** [comment]
Same thing for itkParticlePositionWriter/Reader class. They are in the ITKParticleSystem. Run and View2 are identical and Studio has some differences.

**Comment by sheryjoe** [comment]
Position reader and writer classes have been consolidated in Libs/ParticleSystemUtils. Studio/itkParticleShapeStatistics still needs to be compared to that of Libs/ParticleSystemUtils

**Comment by akenmorris** [comment]
See also issue #45

**Comment by sheryjoe** [comment]
@akenmorris still an issue?

**Comment by akenmorris** [comment]
Yes, they all use the same one in Libs/Particles.
