### ISSUE TITLE
notebook results are different from videos

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1110]
This problem is likely deeper than the notebook in which it's seen. But to reproduce...
1. open `getting-started-with-grooming-segmentations`
2. follow instructions down to "Visualizing Resampled Segmentations" and look at the plots

Some of the ellipsoids seem to have been clipped. 
<img width="929" alt="2021-03-04 (2)" src="https://user-images.githubusercontent.com/1260945/110040234-afa0fc80-7cff-11eb-9380-c23c816d8fc1.png">

**Comment by cchriste** [comment]
related to #1113

**Comment by akenmorris** [comment]
Same as #1113
