### ISSUE TITLE
pyvista viewpoint different than in videos (windows only?)

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1113]
this screenshot shows the difference:
<img width="940" alt="2021-03-04 (1)" src="https://user-images.githubusercontent.com/1260945/110043359-7e76fb00-7d04-11eb-8a30-4836cae0e6fd.png">

**Comment by sheryjoe** [comment]
@jadie1 @iyerkrithika21 with the refactored notebooks, is this still an issue?

**Comment by iyerkrithika21** [comment]
This is still an issue when we visualize the data in grids

**Comment by cchriste** [comment]
Since it's still functional I propose we push this back to 6.2.

**Comment by jadie1** [comment]
Per our discussion, I will add a note to the notebooks that the videos were captured on linux/mac and might look different on Windows.
