### ISSUE TITLE
[Notebook] getting started with meshes has incorrect pathname

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1115]
Its instructions say to use ellipsoid-v1.zip (from ellipsoid-v2 girder directory), but it tried to load meshes from non-existent ellipsoid-v2 directory, and there is also no ellipsoid-v2.zip file in girder, so I presume the path is incorrect in the notebook.

**Comment by iyerkrithika21** [comment]
This was fixed in #1093

**Comment by cchriste** [comment]
fix confirmed
