### ISSUE TITLE
Clip meshes to apply cutting plane constraints

### ISSUE THREAD

**Issue by HeavenlyBerserker** [SCIInstitute/ShapeWorks#1125]
This was your idea, @medakk.

This has been selected as a temporary, more principled fix to what I implemented in #1123.

I can implement this unless you want to.

**Comment by medakk** [comment]
You can go ahead and implement it.

Which version is going into the release? Does  PR  #1123 still need to be tested?

**Comment by sheryjoe** [comment]
Please keep in mind this is not a full-fledged fix. It won't work if given multiple constraints per sample that result in disjoint meshes/compartments.

**Comment by HeavenlyBerserker** [comment]
@akenmorris or @medakk , I've successfully clipped the meshes in the constructor for VtkMeshWrapper, but even though the cutting planes are the same as in the constraints class, the place where it cuts on the femur differs. Any ideas why this might be the case? Is the coordinate system during the optimization different from the one in the parameter reading steps?

![Screenshot from 2021-03-11 13-51-01](https://user-images.githubusercontent.com/11202328/110854729-9d304100-8272-11eb-941b-69b327d24000.png)
Fig. 1 This image shows a successful clipping, but the clip happens higher on the femur than expected.

**Comment by akenmorris** [comment]
They should be the same.

I would suggest having the VtkMeshWrapper print out the bounds that it computes and compare to your cutting plane.
