### ISSUE TITLE
One mode ellipsoid data

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1133]
Change ellipsoid data to only vary along x axis. Working on the one_mode_ellipsoid branch.

- [x] Update shape cohort generation code so user can specify which axis should vary
- [x] Create ellipsoid_1mode data and put on portal with readme ([use-case-data-v2/ellipsoid_1mode/](http://cibc1.sci.utah.edu:8080/#collection/5f6b134f2abccd68562c6a81/folder/6047f2f6d4ef8d408a33eda3))
- [x] Check ellisoid_1mode into github and remove ellisoid-v0 and ellipsoid_fd-v0
- [x] Create ellipsoid_1mode_aligned data and put on portal with readme ([use-case-data-v2/ellipsoid_1mode_aligned/](http://cibc1.sci.utah.edu:8080/#collection/5f6b134f2abccd68562c6a81/folder/6047e4aed4ef8d408a33eadd))
- [x] Update all use cases
    - [x] Update ellipsoid use case to use ellipsoid_1mode segs
    - [x] Update ellipsoid_cut use case to use ellipsoid_1mode_aligned segs (issue #1104)
    - [x] Update ellipsoid_mesh use case to use ellipsoid_1mode_aligned meshes
    - [x] Update ellipsoid_fd to use ellipsoid_1mode segs
    - [x] Verify ellipsoid_evaluate use case still works as expected
- [x] Update portal data to have all use case output (all but ellipsoid_cut added issue #1104)
- [x] Update all notebooks
    - [x] Update getting-started-with-segmentations.ipynb to use ellipsoid_1mode data
    - [x] Update getting-started-with-meshes.ipynb to use ellipsoid_1mode data
    - [x] Update getting-started-with-exploring-segmentations.ipynb to use ellipsoid_1mode data
    - [x] Update getting-started-with-grooming-segmentations.ipynb to use ellipsoid_1mode data
    - [x] Update getting-started-with-shape-cohort-generation.ipynb for changes to shape cohort generation
- [x] Update documentation for getting-started-with-shape-cohort-generation.ipynb

**Comment by jadie1** [comment]
@sheryjoe Could you review this and let me know if I missed anything?

**Comment by jadie1** [comment]
@akenmorris Since none of the use cases will be using ellipsoid-v0 now I will remove it from github. Should I add the new dataset to github or should we require the users download it from the portal?

**Comment by jadie1** [comment]
@sheryjoe Do you think we need to replace every video and png in the notebooks? If the output looks similar but a little different is that okay?

**Comment by jadie1** [comment]
@sheryjoe Here is an example of the output using the new data compared to the video: 
![image](https://user-images.githubusercontent.com/54382613/110699969-a525ad80-81ac-11eb-8682-70afbcb252bc.png)

Do you think it is okay if the output is similar but not identical? If not we need to start re-recording the ~40 mp4s.

**Comment by sheryjoe** [comment]
@jadie1 given similar output, i don't think we have to update the videos.

**Comment by sheryjoe** [comment]
@jadie1 please keep in mind that the ellispoid_fd and ellispoid_cut use cases assume aligned ellipsoids (as far as I recall). They were using ellispoid-v0

**Comment by jadie1** [comment]
> @jadie1 please keep in mind that the ellispoid_fd and ellispoid_cut use cases assume aligned ellipsoids (as far as I recall). They were using ellispoid-v0

Yes they are now using the ellispoid_1mode_aligned dataset which is essentially the same as ellipsiod_v0, just generated using the shape cohort generator package.

**Comment by jadie1** [comment]
Here are the results using the new data.

**ellipsoid**
![image](https://user-images.githubusercontent.com/54382613/110864800-da4f0000-827f-11eb-8e30-5f5b6904ff23.png)

**ellipsoid_fd**
![image](https://user-images.githubusercontent.com/54382613/110864481-6d3b6a80-827f-11eb-9642-7b95fb510961.png)

**ellipsoid_mesh**
![image](https://user-images.githubusercontent.com/54382613/110865590-159dfe80-8281-11eb-85a5-854a9efc3856.png)

**ellipsoid_cut**
![image](https://user-images.githubusercontent.com/54382613/110867420-f05ebf80-8283-11eb-8782-9f7e78a98abf.png)
(Issue #1104)

**Comment by akenmorris** [comment]
What branch is this on?

**Comment by iyerkrithika21** [comment]
> 
> 
> What branch is this on?

one_mode_ellipsoid

**Comment by akenmorris** [comment]
Ok, the only thing remaining is the ellipsoid_cut params?

**Comment by iyerkrithika21** [comment]
Yes
https://github.com/SCIInstitute/ShapeWorks/issues/1073#issuecomment-797093850
