### ISSUE TITLE
Larger spacing causes out of narrow band error

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1134]
@iyerkrithika21  noticed this:

![image](https://user-images.githubusercontent.com/1693349/110544323-cae97e80-80e8-11eb-82b3-d406af5b0b79.png)

The problem is that the spacing (on at least one of the ellipsoids) is 2.0 and with a 4.0 world space narrow band only gets two voxels and runs off.

**Comment by sheryjoe** [comment]
should we close this one?

**Comment by sheryjoe** [comment]
@akenmorris should we close this?

**Comment by akenmorris** [comment]
Yep, merged.
