### ISSUE TITLE
DeepSSM: Data Augmentation Parallelization

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1136]
User should be able to specify how many processes to use in deep_ssm use case. We also need to verify this works as expected on Windows.

**Comment by akenmorris** [comment]
For Studio (embedded python), some info on the challenges here:

https://stackoverflow.com/questions/60328557/using-python3-with-pybind11-from-c-with-multiprocessing-process?noredirect=1&lq=1

**Comment by jadie1** [comment]
Pushing to 6.3 as this will require refactoring for Studio

**Comment by akenmorris** [comment]
@jadie1, what's the status on this issue?

**Comment by jadie1** [comment]
We should resolve this for the next stage of DeepSSM in Studio #1887

**Comment by jadie1** [comment]
@akenmorris Does PR #2089 resolve this?

**Comment by akenmorris** [comment]
> @akenmorris Does PR #2089 resolve this?

Partly in that you can use the multiprocessing package now within Studio.  The fix was only needed for the pytorch dataloader though (as far as I know).  Were we already using multiprocessing for the data augmentation?

**Comment by jadie1** [comment]
We have multiprocessing for data augmentation implemented; it parallelizes the image generation part to speed it up in `Python/DataAugmentationUtilsPackage/DataAugmentationUtils/DataAugmentation.py.` It just uses the Python multiprocessing lib, but if I remember correctly, it was throwing an error on Windows.

**Comment by akenmorris** [comment]
Ok, it should work then.  I will check on windows as well.

**Comment by akenmorris** [comment]
I've fixed this and enabled parallel data augmentation in Studio in #2093

**Comment by jadie1** [comment]
@akenmorris Can we close this issue?

**Comment by akenmorris** [comment]
Yep.  Merged in #2093
