### ISSUE TITLE
Single shape run with image domain fails

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1138]
Description: itk::ERROR: DataObject(0x61500099f280): Attempt to sample at a point outside the narrow band: [nan, nan, nan]. Consider increasing the narrow band

I believe mesh domain works.

**Comment by akenmorris** [comment]
Ah, mesh domain works because NaN updates don't go out of any boundaries.  Single shape run should probably ignore the correspondence term or stick with mean energy (no-op anyway).

**Comment by sheryjoe** [comment]
should we close this? @akenmorris

**Comment by akenmorris** [comment]
Yes, merged.
