### ISSUE TITLE
GitHub actions do not stop at "Build Dependencies" failure

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#1152]
If build dependencies fails for whatever reasons, it returns an exit code 1 and exits the script. However, our GitHub actions workflow seems to consider this a "success" and moves on to the next step. This is on atleast windows, I'm not sure of other platforms.

See https://github.com/SCIInstitute/ShapeWorks/runs/2107766692 for an example:

![image](https://user-images.githubusercontent.com/10536745/111096483-3bd3d080-8505-11eb-82db-3b459b3ef12a.png)
Build Dependencies succeeded even though the ITK install failed.

It eventually fails at the later cmake step with a message about FindITK failing.

**Comment by akenmorris** [comment]
Resolved.
