### ISSUE TITLE
Studio: Allow passing in initial points

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#1159]
Currently, we can pass `<point_files>` as a parameter in the XML to `shapeworks optimize`. This allows users to place manually chosen initial correspondence points. It'd be great if we had to pass in these initial points via studio, perhaps as a folder where initial .particles files are stored per mesh.

@elevendavis Could you please share an example of the registered point data?

(I also noticed that we have #922 for adding landmarks to studio. If this is a duplicate of that, feel free to close any one.)

**Comment by medakk** [comment]
As per a discussion with @elevendavis - once this feature is added, we need to verify that the landmark points go through the snap-to-mesh/apply-constraint step

**Comment by medakk** [comment]
@TannerAsh has shared exaple landmarks in #1164

**Comment by TannerAsh** [comment]
Here are the points and the models. These models have been aligned previously based on the scapular plane. 
Note: The points were assigned to old scapula models before they were cleaned up. However as talked about they should still work. 

[n7_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208445/n7_tab.txt)
[n8_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208447/n8_tab.txt)
[n9_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208448/n9_tab.txt)
[n10_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208449/n10_tab.txt)
[n11_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208450/n11_tab.txt)
[n12_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208451/n12_tab.txt)
[n13_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208452/n13_tab.txt)
[n14_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208453/n14_tab.txt)
[n15_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208454/n15_tab.txt)
[n16_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208455/n16_tab.txt)
[n17_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208456/n17_tab.txt)
[n18_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208457/n18_tab.txt)
[n19_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208458/n19_tab.txt)
[n20_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208459/n20_tab.txt)
[n21_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208460/n21_tab.txt)
[n1_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208461/n1_tab.txt)
[n2_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208462/n2_tab.txt)
[n3_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208463/n3_tab.txt)
[n4_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208464/n4_tab.txt)
[n5_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208465/n5_tab.txt)
[n6_tab.txt](https://github.com/SCIInstitute/ShapeWorks/files/6208466/n6_tab.txt)
[N1-N11.zip](https://github.com/SCIInstitute/ShapeWorks/files/6208483/N1-N11.zip)
[N12-N21.zip](https://github.com/SCIInstitute/ShapeWorks/files/6208486/N12-N21.zip)
