### ISSUE TITLE
Feature map not displayed when playing with PCA modes

### ISSUE THREAD

**Issue by ben2k** [SCIInstitute/ShapeWorks#1160]
For 3D models that embed surface features in PCA model, at the Analyze step of ShapeworkStudio, the feature map for reconstructed mean model is well displayed (see screenshot #1), however, the feature map is not displayed at the PCA step when we can play with PCA variation mode (see screenshot #2).

It may be useful to visualize the feature variations along shape variations at this step.

To reproduce, simply load the feature_map_example in ShapeWorkStudio, do the Grooming, do the Optimization and go to Analyse step, PCA, and play with Std. Dev. cursor --> even the Feature map is selected in the combobox (bottom of 3D window), the colors are uniform (but we see the color bar, see screenshot #2).

![feature_map_example_neab_model](https://user-images.githubusercontent.com/80735487/111540297-5e542c80-8745-11eb-8595-a4e91f7e2f1d.png)
![feature_map_example_PCA_step](https://user-images.githubusercontent.com/80735487/111540298-5e542c80-8745-11eb-8c22-a7e2c59bd727.png)

**Comment by sheryjoe** [comment]
Related to  #985

**Comment by akenmorris** [comment]
Merged
