### ISSUE TITLE
getting-started-with-data-augmentation can't find shapeworks (MacOS)

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1169]
ModuleNotFoundError: no  module named 'shapeworks'

I think this has the old cut and pasted shapeworks finding code.

**Comment by jadie1** [comment]
In the cell where shapeworks is imported, thry changing this:
`shapeworks_bin_dir   = "../../../../build/bin"`
To this:
`shapeworks_bin_dir   = "../../../../bin"`

**Comment by akenmorris** [comment]
The notebook works otherwise.  I just noticed it pops up extra windows with the violin plots.  Not a big deal, they are also in the notebook.
