### ISSUE TITLE
MeshQC method in Reconstruct.cpp

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#117]
Sometimes the tmp.vtk being written is empty (failure in writing vtk, ply writing maybe an alternative), hence resulting in next steps.

**Comment by prafulag** [comment]
/usr/sci/projects/Japanese_dysplasia_shape_analysis/JointModel1-DysplasiaOnly/Experiment_XYZ_Normals_joint_kraken/model_a_i0.001_f100_reg_s1e9_e0.1_r2_proc2_statsInit_0_initIter_3000_optIter_5000/WarpToMeanwProcWithPreviewQC_Updated_pelvis_2048_wpts_1_normalAngle_90/

**Comment by sheryjoe** [comment]
Addressed ...
