### ISSUE TITLE
Consolidate ParticleShapeStatistics

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1172]
ParticleShapeStatistics is used for Python PCA API (#1054).

Things to consider:
- [x] Use ParticleSystem as input
- [x] Deprecate the use of vnl_vector

**Comment by cchriste** [comment]
#830

**Comment by archanasri** [comment]
@sheryjoe Can we move this to 6.3? We can focus on consolidation of particle-based executables for the next release
