### ISSUE TITLE
mesh.toImage(spacing) gives std::bad_alloc (femur_cut use case)

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1175]
When I run the femur_cut example and answer "n" to the isotropic spacing question.  It asks for spacing and it seems that unless I give it 1/1/1, I get:

```
Traceback (most recent call last):
  File "RunUseCase.py", line 94, in <module>
    module.Run_Pipeline(args)
  File "/Users/amorris/sci/data/test/Python/femur_cut.py", line 242, in Run_Pipeline
    fileList_seg = MeshesToVolumes(parentDir + "volumes", reflectedFiles_mesh, spacing)
  File "/Users/amorris/sci/data/test/Python/GroomUtils.py", line 451, in MeshesToVolumes
    image = mesh.toImage(spacing)
MemoryError: std::bad_alloc
```

I've tried a lot of different spacings and always seem to get this unless it's 1.0/1.0/1.0.  Some examples

2.0 2.0 2.0
0.5 0.5 0.5
1.1 1.1 1.1
1 2 3

**Comment by cchriste** [comment]
I'm looking into this now, and have pushed `spacing_alloc` branch with one fix, though it's unlikely causing the crash.
