### ISSUE TITLE
Supershape generate with Chi-Squared instead of Uniform

### ISSUE THREAD

**Issue by riddhishb** [SCIInstitute/ShapeWorks#1177]
The, `n1,n2,n3` parameters of the supershapes generate in the shape works cohort need to come from Chi-squared distribution instead of uniform.
@sheryjoe Can you weigh in on why this needs to be the case?

Additionally, current generation is 2 modes with `n2=n3`, do we need to include a flag for more/less number of modes with the default being 2 modes.

**Comment by riddhishb** [comment]
Update after meeting with Shireen. There are three reasons of using Chi-squared distribution versus the uniform distribution in the current formulation.

1. Uniform distribution requires bound values, where supershapes can exist in the full real space for the parameters n1, n2, n3. Hence the chi-squared can capture this full space much better than the uniform distribution.
2. The degrees of freedom for chi-squared capture how heavy tail the distribution is, so say a degree of 4 will give a good spread of likely samples but at the same time will get us some samples from the heavy tail.
3. Uniform can sometimes give more weightage to extremely sharp and pointy supershapes that chi-square will prevent.

The second point of discussion was keeping the number of modes as a parameter, we can add in the number of modes as a parameter, based on which we can put random distribution on 1, 2 or all three parameters.

What do you think @medakk

**Comment by medakk** [comment]
>  where supershapes can exist in the full real space for the parameters

Is this desirable though? For negative values I've observed the supershape turning in on itself

> There are three reasons of using Chi-squared distribution versus the uniform distribution in the current formulation.
> The second point of discussion was keeping the number of modes as a parameter, we can add in the number of modes as a parameter, based on which we can put random distribution on 1, 2 or all three parameters.

The [current version in the contour_domain branch](https://github.com/SCIInstitute/ShapeWorks/blob/a792fad4c06eb5e23f8537730b8028c343bf2c49/Python/ShapeCohortGenPackage/ShapeCohortGen/Supershapes.py#L78) only exposes a function to generate a single 2D supershape for a given set of parameters.

My question for now is:  Does the supershape generator need to expose a function to generate these shapes via different distribution functions, various combinations of n1, n2 and n3 varying?  Such an API would be needlessly complex: which modes to keep constant(+what is that constant?), what degree for chi sq is used for this, or maybe the user wants to use uniform sampling instead etc. By just exposing:

```python
# Sample points for a 2D supershape and return as np.ndarray
def sample_super_formula_2D(n_points, m, n1, n2, n3):
```

the caller is free to make any of these decisions transparently.


> Uniform can sometimes give more weightage to extremely sharp and pointy supershapes that chi-square will prevent.

Why are pointy supershapes a problem? I was able to train a shape model on this fine:
![image](https://user-images.githubusercontent.com/10536745/112779182-5c228580-9003-11eb-9dca-1be05baafe18.png)

**Comment by sheryjoe** [comment]
@medakk 
> where supershapes can exist in the full real space for the parameters
> Is this desirable though? For negative values I've observed the supershape turning in on itself
By construction of these parametric shapes, these parameters should not have negative values. That is why we need a distribution that don't generate negative values.

**Comment by sheryjoe** [comment]
@medakk Uniform distribution would require defined a range for each parameter which is less intuitive than defining a single degree of freedom for chi-2 distribution. Users can increase the degree-of-freedom if samples with more spike are required due to the heavy tails.
