### ISSUE TITLE
Construct mesh from surface points

### ISSUE THREAD

**Issue by ThisGame42** [SCIInstitute/ShapeWorks#1183]
Hi,

First of all, thank you very much for developing this amazing software! It makes shape analysis so much easier :)

Lately, I've been using ShapeWorks to generate statistical shape models (SSM) from binary segmentation labels. It works very well and I can get my SSM which is expressed as a PCA model. ShapeWorks Studio also does a very nice job at generating a 3D mesh from the learned PCA points and I can export the mesh to a VTK file. However, when I try to generate a new shape from my SSM (which gives me a new set of PCA points) I can't find a way to use the command-line tool to generate the corresponding mesh from my new PCA points. Is this possible with the command-line tool? I'm trying to generate new shapes by varying the eigenvalues from a python script, so it would be nice if I could integrate this mesh generation process into my script. I've tried a few other python packages such as PyVista but they don't do a good job at generating meshes as ShapeWorks does.

Thank you very much,
JZ

**Comment by sheryjoe** [comment]
@ThisGame42 Yes it is possible, however, we might not have exposed it as a standalone command or Python API. 

@riddhishb let's discuss in the dev mtg how could we add a shapeworks command (and associated Python API) to provide such functionality.

**Comment by akenmorris** [comment]
Yes, @riddhishb created it already, but we were unsure about connecting it with read-particle-system command.  See #898 discussion.

**Comment by ThisGame42** [comment]
Oh, awesome! It's great to know such functionality exists already. It would be super useful if we could, for example, pass a file containing coordinates of PCA points, to the ShapeWorks executable to generate a mesh. Anyway, thanks very much for your amazing work, much appreciated 👍

**Comment by akenmorris** [comment]
This is now possible with #1217 that provides the warp-mesh command.

I don't think we need to provide an interface to the legacy surface reconstructor that uses only points as the results are very rarely acceptable.  You need a template mesh for acceptable results.
