### ISSUE TITLE
replace itkwidgets viewer in jupyter notebooks with pyvista viewer

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1186]
Lots of info in #1168, including the underlying reason for this: crashes most likely due to python module linking issues.

Note that the [pyvista](https://docs.pyvista.org) can do anything vtk can do. It's just built on vtk with a more comprehensible interface (kind of like ShapeWorks on itk). It's classes are just wrappers around vtk classes. For example, adding a volume to a plotter returns the `vtk.vtkVolume`, and all functions (`help(vtk.vtkVolume)`) are available.
If we [put our heads together](https://kitware.github.io/vtk-examples/site/Python/Rendering/WalkCowB/) I'm sure we can figure this out.

Note also that itkwidgets's viewer is built on vtk, so look for `def view(...` in [here](https://github.com/InsightSoftwareConsortium/itkwidgets/blob/master/itkwidgets/widget_viewer.py) if you want to try to emulate it more closely.

**Comment by sheryjoe** [comment]
@jadie1 @iyerkrithika21 you will take the lead on this as you restructure the notebooks.
