### ISSUE TITLE
GitHub linux build failing on startup as of this morning (April 1st) 

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1188]
Linux build error during GitHub action setup:
```
Run sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
update-alternatives: error: alternative path /usr/bin/gcc-7 doesn't exist
Error: Process completed with exit code 2.
```

**Comment by akenmorris** [comment]
Hmm...  well, it's gone:

https://github.com/actions/virtual-environments/commit/18062f1b881bbebac1e4fd958949420a5284c78e

<img width="425" alt="image" src="https://user-images.githubusercontent.com/1693349/113326035-692ac780-92d6-11eb-863b-e6bb91c2300e.png">

**Comment by akenmorris** [comment]
Fixed.
