### ISSUE TITLE
Output prefix in Reconstruction code

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#119]
The output prefix was helpful when the shape names were not consistent with the Input names, now with these being synced, the outputs subject-wise point files have an extra prefix, which maybe un-necessary.

**Comment by sheryjoe** [comment]
Which cmd tool you are referring to? ReconstructSurface?

**Comment by sheryjoe** [comment]
This has been addressed ...

**Comment by prafulag** [comment]
[warpToMean_wProc_Updated_pelvis_2048_wpts_1_normalAngle_90.txt](https://github.com/SCIInstitute/ShapeWorks/files/3567125/warpToMean_wProc_Updated_pelvis_2048_wpts_1_normalAngle_90.txt)
