### ISSUE TITLE
Check if vanilla LibIGL can now be used

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1201]
With the mesh warp fixes, we should check if regular LibIGL can now be used instead of our modified version.

**Comment by akenmorris** [comment]
The answer is yes.  This is done in shared_boundary_merge branch, if it gets merged to master then we can close this issue.

**Comment by iyerkrithika21** [comment]
The shared boundary branch will not be merged for this release. 
Should we include this in a separate PR?

**Comment by akenmorris** [comment]
It can wait for the other branch
