### ISSUE TITLE
Expose current segmentation grooming steps in Studio

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#1203]

**Comment by akenmorris** [comment]
Can you be more specific?  Do you have a particular list of what's missing?

**Comment by sheryjoe** [comment]
@akenmorris this issue entails adding the following to studio: (backend tools are already consolidated and used in the python use cases)
- [ ] image/segmentation resampling
- [ ] reference selection for alignment
- [ ] segmentation based registration (ICP, COM)
- [ ] topology preserving smoothing

@jadie1 am I missing something here?

**Comment by akenmorris** [comment]
Can we close this since we have a separate issue for the tpsmoothing?
