### ISSUE TITLE
Padding distance transform with mesh-to-dt on windows is broken after V 6.0.0-RC9

### ISSUE THREAD

**Issue by rl00100** [SCIInstitute/ShapeWorks#1209]
Hi, 

I have been using the mesh-to-dt to calculate the distance transform of one mesh, to then interpolate how close an internal surface is to its boundary. To do this i needed to i needed to shift the bounding box (origin -> min(v)-pad; size -> range(v)+2*pad). With version 6.0.0-RC9 this worked perfectly, but with the release and dev version 6.1.0 this resulted with voxel spacing being reduced but no change in position of the image, or the origin of the image shifted so the bounding box of the image is out of range of the model. 

Rob

**Comment by cchriste** [comment]
Hi Rob, sorry to take so long to get back to you. Can you please share the code you've been using? (the version that worked) Thanks!

**Comment by rl00100** [comment]
Hi Christe, 
 
We were using it in a matlab wrapper, where we print the info from the STL file and the desired padding to a string. Then send this to the command prompt to run it. 

for example: shapeworks read-mesh --name="FileIn" mesh-to-dt --originx=-89.821 --originy=-83.146 --originz=-101.926 --sizex=173.000 --sizey=160.000 --sizez=205.000 --spacex=1.000 --spacey=1.000 --spacez=1.000 writeimage --name="FileOut"

I've attached the script script we use to run this command through shape works. 
[stl2distmap.txt](https://github.com/SCIInstitute/ShapeWorks/files/6445188/stl2distmap.txt)
