### ISSUE TITLE
Crash in Mesh Warp

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1210]
__pthread_kill 0x00007fff738c333a
pthread_kill 0x00007fff7397fe60
abort 0x00007fff7384a808
__assert_rtn 0x00007fff73849ac6
Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> const, Eigen::Replicate<Eigen::Matrix<double, 1, 3, 1, 1, 3>, -1, 1> const>, 0>::Product(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> const, Eigen::Replicate<Eigen::Matrix<double, 1, 3, 1, 1, 3>, -1, 1> const> const&) Product.h:95
Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> const, Eigen::Replicate<Eigen::Matrix<double, 1, 3, 1, 1, 3>, -1, 1> const>, 0>::Product(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> const, Eigen::Replicate<Eigen::Matrix<double, 1, 3, 1, 1, 3>, -1, 1> const> const&) Product.h:94
Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> const, Eigen::Replicate<Eigen::Matrix<double, 1, 3, 1, 1, 3>, -1, 1> const>, 0> const Eigen::MatrixBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::operator*<Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> const, Eigen::Replicate<Eigen::Matrix<double, 1, 3, 1, 1, 3>, -1, 1> const> >(Eigen::MatrixBase<Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> const, Eigen::Replicate<Eigen::Matrix<double, 1, 3, 1, 1, 3>, -1, 1> const> > const&) const GeneralProduct.h:415
shapeworks::MeshUtils::warpMesh(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::Matrix<int, -1, -1, 0, -1, -1> const&) MeshUtils.cpp:137
shapeworks::MeshWarper::build_mesh(vnl_vector<double> const&) MeshWarper.cpp:33
shapeworks::MeshGenerator::build_mesh_from_points(vnl_vector<double> const&, int) MeshGenerator.cpp:72
shapeworks::MeshGenerator::build_mesh(shapeworks::MeshWorkItem const&) MeshGenerator.cpp:45
shapeworks::MeshWorker::run() MeshWorker.cpp:28
QThreadPoolThread::run() 0x0000000109a550de
QThreadPrivate::start(void*) 0x0000000109a5841f
_pthread_start 0x00007fff73980109
thread_start 0x00007fff7397bb8b

Demonstrating example:

[mesh_warp_crash.zip](https://github.com/SCIInstitute/ShapeWorks/files/6327909/mesh_warp_crash.zip)

**Comment by akenmorris** [comment]
LibIGL prints out: "include/igl/min_quad_with_fixed.cpp"

**Comment by akenmorris** [comment]
So the problem here is that the reference mesh had a few extra disconnected triangles for some reason. We need some mesh grooming.

For the mesh warping, I can fix the crash. We are not checking the return call from the igl harmonic call and we should. It’s returning failure in this case, but because we ignore it, the warp call crashes.

**Comment by riddhishb** [comment]
The method does not work with open meshes (having disconnected vertices) or even meshes with intersecting faces. Can we add a mesh QC step like what PreviewQC was doing for such meshes?

Also check out PR #1212 where I have a dataset that the warping crash under, and as far as I know the mesh has no such problems.

**Comment by akenmorris** [comment]
All known crashes are now fixed.
