### ISSUE TITLE
Python API for mean mesh

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1219]
Do we have a python function for generating and exporting the mean mesh and mean particle position for correspondence models?
The export option is available on Studio. 

~~It will also be useful to have function which can read segmentations images(.nrrd) or mesh files(.vtk) and calculate the mean image/ mesh. 
Maybe we could input the analyze.xml and have python commands to generate the data we are interested in.~~

**Comment by iyerkrithika21** [comment]
@sheryjoe, what do you think about this feature?

**Comment by cchriste** [comment]
#1080 (pr #1633) adds the functionality for most of ReconstructSurface, but not `meanSurface` function. 
Maybe an accidental omission?

**Comment by cchriste** [comment]
> #1080 (pr #1633) adds the functionality for most of ReconstructSurface, but not `meanSurface` function.
> Maybe an accidental omission? Or maybe this is completely unrelated.

Was (me) mentioning #1080 a mistake? It doesn't seem related.

**Comment by akenmorris** [comment]
@iyerkrithika21 , @jadie1 , is this complete?

**Comment by iyerkrithika21** [comment]
> @iyerkrithika21 , @jadie1 , is this complete?

I have not been working on this. Not sure what is the status

**Comment by akenmorris** [comment]
We have this:

`sw.utils.findMeanShape(shape_model_dir)`

that the incremental use case is using. 

but this gives the mean particles, not a mesh. You will need a mesh reconstruction to get the mesh. 

I’m not sure about the request to take a list of mesh files and generate a mean mesh. Doesn’t this need a particle system?

**Comment by iyerkrithika21** [comment]
> I’m not sure about the request to take a list of mesh files and generate a mean mesh. Won’t we need a particle system? And in this case, we only need the template mesh to create the mean mesh.

This makes sense. 

The feature request stemmed from the need to build figures for a paper where I had to overlay different features on the mean shape of the model. We already have the functionality of exporting mean mesh and correspondence model in studio. 

> It will also be useful to have function which can read segmentations images(.nrrd) or mesh files(.vtk) and calculate the mean image/ mesh.

This can be removed.

**Comment by akenmorris** [comment]
Ok, should we close the issue, or is there anything else to resolve?

**Comment by iyerkrithika21** [comment]
Closing for now as we have the functions in Studio. 
Can re-open in the future if needed.
