### ISSUE TITLE
Command line tool for the analysis tab

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1220]
For [ShapeWorks Cloud](https://github.com/girder/shapeworks-cloud), it is easier to use command-line tools than Python API. So we need to ensure we have all the functionality of the analysis tab accessible using the command line tools.
Tools:

- [ ] PCA Analysis - eigen values, explained variance,eigen vectors
- [ ] Mesh Reconstrunction - legacy, mesh warping based , distance transform based 

Please add any function if missing.

**Comment by cchriste** [comment]
Is this due to lack of training or documentation for Python? Can you please
provide examples?

**Comment by akenmorris** [comment]
I think the problem is that the two python environments are not compatible.  I assume this meant primarily Python 3.7 vs 3.8.

**Comment by cchriste** [comment]
Also see #839. We should upgrade at some point, which will render this issue moot.

**Comment by archanasri** [comment]
Is this issue required for the 6.2 release?

**Comment by sheryjoe** [comment]
@archanasri no, this is relevant to 6.3 when we upgrade to the new portal.

**Comment by cchriste** [comment]
"Right issue, wrong reasons."

Here's what I think we should do:
- [ ] upgrade to python 3.8 (#839)
- [ ] ensure the command line can accept all the requested parameters
- [ ] _also_ ensure the Python API accepts all parameters

**Comment by cchriste** [comment]
@iyerkrithika21 Can we revisit this wrt the new girder installation? Will it still require updated Python?

**Comment by iyerkrithika21** [comment]
> @iyerkrithika21 Can we revisit this wrt the new girder installation? Will it still require updated Python?

I'll reach out to the Kitware team and provide an update on this requirement.

**Comment by iyerkrithika21** [comment]
> @iyerkrithika21 Can we revisit this wrt the new girder installation? Will it still require updated Python?

Reponse from the Kitware team:

> Looking at the available command line tools, I think they are sufficient for the MVP.  I think we will mostly be using groom, optimize, warp-mesh.  I think we'll be more certain about this in a week or three.

**Comment by iyerkrithika21** [comment]
Changing the milestone as it is not required currently as per Kitware team's reply.

**Comment by akenmorris** [comment]
This should be considered done until further requests
