### ISSUE TITLE
Studio: Mesh Warping needs a progressbar

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1229]
With all of the fixes, the mesh warping is significantly slower, depending on the number of particles. This is due to iteratively adding vertices and splitting triangles.  The biggest cost is probably that the locator and links have to be rebuilt each time as we don't have a way of only incrementally changing them inside of VTK.

**Comment by medakk** [comment]
>  The biggest cost is probably that the locator and links have to be rebuilt each time

It _may_ be faster to check distance to every triangle and pick the minimum vs rebuilding the (kd)tree for every query. O(n) vs O(n log n) where n is the number of triangles. But its nice to have VTK take care of all the details of the query
