### ISSUE TITLE
Eigen objects being passed by value in VtkMeshWrapper

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#1243]
One example:

```cpp
VtkMeshWrapper::GeodesicWalkOnFace(Eigen::Vector3d point_a, Eigen::Vector3d projected_vector,
                                   int face_index, int &ending_face) const
```

https://eigen.tuxfamily.org/dox/group__TopicPassingByValue.html
> With Eigen, this is even more important: passing fixed-size vectorizable Eigen objects by value is not only inefficient, it can be illegal or make your program crash!

**Comment by medakk** [comment]
This _may_ not be affecting us, however:

https://eigen.tuxfamily.org/dox/group__TopicFixedSizeVectorizable.html
Eigen::Vector3d is not considered "fixed size vectorizable"

**Comment by akenmorris** [comment]
Investigated, I don't think this is a problem.
