### ISSUE TITLE
Python API for evaluation commands

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1248]
The ellipsoid-evaluate still uses the command line tools and not python API for compactness, specificity, and generalization need python APIs.  - [ShapeEvaluation.h](https://github.com/SCIInstitute/ShapeWorks/blob/master/Libs/Particles/ShapeEvaluation.h)

```
cmd = f'shapeworks read-particle-system --names {particles_glob} -- '\
        f'           compactness --nmodes 1 --saveto {working_dir}/scree.txt'

cmd = f'shapeworks read-particle-system --names {particles_glob} -- '\
          f'           generalization --nmodes 1 --saveto {working_dir}/'

cmd = f'shapeworks read-particle-system --names {particles_glob} -- '\
          f'           specificity --nmodes 1 --saveto {working_dir}/'

```

**Comment by iyerkrithika21** [comment]
I will try to follow the [documentation ](http://sciinstitute.github.io/ShapeWorks/dev/python-apis.html) and try to include the binding and will get back to @cchriste/ @archanasri  to verify the changes.

**Comment by iyerkrithika21** [comment]
The commands are already included in [ShapeworksPython.cpp](https://github.com/SCIInstitute/ShapeWorks/blob/6ec731a77cfa82ab4a69a6132c5d69e476cbfdf1/Python/shapeworks/ShapeworksPython.cpp#L662)

**Comment by cchriste** [comment]
Can Archana and I be removed from this issue and simply added as reviewers when it's done?

**Comment by sheryjoe** [comment]
@iyerkrithika21 will take the lead on this but might need help from @cchriste or @archanasri .
