### ISSUE TITLE
Adding Studio Visualization to SCI Servers

### ISSUE THREAD

**Issue by elevendavis** [SCIInstitute/ShapeWorks#1253]
Hi all,

Yesterday myself and Penny Atkins were able to get ShapeWorks (6.1.0-dev, build capable of geodesics and landmarks) running on the SCI servers. We built the version using the ardashir server and ran the optimize pipeline on 20 scapula models, it completed in 9 hours (compared to 24 hours on my local machine).

We tried to open ShapeWorks Studio by using the ssh -X method and received the following error below. Can you help us get Studio available on the SCI servers? Additionally, should we change the folder where ShapeWorks is kept? It is currently on: 

export PATH=/home/collab/evan.davis/ShapeWorks-PR-1208-linux/bin/:$PATH

**Error code:**

_evan.davis@shell1:~> ssh -X evan.davis@ardashir.sci.utah.edu
Password:
Last login: Wed May 19 12:40:54 2021 from 155.98.59.10
Have a lot of fun...
evan.davis@ardashir:~> source .profile
evan.davis@ardashir:~> ShapeWorksStudio
[2021-05-19 12:45:55.880|main.cpp|29] MESSAGE: ShapeWorksStudio initializing...
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display._

**Comment by akenmorris** [comment]
You might need to use -Y instead of -X.

Are you coming from a Linux machine or Windows.  If Windows, you will need an X server.  Besides ShapeWorks, you can check of the X11 connection is working by running "xclock".  You should get something like this:

<img width="176" alt="image" src="https://user-images.githubusercontent.com/1693349/119047408-1e930680-b97b-11eb-91ad-aa02a42eac59.png">

**Comment by akenmorris** [comment]
@elevendavis , were you able to run X11 programs over the network yet?

**Comment by elevendavis** [comment]
@akenmorris yes thank you, I downloaded MobaXTerm on my computer and was able to open Studio on the SCI server. I have not tried to run studio through the program, but was able to view a processed model. I have just been editing the files locally in studio, uploading and running from the command line on the server

**Comment by akenmorris** [comment]
Cool.
