### ISSUE TITLE
Python API for spreadsheet project file IO

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1257]
1. Provide Python API for the project file IO operations
2. Update use cases to support spreadsheet project files #1440 
3. Enable optimizer to run with project sheet and add API calls #568

**Comment by cchriste** [comment]
@iyerkrithika21 Can you please provide a concrete example for this?

**Comment by iyerkrithika21** [comment]
> @iyerkrithika21 Can you please provide a concrete example for this?
- These API calls will be replacing the way XML files are created in the python script, and we will move towards using project sheets universally (Studio, use cases, data portals) 
- use the same classes(Project, Subject, Variant) as Studio to create the project sheets in python.

- @akenmorris, @jadie1, and I have been working on the `project_API` branch to add the [python bindings](https://github.com/SCIInstitute/ShapeWorks/blob/4ce02a6ce0b2ee5e65b8d704c7f7c125012f4a1c/Libs/Python/ShapeworksPython.cpp#L1475) and [refactoring the use cases](https://github.com/SCIInstitute/ShapeWorks/blob/4ce02a6ce0b2ee5e65b8d704c7f7c125012f4a1c/Examples/Python/femur_cut.py#L183).
