### ISSUE TITLE
Disable mesh/DT surface reconstructions if local particles are not specified in an analysis XML

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1262]
The legacy XML doesn't require local particle files, but we must insist on them for distance transform or mesh based surface reconstruction.  It does not crash, but will give you a very poor reconstruction as it will use the world particles since the particle stats will set local and world to the same if only the old <point_files> is specified.

**Comment by sheryjoe** [comment]
is this for 6.1?

**Comment by akenmorris** [comment]
Sure.
