### ISSUE TITLE
Testing of shapeworks Optimize

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1263]
At least in the Python version, this test is incomplete. Please see this comment in Testing/PythonTests/optimize.py:
`# TODO: check results are what would be expected (save a file with them?)`

**Comment by cchriste** [comment]
Can uploads of results (#750) be used as comparisons?

**Comment by cchriste** [comment]
This test has been broken for the past three weeks. @archanasri and I just noticed today, restoring the file that was missing.

**Comment by akenmorris** [comment]
What file was deleted?  And this test is currently failing on master branch but not being picked up by google test?

**Comment by akenmorris** [comment]
Done with #1343
