### ISSUE TITLE
Add p-values for group differences in studio 

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1271]
We can define the p-values for each correspondence point to indicate if the group differences are statistically significant. This is computed by performing a separate statistical test of difference for each correspondence point. In Cates thesis (page 46), a nonparametric permutation test of the Hotelling T2 metric, with false-discovery-rate (FDR) correction for multiple comparisons, was used. 

https://www.cs.utah.edu/~whitaker/papers/CatesThesis2010.pdf

**Comment by iyerkrithika21** [comment]
Add the python script that calculates the p-values to the shapeworks python module. 
Add `stats.py` to `ShapeWorks/Python/shapeworks/shapeworks/`

**Comment by akenmorris** [comment]
@iyerkrithika21, @sheryjoe  the use case, non-tiny-test mode takes about 2 minutes to run.  Is this expected?

**Comment by iyerkrithika21** [comment]
Yes,it depends on the number of particles and the number of time the test is repeated.

**Comment by iyerkrithika21** [comment]
Addressed in #1421
