### ISSUE TITLE
Implement sub-sampling for multiple domain

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1272]

**Comment by iyerkrithika21** [comment]
1. Need a general pipeline for sub-sampling which works for single and multiple domains.
2. Should work with both segmentations and meshes

**Comment by akenmorris** [comment]
What does sub-sampling mean in this context?

**Comment by iyerkrithika21** [comment]
--use_subsample: To run on a subset of the data in the use case, along with the --num_subsample tag where the number of samples is specified. 
Right now, a clustering-based subset selection is implemented so that the subset is representative of the entire dataset
