### ISSUE TITLE
Replace proprietary Transform type with Eigen matrix in Python bindings

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1276]
Currently we bind an opaque itk::Transform to the Transform type in Python.
This can be passed back and forth (thereby enabling it to be modified on the Python side) by sending a transparent Eigen matrix, like we already do with most other similar thing such as Image.coordsys, the Eigenvectors of ParticleShapeStatistics, etc. 

Let's do the same thing with Transform, either passing it as a 3x4 or 4x3 or (more common in graphics) 4x4 [right-handed] matrix incorporating rotation, scaling, shear, and translation. 

This task should include providing examples of using the transforms in a Jupyter notebook.

**Comment by sheryjoe** [comment]
@cchriste where are we on this one?

**Comment by cchriste** [comment]
We can also just change them to numpy exactly as lots of other things use. On the Python side they are numpy whether or not they come from Eigen since there is no Eigen in Python, just that pybind11 has a nice wrapper for moving back and forth with them.

**Comment by cchriste** [comment]
<img width="436" alt="Screen Shot 2021-09-28 at 3 23 10 PM" src="https://user-images.githubusercontent.com/1260945/135167750-8623e051-0721-49a8-956c-a598c179b93a.png">

As confirmed by the comment in #767, this proprietary shapeworks Python class that wraps a 3x3 itk::Transform doesn't provide any functionality for the user. It creates a transform that can then be applied to the image itself or to other images in a series. It's used heavily in some of our use cases. One big problem for the Python API is a lack of help documentation (new users are a great resource; take pride in your lack of knowledge about ShapeWorks and help us improve!)

The result of this fix will be...
- [ ] improved docs (`help(Image.createTransform)` along with the C++ comments and command line instructions), 
- [ ] simply receiving a 3x3 `numpy` array from `Image.createTransform`, able to be modified and 
- [ ] used with `Image.applyTransform` (you can also make your own with `shapeworks.createTransform()`). 

Now about `Mesh.createTransform` (and `Mesh.applyTransform`)... see #1493.

**Comment by cchriste** [comment]
Almost done. Need to add some better tests (which uncovered Python tests issue #1465, will fix tomorrow).

**Comment by cchriste** [comment]
Pushed transforms_python_api branch, but two remaining issues:
- [ ] clean up `createTransform` functions to un-mix-up CenterOfMass and ICP
- [ ] figure out how to handle warp transforms, large matrices* from thin plate splines (used for particles), which were also passed and applied as itk Transforms, but we got rid of the proprietary (dark and uneditable) Transform class, presuming it was always a simple 4x3 affine matrix transformation (that we now pass as a typical 4x4 numpy matrix).
*the one from our unit test is 513x3
