### ISSUE TITLE
GH Action Mac for master should deploy pkg as well.

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1278]
Right now only deploying zip.

**Comment by cchriste** [comment]
This is now working.

**Comment by akenmorris** [comment]
This is still an issue.  The development/master automatic releases only contain the zip for mac.  This is not a release/6.1 issue.

See here:

https://github.com/SCIInstitute/ShapeWorks/releases/tag/dev-mac

**Comment by akenmorris** [comment]
Now it's working with 6c00931923e59a1e48adb4dafbd9b7e725f3246f
