### ISSUE TITLE
Release notes for 6.1

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#1285]
Please add to this issue a paragraph (plus videos/snapshots for illustration) about each new/improved/bug-fix included in this release. Please add bullets to the below outline that are relevant to your contributions for the 6.1 release. I will consolidate and add to the documentation right away and put together the graphical abstract for release announcement before the SB3C workshop.

- **What is new?**
    - User's Support
    - ShapeWorks Back-end
    - All-in-one Studio Front-end
    - Deep Learning & Shape Modeling
- **Improvements**
     - User's Support
    - ShapeWorks Back-end
    - All-in-one Studio Front-end
    - Deep Learning & Shape Modeling
- **Fixes**
    - User's Support
    - ShapeWorks Back-end
    - All-in-one Studio Front-end
    - Deep Learning & Shape Modeling

NOTE: To add these comments to the documentation (markdown format), select "edit" on a message and cut-and-paste.

**Comment by iyerkrithika21** [comment]
-**What is new?**

> -User's support

1. Ellipsoid joint generation added to ShapeWork's cohort generator python module. Cohorts of joints can be generated with options available for distance separating the joints, modes of variations(size/rotation). These cohorts can be used for troubleshooting multiple domain shape modeling workflow. 
![image](https://user-images.githubusercontent.com/11266258/121827902-1167ef80-cc7b-11eb-963b-66b4c48a5c27.png)


> -ShapeWorks Back-end

1. Consolidation of PCA shape analysis tools: Updated `shapeworks` API to include PCA shape analysis tools (read particle files, calculate eigenvectors, eigenvalues, mode variance). A new use case `ellipsoid_pca` demonstrating the usage of PCA tools has been added.

-**Improvements**

> -User's Support

1. Updated 'OptimizeUtils` and `AnalyzeUtils` to handle multiple domain datasets. 
2. Two new use cases - `ellipsoid_multiple_domain` and `ellipsoid_multiple_domain_mesh` added to demonstrate multiple domain use cases for segmentation images and meshes. 
![image](https://user-images.githubusercontent.com/11266258/121828024-820f0c00-cc7b-11eb-9d79-123a89d21869.png)

3. Depreciated `GroomUtils` and  `EvaluationUtils` and restructured all use cases to make the grooming steps more transparent by using the python API.

**Comment by HeavenlyBerserker** [comment]
- **What is new?**
    - ShapeWorks Back-end: Constraints are now implemented by turning the problem into an unconstrained optimization using the augmented lagrangian inequality formulation. Now supports cutting planes and spheres.
- **Improvements**
    - ShapeWorks Back-end: Particle splitting and constraints will no longer require that no particle violates constraints. It will work even if a particle violates a constraint. Added multiple unit tests.

Results on new cutting_planes unit test with 3 cutting planes
![Screenshot from 2021-04-12 13-55-59](https://user-images.githubusercontent.com/11202328/114453644-f3a4de00-9b96-11eb-978f-8190c8192fb8.png)
Results on new sphere_constraint unit test with 25 spheres
![Screenshot from 2021-04-17 15-39-26](https://user-images.githubusercontent.com/11202328/115127371-2b46c800-9f93-11eb-87a3-508a71831ce4.png)
Results on new sphere_cutting_plane_constraint unit test with 25 spheres and one cutting plane
![Screenshot from 2021-04-17 12-54-58](https://user-images.githubusercontent.com/11202328/115127341-ff2b4700-9f92-11eb-931b-290cac892c75.png)
Results on ellipsoid_cut use case
![Screenshot from 2021-04-12 09-30-27](https://user-images.githubusercontent.com/11202328/114453078-6792b680-9b96-11eb-9e91-240e71cf89f1.png)
Results on femur_cut use case
![Screenshot from 2021-04-06 18-00-03](https://user-images.githubusercontent.com/11202328/114453220-8e50ed00-9b96-11eb-926c-b3b09c535045.png)

For more information on augmented lagrangian inequality constraints, please see [http://www.cs.cmu.edu/~pradeepr/convexopt/Lecture_Slides/Augmented-lagrangian.pdf](url).

**Comment by medakk** [comment]
- **What is new?**
    - ShapeWorks Back-end
      1. Geodesic distance based repulsion is now supported for mesh domains. This improves results on structures with thin and/or convoluted features at the cost of increased memory and runtime. Refer to the `thin_cavity_bean` use case for an example.
![20210423_bean_geodesic](https://user-images.githubusercontent.com/10536745/121950291-a835ba00-cd16-11eb-8baa-b990cdc24200.gif)
      2. N-dimensional contour domains are now supported in ShapeWorks. Refer to the `supershapes_1mode_contour` use case for an example.
![image](https://user-images.githubusercontent.com/10536745/121949895-41180580-cd16-11eb-9b1b-50f835030a67.png)
![20210426_contourdomain](https://user-images.githubusercontent.com/10536745/121950004-63118800-cd16-11eb-831e-f70fb0df3d77.gif)

**Comment by akenmorris** [comment]
What is new?

Grooming support for Meshes in Studio:

* Smoothing (two methods)
* Hole filling
* Center
* Iterative Closest Point (auto reference shape)

<img width="384" alt="image" src="https://user-images.githubusercontent.com/1693349/122125026-50b64d80-cded-11eb-8fd9-4f773f3d249a.png">

**Comment by cchriste** [comment]
```
- partitioned regions into both index (0-based) regions and physical regions
  - enabling exact specification of crop regions and clip plane for both images and meshes
- significant improvements to shapeworks Python module:
  - now installed with the rest of ShapeWorks
  - entire ShapeWorks library framework now accessible via Python bindings
  - no longer requires any special path modifications to import
  - uses generic Python types (e.g., numpy, arrays, lists) rather than opaque wrappers for parameters to/from ShapeWorks objects
  - now possible to instantiate shapeworks.Image from a numpy array
  - can now request raw image data as a numpy array
  - ability to safely “dot chain” operations (ex: img.translate([tx, ty, tz]).rotate(45, shapeworks::Z).scale([sx, sy, sz)) )
- more clear documentation both from Python, the command line, and online
- better error detection and handling
- more robust automated testing to ensure improvements do not break existing functionality
```

**Comment by jadie1** [comment]
Improvements - Deep Learning & Shape Modeling
- Defined a config file for DeepSSM parameters which is used in training and testing. This will be helpful for parameter tuning, model comparison, and adding additional functionality and parameters to DeepSSM.
- A fine-tuning option has been added to DeepSSM. This allows the model to learn the mapping between the PCA space to the correspondence point space , improving accuracy. 
- DeepSSM evaluation has been adapted to use ShapeWorks mesh warp function and Python binding mesh distance function. 
- The DeepSSM use case has been adapted to run on both GPU and CPU. It is considerably faster on GPU but no longer exits when running on CPU.

**Comment by sheryjoe** [comment]
@iyerkrithika21 

> Consolidation of PCA shape analysis tools: Updated shapeworks API to include PCA shape analysis tools (read particle files, calculate eigenvectors, eigenvalues, mode variance). A new use case ellipsoid_pca demonstrating the usage of PCA tools has been added.

- Do you mean by API here the shapeworks command or python API or both?
- what is the difference between calculating eigenvalues and mode variance?

**Comment by sheryjoe** [comment]
> What Is New?
> 
> * Extending the warp-mesh command to work with multiple meshes at the same time.

@riddhishb please share a snapshot to show case this feature to be used for the graphical abstract.

**Comment by sheryjoe** [comment]
@akenmorris 
> N-dimensional contour domains are now supported in ShapeWorks. Refer to the supershapes_1mode_contour use case for an example.

Want to make sure about adding the above to the release notes. I think the PR has been merged, but the full support with Studio is pushed to 6.2. right?

**Comment by sheryjoe** [comment]
@akenmorris 

I think we should include multi-domain support to what is new in studio.

**Comment by sheryjoe** [comment]
@akenmorris @jadie1 @riddhishb @archanasri @cchriste @HeavenlyBerserker 

Any significant bug fixes we can highlight in the release notes?

**Comment by akenmorris** [comment]
> I think we should include multi-domain support to what is new in studio.

Of course.  Somehow I was thinking that was in 6.0, but I guess it wasn't.

**Comment by akenmorris** [comment]
> Want to make sure about adding the above to the release notes. I think the PR has been merged, but the full support with Studio is pushed to 6.2. right?

That's right.

**Comment by sheryjoe** [comment]
@akenmorris 

> > I think we should include multi-domain support to what is new in studio.
> 
> Of course. Somehow I was thinking that was in 6.0, but I guess it wasn't.

@akenmorris can we add multiple domains to studio documentation?

**Comment by akenmorris** [comment]
> can we add multiple domains to studio documentation?

Yep

**Comment by sheryjoe** [comment]
> > can we add multiple domains to studio documentation?
> 
> Yep
@akenmorris please at a high level description in "New in Studio" page with a link to the multiple domain page (more detailed documentation) in the "ShapeWorks Studio" group.

**Comment by sheryjoe** [comment]
@akenmorris @jadie1 @iyerkrithika21 @cchriste @archanasri @riddhishb  @HeavenlyBerserker 

Please let me know if you have any comments/suggestions to make it better.
<img width="897" alt="image" src="https://user-images.githubusercontent.com/3253036/122322390-a15ba280-cee2-11eb-8370-9b637bee1d95.png">

**Comment by HeavenlyBerserker** [comment]
That looks sick! I like it

**Comment by cchriste** [comment]
**Improved installation** 
- users no longer required to modify PATHs or pass parameters to find executables or import python module
  - works even if non-standard installation directories are used
  - works on all platforms
- new shapeworks environments can now be created using `install_shapeworks [name]`
  - this supports multiple installations for anyone
  - can change installation just by activating a different conda environment

**Comment by cchriste** [comment]
**Improved developer support to facilitate more independent and robust testing**
- **devenv** scripts for all platforms now ensure deliberate testing of specific binaries and a developer's code are always matched with no presumption or accidental inclusion of the wrong python libraries or binaries.
- unit tests suites that once required a _setup environment_ test that all the other tests depended upon no longer have such a dependency, enabling `--gtest_filter="*testname*"` to be used when working on a specific feature. 
  - suites that had this requirement include Python, shapeworks, and UseCaseTests.

**Comment by cchriste** [comment]
RunUseCase improvements 
- no longer requires `--use_case` before use case. 
  - this makes it simpler to use since omitting a use case name immediately prints help, which itself shows the list of use cases as a required argument rather than listing them with the other optional args
- no longer accepts paths to shapeworks executables or python modules
  - all of these are in the user's conda environment, or set using **devenv** for testing by developers

**Comment by sheryjoe** [comment]
Done and added to the docs.
