### ISSUE TITLE
Feature Request - Multi-Domain Export Current Mesh

### ISSUE THREAD

**Issue by RichLisonbee** [SCIInstitute/ShapeWorks#1288]
When exporting the current mesh the 6.1.0 Dev will only export the mesh of the first domain and does not include the the other domains in the exported .vtk file.

**Comment by sheryjoe** [comment]
@akenmorris is this simple enough / feasible to add to 6.1?

**Comment by akenmorris** [comment]
Yes, see #1298

**Comment by RichLisonbee** [comment]
It exports each domain! Works great, thank you!!!

**Comment by akenmorris** [comment]
Completed.
