### ISSUE TITLE
conda_installs.sh is confused about platforms

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#129]
I see that it downloads for linux and then tries to run the mac installer:

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash ./Miniconda3-latest-MacOSX-x86_64.sh

**Comment by cchriste** [comment]
Already fixed. See the pull request I sent yesterday.

**Comment by aogs** [comment]
Oops, sorry.
