### ISSUE TITLE
femur --groom_images issue

### ISSUE THREAD

**Issue by HeavenlyBerserker** [SCIInstitute/ShapeWorks#1292]
When running `femur --groom_images issue`, I get the following error. [log.txt](https://github.com/SCIInstitute/ShapeWorks/files/6652778/log.txt). 

"Output/femur/" is empty after running the regular femur use case successfully. It does not seem to recognize that.

> Traceback (most recent call last):
>   File "RunUseCase.py", line 106, in <module>
>     module.Run_Pipeline(args)
>   File "/home/hxu/Documents/ShapeWorks-dev-3737-e124a282-linux/Examples/Python/femur.py", line 155, in Run_Pipeline
>     img.write(img_out, compressed=0)
> RuntimeError: /home/hxu/Documents/ShapeWorks/dependencies/build/ITK/Modules/IO/NRRD/src/itkNrrdImageIO.cxx:1146:
> itk::ERROR: NrrdImageIO(0x55e61e7d9120): Write: Error writing Output/femur/groomed/images/Output/femur/femur-v0/images/m03_L_femur.nrrd:
> [nrrd] nrrdSave: couldn't fopen("Output/femur/groomed/images/Output/femur/femur-v0/images/m03_L_femur.nrrd","wb"): No such file or directory

**Comment by akenmorris** [comment]
Yep, there several problems in both femur use cases.
