### ISSUE TITLE
ShapeCohort Generator Notebook: Screenshot not visible

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1294]
For step 3 in `Generating an Ellipsoid Cohort`, the link to the screenshot seems to be broken

**Comment by sheryjoe** [comment]
@iyerkrithika21 @jadie1 please double-check snapshots and videos across all docs. I have been seeing some missing image/video content on the currently deployed docs lately.

**Comment by jadie1** [comment]
> @iyerkrithika21 @jadie1 please double-check snapshots and videos across all docs. I have been seeing some missing image/video content on the currently deployed docs lately.

Let's do this on the mkdocs branch and we can merge it right before we make the release.

**Comment by cchriste** [comment]
Please create an independent branch off master* for this task. We have
removed mkdocs after the last merge like we talked about.

*it can be called mkdocs if you want :-)

**Comment by jadie1** [comment]
Okay, I will make one called fix_docs

**Comment by jadie1** [comment]
This is now fixed on the fix_docs branch.
