### ISSUE TITLE
install_name_tool is not available on non-developer macs

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1297]
Unfortunately, install_name_tool isn't available on macs without Xcode.  Running it (as the conda/python install scripts do) results in a window being popped up prompting the user to install the compiler toolchain stuff.  Even if the user does that, it's too late for the script which has already moved on and then the python module stuff doesn't work.

**Comment by cchriste** [comment]
Nice catch. Thanks to whomever let you use their non-dev system to try this. 
I'm on it.
