### ISSUE TITLE
Add File->Open to ShapeWorksView2

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#130]
Then users can start the app and open a file instead of needing to understand how to do this from the command line.

**Comment by cchriste** [comment]
This is what ShapeWorksView2 was able to do and we want to add this functionality into Studio since View2 has been deprecated.

**Comment by cchriste** [comment]
related or possibly duplicate of #157

**Comment by akenmorris** [comment]
Not working on View2 anymore as it is deprecated.
