### ISSUE TITLE
Subset download for femur needs to include "R" samples that need reflection

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1300]
The reflection code sections are not included in the automated tests since none of the subset needs reflection.  To increase test coverage, we need at least one sample to be an "R" that needs reflection.

We don't need this for 6.1 as we are manually testing and fixing these code paths now, this is just something to do afterward.

**Comment by iyerkrithika21** [comment]
Instead of downloading the right side, in the case of a tiny test, reflect the left femurs.
