### ISSUE TITLE
--use_subsample not working for femur use cases

### ISSUE THREAD

**Issue by HeavenlyBerserker** [SCIInstitute/ShapeWorks#1304]
I get this.

> (shapeworks-test) hxu@hxu-SYS-5038AD-I:~/Documents/ShapeWorks-dev-3737-e124a282-linux/Examples/Python$ python RunUseCase.py --use_case femur --use_subsample
> Using shapeworks from /home/hxu/Documents/ShapeWorks/build/bin
> 
> Step 1. Extract Data
> 
> Data available in femur-v0  is sufficient, no new data will be downloaded
> Traceback (most recent call last):
>   File "RunUseCase.py", line 106, in <module>
>     module.Run_Pipeline(args)
>   File "/home/hxu/Documents/ShapeWorks-dev-3737-e124a282-linux/Examples/Python/femur.py", line 49, in Run_Pipeline
>     sample_idx = sw.data.samplemeshes(mesh_files, int(args.num_subsample))
> AttributeError: module 'shapeworks.data' has no attribute 'samplemeshes'

**Comment by akenmorris** [comment]
Apparently it's been changed from `samplemeshes` to `sample_meshes`

**Comment by HeavenlyBerserker** [comment]
Well, fuck me

**Comment by akenmorris** [comment]
Fixed in release_v6.0.1 branch.  Seemed to simple to make a PR.

**Comment by akenmorris** [comment]
If you want to just keep testing from where you were, just edit the py file and change samplemeshes to sample_meshes

**Comment by akenmorris** [comment]
The rest of the use case worked ok for me.

**Comment by HeavenlyBerserker** [comment]
Yep, I did that. Thanks.
