### ISSUE TITLE
Use cases need to be restructured so that automated tests can test all paths

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1305]
We should consider including https://coverage.readthedocs.io/en/coverage-5.5/ and insisting on a very high coverage for automated tests.

We are continually bitten by simple syntax errors such as #1304 that waste a significant amount of time from multiple people.  Someone who is testing is stopped, has to create an issue, another person looks at it, tries to solve it, confirm the problem is solved, create a PR, review, merge, back to testing.  All for a syntax error that wasn't caught because automated testing doesn't run a section of code yet.

**Comment by cchriste** [comment]
An example I noticed yesterday (and I know, I know, it's a Jupyter notebook, but it's still relevant, see #1121):
- data augmentation only shows violin plots, not 'splom' plots

**Comment by cchriste** [comment]
#1465 will provide a means to compare run time of full tests, giving us a heads up if something slows things down.

**Comment by archanasri** [comment]
Testing of use cases has been automated. Closing this now.
