### ISSUE TITLE
Update "How to Install ShapeWorks" sections of the documentation to match READMEs and make them more consistent across platforms

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1312]
The readmes are in `docs/users/<platform>_README.txt`.
The instructions are in `docs/users/install.md`.

There are a few other ideas in the comments for this issue. They're all very closely related and can be part of the same pull request, helping with a host of issues with developers testing as well as user installs, making our whole system more robust and understandable and testable. And none of them are world-changing, primarily just making things consistent for all.

**Comment by cchriste** [comment]
I updated the readmes and didn't realize we had separate installation documentation. Notably, they are now...
- very similarly organized
- partitioned into three sections: installation, python, jupyter
  - an argument could be made that conda_installs is part of installation, but it's not necessary from a user's pov
- `conda activate shapeworks` is part of the instructions, and also mentioned for subsequent use
  - this is because it was confusing not to simply put it in the main python instructions
  - *please todo:* for the jupyter section of Windows_README.txt, please add the identical line as number 2 in Mac and Linux; while line 1 says conda env should be activated, the other two are more clear by simply telling the user to activate it.

**Comment by cchriste** [comment]
Another request. Let's specify a default installation path on Linux. Relative paths are a recipe for problems that are especially difficult to address with users. Instead, let's use:
`$HOME/ShapeWorks`

This means the default paths for Linux, Windows, and OSX binaries will all be explicit rather than relative. It means the notebooks will work the same as the RunUseCase script. It does resolve custom paths to the installation any better than our current system (which lacks any method to address it for Jupyter notebooks, see issue #????), but it makes us able to provide almost the same instructions in the readme for all platforms, and eliminates confusing edge cases wrt notebooks, for which there is no good reason to run from any particular path-- perhaps create a run_notebook.sh/bat script in the ShapeWorks/bin directory? Let's add that item to issue #????).

**Comment by cchriste** [comment]
I'm working on this now. One request: can we change the color of code snippets (`text like this`)?
We use this for a lot of documentation and I think one reason we use 
```
code blocks like this
```
is because they are a calmer color than the red used for snippets. Unfortunately they end up hogging a lot of real estate and breaking up instructions making them more difficult to follow.

**Comment by sheryjoe** [comment]
I think the red color is from the readthedocs theme. Feel free to change it to a more calmer color.

**Comment by cchriste** [comment]
> Another request. Let's specify a default installation path on Linux. Relative paths are a recipe for problems that are especially difficult to address with users. Instead, let's use:
> `$HOME/ShapeWorks`

As of #1355 this is no longer relevant as the paths to both python module and executables are now correct when the conda environment is activated, regardless of installation directory.
