### ISSUE TITLE
Unclosable empty "Visualization Toolkit - OpenGL" windows popping up when running certain notebooks

### ISSUE THREAD

**Issue by HeavenlyBerserker** [SCIInstitute/ShapeWorks#1314]
Seriously, unclosable. Aaaah!!! Attempted the close all command and they're still there. Also, why are they empty?

![Screenshot from 2021-06-16 09-15-42](https://user-images.githubusercontent.com/11202328/122247142-63c82c80-ce84-11eb-963f-d017ed0f29d9.png)
![Screenshot from 2021-06-16 09-16-58](https://user-images.githubusercontent.com/11202328/122247159-662a8680-ce84-11eb-88c7-61903d1ec661.png)

**Comment by cchriste** [comment]
These used to appear with the old version of pyvista. So likely one of two things:
1) old version of pyvista is still installed (can query this from conda command line or through module in python)
2) old way of calling pyvista (can look around the notebooks and/or google to see the new way; also the command line can provide worthwhile information about deprecated usage)
3) windows is different from the other platforms (yeah, I know said "of two things")

**Comment by HeavenlyBerserker** [comment]
I tried with the three newest versions of pyvista: 0.29.1, 0.30.1, and 0.31.1. The conda_install.sh uses 0.30.1.

0.29.1 exhibits slightly different behavior; it still opens empty windows but closes them immediately. None of these are very useful.

I'm running on Ubuntu 20.04.2 LTS, btw, so I shouldn't get the issues Windows users get. @jadie1 , you run on Linux right? Have you gotten this issue before?

**Comment by jadie1** [comment]
Yes this has been happening since we added the notebooks, the windows only close when you close the notebook. I check into if pyvista is aware of the issue.

**Comment by riddhishb** [comment]
I am trying to figure this out currently, any updates on this @HeavenlyBerserker that I should know about?

**Comment by iyerkrithika21** [comment]
@riddhishb, do we need to open an issue with pyvista for this problem, or can we do something from our side?
