### ISSUE TITLE
helper functions in ellipsoid_pca use case

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#1316]
The individual use case should not have help functions defined locally. Are the `violinplot` and `plot_pca_metrics` generic enough to be moved to relevant modules in the shapeworks pymodule?

**Comment by iyerkrithika21** [comment]
`plot_pca_metrics` can be moved to plot utils but the `violinplot` is specifically for loadings so can move it after renaming it appropriately .

**Comment by iyerkrithika21** [comment]
Addressed this with #1329
