### ISSUE TITLE
windows install errors RC5

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1317]
#1273 My Windows install has many permission denied errors and does not result in a proper install. ShapeWorksStudio opens as expected, but I cannot run use cases or use jupyter. See attached output from the terminal. 
[windows10_install.txt](https://github.com/SCIInstitute/ShapeWorks/files/6664827/windows10_install.txt)

**Comment by cchriste** [comment]
Thank you. We are addressing this right now with PR #1315

**Comment by cchriste** [comment]
Hi Penny, I did not initially see the conda-related errors in your install since it wasn't installing at all for us and we were in the middle of debugging and testing. Unfortunately, the recommended solution for that part is to completely remove and reinstall anaconda/miniconda.

**Comment by patkins** [comment]
Thanks, I am trying this now.

**Comment by cchriste** [comment]
Closing this issue since we are leaps and bounds ahead in terms of deployment and documentation. 
Unfortunately, it still includes the statement:

> If you already have anaconda/miniconda installed, this step may hang. If so please uninstall anaconda/miniconda, re-install it, then run install_shapeworks again. This seems to be an occasional problem with Anaconda on Windows.

Please reopen this issue if reinstalling anaconda doesn't help and/or when you try our _upcoming_ release candidate.
