### ISSUE TITLE
Skip groom results in points throughout the volume in feature_map_example in Studio

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1318]
If the user selects Skip Groom and then Run Optimization, the optimization will place particles throughout the volume instead of on the surface. This occurs even if Run Groom has already been performed.
![image](https://user-images.githubusercontent.com/13870137/122268251-14402b80-ce99-11eb-985e-07d354c81125.png)
#1273 (the user should probably Run Groom instead of Skip Groom, but I wanted to point this out anyways)

**Comment by akenmorris** [comment]
Yeah I guess this goes back to the optimizer input verification issue. If you give the optimizer segmentations instead of distance transforms, it’s going to go haywire. 

The “skip grooming” step allows you to import and use distance transforms directly. But that’s not obvious to users, nor are there any checks.

**Comment by sheryjoe** [comment]
@patkins please mention the issue (and other issues that you submitted) in the relevant cell in the release testing table. thanks

**Comment by patkins** [comment]
@sheryjoe I am unable to edit the release testing table, sorry.

**Comment by akenmorris** [comment]
@sheryjoe , do you have any ideas on how to definitively determine if an image volume is a distance transform or not?

**Comment by akenmorris** [comment]
@sheryjoe , @patkins , do you think it would be sufficient for now to add a Question Dialog asking the user to make sure their inputs are already distance transforms if they click "skip grooming" for image based domains?

**Comment by akenmorris** [comment]
Something like this?

<img width="532" alt="image" src="https://user-images.githubusercontent.com/1693349/122446146-91ce6f00-cf5f-11eb-81b1-790c3de8e211.png">

**Comment by akenmorris** [comment]
This will display if any of the domains (e.g. multiple domains) are image type.

**Comment by patkins** [comment]
@akenmorris I think that's great!

**Comment by sheryjoe** [comment]
> @sheryjoe , do you have any ideas on how to definitively determine if an image volume is a distance transform or not?

@akenmorris it should have both +ve and -ve values and its "zero" level set should be a nonempty mesh, a binary segmentation and a regular image (CT/MRI) should fail this test.

**Comment by akenmorris** [comment]
Ok, that's a very computationally expensive check.  We might consider adding this as part of the optimizer verification check on input, but I don't think we should add this to studio for "skip grooming".

**Comment by sheryjoe** [comment]
Is checking the min and max of an image expensive? I think VTK isosurface filter throws an error if no surface found. How expensive is this?

**Comment by akenmorris** [comment]
Well, within Studio for this particular case, I think we are much better off just asking the question.  Assuming the user really does have lots of large distance transforms, we will waste a lot of time simply reading them from disk.
