### ISSUE TITLE
Studio: output filenames 

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#132]
Please avoid using "." to augment filenames, "_" is preferred. Some tools, such as paraview crash for the ambiguity of extension. Since the extension is defined by ".*"

All the point files should have an extension ".particles" - a recognized point file format in paraview

**Comment by sheryjoe** [comment]
@akenmorris still an issue?

**Comment by akenmorris** [comment]
Yes, this has been resolved.
