### ISSUE TITLE
jupyter import sw error

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1320]
#1273 I am still having issues with the module not found on linux (OpenSUSE15.2) within jupyter only (command line and python seem to be working now). I am also not sure if there is supposed to be a video in the gray box...
![image](https://user-images.githubusercontent.com/13870137/122272381-b95d0300-ce9d-11eb-8f3d-5c92f0b5ec24.png)

**Comment by cchriste** [comment]
By "command line" do you mean `python RunUseCase.py ...` or importing from a python session directly executed from the command line?

**Comment by cchriste** [comment]
> I'll be more baffled if this works but the notebook doesn't.

If it does, please also share these two things:
`echo $PYTHONPATH`
`echo $PATH`

**Comment by patkins** [comment]
`(base) C:\Users\penny>conda activate shapeworks                                                                                                                                                                                                 (shapeworks) C:\Users\penny>python                                                                                      
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)] on win32         
Type "help", "copyright", "credits" or "license" for more information.                                                  
>>> import shapeworks                                                                                                   
Traceback (most recent call last):                                                                                        
  File "<stdin>", line 1, in <module>                                                                                  
ModuleNotFoundError: No module named 'shapeworks' `

**Comment by cchriste** [comment]
> I am also not sure if there is supposed to be a video in the gray box...

@sheryjoe Can you please assign someone to address the missing video issue?

**Comment by sheryjoe** [comment]
@jadie1 could you check out the video issue?

**Comment by iyerkrithika21** [comment]
The videos are in place and can be played on other platforms. This issue is related to OpenSUSE and codecs for MP4 videos. 
https://www.reddit.com/r/firefox/comments/et4psc/firefox_doesnt_play_mp4_videos_on_opensuse/

**Comment by cchriste** [comment]
> By command line I was referring to `shapeworks optimize ...`, but `python RunUseCase.py ...` also works.

The information you provided is very helpful. 
Just to be clear, by "also works" I am guessing you mean "also works to fail to import."

The failure of both the jupyter notebooks and the command line above (running python then directly trying to import shapeworks as you showed) is due to an installation script that was broken until the fix was merged with master this morning. 

This new version should work. But before you download and install, I want you to try something directly (deep breath):
- Edit this file: `/home/wolverine/miniconda3/envs/shapeworks/lib/python3.7/site-packages/shapeworks/setup_path.py`
- Change the empty string on the third line (`""`) to look like this: `"/home/programs/ShapeWorks-v6.1.0-rc5-linux/bin/"`

Then like before simply run python from the command line and import shapeworks.

**Comment by patkins** [comment]
For clarification, I can run use cases via the command `python RunUseCase.py --use_case usecasename`.

**Comment by patkins** [comment]
@cchriste Your suggested edit to `setup_path.py` also worked, so within python, I can `import shapeworks`.

**Comment by cchriste** [comment]
> @cchriste Your suggested edit to `setup_path.py` also worked, so within python, I can `import shapeworks`.

Great! Our latest installable versions will correctly configure this.

It will also work from your jupyter notebooks (please verify for us) no matter what directory you start the server from, and RunUseCase.py will work similarly from anywhere you call it.

**Comment by cchriste** [comment]
I just verified Windows install works (simultaneously, Alan had a conda issue similar to the one described above; I added `conda env remove -n shapeworks` in #1330, which might help and won't hurt). Closing this issue.

**Comment by jadie1** [comment]
> The videos are in place and can be played on other platforms. This issue is related to OpenSUSE and codecs for MP4 videos.
> https://www.reddit.com/r/firefox/comments/et4psc/firefox_doesnt_play_mp4_videos_on_opensuse/

@patkins I open the notebooks on Chrome with OpenSUSE and they display correctly. Not sure what we can do about the OpenSUSE/firefox issue.
