### ISSUE TITLE
DeepSSM use case crashes with error

### ISSUE THREAD

**Issue by HeavenlyBerserker** [SCIInstitute/ShapeWorks#1322]
After running for >2 days, Path issue? [deep_ssm_log.txt](https://github.com/SCIInstitute/ShapeWorks/files/6665515/deep_ssm_log.txt). Can we get a smaller use case for this? It takes way too long.

> Traceback (most recent call last):
>   File "RunUseCase.py", line 106, in <module>
>     module.Run_Pipeline(args)
>   File "/home/hxu/Documents/ShapeWorks-dev-3737-e124a282-linux/Examples/Python/deep_ssm.py", line 176, in Run_Pipeline
>     avg_distance = DeepSSMUtils.analyzeResults(out_dir, DT_dir, prediction_dir + 'FT_Predictions/', mean_prefix)
>   File "/home/hxu/anaconda3/envs/shapeworks-test/lib/python3.7/site-packages/DeepSSMUtils/__init__.py", line 26, in analyzeResults
>     avg_distance = eval_utils.get_distance_meshes(out_dir, DT_dir, prediction_dir, mean_prefix)
>   File "/home/hxu/anaconda3/envs/shapeworks-test/lib/python3.7/site-packages/DeepSSMUtils/eval_utils.py", line 12, in get_distance_meshes
>     for file in os.listdir(prediction_dir):
> FileNotFoundError: [Errno 2] No such file or directory: 'Output/deep_ssm/Results/PredictedParticles/FT_Predictions/'

**Comment by jadie1** [comment]
Thanks, this was fixed in PR #1307. To run a smaller test you can reduce num_samples on line 76 and epochs on line 132

**Comment by HeavenlyBerserker** [comment]
Oh, I see. I'll test it on the new artifact and close it if it works. What are good numbers for num_samples and epochs, @jadie1 ?

**Comment by jadie1** [comment]
Thanks! If it works for low value it will work for high values, the results just won't be as good. So you could do something like 3 for both.

**Comment by HeavenlyBerserker** [comment]
Seems to work. `Average surface-to-surface distance from the original to predicted shape = 4.516291423311977`

I'll close this.
