### ISSUE TITLE
Docs: Update groom.md with new mesh grooming steps

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#1325]
We should update groom.md to also include mesh grooming steps for optimizing particles on meshes.

**Comment by jadie1** [comment]
Moving to 6.3 for when we have mesh grooming steps in the use cases

**Comment by iyerkrithika21** [comment]
We have included the typical steps used in mesh grooming and updated the use cases and documents to show mesh grooming. 
http://sciinstitute.github.io/ShapeWorks/6.2/workflow/groom.html#remesh
I think we can close this 
@sheryjoe @akenmorris

**Comment by akenmorris** [comment]
Done
