### ISSUE TITLE
update studio splash screen and readmes and docs to say 2021

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1334]

**Comment by akenmorris** [comment]
Studio splash screen is updated in fix-docs branch.

**Comment by cchriste** [comment]
I've reviewed and updated [installation] readmes (see #1335) and they now say 2021 (before they didn't say anything)

**Comment by cchriste** [comment]
> Studio splash screen is updated in fix-docs branch.

Has the updated documentation branch been merged yet? I'm going through notebooks and documentation and learning that some of the changes I'm making were already noted. If not, can we get a pull request open?
