### ISSUE TITLE
clicking on sections in documentation TOC always returns to the top

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1341]
Also, it would be better to have things like "Use Cases" be sections so selecting one of them shows a list of available use cases. Then such a link could be made available in RunUseCase's --help (#1103).

This could be related to a theme's `navigation_depth` and `stick_navigation`, though the default parameters for both should Just Work™. See https://www.mkdocs.org/user-guide/choosing-your-theme/

**Comment by akenmorris** [comment]
I believe this is fixed with the new theme.
