### ISSUE TITLE
distill duplicate sections of documentation

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1347]
In general, there are lots and lots of cut-and-pasted pages or subsections thereof in the docs, for example in the Use Case descriptions. Is it possible there is a better way to organize these use case descriptions? They may not all be identical, but if a user has gone through a couple of them they'll be skimming the things they've read before and very likely miss any differences. 

A shared section might instead summarize and each use case description note any differences.

**Comment by iyerkrithika21** [comment]
For each use case include three sections:

1. What is this use case demonstrating? what is different/new?
 - Explain the features of the input data
2. Reference output
3. Default optimization parameters 

One page explaining all the tags available for the use cases.
