### ISSUE TITLE
RC12 documentation for Examples

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1349]
#1273 The install worked well (I was able to run a use case and notebook tutorial), however it seems the commands for the use cases have changed, but have not been updated in the Windows_README.txt 
```
4. Run one of the included use cases. To list them all, run: `python RunUseCase.py --help`.
`python RunUseCase.py --use_case ellipsoid_fd`. 
```
Anaconda console output:
```
(shapeworks) C:\Users\penny\Documents\shapeworks\Examples\Python>python RunUseCase.py --use_case ellipsoid
Using shapeworks module from C:\Users\penny\miniconda3\envs\shapeworks\lib\site-packages\shapeworks\__init__.py
Using shapeworks from c:\Program Files\ShapeWorks\bin\shapeworks.EXE
usage: RunUseCase.py [-h] [--use_subsample] [--num_subsample NUM_SUBSAMPLE]
                     [--interactive] [--skip_grooming] [--groom_images]
                     [--use_single_scale] [--tiny_test]
                     {ellipsoid,ellipsoid_evaluate,ellipsoid_mesh,ellipsoid_fd,ellipsoid_cut,ellipsoid_pca,ellipsoid_multiple_domain,ellipsoid_multiple_domain_mesh,lumps,left_atrium,femur,femur_mesh,femur_cut,deep_ssm,supershapes_1mode_contour,thin_cavity_bean}
RunUseCase.py: error: unrecognized arguments: --use_case

(shapeworks) C:\Users\penny\Documents\shapeworks\Examples\Python>python RunUseCase.py ellipsoid
```

There is also no feedback for the user if the folder doesn't exist (i.e. has not yet been unzipped) in the notebook` getting-started-with-exploring-segmentations.ipynb`, this is super minor, but may help novice users.

**Comment by cchriste** [comment]
Good catch, Penny. Thank you!

Devs: I've created `misc_61` branch for little stuff like this so we don't have to wrangle a bunch more PRs but can instead get everything that doesn't modify functionality in with one later today.

**Comment by sheryjoe** [comment]
@cchriste is this resolved?
