### ISSUE TITLE
Prep alignment tools (COM and ICP) shouldnot directly apply transformation to binary images

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#135]
To align a binary segmentation, use antialiasing -> distance transform -> resample -> thresholding to apply the transformation.

**Comment by sheryjoe** [comment]
@jadie1 this should have been addressed already. please double-check.

**Comment by jadie1** [comment]
@sheryjoe in the use cases (GroomUtils) and the notebooks, we do antialiasing -> applyTransform -> binarize 
Is this acceptable? We are not taking the distance transform as the original issue suggests.

**Comment by sheryjoe** [comment]
@jadie1 antialiasing should work too. closing the issue.
