### ISSUE TITLE
Running install_shapeworks.bat on remote CADE Windows machine demands Admin permissions

### ISSUE THREAD

**Issue by HeavenlyBerserker** [SCIInstitute/ShapeWorks#1351]
It asks for admin permissions >20 times. I'm running `install_shapeworks.bat` from the Anaconda Prompt as specified in the [dev instructions](http://sciinstitute.github.io/ShapeWorks/dev/build.html).

It asks for admin permissions on every line of these DEBUG things (there are 4 blocks of these DEBUG lines)
![Screenshot from 2021-06-24 09-44-23](https://user-images.githubusercontent.com/11202328/123296970-58a07c80-d4d4-11eb-855c-318149be5609.png)

I installed Anaconda in that location, which did not require admin permissions, so I find it weird that the admin window pops up so many times too.

**Comment by cchriste** [comment]
Is there a way to reproduce this issue on my local Windows machine, such as by creating a new user without admin privileges? Did it let you install to the default path or did you have to use a custom directory?

**Comment by HeavenlyBerserker** [comment]
Yep, maybe create another user. I installed anaconda3 in my home directory `C:\Users\<name_of_user>\`, which I believe is standard, and just ran `install_shapeworks.bat` from a newly cloned ShapeWorks.

Another option is that if you have access to CADE, you can also remote in and try there. [Instructions here](https://www.cade.utah.edu/remote-desktop-access/)

**Comment by akenmorris** [comment]
@HeavenlyBerserker , why is it trying to write to C:\Anaconda?

Is Anaconda already installed on these CADE machines?

**Comment by HeavenlyBerserker** [comment]
Good question. I asked myself the same thing. Everything I install in `C:\Users\<name_of_user>\` ends up in `C:\`. I imagine the system has a soft link between those directories.

I didn't explore further. Do y'all have access to these machines? Maybe it's an issue with these machines. Let me try by creating a new user on my personal Windows machine instead.

**Comment by akenmorris** [comment]
I'm looking at how to access, but I very much doubt I have a CoE account as described here:

https://www.cade.utah.edu/faqs/which-usernamepassword-should-i-use-for-insert-service-name/

If it's not tied to SCI or CIS, I don't have access.

**Comment by HeavenlyBerserker** [comment]
Let me try on my new user account and will get back to you.

**Comment by akenmorris** [comment]
I wasn't able to install shapeworks without admin privileges.  Just running the installer requires administrator access.  You have administrator access on the CADE machines?

**Comment by HeavenlyBerserker** [comment]
Hmm, not that I know of. That's strange.

I was able to run it successfully on my other user account. Let's close this and write this off as a "CADE machines are weird and nobody should try to run ShapeWorks on them" learning experience?

**Comment by akenmorris** [comment]
> Clone SWs?

Huh?

**Comment by akenmorris** [comment]
I would say we close this until a user complains.

My guess is that the majority of windows users will have admin access and be local desktops.

**Comment by HeavenlyBerserker** [comment]
> > Clone SWs?
> 
> Huh?

Oh, I'm reviewing the dev instructions on Windows. I'm guessing you're just testing the release. Dev instructions require Anaconda, so that's why I don't need Admin for most of the `install_shapeworks.bat`.

I'll close this then.

**Comment by akenmorris** [comment]
Oh, you're doing the dev instructions?  I think we can assume shapeworks dev user will be admin.

**Comment by HeavenlyBerserker** [comment]
Makes sense. I just realized you definitely need Admin permissions to install Qt5, unless you want to download a portable version from sketchy sources.
