### ISSUE TITLE
update shapeworks docs with latest images and videos

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1352]
Front page news! Read all about it!
But http://sciinstitute.github.io/ShapeWorks/index.html still shows 6.0 and should show 6.1. 

Any of the other excellent images from last week's presentation would be great to include.

**Comment by sheryjoe** [comment]
fixed release image on the index page.

@akenmorris do we have a tour video for 6.1?

**Comment by akenmorris** [comment]
Do you mean for Studio?  I can work on one.

**Comment by sheryjoe** [comment]
Yes. Studio is the best front end to demonstrate new features. Please include features in the release notes (esp in the graphical abstract) that can be demonstrated within Studio. Thanks!

**Comment by sheryjoe** [comment]
Done in misc_61

@cchriste any other images that you see fit to add?

**Comment by sheryjoe** [comment]
closing this now. please create a new issue with more specific details on what is missing if any.
