### ISSUE TITLE
Remove "geometry-central" from deployment

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1357]
It might be coming from 'make install'.

**Comment by akenmorris** [comment]
Completed in #1488

**Comment by sheryjoe** [comment]
@akenmorris can geodesics computation still use geometry central?

**Comment by akenmorris** [comment]
Yeah, the issue title was a little misleading, this referred to a "geometry-central" folder in the root folder of the binary install.  It contained the source of geometry-central.
