### ISSUE TITLE
Feature map color bar control

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1359]
The feature map color bar seems to adjust automatically, such that when two groups are compared that have different feature value ranges, the color bar is different for the two groups (0.6-7.2 for cam, 0.8-8.0 for control in the images below). This makes it difficult to compare feature values between groups. 
![image](https://user-images.githubusercontent.com/13870137/123690027-27e08000-d811-11eb-8df0-9f661a3ebff1.png)
![image](https://user-images.githubusercontent.com/13870137/123690003-1eefae80-d811-11eb-9df9-3b29dddda794.png)

I would prefer the ability to choose the bounds of the color map, but it should at least be constant (or based on the range from the input data) if it cannot be altered by the user.

**Comment by akenmorris** [comment]
Completed in #1455
