### ISSUE TITLE
ShapeWorksRun: Point splitting

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#136]
How about we put a parameter for point splitting?
with the default value set to 2, the parameter determines that "into how many points a correspondence would be split" during hierarchical splitting. This may help reduce the time required to achieve the desired number of points. We can modify the scripts with a higher value for this parameter in initial stages of splitting and maybe a lower value at the denser stage. 

We can discuss this first and see if this could be a good idea.

**Comment by sheryjoe** [comment]
I am not in favor of this route for two reasons:
- The directional ambiguity of more than 2 points split from a single correspondence
- With more points added at each scale, the optimization problem might be even harder, so this might hurt the correspondence convergence. This splitting strategy is meant to solve a highly nonlinear/nonconvex optimization by optimizing simpler models first, similar to multi-resolution optimization in image registration.

**Comment by akenmorris** [comment]
@sheryjoe, can we close this issue?

**Comment by sheryjoe** [comment]
Yes/
