### ISSUE TITLE
Write image changing coordinate system

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1362]
Tanner noticed that when you read some diccom images and then write them as nrrd's the coordinate system changes.
Here is screenshot of the diccom and resulting nrrd from write-image in paraview:
![shoulder](https://user-images.githubusercontent.com/54382613/123988621-672fdd80-d985-11eb-910b-1e858d14b0d6.png)

**Comment by jadie1** [comment]
This may be a paraview issue... when I load the diccom and nrrd with shapeworks and print them the dims, origin, size, and spacing match.

**Comment by sheryjoe** [comment]
I would load both in itksnap (overlayed) as a sanity check.

**Comment by jadie1** [comment]
If I do the following:
`sw.Image(diccom).setOrigin((0,0,0)).write(nrrd)`
Then the output nrrd and diccom appear aligned in paraview, so paraview might always display diccoms with origin (0,0,0). 

I'll check itksnap

**Comment by jadie1** [comment]
They are identical in itksnap, this must be a paraview issue.
