### ISSUE TITLE
Bug in Feature Map group mean calculations

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1367]
Using data from the cortical thickness project from several years ago, I generated a model from the vtk mesh files which include scalar data representing cortical thickness (Shell Thickness) as the feature map. In reviewing the results, the group mean thickness values seemed to contradict our previous finding that cortical thickness was greater in cam than control. To verify the current results, I removed the control femurs from the studio file such that only the cam femurs were included and evaluated the results (cam only model), which then matched our previous findings. In the figures below, the cam group mean from the cam only model has the shape of the cam group mean from the combined model, but the feature data from the control group mean from the combined model. This is using ShapeWorksStudio from the 6.1 Release on linux.

Combined model (cam group mean): 
![image](https://user-images.githubusercontent.com/13870137/124151078-68c5d800-da4f-11eb-8694-241052b30416.png)

Combined model (control group mean):
![image](https://user-images.githubusercontent.com/13870137/124151117-74b19a00-da4f-11eb-9c80-be81a8f7adaa.png)

Cam only model (cam group mean):
![image](https://user-images.githubusercontent.com/13870137/124151174-8135f280-da4f-11eb-8f3c-b809a4b64b28.png)

**Comment by patkins** [comment]
I uploaded the data [here](/home/sci/atkins/SWIssues/corticalThickness/) for reference.

**Comment by akenmorris** [comment]
Seems like it's flipped, right?

**Comment by patkins** [comment]
Exactly, the thickness for the other group is shown.

**Comment by akenmorris** [comment]
Yeah, it looks like the logic was inverted for applying the slider.  Will fix.

**Comment by akenmorris** [comment]
Fixed.
