### ISSUE TITLE
Studio hangs when opening a specific project file

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1368]
Studio hangs upon loading a specific project file for analysis (corticalThickness_meshes_control.xlsx). I had a single project file (corticalThickness_meshes.xlsx) which I split into two separate analysis files specific to the two groups (cam and control) by removing the data for files associated with the other group. The combined project and the cam project open fine, but studio hangs when opening the control group specific project file. I have tried this on two machines (opensuse and windows) and it seems to have the same behavior on both, without any specific error. The data and project files (within the paramfiles folder) can be found in /home/sci/atkins/SWIssues/corticalThickness.

**Comment by akenmorris** [comment]
It wasn't the fastest startup, maybe 30 seconds, but it loaded ok for me:

<img width="1112" alt="Screen Shot 2021-07-02 at 11 39 54 AM" src="https://user-images.githubusercontent.com/1693349/124311618-42756a80-db2b-11eb-8f5a-d27a1f8b8bc6.png">

Looking at a quick profile, the display is being updated in several places and with this number of particles, the feature map code is fairly slow.

**Comment by patkins** [comment]
The issue project is the one with the suffix of '_control' - does that one also work on your end?

**Comment by akenmorris** [comment]
My bad, I was re-skimming the message and just saw the first filename.

It's hanging in the XLSX reader unfortunately.  Excel opens it just fine.  I noticed the groomed column is messed up:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/1693349/124320522-49a37500-db39-11eb-95ad-7052f7236d03.png">


I delete this column, saved it and then Studio opened it ok.  I'm not sure the interaction.  Maybe just resaving it fixed the file.  Did you use Excel or OpenOffice?

[corticalThickness_meshes_control2.xlsx](https://github.com/SCIInstitute/ShapeWorks/files/6756619/corticalThickness_meshes_control2.xlsx)

**Comment by patkins** [comment]
Interesting. I was using LibreOffice Calc to make edits to an existing file (clearly having an issue with find and replace...). The groomed column would have been equally as messed up in the full file with no suffix though. I did have a similar issue yesterday on another project file though and when I tried to package it up as another example of the issue, it started working, so maybe it's an issue with LibreOffice?

**Comment by akenmorris** [comment]
Ok, I think I see the problem.  It's getting 1048576 rows (which is apparently the max rows for excel), and it thinks this is how many subject there are and is doing queries into the spreadsheet to fill out every subject.  All of the rows are blank except the filled in ones.

I should be able to fix this in Studio.

**Comment by patkins** [comment]
Nice find! 

I left it for probably 15 minutes, which seems like more than enough considering the load time for other files, but 1048576 is a very large number.
