### ISSUE TITLE
Uniform logging interface/library (primarily optimizer)

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1377]
This would replace the internal logging interface in Studio and the verbosity controlled stuff in the optimizer.

Some options:

spdlog - https://github.com/gabime/spdlog
glog - https://github.com/google/glog
loguru - https://github.com/google/glog
g3log - https://github.com/KjellKod/g3log

Some commentary:
https://www.reddit.com/r/cpp/comments/a3gp0s/best_logging_libraries/
https://kjellkod.wordpress.com/2015/06/30/the-worlds-fastest-logger-vs-g3log/

I'm currently leaning toward spdlog.  @cchriste, any thoughts?

**Comment by sheryjoe** [comment]
@all please share your feedback.

**Comment by akenmorris** [comment]
spdlog has been integrated.
