### ISSUE TITLE
New use case which demonstrates the group difference statistics

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1392]
- [x] Identify which dataset can be used to group difference - femur? 
- [ ] Femur data on portal - does it contain normal and pathological samples?
- [x] Use the stats functionality from the python module to calculate the p-values and save them in text file
Related to #1271

**Comment by sheryjoe** [comment]
@iyerkrithika21 please update the slides templates with the newly opened issues. thanks.
