### ISSUE TITLE
add option to save meshes as ascii

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1400]
Add to command line, python api, and Mesh functions.

For Meshes (Images are already binary) 
Default to binary.

Tests to ensure both ascii and binary work:
- readable across platforms
- application to test include Paraview, VisIt, FEBio Studio, Seg3D, Cloud Compare

@archanasri Please attach binary mesh to this issue.

**Comment by akenmorris** [comment]
Images?  What ASCII image format is there?

**Comment by cchriste** [comment]
> Images? What ASCII image format is there?

Haha! [ppm of course. ](http://netpbm.sourceforge.net/doc/ppm.html)

**Comment by cchriste** [comment]
It might help with debugging, but otherwise is this important to write ascii anything?
It's semi-related to #725...

**Comment by akenmorris** [comment]
It is.  Our users interoperate data with other tools.  One example is CloudCompare that reads only ASCII legacy VTK files.
