### ISSUE TITLE
Extra space in optimize params in studio

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#1401]
This is from Studio running on windows and maximized. Is the space between Number of particles and other params expected?

<img width="218" alt="image" src="https://user-images.githubusercontent.com/3253036/127360483-1111a58b-c1eb-4d32-8328-ba1ac6ef9c2f.png">

**Comment by akenmorris** [comment]
I haven't been able to reproduce this so far.   I tried both ShapeWorks 6.0.0 and 6.1.0.  This is what the layout looks like for me on windows 10:

![studio_optimize_layout_win10](https://user-images.githubusercontent.com/1693349/127512853-a268ee1d-08ee-41a2-84be-185d7604f098.png)

**Comment by akenmorris** [comment]
I thought perhaps this might happen if you load a project with multiple domains, which populates multiple particle boxes, and then load a single domain project, but for me this resulted in the same correct layout.

**Comment by akenmorris** [comment]
I was able to reproduce this.  This happens when one of the other tabs has expanded the layout of the control panel.

<img width="399" alt="image" src="https://user-images.githubusercontent.com/1693349/131865171-bbc6d16f-fcfd-4b04-b08c-c58c7cf6ce21.png">
