### ISSUE TITLE
Create mesh grooming example

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1404]
Maybe work with Rich or Penny to identify necessary steps and expected results wrt centering, scaling, smoothing, and adjusting vertex density.

**Comment by jadie1** [comment]
Do we need this now that we have mesh grooming in the use cases?

**Comment by sheryjoe** [comment]
I don't think so. Please make sure that documentation is updated accordingly.

**Comment by iyerkrithika21** [comment]
femur_cut, ellipsoid_mesh, and ellipsoid_multiple_domain_mesh all demonstrate mesh grooming.
