### ISSUE TITLE
Add scalar value export option for particles

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1417]
In ShapeWorksStudio, add an option to export scalar values for all particles (current option for exporting scalars is based on reconstructed mesh nodes instead of particles).

**Comment by akenmorris** [comment]
What scalar values are you interested in here?  From the feature map?

**Comment by patkins** [comment]
Yeah, the scalar values from the feature map.

**Comment by sheryjoe** [comment]
@akenmorris this is a use case for #1080

**Comment by patkins** [comment]
This seems to export data for each mesh node instead of each particle. Additionally, if you try to overwrite the data you end up with additional data in the files (but it seems to be a random number of additional rows).

**Comment by sheryjoe** [comment]
@akenmorris we can enable users to choose whether to export on particles or surface meshes. the latter option is useful of visualization purposes... etc

**Comment by patkins** [comment]
I would agree that the export of scalar values on the 'current mesh' is definitely valuable.

**Comment by akenmorris** [comment]
I've fixed "Export All Subjects Particle Scalars" to export the particles rather than the mesh vertices.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/1693349/168332700-568c512e-14e5-4f58-8dda-23ae51e24c15.png">

Do we also need "Export All Subjects Mesh Scalars"?

**Comment by patkins** [comment]
I wouldn't think so, since the meshes come in with scalars. But would there be a need for volumetric inputs?

**Comment by akenmorris** [comment]
I don't know if it would be useful to anyone.  I guess I can probably add it without too much trouble.

**Comment by akenmorris** [comment]
Added a separate issue for it, #1763
