### ISSUE TITLE
DeepSSM in studio - Testing bug

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1419]
When running DeepSSM in studio, I ran augmentation and training then clicked back to the augmentation tab just to look at it. I then clicked the testing tab and studio closed with a seg fault.

**Comment by akenmorris** [comment]
Are you able to reproduce this?  I've been trying but have been unable to do so.

**Comment by jadie1** [comment]
I did recreate it yesterday but now I can't... I will close this for now and keep an eye out for it.

**Comment by akenmorris** [comment]
When you open the testing tab, it will try to read the testing files. Had you run testing before on this project?

**Comment by jadie1** [comment]
Yeah and I just ran testing successfully on the same project spreadsheet again so I'm not sure what happened.
