### ISSUE TITLE
Add feature to select initialization points

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1423]
Incorporate a feature to select point(s) in space for initialization of the correspondence model. Some models will require more than one initialization point (cartilage models are good examples, if a test case is desired, please reach out). To allow the user to ensure proper projection from the point in space to the model, it may be helpful to be able to visualize all aligned shapes simultaneously for selection and then to visualize the projection on each shape individually (similar to the paned subject viewer used now). 

Alternatively, this could be done based on the axes from a fit ellipsoid or via clustering analysis of the xyz and normals data, however initial testing indicates inconsistent success with these methods dependent on the geometry and variability of the data.

**Comment by akenmorris** [comment]
Makes sense. Will tie in with functionality for landmarks for alignment as well.

**Comment by akenmorris** [comment]
Completed in #1639
