### ISSUE TITLE
Failed grooming step results in incorrect file being written

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1428]
Preface: This happened once to me a while ago and I figured that it was some kind of error in data management, but then I observed it again today and noticed a discrepancy in file time/date. I, unfortunately, cannot recreate it nor do I know any specifics of the error that caused the issue, so this might not be at all helpful. Sorry. 

If there is an error for one of the surfaces during grooming in ShapeWorksStudio, it seems that the groomed surface of one shape can get written under the filename of another shape. Example: A_surface_groomed data is written as B_surface_groomed.vtk and nothing is written for A_surface_groomed.vtk. Rerunning grooming results in the correct files being written for both A and B, so I don't believe the error had to do with the surfaces themselves. In both scenarios, it was not the first time that I had groomed the surfaces, so files were being overwritten in the process (but I was also able to do this successfully when rerunning grooming, so this isn't a cause, but potentially a contributor). Smoothing was the only grooming feature being used.

**Comment by akenmorris** [comment]
This should be fixed now.
