### ISSUE TITLE
Parsing Vertebrae Spreadsheet

### ISSUE THREAD

**Issue by nawazishkhan1-nk** [SCIInstitute/ShapeWorks#1438]
Script for processing the Vertebrae Spreadsheet and fetching segmentation files based on classes and classification codes.

**Comment by cchriste** [comment]
Please add a label (maybe enhancement or feature request? or is this something else like a task for a specific project?). 
Also please specify an assignee who understands the details and context of this issue.

**Comment by nawazishkhan1-nk** [comment]
Spreadsheet processing specific to Vertebra Dataset
