### ISSUE TITLE
Reconstruction/FEMesh should transfer data in memory rather than a file

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#144]
The surface Reconstruction class is currently writing a VTK file to disk and having FEImport read it in order to convert the mesh.  This should either be done directly from the polydata or the ASCII polydata should be written and read to/from a memory buffer.

**Comment by sheryjoe** [comment]
@akenmorris this should have been addressed with an API to load vtk files. right?

**Comment by akenmorris** [comment]
Yes, this was resolved in a temporary way by having the mesh written to a memory buffer and then have FEImport read from a memory buffer.  At some point, it would be better for someone to write a direct converter between the data structures.  But what's there works.
