### ISSUE TITLE
Release notes for 6.2

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1442]
Please add to this issue a paragraph (plus videos/snapshots for illustration) about each new/improved/bug-fix included in this release. Please add bullets to the below outline that are relevant to your contributions for the 6.2 release. 

- Multiple domain support polishing
- Free-form constraints
- Shared boundaries
- DeepSSM in Studio
- Statistical tests in Studio
- Nonlinear SSM
- Consolidations and Python APIs
- Documentation
- Deployment

**Comment by HeavenlyBerserker** [comment]
Free-form constraints

- FFCs support has been added. 
- Added a unit test for FFCs, a typical sphere unit test with a constraint that cuts the sphere like a tennis ball grove.
![Screenshot from 2021-08-14 14-38-46](https://user-images.githubusercontent.com/11202328/130114170-a059eb13-cb96-46fa-9f48-219eec88e754.png)
- Also added a unit test with two domains, both spheres in different locations. The first sphere has one cutting plane and 25 sphere constraints, the second sphere has one cutting plane and one free form constraint. 
![Screenshot from 2021-08-30 11-55-56](https://user-images.githubusercontent.com/11202328/131385115-6acae663-fd1d-4074-8944-a8d14facc6d1.png)

**Comment by akenmorris** [comment]
DeepSSM in Studio
Multiple alignments
Group P-values
Shape Evaluation Charts
Feature map scalar control
Opacity controls
Expose narrow band parameter
Added log window
Added new suppressible error dialog
Multiple domain export options (combined + separate)
Allow initial points?
Write individual procrustes transforms
Fix processing of non-RAI images

**Comment by cchriste** [comment]
Backend developer fixes for Windows.
Transparent, copy-free passing of image data between Python and C++.

Most everything else I've done has been work helping other developers.

**Comment by sheryjoe** [comment]
@all, could you please add more details on each? with figures/videos when applicable. These will be used for our online documentation, so list of things won't be enough to convey new/fixed/improve features in our software. Thanks.

**Comment by iyerkrithika21** [comment]
1. Femur use case analyzing the group differences
A new use case has been added, demonstrating the functionality of shape statistics tools to perform hypothesis testing of group shape differences. This use case analyzes the femur shape model obtained from running the Femur: SSM from Meshes use case. Separate statistical tests for differences in correspondence positions are applied to every correspondence index. We use Hotelling $T^2$ metric(nonparametric permutation test) with false discovery rate correction (FDR) for multiple comparisons. This method helps identify and visualize localized regions of significant shape differences. 

2. Sub-sampling for multiple domains
We can now perform subsampling for multiple domains data by combining the individual shapes from all the domains and generating combined shapes. We perform a clustering-based subset selection on the combined shapes so that the subset is representative of the entire dataset and all domains. 

3. Restructured ellipsoid_evaluate use case
The computation time for calculating specificity, compactness, and generalization has been reduced. We can now calculate the evaluation metrics for all the modes or query the values for a specified mode. The use case has been modified to demonstrates these functionalities.

**Comment by jadie1** [comment]
Snapshots for DeepSSM in Studio:

- Loading data ![image](https://user-images.githubusercontent.com/54382613/134055096-69d554e1-60dd-45d2-87b7-9fd68b1ed0ca.png)
- Splitting data ![image](https://user-images.githubusercontent.com/54382613/134055211-f984bf31-5eb7-4ebe-9963-157a27cd9fac.png)
- Data Augmentation ![image](https://user-images.githubusercontent.com/54382613/134055288-fdc48f91-0471-4c8f-a579-118e3e13e98c.png)
- Training ![image](https://user-images.githubusercontent.com/54382613/134055333-9acb714b-362b-485a-a7a6-260f7708a77a.png)
- Testing ![image](https://user-images.githubusercontent.com/54382613/134055385-64e9dd1c-7b3d-4e1c-8ea6-1f7cf7704ebb.png)
More snapshots can be found here: http://sciinstitute.github.io/ShapeWorks/studio/deepssm-in-studio.html

**Comment by jadie1** [comment]
A few other updates:

- Use Cases: Added --mesh_mode option to image-based use cases. When running in mesh mode, after grooming distance transforms are converted to meshes and optimization is done on meshes
- Shape Cohort Generation: Added segmentation and image generation for 2D contour supershapes.
Segmentations: 
![image](https://user-images.githubusercontent.com/54382613/134228758-076f9605-7673-4cea-9590-22389e9c00c1.png)![image](https://user-images.githubusercontent.com/54382613/134228790-9fa32f63-cf34-4b64-8715-358c2f363acc.png)
Images:
![image](https://user-images.githubusercontent.com/54382613/134229014-5b2b03d3-d57c-4429-8727-be6e027f4537.png) ![image](https://user-images.githubusercontent.com/54382613/134229055-b4787f94-2e2f-4627-aa22-fe68d79d2823.png)
- Improved use case documentation and explanation of modes of variation.

**Comment by archanasri** [comment]
- Consolidation of Mesh grooming executables: curvature, cvdDecimate, fixElement, geodesicDistance between 2 points on mesh, geodesicDistance between all points on mesh to another point (landmark), geodesicDistance between all points on mesh and set of points (curve), computeMeanNormals
- Added mesh query operations: operator+=, closest point, closestPointId, points (list of all points on mesh), faces (list of all faces on mesh, getFace
- Fixed memory leak issues in FEMesh operations
- More robust testing of Python tests
- More efficient conversion of shapeworks mesh to vtk mesh
- Copy-free bidirectional passing of mesh fields
- Images can now be safely constructed without copying and passed without copying from/to Python
- in particular, passing Images for rendering using pyvista is now transparent and copy-free
- note: copying is still supported if necessary
- example jupyter notebook added to demonstrate Image initialization and passing
- added support for passing of multi-value fields in addition to scalar fields
- more robust python bindings of shapeworks API with interactive help
- better testing: reproducibility of functionality using randoms and performance testing
- improved API for Mesh and Image classes (simpler, safer by using const when appropriate)
- can now set coordsys of images in Python
