### ISSUE TITLE
Outside domain error in fixed domain optimization

### ISSUE THREAD

**Issue by WeeenZh** [SCIInstitute/ShapeWorks#1451]
I am using the example code "~/Examples/Python/ellipsoid_fd.py" to operate fixed domain optimization on the femur data.  It reports "outside the given image domain” error.

I don’t think its related to inadequate padding. Because I have tried only one smallest test shape as well as one of the training shape. Both experiments reported the same error.

I think something went wrong just with fixed domain optimization. When I removed the fixed domains in the xml file, it runs without errors.

Running with "use_normals=0" is good. Probably it is not compatible.

This happens with "ShapeWorks-v5.4.1-linux". @riddhishb and @jadie1 have seen it in version 6.1 as well.

Here is my error:
> Initializing variables...
> itk::ExceptionObject (0x2a89ea0)
> Location: "unknown" 
> File: /home/runner/work/ShapeWorks/ShapeWorks/Libs/Optimize/ParticleSystem/itkParticleImageDomainWithGradients.h
> Line: 61
> Description: itk::ERROR: DataObject(0x2a8d2d0): Gradient queried for a Point, [56.5148, 56.0831, 128.539], outside the given image domain.

**Comment by akenmorris** [comment]
Yeah, fixed domains does not work with use_normals yet.  Should we consider this a duplicate of #566 ?  Or are you having this problem even with normals disabled?

**Comment by WeeenZh** [comment]
> Yeah, fixed domains does not work with use_normals yet. Should we consider this a duplicate of #566 ? Or are you having this problem even with normals disabled?

Oh you are right. It is a duplicate. I think we can close this then. There is no more problem with normals disabled. Thanks!
