### ISSUE TITLE
How to report Singular Matrix in group p-value calc?

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1457]
For some data, running the group p-value code returns:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/1693349/132408845-a0b71ded-a212-4dcb-be76-7716f5774056.png">

I'm not really proposing to fix this.  But shall we `catch` this and provide a more intelligible message to the user?

**Comment by sheryjoe** [comment]
I agree that we need a more interpretable message for the user, but it is difficult now without knowing the involved computation. Is this a numerical error that can be resolved? What is the cause of this error? what is the computation involved here? @iyerkrithika21 ?

**Comment by akenmorris** [comment]
Another message if you only give it two shapes:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/1693349/133145754-08b946d8-e380-41e6-a4e8-5c6fd0ecdcb9.png">

**Comment by iyerkrithika21** [comment]
> 
> 
> Another message if you only give it two shapes:
> 
> <img alt="image" width="658" src="https://user-images.githubusercontent.com/1693349/133145754-08b946d8-e380-41e6-a4e8-5c6fd0ecdcb9.png">

This error is because of we are calling `bessel correction`

```
"""bessel_correction.
    Sampling tends to underestimate variability of a population. This is due to the fact that we are more likely to
    sample around the mean than near the extremities. Bessel's correction uses n−1 instead of n which is used to
    calculate variance etc, in order to correct for the bias in the estimation of the population variance.
    :param x: array-like, samples of observations
    :param y: array-like, samples of observations, optional
    :return: returns x_n - 1, y_n - 1
    """
 ```
 
 Since one shape per group is given, it cannot apply this correction.
 We can assert the number of shapes per group to be greater than 1.

**Comment by iyerkrithika21** [comment]
> 
> 
> I agree that we need a more interpretable message for the user, but it is difficult now without knowing the involved computation. Is this a numerical error that can be resolved? What is the cause of this error? what is the computation involved here? @iyerkrithika21 ?

The python package is implementing this :
![image](https://user-images.githubusercontent.com/11266258/133151547-cc180089-a693-4aac-8388-e4bff77dbcc7.png)

The error mentioned by Alan in the description is occurring because the  pooled covariance matrix estimate is singular, hence it cannot to be inverted with `np.linalg.solve` (used by the package)

**Comment by akenmorris** [comment]
Ok, we can provide a nice error message for when there aren't enough samples.

I'm not sure what to do about the other message.  I was trying to read about when this would happen.  If there is correlation of 1.0 in any column, I guess it will be singular?  What does this mean to the user?

**Comment by akenmorris** [comment]
The toy example where I ran into this actually only has 2 real samples and they've been duplicated to make it 4.  Maybe no real user will run into this.

**Comment by iyerkrithika21** [comment]
> I'm not sure what to do about the other message. I was trying to read about when this would happen. If there is correlation of 1.0 in any column, I guess it will be singular? What does this mean to the user?

Yes, you are right. I think this means that the particle coordinates for a correspondence point across the groups are not varying. 
Adding more shapes might help alleviate this problem.  @sheryjoe, is this interpretation correct?

**Comment by akenmorris** [comment]
Let me see if I can fix the feature_map_example.  It would be good if the group p-value could work with the sample data we distribute.

**Comment by akenmorris** [comment]
This seems to happen if I have <3 shapes in each group.  Let's try requiring that and see if anyone runs into a singular matrix.
