### ISSUE TITLE
Update PythonTests to be more complete even if one test in a series fails

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1465]
The python testing files sometimes contain more than one test function. So while testing, if any one of the tests fails in the pipeline, it exits without running the other tests.

To solve this issue, the testing structure laid out in Testing/PythonTests/meshcurvature.py should be followed. New tests should follow this and existing tests should be updated.

**Comment by cchriste** [comment]
I can't figure out what's different in curvature.py than the others. However, in my testing for another issue I've realized that all the Python tests are passing whether or not they fail. Escalating to high priority.

**Comment by archanasri** [comment]
@cchriste it's actually meshcurvature.py. My bad. Edited the issue comment.
Let's talk offline about the failing python tests.

**Comment by cchriste** [comment]
> @cchriste it's actually meshcurvature.py. My bad. Edited the issue comment.

Ah! Perfect. That was independently what I started doing for the tests associated with my current work. It's super simple and I'll just add it to the other tests (in a separate PR from the one I'm about to make and the one you made yesterday).

> Let's talk offline about the failing python tests.

It's failing in my current work with create/applyTransform, so nothing to worry about.
