### ISSUE TITLE
Empty Image after Center of Mass Alignment in Grooming phase for Vertebra SSM 

### ISSUE THREAD

**Issue by nawazishkhan1-nk** [SCIInstitute/ShapeWorks#1466]
This is issue is with some of the images of the VerSe Dataset.
During the Grooming phase, after center of mass alignment, it results in an empty segmentation image. I have tried varying the grooming parameters prior to where this problem is pinpointed, but it has no effect. There are some selective images which always result in empty segmentation image . However, there are other images from the same dataset/class that works without any issues. 

Here's the code snippet from the grooming phase : 

       `shape_seg_list = []
        shape_seg_names = []
        for shape_filename in file_list_seg:
            print('Loading: ' + shape_filename)
            shape_seg_names.append(shape_filename.split('/')
                                   [-1].replace('.nii', ''))
            name=shape_filename.split('/')[-1].split('.nii')[0]
            shape_seg = sw.Image(shape_filename)
            print(shape_seg)
            shape_seg.write(groom_dir + name + '_input.nrrd', compressed=False)
            print(f"{shape_filename} loaded")
            shape_seg_list.append(shape_seg)

        print("\nPerforming resampling, centering,and padding operation on segmentations\n")
        for shape_seg, shape_name in zip(shape_seg_list, shape_seg_names):
            print('Resampling segmentation: ' + shape_name)
            antialias_iterations = 15
            shape_seg.antialias(antialias_iterations)
            iso_spacing = [0.5, 0.5, 0.5]  # tried varying it as well
            shape_seg.resample(iso_spacing, sw.InterpolationType.Linear)
            shape_seg.binarize()

            """
            Grooming Step 2:Recenter the segmentation image
            """
            shape_seg.recenter().write(groom_dir + shape_name + '_recentred.nrrd', compressed=False)

            """
            Grooming Step 3: Padding the segmentation image
            """
            print('Padding segmentation: ' + shape_name)
            padding_size = 10  #tried varying these as well
            padding_value = 0 
            shape_seg.pad(padding_size, padding_value).write(groom_dir + shape_name + "_padded.nrrd")

        """
        Grooming Step 4: Center of mass alignment 
        """
        print('\n')
        for shape_seg, shape_name in zip(shape_seg_list, shape_seg_names):
            print('Center of mass alignment: ' + shape_name)
            shape_center = shape_seg.centerOfMass()
            image_center = shape_seg.center()
            print(shape_center)
            print(image_center)
            #input("Wait")
            translationVector = image_center - shape_center
            shape_seg.antialias(antialias_iterations).translate(translationVector).binarize().write(groom_dir + shape_name +     '_com.nrrd', compressed=False)
            print(shape_seg)
        print('\n COM done')
       # For images having this problem, I have checked the images and they are empty.
       # The Images which results in empty segmentation cannot move further in grooming process after this step
        """
        Grooming Step 5: Select a reference
        """
        print('\n')
        shape_seg_list, shape_seg_names = remove_blank_seg(shape_seg_list, shape_seg_names)
        ref_index = sw.find_reference_image_index(shape_seg_list)
        ref_seg = shape_seg_list[ref_index].write(groom_dir + 'reference.nrrd')
        ref_name = shape_seg_names[ref_index]
        print("Reference found: " + ref_name)
`
[Images .nrrd files for reference](https://drive.google.com/drive/folders/1ADFPe1G3jJ5Vor13oeYpzw0SG-o2UWf2?usp=sharing)

**Comment by akenmorris** [comment]
This is an image orientation issue.  See #62

**Comment by cchriste** [comment]
Hi @nawazishkhan1-nk, I'm trying to reproduce the issue and verify the fix (also adding some unit tests), but I cannot figure out how to do this. I've been trying to use the command line, but I'm able to load the images that supposedly do not work and binarize them just fine (`./bin/shapeworks readimage --name ~/Downloads/verse-issue/Resulting\ in\ Empty\ Seg\ files/sub-verse650_dir-iso_seg-vert_msk_01_input.nrrd binarize writeimage --name /tmp/image_binarized_rai1.nrrd`). 

I'm okay to use Python or the command line, but the code above is too complex to clearly identify the issue or where it's observed. Can you please share a very narrow repro using Python or the command line? Fewer than five lines (so no loops, etc. Just load the file and perform only the operations that cause it to break).

Thanks!

**Comment by cchriste** [comment]
Here's  link to the images read and then saved by the older version of shapeworks: https://drive.google.com/drive/folders/166ilcmbTtjcg2Q8loExiaXrnhn9XHnMC?usp=sharing

**Comment by akenmorris** [comment]
I think the step with the problem is the centering (apply transform). I don’t think Binarize will have a problem.

**Comment by cchriste** [comment]
P.S. I have no idea how to tell if an image is oriented RAI or something else. I've loaded these images and others from our testing suite in both FIJI and itk-snap and they all say the same thing: `space: left-posterior-superior`

**Comment by cchriste** [comment]
> P.S. I have no idea how to tell if an image is oriented RAI or something else. I've loaded these images and others from our testing suite in both FIJI and itk-snap and they all say the same thing: `space: left-posterior-superior`

I found a way using its-snap. Image info shows orientation: LPI vs RAI vs RPI, the last of which is associated with the images that don't work.

**Comment by cchriste** [comment]
So now images such as the femur series (LPI) will be changed on load. The unit tests all passing is a good sign, but are there any other potential issues in the use cases?

**Comment by akenmorris** [comment]
I don't think there are any other issues.  The images are all equivalent, but the problem is that most people write code using ITK that implicitly makes certain assumptions about the axes (ShapeWorks is full of such assumptions).  I think the safest thing to do is always use a consistent orientation.

**Comment by nawazishkhan1-nk** [comment]
> Hi @nawazishkhan1-nk, I'm trying to reproduce the issue and verify the fix (also adding some unit tests), but I cannot figure out how to do this. I've been trying to use the command line, but I'm able to load the images that supposedly do not work and binarize them just fine (`./bin/shapeworks readimage --name ~/Downloads/verse-issue/Resulting\ in\ Empty\ Seg\ files/sub-verse650_dir-iso_seg-vert_msk_01_input.nrrd binarize writeimage --name /tmp/image_binarized_rai1.nrrd`).
> 
> I'm okay to use Python or the command line, but the code above is too complex to clearly identify the issue or where it's observed. Can you please share a very narrow repro using Python or the command line? Fewer than five lines (so no loops, etc. Just load the file and perform only the operations that cause it to break).
> 
> Thanks!

Hi @cchriste,
You can use this [script](https://drive.google.com/drive/folders/1ADFPe1G3jJ5Vor13oeYpzw0SG-o2UWf2?usp=sharing) to repro the results with images. I have just kept the grooming steps in that so that you can get the empty seg files(com nrrd files -- which are empty). The problem occurs after center of mass alignment step.  I have also added the original .nii files to the shared folder for the images(original input type from VerSe Dataset)

**Comment by cchriste** [comment]
@akenmorris can you quickly create orientation_lpi.nrrd and orientation.rpi.nrrd from this image? I cannot find c3d anywhere (I found ezc3d, but it can't load a nrrd). If we have three versions of the same image we can verify the failed operation and the transparent conversion.

Thank you!
 
[orientation_rai.nrrd.zip](https://github.com/SCIInstitute/ShapeWorks/files/7173095/orientation_rai.nrrd.zip)

**Comment by akenmorris** [comment]
http://www.itksnap.org/pmwiki/pmwiki.php?n=Convert3D.Convert3D

Here's a few orientations.

[orientations.zip](https://github.com/SCIInstitute/ShapeWorks/files/7173149/orientations.zip)

There are many to choose from:

https://itk.org/Doxygen/html/namespaceitk_1_1SpatialOrientation.html#a8240a59ae2e7cae9e3bad5a52ea3496e

**Comment by cchriste** [comment]
Okay, I have verified the failure and that the fix works. Once I get (or produce) some re-ordered data (just for the femur here should be fine, and I'll want to double-check), I'll add the unit tests. Thanks both of you.

**Comment by cchriste** [comment]
> I believe it's included in ITK-SNAP. If you check the bin dir, you probably already have it.

😂 

> Here's a few orientations.

Thanks.

**Comment by cchriste** [comment]
<img width="678" alt="Screen Shot 2021-09-15 at 8 54 55 PM" src="https://user-images.githubusercontent.com/1260945/133541958-2c02b86e-9153-4f42-ba87-98e1996d9e36.png">
(images show the original above the translated 'center - center_of_mass'; from left-to-right they are rai, lpi, rpi, sal)  

The simple tests I shared earlier don't work with these data since they neither start out the same nor "translate" the same. I'm especially baffled about the latter. Here's how I got these images as well as the originals' size, dims, etc. 
```Python
rai = sw.Image("/Users/cam/code/ShapeWorks/ShapeWorks/Testing/data/orientation_rai.nrrd")
lpi = sw.Image("/Users/cam/code/ShapeWorks/ShapeWorks/Testing/data/orientation_lpi.nrrd")
rpi = sw.Image("/Users/cam/code/ShapeWorks/ShapeWorks/Testing/data/orientation_rpi.nrrd")
sal = sw.Image("/Users/cam/code/ShapeWorks/ShapeWorks/Testing/data/orientation_sal.nrrd")

images = [rai, lpi, rpi, sal]

idx=0
for image in images:
    image.write("/tmp/original"+str(idx)+".nrrd")
    com = image.centerOfMass()
    ctr = image.center()
    image.translate(ctr - com)
    image.write("/tmp/translated"+str(idx)+".nrrd")
    idx+=1

rai
{
	dims: [94, 69, 133],
	origin: [44, -195, -740],
	size: [94, 69, 133],
	spacing: [1, 1, 1]
}

lpi
{
	dims: [94, 69, 133],
	origin: [-49, -263, -740],
	size: [94, 69, 133],
	spacing: [1, 1, 1]
}

rpi
{
	dims: [94, 69, 133],
	origin: [44, -263, -740],
	size: [94, 69, 133],
	spacing: [1, 1, 1]
}

sal
{
	dims: [133, 69, 94],
	origin: [-88, -195, -833],
	size: [133, 69, 94],
	spacing: [1, 1, 1]
}
```

One might argue the conversion is still fine, but will this be what is needed to resolve this issue?

**Comment by akenmorris** [comment]
Hmm, I see.  I was mistaken that they are equivalent.

<img width="497" alt="image" src="https://user-images.githubusercontent.com/1693349/133630371-548fb602-f13a-42be-82e7-b5371109150d.png">

**Comment by akenmorris** [comment]
Ok, it seems c3d is doing something more along the lines of a ChangeInformationFilter where the axes are just being overwritten and everything else is left alone.  If we instead use itk::OrientImageFilter, we can create the different orientations for these images and maintain and equivalent image in world coordinates and true orientation:

```
$ for i in sw*.nrrd ; do echo $i ; c3d $i -info ; done
sw_lpi.nrrd
Image #1: dim = [94, 69, 133];  bb = {[137 -127 -740], [231 -58 -607]};  vox = [1, 1, 1];  range = [0, 1];  orient = LPI
sw_rai.nrrd
Image #1: dim = [94, 69, 133];  bb = {[44 -195 -740], [138 -126 -607]};  vox = [1, 1, 1];  range = [0, 1];  orient = RAI
sw_rpi.nrrd
Image #1: dim = [94, 69, 133];  bb = {[44 -127 -740], [138 -58 -607]};  vox = [1, 1, 1];  range = [0, 1];  orient = RPI
sw_sal.nrrd
Image #1: dim = [133, 69, 94];  bb = {[137 -195 -608], [270 -126 -514]};  vox = [1, 1, 1];  range = [0, 1];  orient = SAL
```

<img width="502" alt="image" src="https://user-images.githubusercontent.com/1693349/133638712-14cdc9cc-6db3-43b9-813a-411c80296620.png">

[sw_orientations.zip](https://github.com/SCIInstitute/ShapeWorks/files/7179006/sw_orientations.zip)

**Comment by cchriste** [comment]
Awesome! These images show the itk-modified femur images (thank you) on top, the versions that are written directly after being loaded by ShapeWorks in the middle, and the translated versions on the bottom, demonstrating this PR does the right thing. I'll push the unit tests shortly.

**ORIGINAL CODE**
<img width="595" alt="orig_itkmods" src="https://user-images.githubusercontent.com/1260945/133664204-b78bd072-c464-4aee-8b3d-616738ad2b37.png">
**NEW CODE**
<img width="588" alt="new_itkmods" src="https://user-images.githubusercontent.com/1260945/133664211-645300ef-a0a0-453e-83e2-093e7395acf9.png">
