### ISSUE TITLE
Removing inconsistencies in image orientation as first step in Studio 

### ISSUE THREAD

**Issue by nawazishkhan1-nk** [SCIInstitute/ShapeWorks#1478]

**Comment by sheryjoe** [comment]
@nawazishkhan1-nk @akenmorris please link the PR that fixed this issue.

**Comment by akenmorris** [comment]
@sheryjoe , this was fixed in Studio well over a year ago.  I believe the issue was made in error.

**Comment by sheryjoe** [comment]
@akenmorris this should be a different issue, but we need to have a grooming step in the python use cases to make all input images/segmentation have a  consistent orientation.

**Comment by sheryjoe** [comment]
Great thanks 👍
