### ISSUE TITLE
Studio DeepSSM - Training examples display

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1479]
Update the studio DeeepSSM training tab to display best, worst, and median (instead of mean) examples for both training and validation sets.

**Comment by jadie1** [comment]
@akenmorris I added support for this in the python package on the `deepssm` branch if you want to update it in studio.
It now outputs files to a folder called 'examples/' with format like: validation_worst.scalars or validation_median.particles, or train_best.particles
Note you'll need to run this again: `pip install ShapeWorks/Python/DeepSSMUtilsPackage/`

**Comment by cchriste** [comment]
> Note you'll need to run this again: `pip install ShapeWorks/Python/DeepSSMUtilsPackage/`

Is there any way to convey to developers that they should _not_ be doing this? Instead, from their source directory they should:
`source ./devenv.sh /path/to/build/bin` 
I'm sorry to sound like a nag. This puts both the freshly built shapeworks executable and all the python modules from developers' source trees in their path. Developers shouldn't pip install anything ever (except to test the user deployment itself).

This even works on Windows both from git bash, using the same command as above, and Anaconda terminal, in which you replace .sh with .bat and don't use source:
`devenv .\path\to\build\Release\bin`
