### ISSUE TITLE
Crop followed by resample results in an empty image, but crop->save->load->resample works fine

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1483]
I think Image::crop should probably use itk::RegionOfInterestImageFilter instead of itk::ExtractImageFilter.

From https://itk.org/Doxygen/html/classitk_1_1ExtractImageFilter.html

"The output image produced by this filter will have the same origin as the input image, while the ImageRegion of the output image will start at the starting index value provided in the ExtractRegion parameter. If you are looking for a filter that will re-compute the origin of the output image, and provide an output image region whose index is set to zeros, then you may want to use the RegionOfInterestImageFilter. The output spacing is is simply the collapsed version of the input spacing."

It appears Image::resample makes some assumptions that are incorrect for the output of itk::ExtractImageFilter

```
Dims dims({ static_cast<unsigned>(std::floor(inputDims[0] * inputSpacing[0] / spacing[0])),
              static_cast<unsigned>(std::floor(inputDims[1] * inputSpacing[1] / spacing[1])),
              static_cast<unsigned>(std::floor(inputDims[2] * inputSpacing[2] / spacing[2])) });
  
  Point3 new_origin = origin() + toPoint(0.5 * (spacing - inputSpacing));  // O' += 0.5 * (p' - p)
```

To demonstrate, try the following python code:

```
from shapeworks import *

img = Image("seg.nrrd")
img.crop(img.physicalBoundingBox(0.5))
img.write("cropped.nrrd")

img.resample(1.0)
img.write("resampled.nrrd")

img = Image("cropped.nrrd")
img.resample(1.0)
img.write("resampled2.nrrd")
```

The resulting **resample.nrrd** is empty, but **resampled2.nrrd** is what the user expects.

Switching to itk::RegionOfInterestImageFilter gives both files being identical and what is expected.

[example.zip](https://github.com/SCIInstitute/ShapeWorks/files/7212190/example.zip)

I'm not sure the other implications of switching filters.  The region of interest filter doesn't have `SetDirectionCollapseToIdentity` that we are using.

**Comment by akenmorris** [comment]
We may have the same problem with Image::pad given the notes here:

https://github.com/SCIInstitute/ShapeWorks/blob/0362cafe7f830473c1000a04e28b9368a8252c7a/Libs/Image/Image.cpp#L413

**Comment by archanasri** [comment]
From https://itk.org/Doxygen/html/classitk_1_1RegionOfInterestImageFilter.html:

"This filter produces an output image of the same dimension as the input image. The user specifies the region of the input image that will be contained in the output image. The origin coordinates of the output images will be computed in such a way that if mapped to physical space, the output image will overlay the input image with perfect registration. In other words, a registration process between the output image and the input image will return an identity transform.

If you are interested in changing the dimension of the image, you may want to consider the ExtractImageFilter. For example for extracting a 2D image from a slice of a 3D image."

It looks like it would be better to use this filter for cropping
