### ISSUE TITLE
Latest dev build issue with Studio

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1485]
I cannot seem to open Studio with the ShapeWorks-dev-4516-8ac83913-linux build. I initially had a error that libopenvdb.so.7.0 was too short (and it appears to not be a shared library, see image). As a shot in the dark, I then tried copying the library from a previous build, but that resulted in an error finding the xcb Qt plugin. For a sanity check, I reinstalled the last PR I had downloaded and it seemed to work fine. 
![image](https://user-images.githubusercontent.com/13870137/134595936-1c02d256-9cca-4c62-90b8-6500e07ae71b.png)

**Comment by akenmorris** [comment]
Thanks Penny, I’ll check it out. That file should be a symlink to libopendvb.so.7.0.0. I recently made a change in the deployment since I found it was creating copies rather than maintaining the symlink. This was doubling and tripling the size of the deployment.

**Comment by akenmorris** [comment]
I get the same error with xcb.  Will fix.

**Comment by patkins** [comment]
Thanks, Alan!

**Comment by sheryjoe** [comment]
Can't be reproduced on other Linux machines.
