### ISSUE TITLE
developer documentation: use devenv, not pip install

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1486]
We need to convey to developers that they should _not_ even be installing their python modules during development. Instead, from their source directory they should:
`source ./devenv.sh /path/to/build/bin` 
This puts both the freshly built shapeworks executable and all the python modules from developers' source trees in their path. Developers shouldn't pip install anything ever (except to test the user deployment itself).

This also works on Windows both from git bash, using the same command as above, and Anaconda terminal, in which you replace .sh with .bat and don't use source:
`devenv .\path\to\build\Release\bin`

**Comment by cchriste** [comment]
There are a host of issues avoided by using this method since it ensures both PATH and PYTHONPATH are correct and aligned with your current source and build of Studio, shapeworks, and the python module.

**Comment by jadie1** [comment]
The devenv script is being used by developers and is in the documentation: http://sciinstitute.github.io/ShapeWorks/latest/dev/paths.html#using-devenv-script-to-configure-developer-environment
Closing this issue.
