### ISSUE TITLE
Sphere Constraints used as FFCs are ambiguous

### ISSUE THREAD

**Issue by HeavenlyBerserker** [SCIInstitute/ShapeWorks#1491]
This is a controversial way of using sphere constraints since you are not able to specify which side is in and which side is out. This makes it an ambiguous tool.

On the other hand, there's the argument that people should stop using Sphere constraints in this way since FFCs exist now.

So... Is this issue an issue?

**Comment by akenmorris** [comment]
I believe we are dropping sphere constraints.  Please re-open if that is not the case.
