### ISSUE TITLE
Shape statistics in python could link to Python API when we have docs for that 

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1492]

**Comment by iyerkrithika21** [comment]
Related to #1079

**Comment by akenmorris** [comment]
We have docs for the python API, what needs to be done now?

**Comment by iyerkrithika21** [comment]
The document for shape statistics should point to the APIs. Will include this in my multiple domain use case PR

**Comment by akenmorris** [comment]
@iyerkrithika21 Was this completed with #1961?

**Comment by iyerkrithika21** [comment]
> @iyerkrithika21 Was this completed with #1961?

I think I missed that. Will create a PR with #1492 and #1810

**Comment by akenmorris** [comment]
Resolved #2023
