### ISSUE TITLE
fix Mesh.create/applyTransform Python bindings

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1493]
`Mesh.createTransform` returns an invalid Python type. It should simply return a 4x4 `numpy` array, similarly to the way `Image.createTransform` returns a 3x3 `numpy` array.*

- [x] The Python binding for `Mesh.applyTransform` should accept such an array.

- [x] Documentation for these functions is also lacking and should be improved as in Image.create/applyTransform (C++ header, Python description in ShapeworksPython.cpp, and `shapeworks` command line commands). 

- [x] Unit tests should also be added.

- [x] NOTE: these functions aren't apparently used in any use cases (or unit tests, tsk tsk). It seems very useful, just as the Image versions. We might consider using them in one of our Mesh-based use cases.
       - added Jupyter notebook

- [x] *once #1276 is finished

**Comment by cchriste** [comment]
Here is the error in a Jupyter notebook: 
<img width="956" alt="Screen Shot 2021-09-28 at 4 30 02 PM" src="https://user-images.githubusercontent.com/1260945/135174476-e5eb8b03-29f1-48ed-a77f-0eba691d2478.png">

**Comment by cchriste** [comment]
For bonus, figure out a way to produce a simple error when an argument is omitted like this
<img width="926" alt="Screen Shot 2021-09-28 at 4 30 48 PM" src="https://user-images.githubusercontent.com/1260945/135174586-138cde7e-d6c2-4d81-81f2-dfa23661d279.png">
:

**Comment by akenmorris** [comment]
We should be able to use these 4x4 transforms on both meshes, images, and particles.
