### ISSUE TITLE
ICP transforms fail when image is a segmentation

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1496]
The iterative closest point version of computing a transform fails when the image is a segmentation, but does fine if it’s “raw” (like a ct). It reports the error:
`ERROR:root:Can't execute with nullptr or empty input.`

This error message does not exist in our code.

I've attached both a padded and unpadded segmentations of the first two (m03 and m04) images from the femur-v1 dataset (originals are too big to upload). 

Here's a view from a jupyter notebook:
<img width="719" alt="Screen Shot 2021-09-29 at 4 54 50 PM" src="https://user-images.githubusercontent.com/1260945/135359509-d8747626-5f99-490e-918f-aaf3bd561161.png">

This command line shows the same error:
`shapeworks readimage --name ~/data/sw/femur1_seg_unpadded.nrrd icpimage --target ~/data/sw/femur2_seg_unpadded.nrrd`

[femur1_seg.nrrd.zip](https://github.com/SCIInstitute/ShapeWorks/files/7255429/femur1_seg.nrrd.zip)
[femur1_seg_unpadded.nrrd.zip](https://github.com/SCIInstitute/ShapeWorks/files/7255455/femur1_seg_unpadded.nrrd.zip)
[femur2_seg_unpadded.nrrd.zip](https://github.com/SCIInstitute/ShapeWorks/files/7255464/femur2_seg_unpadded.nrrd.zip)
[femur2_seg.nrrd.zip](https://github.com/SCIInstitute/ShapeWorks/files/7255465/femur2_seg.nrrd.zip)

**Comment by archanasri** [comment]
This bug is resolved. The functions work in the master branch.
