### ISSUE TITLE
thin_cavity_bean is broken on osx

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1499]
This was marked correct by the people who tested it for the 6.1 release.

Current linux overall mean: 
<img width="934" alt="Screen Shot 2021-10-04 at 1 54 49 PM" src="https://user-images.githubusercontent.com/1260945/135915813-9e98ce2d-f602-4ef0-b9a6-7cf35f28cc2c.png">

Current OSX overall mean:
<img width="1152" alt="Screen Shot 2021-10-04 at 1 48 26 PM" src="https://user-images.githubusercontent.com/1260945/135914942-f6b12f43-a0c4-440e-9795-a41efc7879bf.png">

**Comment by akenmorris** [comment]
Here's what I see with 6.1 on MacOS.  Assuming I ran it with the correct binary.

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/1693349/135943016-1c6476e9-ecfc-498e-b666-baa6beae1704.png">

**Comment by akenmorris** [comment]
windows:

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/1693349/136034126-0022046f-97d4-4701-9775-068d262596cc.png">

**Comment by akenmorris** [comment]
Fixed in 74c97d0fa6963147f5a39cfb8650c73e720c2ce5
