### ISSUE TITLE
Geodesic Distance cannot be applied for certain meshes

### ISSUE THREAD

**Issue by nawazishkhan1-nk** [SCIInstitute/ShapeWorks#1501]
Geodesic distance works fine when applied to a smaller number of meshes but when the shape cohort is of large size(above 100), it gives Non-finite matrix error. I guess it might be due to some particular meshes in the cohort or due to the larger size of shape cohort.
![Screen Shot 2021-10-05 at 12 26 22 PM](https://user-images.githubusercontent.com/84894476/136081303-0df714af-6ab2-4f3e-8ae6-d16f6a43e382.png)

**Comment by akenmorris** [comment]
Can you point me to the data?

**Comment by cchriste** [comment]
Best fix might be simply finish #1502

**Comment by akenmorris** [comment]
@nawazishkhan1-nk , can you point me to the data?  I am not sure where this error message is coming from.

**Comment by nawazishkhan1-nk** [comment]
> Can you send me the xlsx file you are using?
> 
I didn't use any xlsx file for this. 
> I imported the avcd_mesh files, groomed and optimized with the options I can see in your screenshot and it seems to work.
> 
Yep, I have optimized in similar manner as well.
> Also, what version of ShapeWorks is this? I notice the narrow band option is not your optimize page.
I have tried this on the user version of Shapeworks 6.1.

**Comment by akenmorris** [comment]
Ok, before you hit optimize, you can save the project as an XLSX file. 

I will try the groom parameters you used.
