### ISSUE TITLE
Investigate replacement of cvdDecimate with AVCD

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1502]
We seem to be having some crashes with cvdDecimate.  The following repo is from the original author and has recent updates:

https://github.com/valette/ACVD

**Comment by nawazishkhan1-nk** [comment]
These are some of the results for comparing ACVD vs decimate meshes:
ACVD-
![acvd_1](https://user-images.githubusercontent.com/84894476/137012832-644da4cd-3786-449b-b03d-9cc4e75a3819.png)
![acvd_2](https://user-images.githubusercontent.com/84894476/137012835-77c7dc05-3081-448a-8f2e-210011c6ceee.png)

Decimate:
![decimate_2](https://user-images.githubusercontent.com/84894476/137012932-ebe4b91e-792f-40d2-8d4b-3d0e425da1c8.png)
![decimate_3](https://user-images.githubusercontent.com/84894476/137012936-4d2939f5-95e6-4cca-bc28-8e1411ccb299.png)
