### ISSUE TITLE
consolidate `Mesh::getFieldValue` and `Mesh::getMultiFieldValue`

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1504]
It's (understandably) confusing to have separate functions to return scalar vs vector field values (e.g., distances vs normals). 

Currently, `getFieldValue` silently returns the first component of a vector value, and similar issues exist for `getFieldRange` and other field computations in the Mesh class.

Many of the functions in the Mesh class can be moved into the upcoming `Field` class (#935) where they can be handled more elegantly (whatever that means).

**Comment by akenmorris** [comment]
@HeavenlyBerserker, does this need to be done, or is this issue obsolete?

**Comment by HeavenlyBerserker** [comment]
Idk if this is necessary. Also, I don't think we're doing the field class.
I'd vote to scrap this.

**Comment by akenmorris** [comment]
Closing for now, re-open if it becomes needed.
