### ISSUE TITLE
Surface Reconstruction

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#151]
I need a stand-alone functionality from surface reconstruction code: Given a distance transform, generate a high-quality QC'ed dense mesh. 

All of this code is already part of the ReconstructMeanSurface. It would be helpful if that piece of code is cut-out as an independent module and called into where needed - as a function call or as a stand-alone tool to generate good quality meshes.

I am willing to take on this task, however, would like to first discuss my plan and the place where such a module should reside.

**Comment by sheryjoe** [comment]
Isosurfacing is already provided by MeshFromDistanceTransforms tool, and Mesh QC is provided by PreviewCmd (not a descriptive enough name though, could be renamed as MeshQC or something similar). You could also add an optional MeshQC to the MeshFromDistanceTransforms to perform what you need using one tool.

ShapeWorks/Prep/Source/FileFormats/MeshFromDistanceTransforms/
ShapeWorks/Prep/Source/MeshTools/PreviewCmd/

**Comment by prafulag** [comment]
Thanks Shireen! I was not aware this was in FileFormats. I was looking in MeshTools only. 

Yesterday, I ended up adding a method - "MeshFromDT" in Reconstruction class, and a MeshFromDT tool which reads a paramfile and calls this method from Reconstruction class.

**Comment by sheryjoe** [comment]
MeshFromDT is added to the Reconstruction class.
