### ISSUE TITLE
Reduce constraint annotation burden

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1517]
Currently, we assume the user defines sample-wise cutting planes or free form constraints for optimization. We could reduce this burden by allowing the user to define constraints on a representative subset of the data then appropriately transforming those constraints for each sample. Would need a use case to demonstrate this.

**Comment by akenmorris** [comment]
@sheryjoe , Are we sure we need to do this given the cutting plane copy & paste in studio?

**Comment by akenmorris** [comment]
I am wondering if this issue can be considered complete based on the ability to define a cutting plane on one sample in Studio and transform it to all of the other shapes (via centering or ICP transform)?  This seem to work very well for cases like the femur.

The issue description describes doing this for free form constraints as well, but it's difficult to see how this could ever work properly.  For example, a typical use case for the free form constraint would be something like excluding veins or a left atrial appendage from an LA.  This is something that's going to be very customized for each subject and there's really no time savings or reduced burden in attempting to apply one constraint to another subject.

**Comment by sheryjoe** [comment]
I was thinking along the lines of using a non-rigid registation that does not require correspondences from one shape to another to propagate free-form constraints.

**Comment by akenmorris** [comment]
Yes, that concept makes sense. I’m just having a hard time envisioning a real world use case where this would transfer constraints to other shapes that would be usable without requiring manual cleanup.  The tools to define constraints from scratch on each shape are quite fast to use and I’m not seeing the advantage in having a likely sloppy approximation from another shape. 

As an example, defining a free form constraint excluding a left atrial appendage, applied through a non-rigid registration to other left atria will just result in a mess taking longer to clean up than to start from scratch.

**Comment by sheryjoe** [comment]
I see. Let's move this issue to backlog and revisit it if/when needed.
