### ISSUE TITLE
create [windows] startup script?

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1528]
While it's handy that the install_shapeworks.bat puts everything in the conda environment and its path, it might also be handy to have a way to manually override that PATH and its corresponding PYTHONPATH to the version being used, especially given the time it takes to install shapeworks.

Longer version: I don't want to re-run install_shapeworks.bat to test the latest version if I don't have to. The requested script is nearly equivalent--maybe identical--to the devenv.bat/sh script.

P.S. the README on Windows? Confusing^nth! I know I may have helped write it, but I'd hate to be a Windows user installing to a custom directory. (Regarding that, remember #1296?)

**Comment by sheryjoe** [comment]
@akenmorris @cchriste is this still an issue?

**Comment by cchriste** [comment]
> @akenmorris @cchriste is this still an issue?

I think we started including the devenv script with our release (Alan can confirm). If not, I still think it would be very useful.

Regarding the reasoning behind this issue, it's use would predominately be for testing, enabling comparison of binary versions _installed in different directories and/or using different conda environments_. Since this would most likely require working closely with users--for example, to show different results of some computation across versions--it would probably be used most by developers and expert users during pre-release testing.

I suggest we include devenv.sh/bat and add something to a doc, maybe "release testing" explaining how to use it so that we can save manual time when possible. Then we can close this issue.

**Comment by cchriste** [comment]
We can require using git bash and eliminate the devenv.bat no longer works (and we already require it for installation).

**Comment by cchriste** [comment]
These are the two items left for this issue:
- [ ] add devenv.sh to releases so it can be used by developers when testing release candidates
- [ ] remove devenv.bat (or fix it)

**Comment by akenmorris** [comment]
Will be resolved with #1969
