### ISSUE TITLE
Logging interface for use cases [too much output when running use cases]

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1532]
This should be quiet and meaningful for users running these things. 
Users only need to see the steps, and if being run interactively, we can use `\r` to show an animated "..." as something is executing. At the end they should be able to see everything that happened in a single page.

As it is currently, it's virtually worthless for demonstration and for testing. All we see is pages of text whipping past. 

We could add a `--verbose` option if necessary, but there are numerous things that could be removed on a normal run, such as printing out the name of every file each time it's processed. We could even add levels of verbosity.

Given the timeframe on testing and the advantages this will provide for demonstration, I suggest we bite the bullet and add this for our current release.

**Comment by sheryjoe** [comment]
Related to #1377

**Comment by jadie1** [comment]
Discussed plan: For 6.2 change the optimize verbosity to be minimal since the vast majority of use case output is coming from optimization. Moving forward we need a python logging interface so we can control verbosity for print statements coming from python as well.

**Comment by akenmorris** [comment]
We have reduced the verbosity and added log files from scripts such as VerifyUseCases.py
