### ISSUE TITLE
Grooming gives meshes with flipped normals

### ISSUE THREAD

**Issue by nawazishkhan1-nk** [SCIInstitute/ShapeWorks#1537]
Upon grooming a few meshes from VerSe Dataset, we get surfaces with flipped normals as shown below:
![Screen Shot 2021-10-26 at 12 26 07 PM](https://user-images.githubusercontent.com/84894476/138938768-507b6c8b-8386-45c1-9e3b-d3fd336de297.png)

![Screen Shot 2021-10-26 at 12 27 28 PM](https://user-images.githubusercontent.com/84894476/138938965-99571554-efb2-4e44-b6fa-ae0bbb5d78a0.png)

This artifact arises specifically when we apply smoothing(both Laplacian and WIndowedSinc) on the mesh and it is irrespective of the Alignment and Fill Holes Step of the Grooming pipeline. Moreover, varying the number of smoothing iterations has no effect as well.

[Meshes](https://drive.google.com/drive/folders/1EmyPN568ObHazG2HOC2HXRX47ywmdNmH?usp=sharing)

![Screen Shot 2021-10-26 at 12 37 33 PM](https://user-images.githubusercontent.com/84894476/138940355-cc6020da-a03b-42c3-92d6-e3ea89c3c0f2.png)

**Comment by nawazishkhan1-nk** [comment]
I have used the python implementation[(pyACVD)](https://github.com/pyvista/pyacvd) in my code for the vertebra dataset and yes, now I've noticed it flips the normals by default while re-meshing.

**Comment by sheryjoe** [comment]
Is this resolved? @akenmorris @nawazishkhan1-nk

**Comment by nawazishkhan1-nk** [comment]
1. Yes, @sheryjoe, I think this issue must be resolved. These meshes are constructed by ShapeWorks Decimate followed by ACVD Remeshing, which is why we were getting non-manifold edges. This does not occur with our current grooming pipeline, which entails only ACVD remeshing for iso-surface.
2. Moreover, I have tried the force manifold option in ACVD remeshing as suggested by Alan to see if it helps remove these non-manifold edges, and apparently, the force manifold option doesn't make a difference for the above set of meshes.
