### ISSUE TITLE
Duplicate faces and non-manifold meshes in PreviewQC'ed mesh

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#154]
The QC'ed mesh generated after preview step contains duplicate triangles, hence resulting in the crashing of further steps such as loopsubdivisiom.

**Comment by sheryjoe** [comment]
This could be solved by adding a generic function to PreviewQC lib to remove duplicates. @prafulag would you mind adding this function? and I will update the reconstruction code accordingly.

**Comment by prafulag** [comment]
I am not sure trimesh provides this functionality. Which is why I suggested 
"This could be solved by adding a generic function to PreviewQC lib to remove duplicates." to Steve (in mail), in case he already has a similar functionality.

**Comment by prafulag** [comment]
@sheryjoe: For now, one way could be that we apply a loop subdivision filter in try-catch construct to see if it fails, coz implicity this filter checks for valid number of neighbors for every edge. If this filter fails then we change the decimation percentage by 0.9*current_value OR 1.1*current_value and redo MeshQC.

**Comment by akenmorris** [comment]
Where is this loop subdivision?  How do we reproduce this crash?  What data?

**Comment by sheryjoe** [comment]
@akenmorris as we are replacing PreviewCmd and its backend lib (FEMeshPreviewQC) with mmgtools and vtk tools for mesh grooming/QC, I don't think this issue is relevant anymore. Closing.

**Comment by sheryjoe** [comment]
This should be fixed by #1502

**Comment by sheryjoe** [comment]
Not relevant anymore, using ACVD now.
