### ISSUE TITLE
femur mode 2 results may be bad

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1541]
The pictures don't look like the docs, so adding this issue. I'm glad to Zoom with someone to interact with the results if that would be helpful.
<img width="1541" alt="2021-10-26 (4)" src="https://user-images.githubusercontent.com/1260945/138972019-62581f2d-7d1b-4626-8a3c-d89868425e4f.png"
<img width="1541" alt="2021-10-26 (3)" src="https://user-images.githubusercontent.com/1260945/138972025-90366a71-135d-405e-81c3-b77cc7be55f0.png">
>

**Comment by jadie1** [comment]
Update: I was misunderstanding the translate function - it only translates the image contents, it does not translate the coordinate system. To translate the image and coordinate system I used setOrigin() instead. The alignment is fixed in PR #1553
