### ISSUE TITLE
Femur_mesh use case issues

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1543]
The docs page looks like it was run with way more than 128 particles:

http://sciinstitute.github.io/ShapeWorks/use-cases/mesh-based/femur-mesh.html

The current run of the use case only uses 128 and doesn't look very good to me (linux).  Notice the poor sampling:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/1693349/139123903-7b49ac3e-0f2e-4e72-af95-ce07ccd5dbdc.png">

**Comment by jadie1** [comment]
Fixed in PR #1553
