### ISSUE TITLE
DeepSSM torch multiprocessing bug

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1556]
DeepSSM use case is currently failing with this error when training starts:

RuntimeError: Too many open files. Communication with the workers is no longer possible. Please increase the limit using `ulimit -n` in the shell or change the sharing strategy by calling `torch.multiprocessing.set_sharing_strategy('file_system')` at the beginning of your code

**Comment by akenmorris** [comment]
Fixed in #1557
