### ISSUE TITLE
upgrade shapeworkspost to use ImGui instead of nanogui (libigl now uses this)

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#156]
https://libigl.github.io/tutorial/#viewer-menu

**Comment by sheryjoe** [comment]
@riddhishb  @akenmorris @cchriste We need to discuss the plan for Post along with View and Studio. 

In general, I am not in favor of maintaining multiple GUIs to perform similar functions. It would also not be an efficient use of Cam's and Alan's time to fix and maintain such multiple GUIs. 

@cchriste Please hold off on Post-related fixes/reorg for now. 

We discussed earlier that we could refactor the core method of surface reconstruction, which is faster than the current particle-based surface reconstruction, update the Vis lib (Reconstruction class), and expose it through View and Studio. 

Let's discuss more on our dev meeting. @cchriste Please add this to the meeting agenda.

**Comment by akenmorris** [comment]
I agree.  It was always my intention to eventually replace View2 entirely with Studio.

**Comment by sheryjoe** [comment]
@akenmorris I would still keep View2 or some lightweight visualization of shape models. For instance, if we could run Studio in a mode that would only accept shape models, that would be better.

**Comment by akenmorris** [comment]
Yes, exactly.  My plan was to have Studio be capable of running in a lightweight mode and operate nearly exactly as View2 when a parameter file of point files is given (View2's parameter file).  The idea was more or less to merge the code bases and functionality to reduce the code duplication and the need for separate tools.

**Comment by cchriste** [comment]
Alan, will you please create a handful of issues related to this task? They can then be added to a milestone "Consolidate GUIs."

**Comment by cchriste** [comment]
Closing this issue since post has now been deprecated and will not be upgraded to use a new GUI library.
