### ISSUE TITLE
Add query functionality to operator+= in Mesh API

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1561]
The operator += in Mesh API appends two meshes and the output mesh contains a single vertex list and single face list. This should be modified such that a user can query and find which vertices and faces belong to a specific mesh.

This will be useful for multi-domain modeling.

We can maintain a separate vertex and face list for each mesh for such a query.

**Comment by cchriste** [comment]
This would be strange and complicated to add to Mesh. 
Instead, an external class could keep an array of independent meshes and perform the necessary complications for these. 

Closing for now.
