### ISSUE TITLE
Support versioned documentation pages

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1575]
It would be great if we could have a snapshot of the documentation for each release posted on the website somewhere.

**Comment by sheryjoe** [comment]
This supports versioning on gh-pages
https://github.com/jimporter/mike

**Comment by akenmorris** [comment]
Good find.

**Comment by cchriste** [comment]
Selecting some pages from documentation hides the version selection dropdown.

**Comment by akenmorris** [comment]
Done
