### ISSUE TITLE
release notes should link to online/deployed documentation

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#1582]
As of now, links are added to the GitHub md pages.

**Comment by archanasri** [comment]
@sheryjoe Should all the links to documentation be like `http://sciinstitute.github.io/ShapeWorks/new/free-form-constraints.html` instead of `../new/free-form-constraints.md`?

**Comment by sheryjoe** [comment]
yes. is this addressed already? @archanasri

**Comment by akenmorris** [comment]
I'm not sure I understand this.  Mkdocs converts the md files to html:

See the release notes here:

http://sciinstitute.github.io/ShapeWorks/about/release-notes.html

The link for free form constraints already goes to "http://sciinstitute.github.io/ShapeWorks/new/free-form-constraints.html"

**Comment by sheryjoe** [comment]
I see, my bad, I was getting the links for the announcement directly from the md file before doc deploy. closing this one.
