### ISSUE TITLE
Isotropic explicit remeshing

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1585]
Use mesh decimate command and retain almost 95-99% of the original mesh for re-meshesing 
>>We have no way to do isotropic explicit remeshing in ShapeWorks now. Once mmgtools is added, we should use that.

**Comment by iyerkrithika21** [comment]
This is related to #1502 and fixed with #1587 
@sheryjoe @akenmorris can we close this?

**Comment by akenmorris** [comment]
Yes
