### ISSUE TITLE
consolidate Anaylze/MeshFromDT

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1588]
This seems like a straightforward addition to the Mesh class. Is there any reason it isn't already an issue?

**Comment by sheryjoe** [comment]
@cchriste @archanasri does this command do an isosurface of a given distance transform? isn't that redundant with .toMesh API?

**Comment by archanasri** [comment]
This command extracts the isosurface and uses a subdivision filter which our Mesh API does not do

**Comment by archanasri** [comment]
This executable can be removed since it is redundant.
