### ISSUE TITLE
Uniform transform interface

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1602]
Currently, the mesh and image transforms in the Python module are not commensurate. This means we cannot find a transform using meshes and apply it t the meshes and corresponding images (as is required in the femur use case).  For images, it takes an ITK transform and turns it into a 4x4 eigen matrix, which is different the 4x4 from VTK (inverse and last row/column are switched).  Studio uses the mesh transform format. 

We need to adapt this so that a transform can be generated by aligning meshes or segmentations and then can be applied to either.

**Comment by archanasri** [comment]
Done and merged in #1618
