### ISSUE TITLE
X11 libraries from Anaconda are incompatible with OpenSUSE 15.3

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1604]
This only affects locally built versions of ShapeWorks, the binary deployments work fine.

When built locally on an OpenSUSE machine, ShapeWorksStudio will fail to open:

[2021-12-16 15:27:54.459|ShapeWorksStudioApp.cpp|705] MESSAGE: ShapeWorks Studio Initialized
The X11 connection broke: No error (code 0)
XIO:  fatal IO error 2 (No such file or directory) on X server "localhost:12.0"
      after 429 requests (429 known processed) with 0 events remaining.

This is due to the X11 libraries in anaconda/envs/shapeworks/lib being used instead of the system X11 libraries in /usr/lib64.

I have confirmed this by moving libX* out of anaconda/envs/shapeworks/lib and Studio now works properly.

We have this section in `install_shapeworks.sh`:

```
# linux and mac (only) deps
  if [[ "$(uname)" == "Linux" || "$(uname)" == "Darwin" ]]; then
    if ! conda install --yes \
      xorg-libx11=1.6.12 \
      xorg-libsm=1.2.3 \
      libxrandr-devel-cos6-x86_64=1.5.1 \
      libxinerama-devel-cos6-x86_64=1.1.3 \
      libxcursor-devel-cos6-x86_64=1.1.14 \
      libxi-devel-cos6-x86_64=1.7.8 \
      openmp=8.0.1 \
      ncurses=6.2 \
      libuuid=2.32.1
    then return 1; fi
  fi
```

I am questioning why we need to install xorg-libx11 at all if may not even be compatible with the local system at all.  Furthermore, why do we need them on MacOS?

I think it's likely that linux developers will just have to install packages like `libX11-devel` from their own system package manager.  It doesn't appear that conda can properly do this for us.

**Comment by iyerkrithika21** [comment]
@akenmorris,we addressed this in commit 99f80be1e68736038c0987ad4257ce5bbeb827de
