### ISSUE TITLE
Parent Issue for Repo Cleanup

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1607]
This is a parent issue for all issues that pertain to cleaning up the repo:
- [x] #160 
- [x] #101
- [x] #171 
- [ ] #408 
- [ ] #173
- [ ] #1149

**Comment by iyerkrithika21** [comment]
@akenmorris: can we close this issue?

**Comment by akenmorris** [comment]
Yeah, the remaining couple of things can stand on their own.
