### ISSUE TITLE
Add superimposition of groomed and reconstructed models in Studio

### ISSUE THREAD

**Issue by ben2k** [SCIInstitute/ShapeWorks#1611]
Today, we cannot superimpose both groomed and reconstructed model since we choose "Groom" or "Reconstructed" in visualization mode (combo box "View mode"). Switching from "Groomed" to "Reconstructed mode" view mode changes the camera orientation, so we cannot easily show/imagine both models, moreover, when using Procrustes in the optimization, the residual transform move the models between the two view modes, For instance, see this blending made from two screen captures of Groomed and Reconstructed:

![Blending_Groomed_Reconstructed](https://user-images.githubusercontent.com/80735487/148095056-af62190d-3a03-48e7-90de-f2b67e15962e.PNG).

Adding two buttons to toggle the surface displays will allow to quickly identify shape having reconstruction issue (due to bad particle correspondences) by superimposing both models in the same viewer/renderer box (taking into account alignment and optional Procrustes transforms between the two spaces). Some tests shows that is feasible (for both surface and particles, that are perfectly superimposed when "Center" is checked) For instance (reconstructed mesh in yellow):

![Superimposition](https://user-images.githubusercontent.com/80735487/148095870-e3319b1c-17ed-4527-b75a-c9b7c520e727.PNG)

Optionally, a button to compute the mesh/mesh distances allowing to show the error map directly in Studio can be also added.

**Comment by akenmorris** [comment]
Complete in #1777
