### ISSUE TITLE
add the Tests executables to ShapeWorks releases

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1613]
This will enable us to verify things are working as expected on our users' deployments when something isn't working for them. The deployed use cases do not cover everything (and in general, we shouldn't assume they always will). 

- [ ] include data
- [ ] update GitHub deployment to include tests
- [ ] update Cmake script to set TEST_DATA_DIR so it can be used from any install location 
- [ ] modify test execution script to be run from anywhere (@akenmorris knows about this)
- [ ] add brief note in documentation (maybe a Testing section)

**Comment by akenmorris** [comment]
I see no reason to do this.
