### ISSUE TITLE
Studio is missing Group Differences

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#163]
ShapeWorksStudio is missing the entire group differences, group coloring and group glyphs (arrows) from ShapeWorksView2.

This includes:

- [x] Difference button
- [x] Support for <group_ids> tag
- [x] Group1 / Group 2 buttons
- [x] Group1 <---> Group2 slider in PCA tab

**Comment by akenmorris** [comment]
Difference display complete:

<img width="1009" alt="Screen Shot 2020-02-02 at 11 42 54 AM" src="https://user-images.githubusercontent.com/1693349/73613286-317c9e80-45b1-11ea-8de2-8a17fb557eaa.png">

**Comment by sheryjoe** [comment]
Nice job Alan! and just in time for the users meeting. Thanks!

What is left here is the animation from group 1 mean to group 2 mean.

**Comment by akenmorris** [comment]
This has been completed.
