### ISSUE TITLE
Fixed Domain Project API

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1645]
We need to add fixed domains option to the ShapeWorks project spreadsheet. 
This will involve an option to initialize subjects (using previously optimized particles or mean) and an option to fix subjects. 
This will be used in the new ellipsoid_fd use case and full deep_ssm use case.

**Comment by akenmorris** [comment]
Is this an API issue or an issue to support fixed domains in the spreadsheet as we do in XML?

**Comment by jadie1** [comment]
Both I think, once we support fixed domains in the spreadsheet we can update the project API so that we can use it in python
