### ISSUE TITLE
Mesh warping in Post should be refactored (using VTK) and integrated into the Reconstruction class

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#166]
The mesh warping code in Post will be refactored to use VTK and will be integrated into the Reconstruction class to be used (using a method flag) via cmd tools and Studio.

**Comment by sheryjoe** [comment]
The surface reconstruction class should be extended to work with meshes too. This will support the analyze phase when we optimize particles directly on meshes; @0leks 's work. Adding @akenmorris to this issue to have Studio reconstruct surfaces using meshes when optimizing on meshes.

**Comment by riddhishb** [comment]
@akenmorris What Eigen should I use, I am writing this code currently, will create the branch soon

**Comment by akenmorris** [comment]
I'm not sure what's going on with our Eigen versions.  @cchriste ?

**Comment by akenmorris** [comment]
This is completed.  It is separate from the Reconstruction class however as it does not have anything to do with Images.
