### ISSUE TITLE
Add ability to run procrustes in scaling only mode

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1673]
Add option in Studio, in spreadsheet, maybe even XML.

**Comment by ShaquilleCharles** [comment]
Is there any update regarding this feature?

**Comment by sheryjoe** [comment]
@ShaquilleCharles This feature is planned to be added in the 6.3 release scheduled in April. @akenmorris please confirm.

**Comment by akenmorris** [comment]
Yes, 6.3

**Comment by ShaquilleCharles** [comment]
Any update on when 6.3 rolls out? Sorry to keep inquiring! This is the last piece to the puzzle and our attendings are eager to see the study results =)

**Comment by akenmorris** [comment]
We are hoping on this month, but for this particular issue, I am actively working on it this week and hope to have it finished by Friday.

**Comment by ShaquilleCharles** [comment]
Excellent! Thank you so much! I'll be sure to update the team =)

**Comment by akenmorris** [comment]
@ShaquilleCharles - This is completed, merged and available in the development releases:

https://github.com/SCIInstitute/ShapeWorks/releases

**Comment by ShaquilleCharles** [comment]
Thank you so much!
