### ISSUE TITLE
ShapeWorks Portal data missing 

### ISSUE THREAD

**Issue by NahomKidane** [SCIInstitute/ShapeWorks#1703]
It may be a stupid question. I am trying to download the sample data but the ShapeWorks Portal is empty. Did I miss something during the registration process?

**Comment by akenmorris** [comment]
Are you looking here?

https://girder.shapeworks-cloud.org/#collections

**Comment by NahomKidane** [comment]
Yes. No files are visible.

**Comment by akenmorris** [comment]
Can you try it now?

**Comment by NahomKidane** [comment]
I see use-case-data-v2 folder now, but it is empty inside

**Comment by akenmorris** [comment]
Ok, I think this time I've got the permissions fixed.  Not sure how this happened.

**Comment by NahomKidane** [comment]
Thank you! I see the files!
