### ISSUE TITLE
dev versions of documentation are not being produced by GitHub actions

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1719]
http://sciinstitute.github.io/ShapeWorks/6.2/ is showing latest (the latest official release) documentation version, but the automatic GitHub actions should be producing the dev versions, "6.3.x (dev)".

**Comment by cchriste** [comment]
@akenmorris Does this somehow need to explicitly specify a branch to deploy?
```
-mkdocs gh-deploy --config-file "${GITHUB_WORKSPACE}/mkdocs.yml"
+cd "${GITHUB_WORKSPACE}" && mike deploy --title "6.3 (dev)" 6.3 dev
+mike set-default 6.2
```
There is a `--branch <name>` parameter for mkdocs.

**Comment by akenmorris** [comment]
I think we're always doing master branch.

https://github.com/SCIInstitute/ShapeWorks/blob/7857af0c8e9a3cc5afa21a6f472cb2607a0a27a3/Support/deploy_docs.sh#L49

**Comment by cchriste** [comment]
> I think we're always doing master branch.
> 
> https://github.com/SCIInstitute/ShapeWorks/blob/7857af0c8e9a3cc5afa21a6f472cb2607a0a27a3/Support/deploy_docs.sh#L49

This is how it's supposed to work. Explicitly specifying the documentation branch might fix things, though by default it assumes `gh-pages`. Should we use something like `origin/gh-pages`? Or an explicit full path to the gh-pages branch?

`mike deploy --title "6.3 (dev)" 6.3 dev --branch gh-pages`

**Comment by akenmorris** [comment]
I don't know.

You will probably have to experiment with doing the deploy from your local system.  The docs stuff only runs on master, so the only way to test it from GHA is to either merge or commit directly to master.

**Comment by akenmorris** [comment]
I mean, are able to deploy **_to github.io_** successfully from your local machine?  We should be able to see the results here if so:

http://sciinstitute.github.io/ShapeWorks/6.2/

You can make a PR, but keep in mind the deploy docs won't run (unless you alter the branch name check) until you merge it.

**Comment by akenmorris** [comment]
Fixed
