### ISSUE TITLE
Add a constructor to Mesh class to create a sw.Mesh using points and faces 

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1724]
Given points and faces as Eigen matrices, create the mesh. 
This is required for the shared boundary command.

**Comment by akenmorris** [comment]
I think Ben already added this:

https://github.com/SCIInstitute/ShapeWorks/blob/7857af0c8e9a3cc5afa21a6f472cb2607a0a27a3/Libs/Mesh/Mesh.h#L50

https://github.com/SCIInstitute/ShapeWorks/blob/7857af0c8e9a3cc5afa21a6f472cb2607a0a27a3/Libs/Python/ShapeworksPython.cpp#L921

Is this suitable?

**Comment by iyerkrithika21** [comment]
Oh, this is exactly what I wanted! Great! 
It looks like it was added 5 days ago.
