### ISSUE TITLE
Studio: Particle coloring is not removed when optimization is rerun

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1734]
When running a model in Studio, if you have used the particle coloring options (pressing 1 or 2 when hovered over a particle to show distances or running good/bad particle tool), the coloring is maintained based on particle number (I think) even after rerunning the optimization. It seems like this should be cleared with the 'Run Optimization' button.

**Comment by akenmorris** [comment]
Agreed.

**Comment by akenmorris** [comment]
It looks like this was completed in February.  Can you confirm in a recent development build?

**Comment by patkins** [comment]
I am using a recent dev build and definitely could not remove the good/bad particle coloring, the particles would be colored normally until the same number of particles were on the shape and then would only be green and red, but wouldn't correspond to anything relevant.

**Comment by akenmorris** [comment]
Ah, the good/bad.  I thought you meant the '1' and '2'.

**Comment by patkins** [comment]
Yeah, sorry. I didn't verify that issue still existed. But I did have a weird pattern of colors for the '1' option in the latest dev build, which I assumed was related. I'll see if I can recreate it and add additional info.

**Comment by patkins** [comment]
I think the oddity I noted yesterday using the '1' option (where the particle color map shows the distance to the chosen particle) may have been if a particle is chosen during optimization. In this scenario, only some particles are colored and the colormap doesn't seem to correlate to distance. (It's possible that it is not intended to function in this scenario, but I figured I would let you know.)
