### ISSUE TITLE
Studio: Abort Optimization does not always seem to stop the optimization

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1735]
I think this only occurs if optimization parameters have not been changed (and potentially only when done quickly after the start of optimization), but when trying to understand where particles are initializing, I  hit the 'Abort Optimize' button as soon as particle optimization starts and then view where the first two particles are located. If done repeatedly, the particles seem to keep optimizing in the background (even if the project is reopened), such that if you press 'Run Optimize' it will start more than 2 particles, depending on the time that has passed.

**Comment by akenmorris** [comment]
I'll look into it.  

I'd also like to replace the behavior of the Run Optimize to be more like the DeepSSM Run button that disables temporarily so that you don't accidentally double click it and cancel.
