### ISSUE TITLE
Studio: Landmark placement sensitive to scrolling 

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1739]
When using the place landmark tool in Studio, if you have more shapes than are currently shown on the screen, when you try to scroll up/down (with your mouse wheel or on screen) to view additional shapes, the landmark placement tool stops working or works intermittently (sometimes even moves landmarks of the initially viewed shapes and removes the visualization of the landmark). The shapes that were not visible prior to scrolling also sometimes turn red after scrolling (for the black background and gray shapes color scheme on linux, this did not happen on windows, but it could have been chance).  If you adjust the viewer to show all shapes, you can place landmarks and see all landmarks as expected.

**Comment by patkins** [comment]
FYI The red shapes also occurs on windows.

**Comment by akenmorris** [comment]
I think this is two separate issues.  Can you tell me more about the red shapes?  Are you displaying a scalar field on them, or are the regular ones just "orange" or whatever your default color is?

**Comment by patkins** [comment]
The shapes are just the default color. I did a bit more fiddling with this and it seems that the red shapes are the ones that aren't visualized after scrolling. For this example, I started with 16 shapes visualized, added a new landmark, scrolled down one mouse click, then zoomed out twice. If you don't scroll after adding a landmark, the shapes don't turn red. Interestingly, if I scroll one click up from what is shown, the 'red' shapes are the shapes located in the location of the red shapes in this image (but include a different set of shapes). I can make a video if that's helpful, just let me know.
![image](https://user-images.githubusercontent.com/13870137/164285722-ead45295-8caf-491b-8b7e-15a67b7fe653.png)

**Comment by patkins** [comment]
You have to add a landmark, but you don't have to place any yet. I've uploaded a quick video to /home/sci/atkins/forAlan that shows what is happening (note that at second 12 or 13, I scroll down one click on my mouse, which is important in recreating this). Hope this helps.

**Comment by akenmorris** [comment]
Thanks!  The video made all the difference.  For whatever reason (haven't discovered yet), it only does this when opening the new shapes from within Studio like this.  When I open them from the command line as I usually do (e.g. studio *.nrrd), I don't get this behavior.  Thanks again!

**Comment by akenmorris** [comment]
Nevermind, I can do it on the command line itself, but I was doing about 600 shapes there and for some reason it doesn't happen then.  But the smaller selection I was doing from the file chooser triggered it and so do using a similar amount from the command line, as does loading them from a project file.

**Comment by akenmorris** [comment]
This should be fixed in dev releases, @patkins , please re-open the issue if that's not the case.
