### ISSUE TITLE
Python Optimization

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1741]
We need to recreate the Python optimization particle update process in Python and verify that it is the same (slight numerical difference aside) as C++ optimization. This will aid in implementing new optimization schemes such as issue #1701

**Comment by iyerkrithika21** [comment]
We have an issue for this: #568
And some updates have been made for this in branches: python_optimize and sub_optimize_python

**Comment by jadie1** [comment]
Okay, thanks. I knew progress had been made but didn't know there was already an issue open. Closing this now.
