### ISSUE TITLE
itk filter source files within shapeworks code base

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#177]
I found following two places with some itk filters existing in our code.

Libs/Transforms
Prep/Source/MeshTools/ParticleBasedSurfaceReconstruction/source

@cchriste : As per our discussion today, I think there is a need to comb all the source folders in our code base to check where the itk files have been copied and pasted, this could be due to phasing out of those filters in the past.

**Comment by sheryjoe** [comment]
@archanasri @cchriste still relevant?

**Comment by archanasri** [comment]
Maybe. We'll have to check.

**Comment by cchriste** [comment]
Maybe Libs/Analyze/Reconstruction.h/cpp? The only directory called "source" is now a top level path in <src>/Post, so maybe the other one is gone. `Reconstruction` a complicated itk-ish class though. 🤷 

I'd love to close this issue, but I don't know for certain if we're still using cut-and-pasted itk classes.

**Comment by cchriste** [comment]
> Libs/Transforms

This library is now gone. Hopefully the cut-and-pasted itk code went with it.

**Comment by cchriste** [comment]
@archanasri @akenmorris @prafulag Can we close this issue now?

**Comment by archanasri** [comment]
I think we can close this issue and create a new one if we find itk filter source files later.
