### ISSUE TITLE
Updating Splitting and Initialization to Avoid Correspondence Issues

### ISSUE THREAD

**Issue by HeavenlyBerserker** [SCIInstitute/ShapeWorks#1772]
Improving correspondences in general but especially within constraints framework by improving splitting and initialization.

**Comment by akenmorris** [comment]
@HeavenlyBerserker , we don't have anything planned on this for the 6.4 release, right?  Move to 6.5?

**Comment by HeavenlyBerserker** [comment]
Sure, this is something that is not clear how to do. I have a bunch of ideas, but they keep changing.

**Comment by HeavenlyBerserker** [comment]
I don't think this is relevant anymore? At least not as an issue, more of a general goal.

**Comment by akenmorris** [comment]
Yeah.
