### ISSUE TITLE
number_of_clusters=1 in warpToMean

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#178]
For first cluster, the cluster center is randomly assigned. We may add an option in xml to provide the sample to be used as first cluster center.

@sheryjoe : I can add it if this seems sensible to do.

**Comment by sheryjoe** [comment]
If one cluster is given, this should be the median shape not a user defined sample or a random one.

**Comment by prafulag** [comment]
The code for kmeans is actually the kmeans++ initialization. No iterative clustering after that initialization. I think if I recall we may have decided against running clustering iterations to not make it further slow.

**Comment by sheryjoe** [comment]
Fixed. If one cluster is indicated for the ReconstructMeanSurface, the median shape is used.
