### ISSUE TITLE
Which api should I use to generate a mesh model after building the shape model?

### ISSUE THREAD

**Issue by oliverzzm** [SCIInstitute/ShapeWorks#1796]
I'm new to shape modeling domain. I've run the ellipsoid_pca.py example, and got the loadings.txt and eigen_vectors.txt.
Do I have to read in both of these files and write some code to generate a bunch of particles given a sampling vector, as is written in the original thesis. After that, I need to use the class meshWarper, pass in the refereceMesh, the referenceParticles and the particles I just generated to generate a surface model. Or is there an api that handles all of these for me? Thank you!

**Comment by oliverzzm** [comment]
Wish there could be an example for this.

**Comment by iyerkrithika21** [comment]
If you have run the ellipsoid use case, you can open the shape model in ShapeWorksStudio, where everything you described is done. The shapes along the modes of variation are visualized.
- See Analyzing Shape Model in http://sciinstitute.github.io/ShapeWorks/6.3/use-cases/segmentation-based/ellipsoid.html. 
- You can export the meshes from Studio See http://sciinstitute.github.io/ShapeWorks/6.3/studio/studio-export.html

There is no python API yet to support this.

**Comment by oliverzzm** [comment]
> If you have run the ellipsoid use case, you can open the shape model in ShapeWorksStudio, where everything you described is done. The shapes along the modes of variation are visualized.
> 
> * See Analyzing Shape Model in http://sciinstitute.github.io/ShapeWorks/6.3/use-cases/segmentation-based/ellipsoid.html.
> * You can export the meshes from Studio See http://sciinstitute.github.io/ShapeWorks/6.3/studio/studio-export.html
> 
> There is no python API yet to support this.

Thank you for your reply. Actually shape modeling is only one part of the project I am doing. I have biplane x-rays of a femur sawbone, which contain both frontal and lateral view. I wish to find the best modes of variation and the pose of the sawbone , so that the bone I generate perfectly matches the silouhettes of both x-rays when viewed from their viewpoints. So I need to write some code to somehow minimize a cost function. The studio won't suit for this scenario.

**Comment by sheryjoe** [comment]
@akenmorris This is related to #1018. Do we have Python examples to use the consolidated APIs for sampling along PCA modes?

**Comment by akenmorris** [comment]
@sheryjoe , yes there is an example of using the Python API from consolidation of ReconconstructSamplesAlongPCAModes:

https://github.com/SCIInstitute/ShapeWorks/blob/master/Testing/PythonTests/reconstructpca.py

What was consolidated was only the existing functionality and since there was not an executable that uses the mesh warping approach, there's isn't an example for this.

A higher level, easier to use API will be added with these two issues which are both needed in the short term for ShapeWorks-Cloud:

* #1778 
* #1779
