### ISSUE TITLE
Building from source failed( failed at building openvdb dependency)

### ISSUE THREAD

**Issue by oliverzzm** [SCIInstitute/ShapeWorks#1806]
Steps to reproduce:
OS: win11

1. download source code 6.3.0.zip
2. install shapeworks.bat into a new conda environment
3. add Qt dir to path variable
4. open source folder with git bash, and run "bash ./build_dependencies.sh --build-type=RelWithDebInfo"
The following error occured.
<img width="879" alt="image" src="https://user-images.githubusercontent.com/30902598/176351301-d8eeaa69-388b-4679-826f-c341af1407d7.png">

**Comment by akenmorris** [comment]
It seems our build documentation here is slightly in error:

http://sciinstitute.github.io/ShapeWorks/6.3/dev/build.html

To build from source, you will need to use the `install_shapeworks.sh`.  The bat file is provided for end-users only so that they do not need to install msys2, so it does not included all of the packages needed for building.  I will add a separate issue about fixing the build docs.

**Comment by akenmorris** [comment]
Also, if it helps, the build recipe used by GitHub Actions to create the releases is here:

https://github.com/SCIInstitute/ShapeWorks/blob/master/.github/workflows/build-windows.yml

**Comment by oliverzzm** [comment]
> 

Thank you! Still I want to build a windows .sln on my local computer so that I could integrate shapeworks as a 3-rd party lib into my other solution files. I found it impossible to "source ./install_shapeworks.sh" on native comand prompt or powershell. So I installed windows subsystem for linux. Is this the correct way to run shell files on windows?
By the way, have you considered register shapeworks into c++ package mangers like vcpkg or conan?

**Comment by oliverzzm** [comment]
Thank you morris! I really appreciate your patient help here! I did not major in software enginnering, so the Github Actions featue is too hard-core for me. But I will try to learn what  "Github Actions" is and guess what each term in the YAML file means.
Just for now, I think following the guide in the documentation suits me better. I have downloaded git-bash, and I'll first try 
"source ./install_shapeworks.h" in git-bash. I hope following the steps in the doc will bring me a .sln finally. I will let you know if I succeed.
Again, appreciate your reply!

**Comment by akenmorris** [comment]
You don't need to learn about Github Actions, but you can look at the "run:" lines to see what it's doing.  In any case, the rest of the windows build documentation should be mostly up to date.  Let us know if you have any other questions.

**Comment by oliverzzm** [comment]
Hello morris, I succeeded! Solution building passed 100%  in visual studio.

Below are steps to reproduce, in case anyone needs it.
Environment:
os: win11
visual studio 2019
qt 5.15.2

1. Use git-bash through out the time. Don't use command prompt or powershell. If one has already installed anaconda, one can
do little setup to make conda accessible in git-bash (basically editing .bashrc file, I suppose one could find many instructions on stackoverflow.
2. Then source "source ./ install_shapeworks.sh". However, the "font-awesomemarkdown" may not be successfully installed through pip install as in the shell script (something related to encoding). That's because there's some code problem in the setup.py. So download  the font-awesomemarkdown0.2.6 from the pypi website. And change line 25 from:
with open('README.rst') as f:            To
with open('README.rst',encoding="utf-8") as f:

then cd to the directory where setup.py is located and type in "pip install ."

3. Then run ./build_dependencies.sh. Remember to use --build-type=RelWithDebInfo. During building vtk and JKQTPLOTTER, there might be some compiler error and link error about something "QPaintPath". Just #include <QPainterPath> in all cpp files that report this error, and you will be fine.
Also when building xlnt, there might be some encoding problem that leads to compiler and link error (code has non-ascii character). Just dive into the corresponding file and go to the corresponding line, change the character to similar ascii character then the problem would be solved.

4. If everything is fine, then a cmake command suggestion would be printed in git-bash, like the following

`Dependency paths:
  VXL_DIR:
  VTK_DIR: /d/open_source_library/sw/ShapeWorks-6.3.0/../dependencies/lib/cmake/vtk-8.2
  ITK_DIR: /d/open_source_library/sw/ShapeWorks-6.3.0/../dependencies/lib/cmake/ITK-5.2
  EIGEN_DIR: /d/open_source_library/sw/ShapeWorks-6.3.0/../dependencies\\share\\eigen3\\cmake
  OpenVDB_DIR: /d/open_source_library/sw/ShapeWorks-6.3.0/../dependencies/lib/cmake/OpenVDB/
  LIBIGL_DIR: /d/open_source_library/sw/ShapeWorks-6.3.0/../dependencies/libigl/cmake
  GEOMETRY_CENTRAL_DIR: /d/open_source_library/sw/ShapeWorks-6.3.0/../dependencies/geometry-central
  ACVD_DIR: /d/open_source_library/sw/ShapeWorks-6.3.0/../dependencies


## To configure ShapeWorks, create a build directory and from there run...

cmake -DCMAKE_CXX_FLAGS=-g -DCMAKE_PREFIX_PATH=/d/open_source_library/sw/ShapeWorks-6.3.0/../dependencies -DVXL_DIR= -DUSE_OPENMP=ON -DBuild_Studio=1  -Wno-dev -Wno-deprecated -DCMAKE_BUILD_TYPE=RelWithDebInfo /d/open_source_library/sw/ShapeWorks-6.3.0

real    4m51.452s
user    0m0.545s
sys     0m1.473s`

5. Run the command, it should produce the following output:
`-- Building for: Visual Studio 16 2019
-- Found Python3: C:/Users/Cong/anaconda3/envs/shapeworks_630_win_dev/python.exe (found suitable exact version "3.7.8") found components: Interpreter
-- SHAPEWORKS_GUI: ON
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.29.30145.0
-- The CXX compiler identification is MSVC 19.29.30145.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OpenVDB_DIR set to D:/open_source_library/sw/ShapeWorks-6.3.0/../dependencies/lib/cmake/OpenVDB (must contain FindOpenVDB.cmake)
-- Found OpenVDB: D:/open_source_library/sw/dependencies/include (found version "7.1.0") found components: openvdb
CMake Warning at D:/open_source_library/sw/dependencies/lib/cmake/OpenVDB/FindOpenVDB.cmake:410 (message):
  Unable to determine OpenVDB ABI version from OpenVDB installation.  The
  library major version "7" will be inferred.  If this is not correct, use
  add_definitions(-DOPENVDB_ABI_VERSION_NUMBER=N)
Call Stack (most recent call first):
  CMakeLists.txt:50 (find_package)


-- Found IlmBase: C:/Users/Cong/anaconda3/envs/shapeworks_630_win_dev/Library/include/OpenEXR (found version "2.5") found components: Half
-- Found TBB: C:/Users/Cong/anaconda3/envs/shapeworks_630_win_dev/Library/include (found version "2019.9") found components: tbb
-- Found ZLIB: optimized;C:/Users/Cong/anaconda3/envs/shapeworks_630_win_dev/Library/lib/z.lib;debug;C:/Program Files (x86)/zlib/lib/zlibd.lib (found version "1.2.11")
-- Found Boost: C:/Users/Cong/anaconda3/envs/shapeworks_630_win_dev/Library/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0") found components: iostreams system
-- warning: could not find 'objdump' - cannot analyze prerequisites...
-- CMAKE_SHARED_LINKER_FLAGS: /machine:x64
-- Looking for XLNT in
-- Found XLNT: D:/open_source_library/sw/dependencies/lib/xlnt.lib
-- Found XLNT under D:/open_source_library/sw/dependencies/include
-- XLNT_INCLUDE_DIR=D:/open_source_library/sw/dependencies/include
-- XLNT_LIBRARY=D:/open_source_library/sw/dependencies/lib/xlnt.lib
-- XLNT_LIBRARIES=D:/open_source_library/sw/dependencies/lib/xlnt.lib
-- Looking for ACVD in
-- Found ACVD: D:/open_source_library/sw/dependencies/lib/vtkDiscreteRemeshing.lib
-- Found ACVD under D:/open_source_library/sw/dependencies/include
-- ACVD_INCLUDE_DIRS=D:/open_source_library/sw/dependencies/include/ACVD/DiscreteRemeshing;D:/open_source_library/sw/dependencies/include/ACVD/Common;D:/open_source_library/sw/dependencies/include/ACVD/VolumeProcessing
-- ACVD_LIBRARIES=D:/open_source_library/sw/dependencies/lib/vtkDiscreteRemeshing.lib;D:/open_source_library/sw/dependencies/lib/vtkVolumeProcessing.lib;D:/open_source_library/sw/dependencies/lib/vtkSurface.lib
Looking for LIBIGL in
-- Found LIBIGL under D:/open_source_library/sw/dependencies/libigl/cmake
-- MSVC -> forcing use of dynamically-linked runtime.
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Creating target: igl::core (igl)
-- Found Boost: C:/Users/Cong/anaconda3/envs/shapeworks_630_win_dev/Library/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0") found components: filesystem
-- Found nlohmann_json: C:/Users/Cong/anaconda3/envs/shapeworks_630_win_dev/Library/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found suitable version "3.10.5", minimum required is "3.10.5")
-- Building STATIC libraries
--  resolving Eigen dependency:
-- Searching for SuiteSparse.
-- Found BLAS: C:/Users/Cong/anaconda3/envs/shapeworks_630_win_dev/Library/lib/openblas.lib
-- Failed to find SuiteSparse - Did not find AMD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find AMD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CAMD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CAMD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find COLAMD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find COLAMD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CCOLAMD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CCOLAMD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CHOLMOD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CHOLMOD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find SuiteSparseQR library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find SUITESPARSEQR header (required SuiteSparse component).
-- Failed to find SuiteSparse - Failed to find either: SuiteSparse_config header & library (should be present in all SuiteSparse >= v4 installs), or UFconfig header (should be present in all SuiteSparse < v4 installs).
-- Did not find METIS library (optional SuiteSparse dependency)
-- Failed to find some/all required components of SuiteSparse. (missing: AMD_FOUND CAMD_FOUND COLAMD_FOUND CCOLAMD_FOUND CHOLMOD_FOUND SUITESPARSEQR_FOUND SUITESPARSE_VERSION)
-- Did not find all SuiteSparse dependencies, disabling SuiteSparse support.
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Found PythonInterp: C:/Users/Cong/anaconda3/envs/shapeworks_630_win_dev/python.exe (found suitable version "3.7.8", minimum required is "3.7")
-- Found PythonLibs: C:/Users/Cong/anaconda3/envs/shapeworks_630_win_dev/libs/Python37.lib
-- Performing Test HAS_MSVC_GL_LTCG
-- Performing Test HAS_MSVC_GL_LTCG - Failed
-- LTO disabled (not supported by the compiler and/or linker)
-- opt libs
-- Found OpenGL: opengl32
-- Setting C:/Qt_online/5.15.2/msvc2019_64/bin/windeployqt.exe command.
-- QT widget: C:/Qt_online/5.15.2/msvc2019_64/bin
-- Found GTest: C:/Users/Cong/anaconda3/envs/shapeworks_630_win_dev/Library/lib/gtest-md.lib
-- CMAKE_CXX_FLAGS: /EHsc   /bigobj -openmp -fPIC
-- CMAKE_EXE_LINKER_FLAGS: /machine:x64
-- CMAKE_SHARED_LINKER_FLAGS: /machine:x64
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    VXL_DIR`

We could see that vxl truly is not needed anymore.

7. Finally open the .sln, and remember to change build type from default debug to RelWithDebInfo. Otherwise there might be 9 projects in the solution that failed to build.

**Comment by oliverzzm** [comment]
Hello Morris, I tried to run the ShapeWorksStudio project in the solution and got errors: "Cannot find ***.dll, reinstalling this program may solve the issue". I know a general solution to this is to copy missing dlls to .exe path, or we can add the paths to missing dlls in the project properties, under Debugging/enviroment, adding things like, PATH=%PATH%; some_path\lib1\build;some_path\lib2\build. But there seemed to be lots of dlls. Would it be possible to do some setup in cmake so that when the solution finishes building, it automatically handles all of these messy things for us?

**Comment by akenmorris** [comment]
I think it's currently handled in this script:

https://github.com/SCIInstitute/ShapeWorks/blob/master/Support/package_windows.sh

It's probably possible to convert this to a set of cmake commands?

On dev machines, I typically just copy the DLLs once and then it doesn't need to be done again.

**Comment by oliverzzm** [comment]
> I think it's currently handled in this script:
> 
> https://github.com/SCIInstitute/ShapeWorks/blob/master/Support/package_windows.sh
> 
> It's probably possible to convert this to a set of cmake commands?
> 
> On dev machines, I typically just copy the DLLs once and then it doesn't need to be done again.

Thanks! It worked!
