### ISSUE TITLE
Support for grooming of multi-type data in multiple domain projects

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1808]
How do we support grooming when the input data contains a mixture of data types in Studio? 
For example, the shared boundary project contains mesh and contours, and the mesh grooming options show up, which are also applied to contour, leading to the groomed contour file being saved as ".vtk" losing all the contour info and breaks when you move to optimization.

**Comment by akenmorris** [comment]
This is already handled with domain types.
