### ISSUE TITLE
View2 new xml 

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#181]
I need an example xml for the new view2 or information about the new tags

**Comment by prafulag** [comment]
Also, will the old xml work without any modification ?

**Comment by aogs** [comment]
If you run the ellipsoid example it will write out an example of the new format.

**Comment by aogs** [comment]
It still reads the old xml. It will just use the old reconstruction method.

**Comment by prafulag** [comment]
okay, thanks.
