### ISSUE TITLE
Master still shows 6.2 release

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#1813]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/3253036/176940560-8bf5f6b2-fde7-4481-9526-a9d987f4b9cc.png">

**Comment by akenmorris** [comment]
Ah, the readme

**Comment by akenmorris** [comment]
Fixed in c08fba021c4180b65e5d5883f7147a6029958487
