### ISSUE TITLE
Crash on optimize with particular small project

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1815]
[cutting_plane_multi.zip](https://github.com/SCIInstitute/ShapeWorks/files/9032088/cutting_plane_multi.zip)

Not sure how this is any different than Testing/data/sphere/optimize.xlsx

Seems to crash even with the cutting planes removed.

**Comment by HeavenlyBerserker** [comment]
> Seems to crash even with the cutting planes removed.

Very odd. I copy-pasted the test and modified it. Did you figure this out?
