### ISSUE TITLE
Add `shapeworks::Exception` for better error handling

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#182]
Most of our tools could use some better error handling. For example, right now if distance transforms don’t have matching origins, View2 and Studio will just dump out with “std::exception” with no indication what the problem is.

**Comment by akenmorris** [comment]
I think this is a fairly useless issue to have on GitHib as it’s not specific enough and has no real way of being completed. (I’m the one that added it) better is too subjective.

**Comment by cchriste** [comment]
This class should include `operator<<` that describes the reason for it being thrown.
See example usage in the comment for this commit: 
https://github.com/SCIInstitute/ShapeWorks/commit/1a56525e8e31fb1a9c2b297c5ad67f8973a0c3e7

Creating shapeworks-specific exceptions will help us handle errors better at multiple levels. This issue merely creates the class (and an associated unit test, preferably like the example in the comment).
