### ISSUE TITLE
Landmark initialization for multi-type multiple domain projects

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1824]
For projects with multiple domains per shape, if the landmarks are only initialized for one domain, [the particles incorrectly move to a different domain during initialization. 
GIF: /usr/sci/projects/ShapeWorks/debug/landmarks.gif
Data : /usr/sci/projects/ShapeWorks/debug/landmarks_1824.zip

**Comment by akenmorris** [comment]
It looks like the columns are just mixed up.  The column with the landmarks that contains points (for the contour) is labeled "landmarks_file_2", which matches one of the sides, the one where you see the particles spreading on.

I've fixed the columns here:

[peanut_shared_boundary_multiscale_landmark_alan.xlsx](https://github.com/SCIInstitute/ShapeWorks/files/9162194/peanut_shared_boundary_multiscale_landmark_alan.xlsx)

**Comment by iyerkrithika21** [comment]
When I created the project sheet, I named it landmarks_file_4, and after running the optimization, it changed the column name automatically.

**Comment by akenmorris** [comment]
So the project re-saving reordered the columns incorrectly?

I think unfortunately, there may be some parts that assume that the multiple domain columns will always come in the same order, since that's how Studio will always create them.  It may be making assumptions about landmarks_* and not actually comparing the suffixes to match things.

**Comment by iyerkrithika21** [comment]
When I created the project file, I only added column I for domain 4- 
![image](https://user-images.githubusercontent.com/11266258/180315572-6a65bb62-56db-4fde-8f70-e1bf7a71deff.png)
After optimization, more columns were populated - S, T, and U for domains 1, 2, and 3, and the provided landmarks (column I) were automatically for domain 1 during optimization. 

So I guess for multiple domains, we need to initialize the landmarks for all domains and keep the particles files empty for the domains where we don't want the landmarks.

**Comment by akenmorris** [comment]
Yeah, I think it's a general problem with the xlsx project reader/writer that it assumes sets of columns will be complete and in the right order.  Will fix.

**Comment by akenmorris** [comment]
This should now be fixed with the new readers (json and xlsx), these columns take into account the suffix, so the other shouldn't matter any more.
