### ISSUE TITLE
Rigid Alignment

### ISSUE THREAD

**Issue by AtefehKashani** [SCIInstitute/ShapeWorks#183]
checkout the resampling and the nearest neighbor interpolation of the source segmentation in the /Prep/Source/Alignment/ICPRigid3DImageRegistration/source/ICPRigid3DImageRegistration.cxx

**Comment by AtefehKashani** [comment]
Rather than using nearest neighbor and directly resample the segmentation, the resampler of the segmentation should resample the distance transform using linear interpolation and then threshold to resampled distance transform to produce the transformed segmentation.

**Comment by sheryjoe** [comment]
Closing this as a more general issue #195 has been issued.
