### ISSUE TITLE
ShapeCohortGen image size bug

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1878]
Currently, the ShapeCohortGen package creates images of different sizes even when `randomize_size` is set to `False`.

**Comment by sheryjoe** [comment]
@jadie1  We would also want to make this generic enough to handle generating shapes with different alignments. An immediate example would be adding anatomy localization to deepssm that @j-void is working on. In this case, I would generate all shapes first with random translations, rotations, and scaling, then define the image size to be the smallest image size (with some buffering) that would encapsulate all generated shapes.

**Comment by sheryjoe** [comment]
> @jadie1 We would also want to make this generic enough to handle generating shapes with different alignments. An immediate example would be adding anatomy localization to deepssm that @j-void is working on. In this case, I would generate all shapes first with random translations, rotations, and scaling, then define the image size to be the smallest image size (with some buffering) that would encapsulate all generated shapes.

this is something that @j-void  can help with too.

**Comment by jadie1** [comment]
@sheryjoe We have these true or false options already. When you generate the shape you can specify `randomize_center` and `randomize_rotation`.
Then when you generate the segmentation/image you can specify `randomize_size` and `allow_on_boundary`. 
If these two options are both false, the image size is the smallest bounding box that contains all shapes with some padding. If  `randomize_size` is true then the individual shapes bounding box is used with random padding. If `allow_on_boundary` is true then some shapes will lie on the image boundary (we'd only use this option to demonstrate a grooming pipeline). 

Is there anything else you think we need to add?

**Comment by akenmorris** [comment]
Resolved in #1879
