### ISSUE TITLE
Good/Bad Particles Display in Studio

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#189]
SurfaceReconstruction provides a way to tag particles as good or bad.  It would be great if Studio could have a method for displaying this.

**Comment by jadie1** [comment]
Shireen and I were discussing this in context of the femur use case and thought it would be really helpful. Has there been any more consideration of this?

**Comment by akenmorris** [comment]
Sounds great.   I don't actually know much about the good/bad particles since it post-dates my previous involvement in shapeworks, but I will look into it.

**Comment by jmozing2** [comment]
what is the status on this? several of us on the ortho side are eager to leverage this capability

**Comment by akenmorris** [comment]
We will try to prioritize this.  I guess the primary difficulty is that the code for generating these good/bad particles is only part of the distance transform surface reconstruction.  We will have to pull it out and generalize it to work on meshes as well.

**Comment by akenmorris** [comment]
Completed in #1713
