### ISSUE TITLE
Inputs do not occupy the same physical space

### ISSUE THREAD

**Issue by rorschach122** [SCIInstitute/shapeworks#19]
After running ShapeWorksGroom on my dataset, the resultant outputs (distance maps) are fed as input to the ShapeWorksRun (through xml)

> itk::ExceptionObject (00000000001DF9E0)
> Location: "unknown"
> File: d:\setup\itk\insighttoolkit-4.6.1\modules\core\common\include\itkImageToIm
> ageFilter.hxx
> Line: 248
> Description: itk::ERROR: MaximumEntropyCorrespondenceSampler(000000000280C1B0):
> Inputs do not occupy the same physical space!
> InputImage Origin: [-1.6150000e+002, -1.1900000e+002, -3.7500000e+001], InputIma
> ge_1 Origin: [-1.6100000e+002, -1.1950000e+002, -3.7000000e+001]
>       Tolerance: 1.0000000e-006

I assumed that there was a registration in the groom. I ran groom with these options
 groom.xml isolate hole_fill center auto_crop antialias fastmarching blur

Why is this happening?

**Comment by akenmorris** [comment]
Can you check if the images are different dimensions, or is the origin just different?

**Comment by rorschach122** [comment]
Images are of different dimensions and even the offsets from origin are different.

**Comment by akenmorris** [comment]
That's very strange, after the center and auto_crop, they should both be the same.  Is there a chance you could point me to some of your data files?

**Comment by rorschach122** [comment]
https://drive.google.com/open?id=0B74YLcmdfgGHfmhlYzVFLU00LTk3TXR0d0xTTThxdGloTjRMYjJraUJQbVd6eUJyeW8zREE

Can you access that link? Can you try running ShapeWorksGroom and Run with OpenMP on? I seem to be running into the error then. 

Can you also share any ideas on how to optimize the parameters specified in this pdf http://www.sci.utah.edu/images/software/ShapeWorks/ShapeWorksManual_Win.pdf

Are there any thumb-rules or tricks that I can use to search the parameter space based on complexity of the object?
