### ISSUE TITLE
All test/use case datasets should be downloaded from Girder rather than hard coded path

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#190]

**Comment by cchriste** [comment]
Examples currently requiring this:

- LA Use Case needs to download data rather than hard coded path #190
- ellipsoid test use case
- sphere use case  

Oleks will help to ensure data is accessible via Girder.

**Comment by strikerz76** [comment]
@AtefehKashani Is the data currently in /home/sci/atefeh.gk/Public/leftatrium.zip the namic data? If so can you add a README with a link to the source of the data and a copy of the license info?

**Comment by strikerz76** [comment]
@cchriste Where is the data for the sphere use case? Also I'm not seeing a sphere use case script.

**Comment by AtefehKashani** [comment]
> @AtefehKashani Is the data currently in /home/sci/atefeh.gk/Public/leftatrium.zip the namic data? If so can you add a README with a link to the source of the data and a copy of the license info?

@strikerz76 yes, this data is the NAMIC data, that I have downloaded and prepared for the use case. http://insight-journal.org/midas/collection/view/197
what should be in the README file?

**Comment by strikerz76** [comment]
I'm just going to copy the README on their website into the data folder.
New structure of data folder:
leftatrium.zip 
-> segmentation_LGE
-> README.txt

**Comment by AtefehKashani** [comment]
> I'm just going to copy the README on their website into the data folder.
> New structure of data folder:
> leftatrium.zip
> -> segmentation_LGE
> -> README.txt

Sounds good!

**Comment by strikerz76** [comment]
#226
