### ISSUE TITLE
Fixing weight initialization for DeepSSM training

### ISSUE THREAD

**Issue by j-void** [SCIInstitute/ShapeWorks#1900]
The weights should be initialized for Conv3d instead of Conv2d.
`# initialize model weights`
`net.apply(weight_init(module=nn.Conv2d, initf=nn.init.xavier_normal_))`	
`net.apply(weight_init(module=nn.Linear, initf=nn.init.xavier_normal_))`
[Here](https://github.com/SCIInstitute/ShapeWorks/blob/master/Python/DeepSSMUtilsPackage/DeepSSMUtils/trainer.py#:~:text=net.apply(weight_init(module%3Dnn.Conv2d%2C%20initf%3Dnn.init.xavier_normal_)))

**Comment by jadie1** [comment]
This has been fixed.
