### ISSUE TITLE
Issue with subject.set_group_values() from Python call

### ISSUE THREAD

**Issue by ben2k** [SCIInstitute/ShapeWorks#1914]
sub_group_dict = {}
sub_group_dict["base"] = "yes"
sub_group_dict["excluded"] = "no"
subject.set_group_values(sub_group_dict)

This call fails with the current code. It worked before some changes done that use ordered_map in C++. Need to add a wrapper in Python binding.

**Comment by akenmorris** [comment]
Should be fixed now.  Please re-open if that's not the case.
