### ISSUE TITLE
Studio: report progress when performing surface reconstruction

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#196]
When loading the new view2 xml file, it takes time computed the reconstructed surfaces especially for large cohorts and when all samples are taken into account to compute the dense mean (number of clusters = -1). Reporting progress even on the terminal would be helpful.

**Comment by sheryjoe** [comment]
I thought it was supposed to run reconstruction under the hood as View2 did. It turned out that I need to run the reconstruction in the Optimize! panel. A very good reason we need to move this reconstruction toe the Analyze panel.

**Comment by akenmorris** [comment]
Yes, I still need to figure out the workflow with the View2 files.  They skip to the end of the pipeline.  Normally in Studio you would run optimize and I think it even runs reconstruction at the end.  But we're skipping past that.
