### ISSUE TITLE
Release Notes 6.4

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1975]
Please add to this issue a paragraph (plus videos/snapshots for illustration) about each new/improved/bug-fix included in this release.

**Comment by jadie1** [comment]
Added options to the incremental use case when run in `--interactive` mode, including sorting method, initial model size, and incremental batch size. The sorting method determines how the shapes are sorted to be added incrementally. There are three options: 
- random : This option results in sorting the shapes randomly. It may be appropriate to use when the cohort of shapes is very large and the effect of outliers is likely small. 
- median : When this option is used, the pairwise surface-to-surface distance between all of the meshes is first computed. Then the median shape (the shape with minimum distance to all other shapes) is found. The meshes are then sorted from closest to the median to furthest. The shapes furthest from the median typically represent outliers. 
- distribution : Similar to median, when this option is used, the pairwise surface-to-surface distances are computed and the median mesh is selected. We then incrementally add one mesh at a time to the distribution (starting with the median), selecting the mesh with minimum distance to all others in the distribution. This results in meshes sorted from most inlying to most outlying.

Median sorting:
![image](https://user-images.githubusercontent.com/54382613/213803111-5e7b0479-8c54-4b99-b267-f8feed1006c7.png)

Sorting comparison: 
![image](https://user-images.githubusercontent.com/54382613/213802908-300c5e02-b932-4d51-ab92-0930a61b9e8a.png)

**Comment by iyerkrithika21** [comment]
Hip Use Case: The use case uses the hip joint to demonstrate the capability of ShapeWorks to capture inter-domain correlations and interactions directly on triangular surface meshes. The use case showcases calculating the alignment options available for multiple organ anatomies.

Modes of variation of the hip joint with global alignment 
https://sci.utah.edu/~shapeworks/doc-resources/gifs/hip_global.gif
Modes of variation of the hip joint by aligning w.r.t the femur
https://sci.utah.edu/~shapeworks/doc-resources/gifs/hip_domain1.gif
Modes of variation of the hip joint by aligning w.r.t the pelvis
https://sci.utah.edu/~shapeworks/doc-resources/gifs/hip_domain2.gif

**Comment by akenmorris** [comment]
Studio difference to mean:

<img width="1304" alt="studio_difference_to_mean" src="https://user-images.githubusercontent.com/1693349/226119487-2d2f6338-da01-4c1d-bdad-09826b2fd23c.png">

Multi-level PCA:


<img width="1419" alt="studio_analyze_view_pca_multiple_domain" src="https://user-images.githubusercontent.com/1693349/226119619-f35ef339-6dbc-48a5-80ec-1071cfbfb25e.png">


Compare original/groomed/reconstructed:

<img width="349" alt="studio_compare_controls" src="https://user-images.githubusercontent.com/1693349/226119923-f5762b8d-658c-4e21-95e2-b28da6fa93fb.png">

<img width="1371" alt="studio_compare1" src="https://user-images.githubusercontent.com/1693349/226119904-f43931bf-105f-406f-b322-f98b2aa21400.png">
