### ISSUE TITLE
Running tests modifies committed files

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1979]
After running tests cases, the following files are modified:

	modified:   Testing/data/optimize/fixed_domain/optimize_particles/sphere40_DT_local.particles
	modified:   Testing/data/optimize/fixed_mesh_domain/optimize_particles/id0002_ss3_local.particles

These test cases should be updated to use the sandboxing test infrastructure.

**Comment by HeavenlyBerserker** [comment]
Is there a solution to this? I can investigate.

**Comment by akenmorris** [comment]
Yes, there are test case examples that copy to a sandbox and run there.  We need to migrate all
of them to work this way eventually.
