### ISSUE TITLE
Cant import shapeworks_py

### ISSUE THREAD

**Issue by an99990** [SCIInstitute/ShapeWorks#1990]
Hi,
I am trying to install the shape works repo but I am encountering issues even tho the installation seemed to be successful.
I saw these issues #1529 and #1280, and its exactly the same issue. However, it was said to be fixed in master....

OS: Linux
Steps :
$ git clone repo
$ source install_dependencies.sh
$python
![image](https://user-images.githubusercontent.com/87030365/215651347-2b53ad74-4ab4-4af7-a8c6-55384a9a0718.png)

If i search for where the installation is, i can find anything. However, if i do pip list i see shapeworks ...
![image](https://user-images.githubusercontent.com/87030365/215652736-11b20115-8cff-4aa7-acae-d865c5c627a0.png)

![image](https://user-images.githubusercontent.com/87030365/215652705-05206952-dbc4-4395-b326-d362ec86a4f2.png)

Please help

**Comment by akenmorris** [comment]
It is recommended that unless you need to build ShapeWorks from source, that you instead download a pre-built binary.  Instructions to use are here:

http://sciinstitute.github.io/ShapeWorks/latest/users/install.html#installing-shapeworks-on-linux

You are welcome to build from source, instructions are provided here:

http://sciinstitute.github.io/ShapeWorks/latest/dev/build.html

**Comment by an99990** [comment]
Hi Alan,
Thank you for your reply.
Would installing the pre built give me access to the code ?

I need to import the library in python and use the different tools you guys have on my data.
Thank you
________________________________

**Comment by an99990** [comment]
Hi @akenmorris ,
Thank you for your reply.
I have just tried with the pre built binaries and I am able to import the library. However I notice a lot of deprecated messages
![image](https://user-images.githubusercontent.com/87030365/215771221-f8078262-691e-49dd-a845-9c89f7047a67.png)

is it normal?
Thank you

**Comment by akenmorris** [comment]
Yes, the deprecation messages are normal.  This is coming from a dependent python library, sklearn.  In the upcoming ShapeWorks release, dependencies and python have been upgraded.

**Comment by akenmorris** [comment]
The Python code, yes. The C++ source code doesn’t ship in the binary
distribution as most users have no need for it.

Alan
