### ISSUE TITLE
what is ParticleSystem argument

### ISSUE THREAD

**Issue by an99990** [SCIInstitute/ShapeWorks#1995]
Hi,
I am new to this library and would like to understand what needs to be provided to ParticleSystem to be able to compute compactness, specificity, and generalization. I am unable to find precisely the documentation in this regard.
All I found was that it takes a List of point files

but ParticleSystem seems to take any list of strings no matter the data type. What type of data do I need to compute specificity ? I saw something named .particles but what is that extension ? how do I get data like that from .WRL or .VTK for example.

![image](https://user-images.githubusercontent.com/87030365/216733413-e879517a-c3ac-4782-a91f-b9f1934c85e9.png)
http://sciinstitute.github.io/ShapeWorks/6.3/use-cases/stats-based/ellipsoid-pca.html

Update:
I just tried creating a ParticleSystem object with your dataset from [here](https://girder.shapeworks-cloud.org/#collection/5f6b134f2abccd68562c6a81/folder/61b2716f4824b80364e33ce9). After creating the systemParticle, I notice that D is empty but N is 10. so does it mean that it was not able to read the VTK file.
Whats the format that needs to be given to the SystemParticle ?

```
import shapeworks as spw

paths = ["/home/anh/Downloads/ellipsoid_01.vtk","/home/anh/Downloads/ellipsoid_01.vtk","/home/anh/Downloads/ellipsoid_01.vtk"]
particleSystem = spw.ParticleSystem(paths)
nCompactness = spw.ShapeEvaluation.ComputeSpecificity(particleSystem=particleSystem, nModes=1)
print("Compactness value of the 1st mode - ", nCompactness)
```
**How would I create .particles files from WRL ?**

thank you

**Comment by akenmorris** [comment]
The input path filenames to ParticleSystem should be the output `.particles` files from ShapeWorks optimization.  These are correspondence points on each shape.

Also, if you wouldn't mind, it would probably be better for general questions to use the discourse discussion group here (https://shapeworks.discourse.group/) instead of creating GitHub issues.
