### ISSUE TITLE
Documentation : How does one create a dataset from VTK or WRL file

### ISSUE THREAD

**Issue by an99990** [SCIInstitute/ShapeWorks#1996]
Hi, 
I am trying to create .particles files. What format is that file? is it x,y,z? I found this [page](http://sciinstitute.github.io/ShapeWorks/latest/dev/datasets.html) that explains how to  create Dataset but thers no details on how you format that XML  or if theres an API that could ease the conversion.
![image](https://user-images.githubusercontent.com/87030365/216743546-4a66f290-a3d7-4bbd-805d-1d66b26fd297.png)

I tried exporting a .particles from a VTK file, but the output file is empty ... I downloaded from the latest release

How are the xml and the .particles files related ?

Thank you

**Comment by akenmorris** [comment]
Particles files are just ASCII files of `x y z`, however it's not intended that user create them directly.  They are the output of the ShapeWorks optimization.

For first time use. I would recommend using the ShapeWorks Studio GUI application.  Simple import the mesh files, run the `groom` operation with default parameters, then run the `optimize` operation with default parameters.  This will generate the `.particles` files and also allow you do visualize resulting statistics about the model in the `analyze` tab.  See documentation here:

http://sciinstitute.github.io/ShapeWorks/latest/index.html
