### ISSUE TITLE
hip_multiple_domain correspondence poor

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#2039]
The hip multiple domain use case shows very poor correspondence:

https://user-images.githubusercontent.com/1693349/230526326-bffe0576-d297-467d-b2bb-cb287de03fc9.mp4

This is also seen on the documentation page:

http://sciinstitute.github.io/ShapeWorks/6.4/use-cases/mesh-based/hip.html

https://sci.utah.edu/~shapeworks/doc-resources/gifs/hip_global.gif

I think there may be something wrong with the alignment.  Using the resulting project, if I go back to grooming in Studio and use either 'center' or ICP and reuse the same optimization parameters, the result better.

**Comment by iyerkrithika21** [comment]
I tried centering, and relative pose variations are lost. 
The missed correspondence is seen in the global alignment option, but the model looks fine for modes w.r.t domain 1 and 2. 
We could discuss this use case in our dev meeting.

**Comment by akenmorris** [comment]
Running the python script on Linux, all combinations of alignment reference and Multi-level PCA show very poor correspondence for me.

https://user-images.githubusercontent.com/1693349/230780948-62045170-47a1-4a5f-aca1-8d95ebcaea3d.mp4

@iyerkrithika21 , you get different results?

**Comment by akenmorris** [comment]
Using "center" alignment in Studio, leaving all other options as is:


https://user-images.githubusercontent.com/1693349/230783121-8708f7c5-dbfd-4388-bd46-0865d4342ebc.mp4

Can you describe more about the relative pose being lost?

**Comment by akenmorris** [comment]
Resolved.
