### ISSUE TITLE
tinyxml2 external library should be used

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#206]
cmake_superbuild can import it
usage updates are straightforward

**Comment by sheryjoe** [comment]
@cchriste still relevant?

**Comment by cchriste** [comment]
It looks like we're still using tinyxml from our local ExternalLibs directory.

**Comment by akenmorris** [comment]
Not using any kind of cmake_superbuild right now.  XML usage is being universally deprecated.  Closing this issue.
