### ISSUE TITLE
update Eigen3, using cmake to import

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#208]
also be sure to go back on use of the itkeigen/* includes due to their possible customization for use with ITK by renaming the includes <itkeigen/$NAME.h> to <Eigen3/$NAME> (I think)

**Comment by sheryjoe** [comment]
@cchriste still relevant?

**Comment by cchriste** [comment]
This may still be relevant. We should probably use just eigen rather than itkeigen. 

Here is one issue in the code: `TEST(ImageTests, resampleTest5)` in ImageTests.cpp does not compile on linux due to itkeigen template conflict. This issue noted with test, which is (still) commented out.

**Comment by cchriste** [comment]
This may be resolved by #1071
@medakk

**Comment by medakk** [comment]
Yes! Once I get that to build on all platforms
