### ISSUE TITLE
Femur Image Quality

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#2084]
I noticed the femur images on the portal are about half the size memory-wise of the originals.
Here is the original m03 image:
![image](https://github.com/SCIInstitute/ShapeWorks/assets/54382613/6488a696-30ca-4e76-9c62-44776ff946ad)
And here is the one from the portal:
![image](https://github.com/SCIInstitute/ShapeWorks/assets/54382613/392ce388-15e5-4b7e-bbfe-23f0572bfbb6)

I'm not sure if this is a compression issue or what, but it could impact the accuracy of the DeepSSM use case. 
I've put the original images here: /home/sci/jadie/Public/femur_images/

**Comment by zahidemon** [comment]
@jadie1, I have re-uploaded the DeepSSM tiny test use case to the new data portal. Can you please check the image quality of the downloaded images now?

**Comment by jadie1** [comment]
@zahidemon These look correct now! Closing the issue

**Comment by akenmorris** [comment]
@zahidemon , @jadie1, sorry I didn't reply sooner.

I resized/resampled the DeepSSM tiny test femur images to be 100 times smaller (<1mb per images vs 100mb per image)to save both time, bandwidth and disk space for PR unit testing.  We are extremely limited on disk space on the Github Runners and are having to cut corners in many places.  The data download for DeepSSM tiny test is now 617MB with the full size images.  It was <10mb previously.

The purpose of the automated unit test is really only to confirm that the code runs, e.g. no syntax errors, api call errors, etc.  We cannot really check the accuracy of the execution.

The full DeepSSM use case should be the full size images.  If that was in error, then yes, we must fix it, however the tiny test really needs to be kept small.

**Comment by jadie1** [comment]
@akenmorris I apologize when I first made the issue I thought it was a problem with the full use case. Later I realized it was only the tiny test. It makes sense to use smaller images for the tiny test

**Comment by zahidemon** [comment]
@akenmorris I have re-uploaded the reduced size images and tested the use case. It's working as expected.

I don't think we need separate paths for regular and tiny test dataset downloads. It's already handled inside the use case.
