### ISSUE TITLE
cannot import name 'ModelField' from 'pydantic.fields'

### ISSUE THREAD

**Issue by oliverzzm** [SCIInstitute/ShapeWorks#2104]
Desktopinfo:
<img width="784" alt="image" src="https://github.com/SCIInstitute/ShapeWorks/assets/30902598/163fe206-e027-436e-8b30-f50a6a71d9ac">

Steps to reproduce:

1. install wsl
2. In wsl, source installshapeworks.h
3. run python script Run_usecase.py
4. Import Error with the following error snapshot
<img width="988" alt="image" src="https://github.com/SCIInstitute/ShapeWorks/assets/30902598/8170d755-0ae1-4471-9f12-9f92d1b5e12c">

**Comment by oliverzzm** [comment]
There is no "ModelField" in the fields.py. I tried replacing with "FieldInfo" in the  swcc\models\api_mode.py file, but another error occured:
<img width="1113" alt="image" src="https://github.com/SCIInstitute/ShapeWorks/assets/30902598/2dbb0739-28cf-45ba-a179-f4f5b85855d9">

**Comment by akenmorris** [comment]
It seems we have an unspecified python package version.

Try the following:

```
conda activate shapeworks
pip install typing_extensions==4.5.0
pip install pydantic==1.10.7
```

**Comment by oliverzzm** [comment]
It worked! Thank you!
