### ISSUE TITLE
Qualitative and Quantitative Assesment for Particle Coverage in Analysis

### ISSUE THREAD

**Issue by nawazishkhan1-nk** [SCIInstitute/ShapeWorks#2140]
### Feature Summary

This feature will allow us to visualize the coverage area (defined geodesically) for each particle on the mean shape. The coverage area will be color coded by particle color, with the color gradient defined by the statistics (mean and std. dev of that particular coverage area across the population). This can also serve as a good measure to assess the sampling accuracy.

**Comment by akenmorris** [comment]
@nawazishkhan1-nk , can you describe more what you mean about the color gradient being defined by the statistics?  Gradient from what to what?

**Comment by akenmorris** [comment]
Merged in #2145
