### ISSUE TITLE
Image to image registration function parameter fix

### ISSUE THREAD

**Issue by zahidemon** [SCIInstitute/ShapeWorks#2151]
The `transform_type` parameter in this [function](https://github.com/SCIInstitute/ShapeWorks/blob/master/Python/DeepSSMUtilsPackage/DeepSSMUtils/__init__.py#L53)  should not be preset. It should be passed from the previous function.

**Comment by akenmorris** [comment]
Is this what you mean?

https://github.com/SCIInstitute/ShapeWorks/pull/2153

**Comment by akenmorris** [comment]
Resolved
