### ISSUE TITLE
ApplyRigid3DTransformationToImage is not reading the given transformation matrix file

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#217]
ApplyRigid3DTransformationToImage is reading a file called "transformationMatrix" rather than the given filename in the transformationMatrix variable.

https://github.com/SCIInstitute/ShapeWorks/blob/3a2ee71fe939aaa8cd1009936d940cda65fd484e/Prep/Source/Alignment/ICPRigid3DImageRegistration/source/ApplyRigid3DTransformationToImage.cxx#L188

**Comment by AtefehKashani** [comment]
As we agreed, instead of changing this command line, i have changes the transformation matrix which is reported by ICPRigid3DAlignments to omit the heading information of the transformation matrix and just write the matrix elements. I have tested this.

**Comment by AtefehKashani** [comment]
The ifstram input format is fixed.
