### ISSUE TITLE
Principal Geodesic Analysis

### ISSUE THREAD

**Issue by ajensen1234** [SCIInstitute/ShapeWorks#2174]
From "Principal Geodesic Analysis for the Study of Nonlinear Statistics of Shape
P. Thomas Fletcher, Conglin Lu, Stephen M. Pizer, and Sarang Joshi"

I saw that Dr. Fletcher had made his way to Uath in the SCI institute for a bit. I was wondering if his work on Lie Group statistics/PGA ever made it into ShapeWorks? The papers were a bit older, but they seemed to represent an alternative method to standard SSMs.

**Comment by akenmorris** [comment]
No, ShapeWorks does not have this type of analysis yet.
