### ISSUE TITLE
ShapeWorks Studio Hangs/Crashed on Azure Windows VM

### ISSUE THREAD

**Issue by ajensen1234** [SCIInstitute/ShapeWorks#2195]
Hi! I've been trying to get ShapeWorks studio to work in a windows VM on Azure and it hangs in two places:

- "Start New Project"- this just gives a blank screen and nothing happens
- "Load Existing Project" - This yields a log error (attached is the full log file) - "ShapeWorksStudio: ShapeWorksStudio.exe - Fatal Application Exit", "Unhandled Exception - 
[studio-2024-01-30_09_23_37.txt](https://github.com/SCIInstitute/ShapeWorks/files/14099604/studio-2024-01-30_09_23_37.txt)

Here are the specs of the VM:
Operating system - Windows
Image publisher - MicrosoftWindowsDesktop
Image offer - Windows-10
Image plan - win10-22h2-pro-g2
VM generation - V2
VM architecture - x64
Size - Standard NV4as v4
vCPUs - 4
RAM - 14 GiB

**Comment by akenmorris** [comment]
I haven't had luck running Studio in a VM due to the OpenGL requirements coming from VTK.  It may be possible with some VM software that can pass through to a host OpenGL driver, but it certainly doesn't work in VirtualBox that I've tried.  You can see the crash in your log is at:

```
[2024-01-30 09:23:46.337] [error] 00007FF611CF53DA (ShapeWorksStudio): (filename not available): vtkOpenGLBufferObject::UploadInternal
```
