### ISSUE TITLE
Importing Landmarks to ShapeWorks Studio

### ISSUE THREAD

**Issue by amygutierrez** [SCIInstitute/ShapeWorks#2207]
Is there a way to import landmarks instead of manually placing landmarks?
I am using ShapeWorks Studio and importing my data and also manually applying landmarks. Is there a way to possibly import landmark points?

If there is a way to import landmarks, what format is accepted (JSON file, etc.)? 
![MicrosoftTeams-image](https://github.com/SCIInstitute/ShapeWorks/assets/58920810/ddae9113-f20b-4a47-8644-47d968ee8daf)

**Comment by amygutierrez** [comment]
So I can just import a particle file in ASCII format? Where do I import these this landmark particle file when using ShapeWorks Studio?

**Comment by akenmorris** [comment]
So it doesn't have a direct import functionality.  You can supply the files by adding them to the xlsx spreadsheet or json file:


<img width="342" alt="image" src="https://github.com/SCIInstitute/ShapeWorks/assets/1693349/0046d930-8d45-4568-89da-5b0956adf764">

You can double check the structure by creating a few manual landmarks and saving the project.  It will create the landmarks files and you can replace them.

**Comment by amygutierrez** [comment]
Thank you for your response! 
So once I create the spreadsheet with the Name, Notes, Shape_1, and Landmarks_file_1 columns, where do I then import/apply that spreadsheet to?

**Comment by akenmorris** [comment]
ShapeWorksStudio will open the spreadsheet file directly, as a project.
