### ISSUE TITLE
Exporting CSV Component Scores have no labels

### ISSUE THREAD

**Issue by amygutierrez** [SCIInstitute/ShapeWorks#2208]
When I export PCA component scores or other CSV files, I notice that there is no column with a label that corresponds to the images I import. For example, if my images have these names, I notice that the PCA components export does not have those names. 
Is there a way I can export PCA components with the image names?
Here is an xample:

Names of imported nifti images:
![image](https://github.com/SCIInstitute/ShapeWorks/assets/58920810/33a55d27-eef1-4fb1-9a0e-a06293a90ccd)

PCA Component Scores:
![image](https://github.com/SCIInstitute/ShapeWorks/assets/58920810/95fbad9b-77a4-46ff-9135-128589bb9e7a)

**Comment by akenmorris** [comment]
Yes, we need to improve this.  For now, they are in the same order as the project spreadsheet if you save it as xlsx.  You should be able to merge the two.
