### ISSUE TITLE
visualizing effect of multiple modes at once

### ISSUE THREAD

**Issue by bkonkva** [SCIInstitute/ShapeWorks#2214]
I'm in the analyze widget and under the PCA tab of the ShapeWorks app. I'm able to adjust the deviation away from the mean and see the impact on shape, but only one mode at a time. Is there a way to do this for multiple modes? For example, setting the std dev to -2 for mode 1, +1 for mode 2, etc and visualize the cumulative effect?

**Comment by akenmorris** [comment]
Unfortunately not.  It would not be all that hard to combine modes, but our challenge in implementing this is in how to provide an intuitive user interface.

The best way to do this now is to export the eigenvectors and values and perform the combinations and output a new particle file and having the MeshWarper (available in Python and CLI) create a mesh.
