### ISSUE TITLE
Evalation metrics for scalars and shape+scalar

### ISSUE THREAD

**Issue by nawazishkhan1-nk** [SCIInstitute/ShapeWorks#2218]
### Feature Summary
- Add a feature to visualize reconstruction errors on the feature scalar value computed between the feature predicted from the shape model and the original feature value. This would allow users to assess the impact of using "features" during optimization and tune the feature weight accordingly.
- Similarly, add quantitative evaluation metrics (compactness, generalization, specificity) on the feature space and shape + feature space.

**Comment by akenmorris** [comment]
@jadie1 , Please add python implementation.  Thanks!

**Comment by jadie1** [comment]
Here is the equation for chamfer distance between two point clouds S1 and S2: 
![image](https://github.com/SCIInstitute/ShapeWorks/assets/54382613/b55e28ef-c856-466e-99bf-4171e1bb6e4e)
It is the L2 distance between each point and its nearest neighbor in the other point cloud, so the main functionality you need nearest neighbors. 
I've been using this PyTorch implementation: https://pytorch3d.readthedocs.io/en/latest/modules/loss.html
There are some other repos that implement the functionality in C++ and adapt it for pytorch, for example: https://github.com/otaheri/chamfer_distance
