### ISSUE TITLE
return error code when a command fails

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#223]
This is an issue that many Shapeworks executables have. When the operation the executable performs fails for any reason, it should return a failure code (any non-zero value). 

This can (and should) be similarly added to python functions, and furthermore the scripts that execute these commands should test that a command is successful before continuing execution (so part of this issue is to modify the testEllipsoids.py example to test for a successful execution).

The first assignee to this issue should add a comment that creates a repeatable (and simple) reproduction of the current state (the example in our meeting was that one command fails, but the failure is ignored by the script and the next command is executed, so a simple example of this is what we need to start with). (Thanks, Atefeh!)

**Comment by AtefehKashani** [comment]
For example, in reconstruction.cpp when the input files don't have the same origin or dimension it just prints out:
""
terminate called after throwing an instance of 'std::exception'
 what():  std::exception
""
and you can see that there is no error message and the next command executes. 
Recently, I found another problem that one of the optimization parameters was missed and it kept running without creating any particle and error message. I had to read the ShapeWorksRunApp.txx to find out what is the problem. 
I will post if any other cases happen.

**Comment by cchriste** [comment]
To some extend this issues has been addressed since we can now catch exceptions and use `subprocess.check_call` instead of `os.system`. It's unwise to be using `shell=True` but the commands themselves need to be transformed into arrays in order to make that change.

**Comment by AtefehKashani** [comment]
I have removed "use_xyz" parameter for multiscale and test the optimization. With this change nothing is generated as initial particles, therefore nothing is optimized, but it keeps running for other levels.
This parameter is boolean and has to be set for using normals.

**Comment by cchriste** [comment]
Atefeh and I tested this and the script terminates with an error if the user breaks (ctrl-c) or one of the commands returns non-zero exit status. Closing issue.
