### ISSUE TITLE
add time profiling to unit tests

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#225]
...and larger tests such as the test ellipsoids case (which is why Riddhish is the current assignee).

**Comment by cchriste** [comment]
Praful has some recommendations for this.

**Comment by cchriste** [comment]
In `ShapeworksUtils` there is a new timing function, it's been used for a few tests. I'm adding @archanasri since she know how it works and whether or not there are tests for the timer itself (my fault if there aren't). @archanasri can you please create an example of using this for a semi-lengthy test, say one of the optimize tests? Thanks!

I think it would also be useful to have timing for all of the use cases. It could be added to RunUseCase, and the Python bindings for the timing code have already been added.

**Comment by akenmorris** [comment]
We have timing information, but we cannot make a pass/fail determination based on it from the GitHub action runners.  We have no control over the hardware/virtual cpus of these runners.  They can change any day without our knowledge.
