### ISSUE TITLE
Studio Bug: notes column overwritten on saving the project

### ISSUE THREAD

**Issue by nawazishkhan1-nk** [SCIInstitute/ShapeWorks#2251]
### Bug Summary

The contents of the 'notes' column is overwritten by the contents of the 'excluded' column upon saving the project. 

Before Saving Project:
<img width="118" alt="Screenshot 2024-05-13 at 3 16 35 PM" src="https://github.com/SCIInstitute/ShapeWorks/assets/84894476/51dc9f14-54a7-4b9b-bca7-87b69f1b4a86">

After Saving Project:
<img width="125" alt="Screenshot 2024-05-13 at 3 16 44 PM" src="https://github.com/SCIInstitute/ShapeWorks/assets/84894476/467a3604-2e03-43f6-a44c-6a07eefbe1a7">

**Comment by akenmorris** [comment]
Good catch!
