### ISSUE TITLE
Datasets unreachable

### ISSUE THREAD

**Issue by pimatysiak** [SCIInstitute/ShapeWorks#2267]
Hello!

Have you noticed on your end that the datasets needed to run the use cases (at this address https://girder.shapeworks-cloud.org/#collections) have recently stopped responding?

It could just be a temporary DNS shutdown but I would like to make sure if it's an issue on my end or not.

Thank you.

**Comment by akenmorris** [comment]
Thanks for pointing this out.  This should be fixed now.  Please re-open if it's not working for you now.
