### ISSUE TITLE
Incomplete dataset?

### ISSUE THREAD

**Issue by pimatysiak** [SCIInstitute/ShapeWorks#2269]
Hello,

I was trying to run the deep_ssm script on the "hip" dataset that is provided in the use-case-data-v3 collection, and it seems that all of the hip related constraints are empty files (https://girder.shapeworks-cloud.org/#collection/623788ae4824b80364e34621/folder/6389e2a64824b80364e364fe) which only show "null".

I don't think that was intended, because it makes running the script on hip data pretty much impossible as it is. Could you please advise on a workaround to this? Maybe I'm not using the dataset correctly..

Thank you

**Comment by akenmorris** [comment]
The datasets at https://girder.shapeworks-cloud.org/#collections have been restored.

A couple of things to note:

1) The hip dataset has constraints only for the femur (a plane cutting the femur at a uniform location across femurs).  The pelvises don't have constraints.

2) DeepSSM currently only supports a single anatomy at a time.  You can create a pelvis model or a hip model, but not a joint model as the hip dataset contains.

**Comment by pimatysiak** [comment]
Thank you Alan, and also for the additional information.

I had originally thought that constraints were a necessary thing to run a model but after some time playing with ShapeWorks I've got a better understanding of it.
