### ISSUE TITLE
Multiple bodies on a STL issue

### ISSUE THREAD

**Issue by MLopezPon** [SCIInstitute/ShapeWorks#2271]
Good morning,

I have an issue on the model when i have multiple bodies in imported meshes.
I try to see the position of vertebras between 2 segments for exemple and i have the 2 main problems bellow:
1) the groom function (even with centered activated)  does not allow a good centering of samples
![image](https://github.com/SCIInstitute/ShapeWorks/assets/171816567/5b319958-a92b-4991-b8e2-9a3d1d76ecef)

2) during optimization: the particules does not spread from body 1 to body 2.
![image](https://github.com/SCIInstitute/ShapeWorks/assets/171816567/74b6f772-dd84-4d63-9321-761c43f749fd)

Is there a special optmization process for multiple body analysis or is this not supported?

Thanks for the help

**Comment by akenmorris** [comment]
For multiple objects, we suggest the "multiple domain" approach as outlined here:

http://sciinstitute.github.io/ShapeWorks/latest/studio/multiple-domains.html

If you want to use them as a single anatomy, then they must be connected in order for particles to spread between the two.

I am not sure what the alignment problem is, that should work either way.  Does the problem persist with just a few samples, if so, can you share them with us?

**Comment by zestyzy** [comment]
excuse me. how can i download the aligned meshes as '.vtk' files?

**Comment by akenmorris** [comment]
At the present time, you would need to apply the transforms outside of Studio.

ShapeWorks doesn’t modify the position of the meshes for a couple of reasons:

    This allows both the original and groomed shapes to be in the original coordinate space

    This minimizes resampling for segmentations

    Allows for multiple alignments when using multiple anatomies (e.g. local alignment per domain and global alignment, combined)

In the Studio GUI and in the optimization, we instead pass the transform and the original data. The viewer applies the transform only as part of a view/camera transform. The optimization uses the initial transform and may add additional transforms with procrustes.

To apply the alignment transform you can use the ShapeWorks Python API (Mesh.applyTransform)

**Comment by MLopezPon** [comment]
Thanks for the answer. The  "multiple domain" approach solved the issue for the particles.
