### ISSUE TITLE
"overlinking" causing unnecessary deps that are impossible in some cases

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#229]
Too many libraries are being passed to target_link_libraries for most of our executables, resulting in packaging that tries to access unnecessary libs such as Qt for a command line app.

Instead of using (e.g.,) ${VTK_LIBRARIES} we need to specific the specific libraries need for a link. As an experiment I manually modified a couple and things that wouldn't run out of build (because of missing Qt RPATH, itself another issue) now work fine.

**Comment by cchriste** [comment]
Still an issue:
```
ShapeWorks/build_xcode$ otool -L ./bin/Debug/ReflectMesh
./bin/Debug/ReflectMesh:
	@rpath/libvtkDomainsChemistryOpenGL2-8.2.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libvtkFiltersFlowPaths-8.2.1.dylib (compatibility version 1.0.0, current version 1.0.0)
...
	@rpath/libvtkCommonSystem-8.2.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.13.0, current version 5.13.0)
	@rpath/QtGui.framework/Versions/5/QtGui (compatibility version 5.13.0, current version 5.13.0)
	@rpath/QtCore.framework/Versions/5/QtCore (compatibility version 5.13.0, current version 5.13.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
```

**Comment by akenmorris** [comment]
Moving to a single executable, this won't really be an issue, right?  That executable will have to be linked to every library we use.

I'm just curious though, what problem does this cause exactly?  Besides being unnecessary.

**Comment by cchriste** [comment]
One problem was the issue I described yesterday about not being able to run any executable on OSX without manually approving every single shared library with which it linked.

Another issue is that an executable created in a build with the Qt GUI enabled requires the Qt libraries to run. This means our future cloud installations will either require different builds or be bloated by needing to heft around huge libraries for no reason.

**Comment by cchriste** [comment]
Since the deployments are now working, if/when optimization is needed we can revisit this issue.
