### ISSUE TITLE
Java interface Notes and plans

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/ShapeWorks#2291]
Some notes from my investigation of interfaces with Java.  

Most of the Java apps of interest (ImageJ, Matlab, etc.) have python libraries to use, and we can build off of those to make a tutorial or simple interface.  These seem to build on Jython
 - [ImageJ](https://imagej.net/scripting/jython/) python2 support only
 - [PyimageJ](https://pypi.org/project/pyimagej/ )Python wrapper for ImageJ2, a higher dem version of ImageJ.  It also supports ImageJ through legacy bridge.  Fiji is also built on ImageJ2, so should be also possible.  There is a [repo of tutorials](
 - [Matlab engine for Python](https://www.mathworks.com/help/matlab/matlab-engine-for-python.html).  Requires Matlab installation and license.  Matlab also has [a C++ Interface for data and the engine](https://www.mathworks.com/help/matlab/calling-matlab-engine-from-cpp-programs.html?s_tid=CRUX_lftnav)

[Jython](https://www.jython.org) could be used to make a Java app, but it looks like there is no automated way to do this.  
 
To build a Java library that calls c++, the [Java Native Interface (JNI)](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/jniTOC.html) or [Java Native Access(JNA) ](https://github.com/java-native-access/jna), a simpler version of JNI.   [Swig](https://www.swig.org/tutorial.html) may be an option to automate JNI implementations.

**Comment by akenmorris** [comment]
Done
