### ISSUE TITLE
required RPATHS aren't being added automatically

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#230]
Executables in the build directory should just run after they are compiled without any need to set LD_LIBRARY_PATH. This is almost working except some executables seem to arbitrarily depend on Qt. 

${VTK_LIBRARIES} is problematic because of #229, and also because if it's built with Qt, then this list includes libs that themselves require Qt, but cmake isn't recognizing these paths and therefore the required RPATHS aren't being added. 

Cmake's default behavior is to add the paths of all the libs being linked to the executable's set of RPATHs, so there may be some other things we need to explicitly tell it for the VTK-with-Qt libs. Maybe when the VTK library is found it provides a variable that can be used.

**Comment by cchriste** [comment]
Note that this is all a `make install` issue, and the `build_fixes` branch has disabled make install for shapeworks (since it takes a long time and most of the results do not run because of this issue).

**Comment by cchriste** [comment]
Still an issue. After a fresh install, rpath does not point to a relative directory. Here is the error on OSX:
```
ShapeWorks/build_xcode/install$ ./bin/shapeworks
dyld: Library not loaded: @rpath/libITKLabelMap-5.0.1.dylib
  Referenced from: /Users/cam/code/ShapeWorks/ShapeWorks/build_xcode/install/./bin/shapeworks
  Reason: image not found
Abort trap: 6
```

**Comment by cchriste** [comment]
I think this is fixed. @akenmorris, will you please confirm?

**Comment by akenmorris** [comment]
I'm not aware of any current problem like this.
