### ISSUE TITLE
create wrapper for python tests

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#236]
ellipsoidMain and LAMain both use a try/catch block to catch any errors from subprocess.call_check. This try/catch block can be a wrapper for a call to any of these tests of which more are in the pipeline.

1) Create a RunTest.py with the try/catch block.
2) Wrap contents of the various tests into their own functions.
3) Call those functions from RunTest by making them parameters: `python RunTest.py <testname>`

The RunTest will also include bin paths, etc. This will make tests reliable and enable us to have lots of them without reinventing the try/catch, etc for each one.

**Comment by cchriste** [comment]
Note: the subprocess.check_call should not be run with `shell=True`, so at some point these scripts can be modified to be like:
```                    execCommand = "ResampleVolumesToBeIsotropic --inFilename " + inname + " --outFilename " + outname + " --isoSpacing " + str(
                        isoSpacing) + " --isCenterImageOn 1 --isBinaryImage 1"
                    subprocess.check_call(execCommand, shell=True)
```
                   ...should be
```
                    execCommand = ["ResampleVolumesToBeIsotropic", "--inFilename", inname, "--outFilename", outname, "--isoSpacing", str(isoSpacing), "--isCenterImageOn", 1, "--isBinaryImage", 1]
                    subprocess.check_call(execCommand)
```

**Comment by cchriste** [comment]
Here's an example of the wrapper (just the stuff at the beginning/end of the current scripts:
```
import runla
try:

    run_my_thing()

    print("\nShapeworks Pipeline Complete!")


except KeyboardInterrupt:
    print("KeyboardInterrupt exception caught")
    sys.exit(1)
except subprocess.CalledProcessError as e:
    print("general exception caught: "+e.returncode+", "+e.output)
    sys.exit(1)
```

**Comment by AtefehKashani** [comment]
I have addressed these issues and push to the UseCae_LA branch. These are tested for both use cases.

**Comment by cchriste** [comment]
Hi all, I just assigned a few of us to this task since it came up in our meeting and on Slack. Thanks for partially addressing things, Atefeh!  (I just noticed the update on this issue, but I had already noticed in the code itself :).

**Comment by cchriste** [comment]
Is this done?

**Comment by jadie1** [comment]
I think so!

**Comment by cchriste** [comment]
✅
