### ISSUE TITLE
Cmake have weird behavior under debian 8, and ShapeWorksView2 segfaults when fixed.

### ISSUE THREAD

**Issue by P-EB** [SCIInstitute/shapeworks#25]
Hey,

Me, again.

I tried to install shapeworks on my Debian laptop.

When running cmake, I get this

-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found DCMTK: /usr/include/dcmtk/config  
-- The imported target "vtkParseJava" references the file
   "/usr/bin/vtkParseJava-6.2"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkWrapJava" references the file
   "/usr/bin/vtkWrapJava-6.2"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkRenderingQtJava" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingQtJava.so"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
  but not all the files it references.

-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found suitable version "4.8.7", minimum required is "4.7.4") 
-- *\* QT_QMAKE_EXECUTABLE: /usr/bin/qmake-qt4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/becue/git/ibbm/shapeworks/build

I don't know why cmake tries to refer to nonexisting files but anyway, when I try to compile, I get this.

make[2]: **\* No rule to make target '/usr/lib/libjsoncpp.so', needed by 'bin/ShapeWorksView2'. Arrêt.

I have a libjsoncpp.so file in /usr/lib/x86_64-linux-gnu/libjsoncpp.so , when I fix the makefile, it compiles, but ShapeWorksView2 segfaults on startup.

How can I compile with debug options all this stuff so that I can fill a better bug report?

**Comment by brigb123** [comment]
Do you have VTK 6 source built with the java/python/qt packages all enabled? you need to select the proper VTK build directories in the shapeworks CMAKE configure for these to all link up properly.
