### ISSUE TITLE
Add ability to record videos from Studio

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#253]
Feature request from Amy Lenz

**Comment by akenmorris** [comment]
You must have misheard.  There is no video recording capability in View2.

**Comment by sheryjoe** [comment]
- PCA modes
- Group difference

**Comment by akenmorris** [comment]
Lets discuss this at the next dev meeting.  My personal feeling is that it's much easier to use an external tool such as Quicktime or Windows screen recorder (I'm sure there's linux options too) and that it's a considerable amount of effort to bring in an encoder library (ffmpeg), code up export of frames and construction of videos.  It's doable, but it's a lot of code to write and support and the time spent on it will take away from doing things that can only be done in ShapeWorks.

**Comment by akenmorris** [comment]
There is an argument to be made for screenshots for publication because for a screenshot, we could have the ability to render a higher than screen resolution image (e.g. 4000x4000, 8000x8000) using an offscreen VTK renderer.

**Comment by sheryjoe** [comment]
> it's a considerable amount of effort to bring in an encoder library (ffmpeg), code up export of frames and construction of videos.

Do we have to do this from scratch? Paraview exports videos through VTK. So there might be a shortcut for us to have this "usability" feature without spending too much time that is better spent on shapeworks-specific functional/usability features.

**Comment by sheryjoe** [comment]
Closing this for now and moving it to a backlog milestone just in case it is needed to be revisited. -- It might be useful to check out how Paraview records videos, add animations, and capture snapshots.
