### ISSUE TITLE
ParticleSystem optimizers - investigate differences with legacy code

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#258]
@akenmorris please add more details pertaining to our latest dev discussion.

**Comment by akenmorris** [comment]
Using the classic torus example with these base parameters:

<number_of_particles> 256 </number_of_particles>
<iterations_per_split> 200 </iterations_per_split>
<starting_regularization> 10.0 </starting_regularization>
<ending_regularization> 0.1 </ending_regularization>
<optimization_iterations> 200 </optimization_iterations>

Shapeworks from 4-5 years ago gives:

<img width="426" alt="torus_old" src="https://user-images.githubusercontent.com/1693349/68490731-c700d000-0206-11ea-9e9b-a2956db6ab42.png">

The current Shapeworks gives:

<img width="443" alt="torus_new" src="https://user-images.githubusercontent.com/1693349/68490760-d3852880-0206-11ea-8fd0-aee5c761df19.png">

I am not sure what changed or how the parameters need to be changed to generate a good correspondence.  Adding iterations makes it much better of course, but this is not a satisfactory answer.

**Comment by prafulag** [comment]
I believe the biggest difference between your version and current version of shapeworks may be the adaptive timestep. Further, the update vectors are now ensured to stay in the tangent space at the starting point, which may lower the update magnitude at every iteration.

Also, check the relative weighting parameters in both versions, I don’t see a value in your xml print, so it may be using a default value, which could be different in two versions.

Praful

**Comment by akenmorris** [comment]
this->m_relative_weighting = 1.0;
    this->m_initial_relative_weighting = 0.05;

Defaults are the same nn both versions.

I don't mind that things have changed, I just need to know how to adjust the parameters for a good correspondence.  Do we just need 10x iterations?

**Comment by prafulag** [comment]
Changing initial and final regularization may also impact the number of iterations. Use higher initial regularization.

Praful

**Comment by sheryjoe** [comment]
@akenmorris I thought we have resolved this?

**Comment by akenmorris** [comment]
Yes, it's more or less the update vector magnitudes.
