### ISSUE TITLE
Surface reconstruction of sphere data in studio fails

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#265]
Old reconstruction:

<img width="429" alt="Screen Shot 2019-11-21 at 1 57 47 PM" src="https://user-images.githubusercontent.com/1693349/69376091-eb2cca00-0c66-11ea-814b-3d79b13c051a.png">

New:

<img width="451" alt="Screen Shot 2019-11-21 at 1 56 57 PM" src="https://user-images.githubusercontent.com/1693349/69376040-d18b8280-0c66-11ea-9755-5b4cba82444a.png">

On the console, I see:

Isosurface: /tmp/_dense-noQC.vtk
MeshQC failed ... VTK decimation is used instead ...
Decimated mesh: /tmp/_dense-QC.vtk

I don't know yet whether this is a Studio problem or if happens with the command line surface reconstruction as well.

**Comment by sheryjoe** [comment]
@akenmorris still an issue?

**Comment by akenmorris** [comment]
Seems like it's fixed:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/1693349/108316459-2c699d80-717a-11eb-8ca0-3dcc5cebf084.png">

We don't write out these files any more, and haven't for a long time.  I believe this may have been due to the different centering issues with the reconstructor which were fixed some time ago.
