### ISSUE TITLE
Studio does not support multiple domains

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#266]
View 2 is able to visualize them:

<img width="1053" alt="Screen Shot 2019-11-22 at 12 00 05 AM" src="https://user-images.githubusercontent.com/1693349/69404712-2822ac00-0cbb-11ea-94ad-a61c24ba36b8.png">

**Comment by akenmorris** [comment]
Also, neither handles the case of domains with differing numbers of particles.

**Comment by sheryjoe** [comment]
Is there specific xml tag for view2 that would make it handle multiple domains?

**Comment by akenmorris** [comment]
<number_of_domains>

**Comment by prafulag** [comment]
Is this old view2 with just a <number_of_domains> tag ?

**Comment by akenmorris** [comment]
I'm sorry, it's <domains_per_shape>

Yes, View2 has had it for many years.  But the number of particles must be the same.

**Comment by prafulag** [comment]
Great! I was not aware of that. 
Are the domains provided in following manner? :

Shape1_domain1
Shape1_domain2
Shape2_domain1
Shape2_domain2
.
.
.
.
.
ShapeN_domain1
ShapeN_domain2

**Comment by akenmorris** [comment]
Yes.

One caveat is that the domains typically overlap, so I generally translate one of them to the side in order to view them at the same time.

**Comment by prafulag** [comment]
Okay, thanks!

One more question, when we visualize the PCA modes of variation, is it coming out of the joint shape matrix or independent PCA spaces are constructed ?

Praful

**Comment by akenmorris** [comment]
Joint.

**Comment by prafulag** [comment]
Thanks!

**Comment by sheryjoe** [comment]
Closing this and opening a new one to revisit it in the context of the sheet project file.
