### ISSUE TITLE
DatasetUtils (GirderConnector) should stream data to disk

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#278]
Currently, GirderConnector downloads files entirely in memory before writing them to disk.  This is fine for small files, but I ran into memory thrashing on a memory-taxed machine when downloading the ~4gb femur dataset.

Here is an example of streaming to disk using 'requests':

http://masnun.com/2016/09/18/python-using-the-requests-module-to-download-large-files-efficiently.html

**Comment by strikerz76** [comment]
Good catch, I'll get on this as soon as I get back

**Comment by akenmorris** [comment]
Done.
