### ISSUE TITLE
Image::resample may have an issue with input image size vs output from filter

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#299]
I don't really understand, but I'm creating this issue and assigning those who might be able to explain the output. One thing is that the output image in some cases is smaller than the input image, and the original function seems to have been somewhat aware of this since it explicitly changes the output image size to be one smaller in 'z'. 

I created some sample input images and some of them were a pixel smaller in all the axes, sometimes at both ends, so I just don't understand what's going on. I was also informed the use of the bspline filter for resampling binary images produced better results. I'd suggest documenting these things with the detailed description of the function.

**Comment by cchriste** [comment]
Note that the current function behaves identically to the original ResampleVolumesToBeIsotropic executable _except_ that it doesn't recenter or binarize the output because it was requested to break the resample function into its separate operations.

**Comment by cchriste** [comment]
A good method you can experiment with is the function in Testing/ImageTests/ImageTests.cc, or simply use the command line to test. Here's an example:
`shapeworks readimage --name <input_imagename> resample --isospacing 1.0 --isbinary true recenterimage binarize writeimage --name <output_imagename>`

**Comment by sheryjoe** [comment]
@riddhishb can you take the lead on this? - Also, I would check out the logic for handling resampling of binary images, the output should be also binary.

**Comment by cchriste** [comment]
We’ve fixed, finishes, and explained this (it just worked around another problem in the code, and there was no reason to make the output image smaller). Closing this issue now.
