### ISSUE TITLE
Build VTK with Python Support

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#300]
VTK Dependency should be build with Python Support

**Comment by akenmorris** [comment]
We are currently using VTK installed by conda for python support.  It's not too hard to build VTK with python support, but there are some issues involved in setting PYTHON_PATH and LD_LIBRARY_PATH in order to use this VTK.

**Comment by akenmorris** [comment]
See:

https://vtk.org/Wiki/VTK/Tutorials/PythonEnvironmentSetup
```

In the following instructions, I have built VTK in '/home/doriad/bin/VTK'

To run a vtk python script, simply type:

python script.py

If you receive this error:

ImportError: No module named vtk

add the following line to ~/.bashrc

export PYTHONPATH=/home/doriad/bin/VTK/lib:/home/doriad/bin/VTK/lib/site-packages:/home/doriad/bin/VTK/Wrapping/Python:$PYTHONPATH

Try to run the script again. If you get something like this:

ImportError: libvtkCommonPythonD.so.pv3.7: cannot open shared object file: No such file or directory

Add the following to ~/.bashrc

export LD_LIBRARY_PATH=/home/doriad/bin/VTK/lib:$LD_LIBRARY_PATH

```

**Comment by cchriste** [comment]
If these steps are truly necessary, this could be another argument to include the startup script described in #478..

**Comment by cchriste** [comment]
- Trying to do this on Windows (start with the most difficult problem and the rest will seem easy!). 
- cannot run python from git-bash (should we be able to?), but it works from anaconda shell
- `set PYTHONPATH=c:\Users\cam\code\swdeps\install\bin\lib\site-packages` (the others above don't exist in install, are kind of sort of there in build, but install seems to copy them all to the same place)
- ...still can't import vtk:
```python
(shapeworks) c:\Users\cam\code>python
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vtk
Traceback (most recent call last):
  File "c:\Users\cam\code\new_swdeps\install\bin\Lib\site-packages\vtkmodules\__init__.py", line 13, in <module>
    from . import vtkCommonCore
ImportError: cannot import name 'vtkCommonCore' from 'vtkmodules' (c:\Users\cam\code\new_swdeps\install\bin\Lib\site-packages\vtkmodules\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Users\cam\code\new_swdeps\install\bin\Lib\site-packages\vtk.py", line 30, in <module>
    all_m = importlib.import_module('vtkmodules.all')
  File "C:\Users\cam\anaconda3\envs\shapeworks\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\cam\code\new_swdeps\install\bin\Lib\site-packages\vtkmodules\__init__.py", line 15, in <module>
    import _vtkmodules_static
ModuleNotFoundError: No module named '_vtkmodules_static'
```
(note: the `_vtkmodules_static` error is only pertinent if vtk had been compiled statically. The `__init__.py` in vtkmodules just tries this if the original module isn't found.)
In the vtkmodules directory there is a `vtkCommonCore.cp38-win_amd64.pyd` file (and lots of others), and the reason for the error above is that when it compiles it ends up with python 3.8 instead of 3.7, even though 3.7 is what was used in the original call to cmake, while 3.8 is the system/conda default. I tried using that python and it gets to the next problem: no dll found.

**Comment by cchriste** [comment]
`set PATH=c:\\Users\you\path\to\deps\install\bin;%PATH%` worked to find missing DLL.

**Comment by cchriste** [comment]
As mentioned above, wrong Python version is used during build on Windows (just loaded ShapeWorks.sln from Explorer).

**Comment by cchriste** [comment]
For linux:

**Comment by cchriste** [comment]
> As mentioned above, wrong Python version is used during build on Windows (just loaded ShapeWorks.sln from Explorer).

OSX has the same issue, thinking Python3.8 is the current version even after configuring with cmake from the shapeworks conda environment with python 3.7.

**Comment by cchriste** [comment]
> For linux:
> 
> ```shell
> export PYTHONPATH=/scratch/cam/code/swdeps/install/lib/python3.7/site-packages/
> export LD_LIBRARY_PATH=/scratch/cam/tools/Qt5.13.1/5.13.1/gcc_64/lib:/scratch/cam/code/swdeps/install/lib
> ```
> 
> (note that Qt also needed to be in there)

OSX has the same Qt issue, but the vtk library references Qt using @rpath, set to `@loader_path/../../..`, so trickier to get LD_LIBRARY_PATH correct. There must be a better way than this anyway...

**Comment by cchriste** [comment]
OSX vtk import uses `@rpath` from vtk libraries such as `swdeps/install/lib/python3.8/site-packages/vtkmodules/vtkRenderingQt.cpython-38-darwin.so`, which is set to `@loader_path/../../../` (use `otool -l <lib>` and look for `LC_RPATH` to see this). This directory corresponds to `swdeps/install/lib/`.

Manually linking the Qt libraries that cannot be found this this path (i.e., `(base) cam@ananda:~/code/ShapeWorks/swdeps/install/lib$ ln -s /Users/cam/tools/Qt5.13.0/5.13.0/clang_64/lib/* .`) enables successful importing of vtk (🎉), but it's a crappy hack (👻).

For OSX:
```bash
export PYTHONPATH=/scratch/cam/code/swdeps/install/lib/python3.7/site-packages/
swdeps/install/lib$ ln -s /Users/cam/tools/Qt5.13.0/5.13.0/clang_64/lib/* .
```

So two problems getting the vtk Python bindings to be loadable on OSX:
1. Python 3.8 gets used even when cmake is run in an environment containing Python 3.7 (an Xcode issue?)
2. unacceptable way to get it to find the necessary Qt libraries

Note: I've tried setting LD_LIBRARY_PATH, DYLD_LIBRARY_PATH, and DYLD_FALLBACK_LIBRARY_PATH, all to no avail.

**Comment by cchriste** [comment]
This has been shown to be possible on all platforms, but at some difficult. The `upgrade_deps` branch _almost_ succeeds.

**Comment by cchriste** [comment]
This is related to #302.

**Comment by cchriste** [comment]
> This has been shown to be possible on all platforms, but at some difficult. The `upgrade_deps` branch _almost_ succeeds.
> Perhaps more importantly, the `setupenv` script mentioned in issue #478 can be split out from this branch and finished. It's useful today, but when the shapeworks python module is finished, it will be even more important (ex: consider on Linux that the user will have to set their PATH, PYTHONPATH, and LD_LIBRARY_PATH to their installation directory in order to simply run python and `import shapeworks`).

`source devenv.sh /path/to/bin`

**Comment by akenmorris** [comment]
I don't see a need to do this.  Conda/pip will install a version of VTK either way.
