### ISSUE TITLE
build ITK with python support enabled

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#302]

**Comment by sheryjoe** [comment]
@akenmorris still an issue?

**Comment by cchriste** [comment]
We've still not succeeded in doing this, and it means Weber installing two different versions if itk (python and our own build). 

Al the same concerns for vtk.

**Comment by cchriste** [comment]
I think we should give this another try since the pyvista/vtk rendering system has become atrociously slow, and the user might reasonably want to take advantage of itk filters using python.

Another way to address this might be to upgrade the system to use newer python, vtk, pyvista, etc. Many of these issues may already be resolved.

#1097 #839 #725

**Comment by akenmorris** [comment]
Will not be building VTK/ITK with python support.  We are using pip now.
