### ISSUE TITLE
fix ImageTests::resample_test to add binary image and dt test functions

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#303]
Current test (which usefully demonstrates the unit test infrastructure) uses `isbinary` flag for a distance transform image. We want to have two tests, one for each type of image.

**Comment by sheryjoe** [comment]
Clarification: If a distance transform is an input for resampling, it should be handled as a non-binary image since voxel values are continous rather than discrete.

**Comment by sheryjoe** [comment]
@archanasri still an issue?

**Comment by archanasri** [comment]
I can see that there are test cases for binary images but not for distance transforms. Will add them.

**Comment by cchriste** [comment]
Moving this to 6.2 since better testing means a better release. Plus this is a trivial issue to resolve.
