### ISSUE TITLE
add "ShapeWorksPrompt" script to deployment

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#318]
This script should open a terminal, activate the shapeworks conda environment, and add the executables directory to the path. This will help users get right to work without any manual effort each time they want to use ShapeWorks.

There may be other things that should be added, such as PYTHONPATH.

**Comment by cchriste** [comment]
Reasons for providing this:
- /Application is not user-writable
- enables users to get to work without any manual steps
- creates a shapeworks directory for each user in multiuser installations

**Comment by akenmorris** [comment]
Sounds cool. Where would it create a user shapeworks directory and for what purpose exactly?

**Comment by cchriste** [comment]
As it stands, one cannot even run the python examples since it is not possible for a user to create a directory in the /Applications/ShapeWorks/Examples/Python folder. And even if it were, multiple users would overwrite each others' runs. I'd suggest just $HOME/ShapeWorks, but that's not the important part of this issue.

**Comment by akenmorris** [comment]
Yep, the examples are a problem. We might also change the examples to write to a different location.  It could be an arg like the path to bin. 

What about conda installs?

**Comment by cchriste** [comment]
There is user documentation for all these steps, including copying examples elsewhere (see deployment readme.txt). Is a startup script still useful or should we close this issue?

**Comment by cchriste** [comment]
Regardless, this is a duplicate of issue #478.
