### ISSUE TITLE
add detailed documentation shown only for `shapeworks <subcommand> --help`

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#326]
Currently we have a description associated with each subcommand, but it's sometimes too short to adequately convey the command, but doing so would be too verbose to include in simple `shapeworks --help`, so we should consider adding a more detailed description. Note: there may already be a way to do this that I just didn't notice.

**Comment by sheryjoe** [comment]
@archanasri ?

**Comment by archanasri** [comment]
This hasn't been done yet.

**Comment by cchriste** [comment]
I would say what we have for subcommand help is sufficient because it provides details about parameters.

**Comment by archanasri** [comment]
Yeah, that's true. I am closing this issue then.
