### ISSUE TITLE
Update Documentation/*.md when subcommand is added

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#327]
We are converting the various independent commands to `shapeworks <subcommand>` and the documentation for each of these commands should be updated when they are converted.

**Comment by sheryjoe** [comment]
@cchriste @archanasri shouldn't that be addressed by the 
DocumentationUtilsPackage (auto doc)  python package?

**Comment by archanasri** [comment]
@sheryjoe yes it should
