### ISSUE TITLE
Enable multiple values for a single shapeworks command argument (e.g., `-pt x y z`)

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#331]
We need this, for example, to load multiple images: `shapeworks readymades <path1> <path2> ... `
One suggestion to end multi-argument lists is to use the double-dash `--`, after which additional commands can be added.

**Comment by cchriste** [comment]
Related to #330

**Comment by medakk** [comment]
Merged in #363
Implemented as `shapeworks read-particle-system --names <path1> <path2> <path3> --`

**Comment by cchriste** [comment]
Re-opening this since we also want to be able to specify the number of parameters following a given argument. For example, `-pt valx valy valz` instead of `-x valx -y valy -z valz` and without having to trail it with an extra `--`.

**Comment by cchriste** [comment]
> Re-opening this since we also want to be able to specify the number of parameters following a given argument. For example, `-pt valx valy valz` instead of `-x valx -y valy -z valz` and without having to trail it with an extra `--`.

While I still wish we could do this, it's low-priority. 

But it's related to the annoying issue of _always_ needing to specify parameter names (ex: `shapeworks readymade --name foo.nrrd`, for which we all forget to type `--name` every few type we call it).

**Comment by cchriste** [comment]
Related to #325 and #330.
Closing #631 as duplicate of this one.

**Comment by cchriste** [comment]
As mentioned in #331, we should use https://github.com/CLIUtils/CLI11 to update the command line interface.

**Comment by cchriste** [comment]
Duplicate of #331
