### ISSUE TITLE
Add description/documentation of 'coverage' command

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#333]
I found the following on the PostView manual:

 Area Coverage
This tool evaluates the coverage of two surfaces. It assigns a value of one or zero of each node of a surface depending on whether it is covered by a second surface. Coverage is set to 1 if the local surface normal intersects with the opposing surface on the positive side of the normal. To use this tool, simply select the two opposing surfaces and press Apply.

**Comment by prafulag** [comment]
Yes, I think we should put this in terms of details and a link to PostView documentation.

If you need a use-case on how to use the tool, Joe (cc’ed) may provide you the command he runs.

Praful

**Comment by akenmorris** [comment]
Yes, I have a sample, I was mostly looking for the terminology as there were objections to calling the second mesh "second_mesh".

**Comment by prafulag** [comment]
I think first and second mesh should be okay. Especially coz I believe the coverage computation is invariant to which mesh is selected as first. @Steve - is this a correct assumption?

Praful

**Comment by prafulag** [comment]
In the ShapeWorks version of the coverage tool, order does matter, as the covered nodes are only returned for the first mesh.


-Joe

Joseph Mozingo
Postdoctoral Research Associate
Department of Orthopaedics
The University of Utah
Mobile 585-746-1844                                                         medicine.utah.edu/orthopaedics/research/labs/Harold-dunn<https://www.umail.utah.edu/ecp/Customize/medicine.utah.edu/orthopaedics/research/labs/harold-dunn>
________________________________

**Comment by akenmorris** [comment]
Right, it only writes out one mesh.  I guess you could apply it to both meshes and write out two meshes.  I don't really know what this is used for.

**Comment by prafulag** [comment]
The order indeed matters, since the tool only calculates the coverage onto the first surface. If you want both, you will have to run the tool twice with the surfaces flipped.


Best,


Steve

________________________________

**Comment by prafulag** [comment]
Thanks Steve and Joe!

Regards,
Praful Agrawal

**Comment by cchriste** [comment]
Since this issue still exists, can someone point to the documentation? I'm trying to figure out if the test results are correct. Here are two images showing to aligned meshes and the coverage (on the larger mesh).
<img width="620" alt="Screen Shot 2021-01-27 at 11 03 01 PM" src="https://user-images.githubusercontent.com/1260945/106097277-491f3200-60f4-11eb-92fb-71cabeb20f38.png">
<img width="570" alt="Screen Shot 2021-01-27 at 11 03 12 PM" src="https://user-images.githubusercontent.com/1260945/106097282-4ae8f580-60f4-11eb-8e6c-38f186f02f94.png">
@sheryjoe

**Comment by akenmorris** [comment]
I believe the intention here is to compute how much of a femoral head is "covered" by the acetabulum.  You can use the coverage test data, femur.vtk and pelvis.vtk to see this:

femur.vtk and pelvis.vtk:

<img width="704" alt="both" src="https://user-images.githubusercontent.com/1693349/106177251-7fd96480-6155-11eb-9d5f-1474b142114a.png">

Output of coverage (on femur):

<img width="355" alt="coverage_output" src="https://user-images.githubusercontent.com/1693349/106177288-89fb6300-6155-11eb-973e-041a35903928.png">

**Comment by sheryjoe** [comment]
@akenmorris?

**Comment by akenmorris** [comment]
I wrote as much as I know about this command in the comment above.

**Comment by akenmorris** [comment]
I believe what we have is sufficient.
