### ISSUE TITLE
Left atrium use case doesn't work

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#336]
Reported by a user and confirmed.  For me it crashed right after printing "Initialize Step"

**Comment by akenmorris** [comment]
With some digging have determined that it's not ShapeWorksRun that's the problem.  The distance transforms it's trying to run on appear to be blank.  Something else in the pipeline doesn't work properly.

**Comment by akenmorris** [comment]
Looks like it's the "com.aligned" step.  The padded file looks fine.  Note the transform file is full of "nan"s.

inFilename:./TestLeftAtrium/PrepOutput//padded\CARMA0046.laendo_no_veins.isores.pad.nrrd
outFilename:./TestLeftAtrium/PrepOutput//com_aligned\CARMA0046.laendo_no_veins.isores.pad.com.nrrd
translation:-nan(ind) -nan(ind) -nan(ind)
origin:-209.5 -209.5 -63.5
object center:-nan(ind) -nan(ind) -nan(ind)
image center:0 0 0

**Comment by akenmorris** [comment]
Update: this doesn't work on Mac or Linux either.

**Comment by akenmorris** [comment]
Update: The problem is that the input segmentations use 2's rather than 1's for **on**.  This is now propagated to the center of mass alignment (TranslateShapeToImageOrigin.cxx) which finds no pixels of value 0 and then divides by zero.

**Comment by akenmorris** [comment]
I think multiple things here need adjusting/fixing.  For example, we need consistency in how binary volumes are interpreted/treated (e.g. >0?  >=1? etc)

**Comment by akenmorris** [comment]
Can someone confirm that this is working now?

**Comment by AtefehKashani** [comment]
I have run it and it worked. some minor changes are needed that I will apply after merging Jadie's branch.

**Comment by akenmorris** [comment]
Works now.
