### ISSUE TITLE
fix build instructions and separate building shapeworks from building deps

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#343]
Please see my detailed comments here:
https://github.com/SCIInstitute/ShapeWorks/pull/324

Again, sorry I hadn't noticed these inappropriate changes before now.

And just to reiterate: rename superbuild.sh to build_deps.sh and remove building shapeworks from this script (add a script to run cmake if you absolutely must, but I'd advise against it and just have people use cmake themselves. How hard can it be to run `ccmake ..`?

**Comment by 0leks** [comment]
I'm on it boss!

**Comment by cchriste** [comment]
Is this issue resolved?

**Comment by 0leks** [comment]
Waiting on linux/mac build instructions to be merged to make the Windows build instructions mirror the structure

**Comment by akenmorris** [comment]
What is waiting to be merged?  Is there a PR?
