### ISSUE TITLE
Studio: Add ability to set units or read units from input images if available

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#347]
I am fairly certain that ITK has no support for units, so I don't know how likely it is that we will be able to read them from input files.  But in any case we can provide the user a way to set the unit type in a preference dialog for Studio and this value can be used in various places such as the group difference scalar bar.

**Comment by sheryjoe** [comment]
@akenmorris resolved?

**Comment by sheryjoe** [comment]
ITK doesn't read units. Nrrd files don't have units as part of the header.
