### ISSUE TITLE
Turn on file compression for NRRD writing at every stage of our pipelines

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#348]
The output from our demo processing pipelines is unnecessarily large.  I compressed a 17GB left atrium dataset down to 6GB with a simple script.  11GB is a lot of wasted space.

FYI, this is not even a time/space tradeoff.  I have found that it's faster to save with compression on than it is to save the (very large) uncompressed image volumes.

**Comment by cchriste** [comment]
The —compressed=true flag is set by default for writeimage. Otherwise, just
modify the standalone executables if they haven’t been consolidated into
the libraries yet.

**Comment by akenmorris** [comment]
Done.
