### ISSUE TITLE
Reconstruct surface / Reconstruct PCA Modes: Option to use mean DT in place of mean Mesh

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#353]
I need the option to use Mean DT in place of the mean mesh to reconstruct surfaces. The surface need to be generated using warped DT.

**Comment by prafulag** [comment]
Nevermind, not useful

**Comment by sheryjoe** [comment]
@akenmorris do we still need this?

**Comment by akenmorris** [comment]
I don't think so.
