### ISSUE TITLE
Studio PCA tab with large number of modes too large

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#355]
<img width="1000" alt="Screen Shot 2020-02-14 at 2 31 35 PM" src="https://user-images.githubusercontent.com/1693349/74569236-26bdf400-4f37-11ea-9179-f953536ca77a.png">

This chart needs to stop at some point.

**Comment by sheryjoe** [comment]
One way is to detect the dominant modes (using two options - scree plot and parallel analysis) and may be stop somewhere after that (e.g. 10 or 20% of the number of dominant modes). Detecting dominant modes feature has been brought up at least twice in the user meeting. @medakk can you help Alan adding this feature?

**Comment by akenmorris** [comment]
For the moment, I've placed the chart in a QScrollArea so that it has a slider:

<img width="414" alt="Screen Shot 2020-02-14 at 4 31 47 PM" src="https://user-images.githubusercontent.com/1693349/74576361-a653bf00-4f47-11ea-8a60-c416e561c2dc.png">

<img width="414" alt="Screen Shot 2020-02-14 at 4 31 51 PM" src="https://user-images.githubusercontent.com/1693349/74576364-a8b61900-4f47-11ea-965d-7625a8f026d7.png">

**Comment by sheryjoe** [comment]
Can we have the linear scale as the default?  Also for the new graph with the explained variance, please use correct/descriptive x and y labels.

**Comment by akenmorris** [comment]
Agreed.

**Comment by medakk** [comment]
@sheryjoe Sure, I'll work with @akenmorris on finding dominant modes.
