### ISSUE TITLE
Studio: Replace bar chart

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#359]
We currently have this:

<img width="229" alt="Screen Shot 2020-02-14 at 3 53 24 PM" src="https://user-images.githubusercontent.com/1693349/74574858-3bec5000-4f42-11ea-882e-12bb218dc5f7.png">

The y-axis is likely nearly meaningless to most users.  Without knowing the total value, it doesn't tell us much.  We can only see the relative contribution.  I would like to propose a chart more like the following:

<img width="449" alt="Screen Shot 2020-02-14 at 3 53 38 PM" src="https://user-images.githubusercontent.com/1693349/74574909-5de5d280-4f42-11ea-9a1f-af6c1158d7ab.png">

The bars will actually be unchanged, but I think we should be using 0-100 of explained variance rather than the eigenvalue.  Also, I like the addition of cumulative explained variance.

**Comment by sheryjoe** [comment]
Agreed. This graph is more interpretable.

**Comment by prafulag** [comment]
The new graph is certainly better. It will be great if we can also export the graph (picture). I think the current system only allows exporting values in a csv format.

**Comment by akenmorris** [comment]
Default to linear scale.

**Comment by sheryjoe** [comment]
Yes. I agree with Praful. It would be helpful if we can export the graph in a picture format with some font/color/linewidth ... etc control options.

**Comment by akenmorris** [comment]
I will make a separate issue regarding export of the graph.
