### ISSUE TITLE
Add documentation of dataset upload

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#365]
Upload should have:
1) README
2) License
3) ?

**Comment by 0leks** [comment]
Question: Where should this documentation live?

**Comment by 0leks** [comment]
Answer: In a Datasets.md file in the documentation folder, with a link to it from the main README.md

**Comment by 0leks** [comment]
Question: what goes in the readme?

**Comment by sheryjoe** [comment]
"Details about use case datasets" or "Use case datasets guidelines" -- something along these lines.

**Comment by akenmorris** [comment]
This is done, right?

**Comment by 0leks** [comment]
Yes

**Comment by sheryjoe** [comment]
Done. Closing it.
