### ISSUE TITLE
Disable generation of Hessian volumes if normals will not be used.

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#366]

**Comment by sheryjoe** [comment]
@akenmorris still an issue?

**Comment by akenmorris** [comment]
I don't think so, didn't we drop the hessians altogether @medakk ?

**Comment by medakk** [comment]
Yeah, hessians are no longer computed. But the gradient of normals are always computed I think. 

There's some code to delete the gradient of normals computed, but it might be specific to fixed domains. I'm not sure. (see DeletePartialDerivativeImages)

**Comment by akenmorris** [comment]
No longer applicable.
