### ISSUE TITLE
OpenMP parallel loops in MeshBasedGeneralEntropyGradientFunction

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#368]
The computeUpdates method is called in BeforeIteration during optimization. It comprises of multiple components with loops to estimate the final updates. These loops can be parallelized using OpenMP, and can result in massive speedup. Some openMP parallel loops exist in there, but not sure if they actually execute in parallel. I believe some shared data structure may need to be looked at to ensure these loops actually run in parallel.

**Comment by sheryjoe** [comment]
@akenmorris still an issue?

**Comment by akenmorris** [comment]
I don't think so.  Profiling this section of code that takes a lot of time when the number of particles is large.  The time is nearly entirely spent in the very large matrix multiply in Utils::multiply_into.  The loops below it are only pulling out the updates.
