### ISSUE TITLE
BUILD_POST in superbuild.sh

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#379]
This variable is being used in build_shapeworks() but never set to any value.

**Comment by akenmorris** [comment]
We must have used it in some previous version of the superbuild script. @sheryjoe was there a decision made about POST?  Should we build it by default? (If GUI is on?)

**Comment by akenmorris** [comment]
Actually, it doesn't matter.  We are switching to building dependencies only.
