### ISSUE TITLE
please don't use dashes in shapeworks command names

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#397]
They just cause lots of typos and slow everyone down. For example:
`read-image read0-image read-omige read-image read-image read=image read=image`
vs…
`readimage readimage readimage readimage readimage`

If a command is more than two words, try renaming it to something simpler instead of introducing dashes. 

In addition, there are already many, many dashes in the commands, including the new `--` (double dash) introduced to enable multiple values for a single argument. Adding even more dashes makes things much more difficult to read and assess.

**Comment by cchriste** [comment]
I heard there was a brief discussion about this in a group meeting while I was away, but I disagree with the solution enough to create this issue for the inefficiencies introduced when typing a command as well as the confusion when trying to see what a given command is doing.

**Comment by cchriste** [comment]
Another strong argument against dashes is that the functions themselves do not have dashes. Therefore we are diverging unnecessarily away from the ShapeWorks library API, requiring users to essentially learn two different languages to use the API in Python, their own C++ application, or the command line. 

It was necessary to add mesh or image suffixes to the commands since there was no other way to differentiate between e.g., readimage and readmesh, but even using dashes here just makes it more tedious and error prone and confusing to read the command.

**Comment by cchriste** [comment]
On a somewhat related note: even the `=` in the commands is optional, i.e., 
```
readimage --name=/data/foo.nrrd
readimage --name /data/foo.nrrd
``` 
are the same. This suggests "less is more" when it comes to dashes, even when they're stacked.

**Comment by sheryjoe** [comment]
What do you propose for commands with multiple words (e.g. center of mass align) to make them more readable? A one-word command is not an option here as agreed upon by the group.

**Comment by cchriste** [comment]
Two word command names like “writemesh” have not been a problem, but I
agree that more than two words can be confusing. Let’s collect all the
command names to see what we’re working with and keep things coherent
(we’ll create a separate issue to do this).

For the example you mentioned, the command itself is simply “align” and the
type of alignment used is “center of mass”, which can be a parameter to the
command. There may be other types of alignment, which can be specified as
different parameters to that command.

**Comment by archanasri** [comment]
The command line can now understand shapeworks command names with or without dahses
