### ISSUE TITLE
update google sheet w/ all (proposed) command names

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#401]
https://docs.google.com/spreadsheets/d/17gevfSR-bY3cSr0C-rAmOe6kE8OtrFv06iWt_W10T1M/edit#gid=0

Update this will all command names so a coherent collection of these names can be created rather than continuing to have command names that are more verbose than necessary.

Related to #397

**Comment by archanasri** [comment]
This is something we have to tackle as we go.
