### ISSUE TITLE
add ability to specify enum values as command arguments

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#402]
Examples are the different types of alignment or resampling (ex: `align --type=[CENTER_OF_MASS|EXPLICIT|???]`).

**Comment by cchriste** [comment]
The alternative of simply using booleans as is currently used in both existing and new executables can result in argument conflicts.
Making new command names for each type of the same overall operation is redundant and confusing.

**Comment by archanasri** [comment]
Right now, we have filter --type <type of filter>.
E.g: filter --type curvature OR filter --type antialias
