### ISSUE TITLE
Maybe use OptionParser::OptionGroup rather than our own option groups in Executable

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#403]
Not sure why this wasn't used in the first place, so just take a look at the already available class. 
But do keep in mind that "if it ain't broke, don't fix it" so as not to waste too much time.

**Comment by cchriste** [comment]
@archanasri Can we close this or is it worth rewriting the option groups?

**Comment by archanasri** [comment]
@cchriste I think we can close it but do you have reasons as to why you think we should do this?

**Comment by cchriste** [comment]
I'm going to close it as a duplicate since other issues like #330 already discuss other facets of this issue and propose an underlying solution that could resolve them all: use a different command line library altogether.
