### ISSUE TITLE
DICOM to nrrd conversion command

### ISSUE THREAD

**Issue by farshaduou** [SCIInstitute/ShapeWorks#406]
Please add a command to ShapeWorks for converting from DICOM to nrrd files.

**Comment by akenmorris** [comment]
This request should probably be to add DICOM reading support to the existing read-image command. That way the conversion is something like “shapeworks read-image —dicom-dir=<path> write-image —name=out.nrrd”

**Comment by akenmorris** [comment]
This was completed in #415
