### ISSUE TITLE
add --verbose switch to shapeworks command

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#407]
This can print things like the computed "center of mass" transform since saving it to a file was only being done for debugging purposes anyway and the file itself wasn't used.

**Comment by sheryjoe** [comment]
Saving transformations from commands/tools that change shape alignment are not saved only for debugging. These transformations are used to apply the same transformation to any associated data to transformed shape (e.g. landmarks, curves, cutting planes, imaging data ... etc). Alignment commands should save the applied transformation.

**Comment by akenmorris** [comment]
Correct, they can also be used to transform final correspondence points back to the original coordinate system.  I have done this many times for multiple purposes.

**Comment by cchriste** [comment]
The file that is written is very casual. Does that mean we are simply
reading something with a bunch of plain text to effect operations down the
line?
Here's an example of what is written by the TranslateShapeToImageOrigin
executable:
```
inFilename:/path/to/file
outFilename:/path/to/file
translation:1.2345 6.7890 3.1415
origin:1.2345 6.7890 3.1415
object center:1.2345 6.7890 3.1415
image center:1.2345 6.7890 3.1415
```
What other executables use this? (note: this executable never reads such a
file as is written, which is why I thought it was more appropriate to use
as verbose output)

**Comment by cchriste** [comment]
> Saving transformations from commands/tools that change shape alignment are not saved only for debugging. These transformations are used to apply the same transformation to any associated data to transformed shape (e.g. landmarks, curves, cutting planes, imaging data ... etc). Alignment commands should save the applied transformation.

If we're going to save transformations, we should do so in a consistent manner. What we observed in the executable above seems very ad hoc. Are there examples of these used elsewhere? We have created a Transform class and can write the transform, particularly a binary version (i.e., a 4x4 matrix composed of 16 doubles), to be used elsewhere. It's not clear why it would be necessary to save anything but the translation as the rest of these can be computed when an image is loaded (binary or otherwise).

**Comment by akenmorris** [comment]
I agree for the most part it would be translation.  The "old" shapeworks had the option to write out transform files on each image as part of a `center` operation.  The format was something like:

1 0 0 39.5336
0 1 0 25.4936
0 0 1 48.484
0 0 0 1

Either this, or one could also use an ITK Transform file as this is fairly commonplace (e.g. Slicer).

I personally found the text file to be easy to process since my correspondence point transforming program was just a simple script (reading ITK binary would be more difficult, though now that I think of it, I believe there is an ASCII option).

I'm sure there is not yet another program in the current ShapeWorks ecosystem to read this file.

Another consideration for you when designing this is that the transform should be available via the class interface as well so that Studio and other tools could access it.

**Comment by cchriste** [comment]
Yup. That's exactly what I'd suggest, a general affine transform matrix. This is what we created (and further I'd suggest operator<< and operator>> rather than print/read). The Image class has a corresponding transform(const Transform&) function:
```c++
#pragma once

#include "Shapeworks.h"
#include "Image.h"
#include <itkFixedCenterOfRotationAffineTransform.h>

namespace shapeworks {

class Transform
{
public:
  using TransformType = itk::FixedCenterOfRotationAffineTransform<double, 3>;

  Transform() : rotangle(0.0) {}

  TransformType::Pointer get() const;

  void reset();
  void translate(const Point3 &p); 
  void rotate(const Vector3 &axis, double angle);
  void scale(const Point3 &s);

  void print() const;

private:
  Point3 scaling;
  Vector3 translation;
  Vector3 rotaxis;
  double rotangle;
};

} // shapeworks
```

We're starting to push past the reasonable limits of what we'd want to do with the command line. I suggest we move forward with the Python API (which I'm working on), and also create small C++ apps that use the new API, which will basically be the same simple apps that the Python will be, a dramatic improvement over the overcomplicated, inflexible behemoths currently available.

With that in mind, let's add a flag to import/export these transforms, but as you can see above, it's not unreasonable for someone to think these were only meant for debugging: they're just plain text, and there aren't any other applications that use this text.

I'll close this issue make a note in the spreadsheet to add the ability to import/export transforms for commands that use them (so far 0 imports and 1 export).
