### ISSUE TITLE
Windows Issue with ellipsoid_fd use case

### ISSUE THREAD

**Issue by 0leks** [SCIInstitute/ShapeWorks#416]
So I started encountering crashing on the ellipsoid_fd use case.
Can someone confirm if this issue happens on linux?
I narrowed down the pull request that causes this crash to #329 
Here is the command line output:
```
Step 4. Optimize - Particle Based Optimization
Reading inputfile: TestEllipsoidsFD/Ellipsoids_ExistingDT/seg.ellipsoid_0.isores.pad.com.aligned.cropped.tpSmoothDT.nrrd...
... reading more nrrd files ...
Reading inputfile: TestEllipsoidsFD/PrepOutput/distance_transforms/seg.ellipsoid_21.isores.pad.com.aligned.cropped.tpSmoothDT.nrrd...
General exception caught.
        Returncode: 3221225477
        Output: None
```
When building and running from #405 there are no problems.

Side note, there is an unrelated issue with directory paths in ellipsoid_fd.py introduced in #404 that I will have a pull request for shortly.

**Comment by akenmorris** [comment]
I just ran it on Mac with no problem.  I will try on windows.

**Comment by akenmorris** [comment]
Crashes on Windows for me as well.  No idea why.  VS sat for an hour trying to open the debugger.

**Comment by akenmorris** [comment]
It's nothing to do with Windows.  There is a problem with some data being used before initialization.  ShapeWorksRunApp had every little part being initialized as the input file was read.  I tried to correct this as much as possible when separating out the input file, but it looks like I missed a few spots.
