### ISSUE TITLE
omit image/mesh/particlesystem suffixes from shapeworks executable commands and create standalone prefix commands to override default types for the application of successive commands

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#421]
There are many commands that can be applied to more than one type of shared command data, including images, meshes, and particle systems. Examples include reading, writing, and transforming such data. 

Rather than requiring these overloaded command names be followed by the data type for which it be applied, these command should be more elegant and concise and automatically applied to the expected type. 

Read and write commands do not need to be followed by the type of data since the type can be derived from the filenames themselves. Transforms can simply be applied to the most recently used data type. For example, loading an image and then calling the recenter command should apply that command to the recently loaded image. 

For the most part, this is very simple and intuitive. But there may be cases where, for example, a command should be applied to a mesh or particle system when most recently an image was loaded. In these cases, a prefix command can be created in order for successive commands to be applied to the specified prefix. For existing data types, these prefix arguments can be "image," "mesh," and "particlesystem."

This will dramatically shorten commands and make their usage more elegant and natural, and it will be fairly simple to implement.

**Comment by sheryjoe** [comment]
@cchriste still an issue?

**Comment by cchriste** [comment]
It's still an issue, but I wonder if the proposed prefix command would only make subsequent commands more confusing. I'm okay with the current (overly verbose) command names. @archanasri ?

**Comment by archanasri** [comment]
I am okay with them too. Most of the commands are two words. At max, three words. I am okay with how it is right now.

**Comment by cchriste** [comment]
closing this
