### ISSUE TITLE
Update BUILD.md

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#427]
Since we now rely on conda for gtest, the instructions in BUILD.md are a little out of date.  For example, the current instructions describe installing dependencies if not using Anaconda, but the linked deps.txt isn't up to date (e.g. missing gtest).

I think it's also a little inconsistent in that it asks the user to download and install anaconda, and then run conda_installs.sh (which will install it if missing anyway).

We also need to remove the windows instructions (following a merge of #425).

I think it's fine to have the instructions describe only the conda path, and in that case, we can probably remove "CMake 3.11" from the requirements at the top.

**Comment by cchriste** [comment]
I am fine with all these suggested updates to the build instructions. But I'll be out for the next two weeks, so I suggest passing this to someone actively working on the builds, maybe @0leks or @medakk. Thanks!

**Comment by akenmorris** [comment]
👍 I’ll take care of it.  For Windows we will have to discourage the use of cmake-gui.exe (e.g. launched by start menu) as there is no way to activate the conda env for it.

**Comment by cchriste** [comment]
For me, conda is the one who installs cmake, so there is no way to launch it without the env activated. Can this be done on Windows as well? (I recall something about this but can't remember exactly what).

**Comment by akenmorris** [comment]
There is a cmake provided by conda for windows, but no cmake-gui as in our current windows instructions.

**Comment by akenmorris** [comment]
This was completed in PR #425
