### ISSUE TITLE
Make `Image::read` private, and add assignment operator and copy ctor

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#430]
This comment and its associated issue describes the reasoning behind this:
https://github.com/SCIInstitute/ShapeWorks/commit/1a56525e8e31fb1a9c2b297c5ad67f8973a0c3e7#commitcomment-37690192

The SharedCommandData can simply create a new image, then assign it to the existing image when `readimage` command is used.

**Comment by archanasri** [comment]
Done!
