### ISSUE TITLE
Add "helper" commands, for user friendliness

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#432]
* Center of mass alignment:
   1. Get center of mass
   2. Create and apply transform
   3. Return result
* Easy isoresample:
  1. E.g for binary image, takes care of antialias, binarize, etc, all in one.

**Comment by archanasri** [comment]
For center of mass alignment, we have:
shapeworks readimage --name <path> translate --centerofmass 1 writeimage --name <path>

For the isoresample utility, what would be an appropriate command name that performs antialias, isoresample, threshold and recenter?

**Comment by archanasri** [comment]
Done
