### ISSUE TITLE
URGENT for MICCAI deadline: Analyzing multiple domains View2/Studio

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#437]
In case of multiple domains, code assumes same number of points in all domains. I need this to be updated - we can provide number of points per domain like we do for shapeworks optimization, if this is not provided then same number of points can be assumed in all domains.

**Comment by prafulag** [comment]
Number of points in each domain may also be set based on the number of points read from the point files.

**Comment by sheryjoe** [comment]
@akenmorris could you help with this?

**Comment by akenmorris** [comment]
Yes, Praful and I have been going back and forth over email.  I've completed most of the changes already.
