### ISSUE TITLE
Fix Studio/View2 usage of Reconstruction

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#440]
ReconstructMeanSurface has a large section of code that calculates an "origin" and uses "set_origin".

View2 and Studio don't have this section of code.  Instead they use some other method to calculate an origin and then subtract this point from the global/world points.  This method doesn't seem to work.

The above functionality should be migrated into the Reconstruction class to be shared by all three.

**Comment by sheryjoe** [comment]
@akenmorris is this still an issue?

**Comment by akenmorris** [comment]
No, this was all refactored.
