### ISSUE TITLE
build_dependencies can't build in Debug or RelWithDebInfo on Windows

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#449]
We've made significant progress in the branch try_windows_debug:

https://github.com/SCIInstitute/ShapeWorks/tree/try_windows_debug

At this point, VTK won't build with Debug or RelWithDebInfo:

D:\a\bdeps\vtk\ThirdParty\netcdf\vtknetcdf\libsrc4\nc4hdf.c(3638,25): error C2177: constant too big

I found this:

http://vtk.1045678.n5.nabble.com/Trouble-compiling-VTK-7-1-0-with-MSVC-2015-td5742220.html

They suggest, "I suspect that cmake did not find the Windows SDK", which doesn't really make any sense.

After several hours working on this, I'm giving up and suggesting that if developers want to build in Debug mode that they use either Mac or Linux (or take up where Oleks and I left off with this branch).  I'm just creating the issue to document the status and progress.

**Comment by medakk** [comment]
FWIW, it looks like `nc4hdf.c` is moved to a different folder in the current version of VTK, from
https://github.com/Kitware/VTK/tree/master/ThirdParty/netcdf/vtknetcdf/libsrc4
to
https://github.com/Kitware/VTK/blob/master/ThirdParty/netcdf/vtknetcdf/libhdf5
and its smaller than the original (number of lines).

It might be worth trying it out with a newer version of VTK.

**Comment by akenmorris** [comment]
From nc4internal.h:

#ifdef WIN32 /* Windows, of course, has to be a *little* different. */
#define X_FLOAT_MAX	3.402823466e+38f
#else
#define X_FLOAT_MAX	3.40282347e+38f
#endif /* WIN32 */
#define X_FLOAT_MIN	(-X_FLOAT_MAX)
#define X_DOUBLE_MAX	1.7976931348623157e+308 
#define X_DOUBLE_MIN	(-X_DOUBLE_MAX)

**Comment by medakk** [comment]
That may be, VS 2015 defines [_WIN32, not WIN32](https://stackoverflow.com/questions/41643317/c-visual-studios-2015-ifdef-win32-not-executing-properly)

**Comment by akenmorris** [comment]
I can't imagine it should differ between Release and RelWithDebInfo (or Debug)

**Comment by akenmorris** [comment]
Working now.  Adding -DWIN32 for the VTK build fixed it.  The GitHub action does not work because the rest of the script for packaging assumes a Release build.  I don't think there's much reason to deploy debug builds, so I won't worry about that.  But we should probably add a "--debug" option to build_dependencies.sh for windows.

@0leks

**Comment by prafulag** [comment]
Thanks @akenmorris and @medakk! This is very helpful!

**Comment by akenmorris** [comment]
This was completed. Debut builds for all!
