### ISSUE TITLE
Update ShapeWorks Studio to work with the latest SW version and add it to this repo

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#45]
The current version of ShapeWorks Studio [found here ](https://github.com/SCIInstitute/ShapeWorksStudio) uses the old ShapeWorks tools API and needs to be upgraded. The upgraded version should be included in the main repo so it can be built along with the rest of the platform.

**Comment by aogs** [comment]
Should we import the source as is first and then update it?  Or do you think we should continue development in the old repo until it’s ready?

**Comment by akenmorris** [comment]
Should we import the source as is first and then update it? Or do you think we should continue development in the old repo until it’s ready?

**Comment by cchriste** [comment]
I suggest creating a branch, importing the repo (along with its commit history, for which I have instructions), then upgrading it to work with the latest API before merging with master.

**Comment by cchriste** [comment]
Done merging ShapeWorksStudio with ShapeWorks/studio_merge branch!
**NOTE:** The dependencies upgrade should be performed in a separate branch (e.g., `upgrade_deps`) and periodically merged into this new branch as it progresses in order to keep these tasks separated.

Here is the process that was used to perform the merge:
```
Merged ShapeWorksStudio with ShapeWorks (in its own branch until it's ready to be merged with master)

Process:

1) prepare ShapeWorksStudio for merging with ShapeWorks main:

  - git clone git@github.com:SCIInstitute/ShapeWorksStudio
  - cd ShapeWorksStudio

 # remove unnecessary files
  - find . -name ".DS_Store" -exec git rm {} \; -print
  - git rm user_guide/figs_v2/._*
  - git rm .gitignore .gitattributes
  - git commit -am "cleanup in preparation for merge with ShapeWorks main"

 # move Studio files to their own directory
  - mkdir Studio
  - git mv LICENSE.txt README.md src user_guide Studio
  - git commit -am "move everything to Studio subdirectory to be added to ShapeWorks main"

2) merge everything into ShapeWorks main:

 # update to latest master before merging to new branch
  - cd ../ShapeWorks
  - git checkout master
  - git pull

 # add ShapeWorksStudio remote and fetch its branches (it only has master)
  - git remote add Studio ../ShapeWorksStudio
  - git fetch Studio

 # create destination branch and merge Studio
  - git checkout -b studio_merge
  - git merge remotes/Studio/master --allow-unrelated-histories 

 # push new branch to ShapeWorks main
  - git push origin studio_merge
```

**Comment by akenmorris** [comment]
Sounds good.  Studio already uses QT5, right?

**Comment by cchriste** [comment]
I've updated the studio_merge branch with the latest from master. Here's the process that can continue to be used to keep it up-to-date with master:
```
git fetch --all
git checkout studio_merge
git pull
git merge origin/master
```
These code bases will increasingly become dependent, for example when libraries used by Studio are also used inside ShapeWorks they will simply exist in one place (Libs), but I hope to complete the dependent library consolidation asap since it's an issue for many other pieces. 

Just to be clear, the --allow-unrelated-histories step mentioned above _is not required_ now. At this point simply use `git merge origin/master`.

**Comment by cchriste** [comment]
> Sounds good. Studio already uses Qt5, right?

I do not know.

**Comment by cchriste** [comment]
Significant progress has been made on this task (thanks @akenmorris!). Perhaps it should be broken down into a set of smaller tasks that can be collected in a milestone. These tasks could include:
- ensure external dependencies are shared with the rest of the framework
- add ability to load latest SW data
- ???

**Comment by akenmorris** [comment]
Studio mostly just needs to be swapped to the more recent internal libraries. It’s mostly internal library consolidation. It has its own shapeworksrun, its own surface reconstruction, particle statistics, etc.

**Comment by akenmorris** [comment]
The external library stuff is all done. I don’t think there’s a data issue.

**Comment by akenmorris** [comment]
Done.
