### ISSUE TITLE
run ellipsoid test as part of GitHub action

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#450]
This will ensure many things are working which are otherwise not being tested.

**Comment by akenmorris** [comment]
This was done quite a while ago.  See:

https://github.com/SCIInstitute/ShapeWorks/blob/98d38e2ceb7931b294901b93635f15863fea18cb/Testing/PythonTests/PythonTests.cpp#L54

Also see #423.  While ellipsoid tests a lot of the python code, we are still constantly having the problem that the rest of the use cases fail on windows until someone runs them manually and fixes them.

**Comment by cchriste** [comment]
Yeah, I just noticed that we are running them and went to close this issue. However, the reason I opened it is because the ellipsoid use case for a recent pull request could not work (it uses the upcoming native python library, but that wasn't included in the pull request), and yet those tests passed.
