### ISSUE TITLE
Review and release Ellipsoid example parameters and results

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#455]
It's been reported that the ellipsoid example has too few iterations per split and a bad resulting optimization.

**Comment by sheryjoe** [comment]
@riddhishb and @medakk. This is pertaining to releasing tuned algorithmic parameters and trained shape model along with the use case for end-users.  I would come up with specific guidelines to tune and release trained models for the group to flow with other uses cases beyond the ellipsoid example.

**Comment by prafulag** [comment]
Can we fix a deadline for this?

**Comment by sheryjoe** [comment]
Let's revisit the ellipsoid example and use/release prepped and unprepped ellispoid using the new ellipsoid that Alan generated. This will also include optimal hyper-parameters and shape models.

**Comment by jadie1** [comment]
I checked the optimization for current ellipsoid use case and it looks good. I think we can close this issue for this release and make a new one for 5.6.0 to make a better ellipsoid data set, unless we are trying to finish that for this release.

**Comment by akenmorris** [comment]
Agree with @jadie1

**Comment by sheryjoe** [comment]
Agreed.
