### ISSUE TITLE
Review documentation regarding particle system statistics

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#456]
@prafulag mentioned something about that one of the statistics should match the voxel size to confirm a good sampling/optimization.

**Comment by sheryjoe** [comment]
@medakk This is related to generalization and specificity metrics. Reporting this in units of voxel spacing. For compactness, it should be a percentage of explained variance.

**Comment by prafulag** [comment]
Another thought: we should also report shape feature sizes, min and max, like Feret’s diameter. Coz we can always chose a very fine resolution voxel size, but generalisation or specificity won’t change much. This may result in an incorrect assessment of the model.

Regards,
Praful Agrawal

**Comment by medakk** [comment]
@sheryjoe Isn't compactness already a percentage of explained variance? Since we divide by the sum of all eigenvalues.

**Comment by sheryjoe** [comment]
Yes. (x100) ... Units of these metrics should also be included the documentation.

**Comment by sheryjoe** [comment]
@medakk is this still an issue?

**Comment by medakk** [comment]
I don't understand this issue

@sheryjoe 
> Reporting this in units of voxel spacing

Does this mean simply scaling the result by the voxel spacing? What if its anisotropic?

(+the particle commands operate on .particles files. The voxel spacing information is usually unavailable at the point of shape-evaluation)
