### ISSUE TITLE
Memory leak in ParticleMeshBasedGeneralEntropyGradientFunction

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#459]
The constructor of ParticleMeshBasedGeneralEntropyGradientFunction leaks memory. The amount leaked is about 3GB for the femur use case, and 437.5MB for the ellipsoid(at 10000 iterations):

![image](https://user-images.githubusercontent.com/10536745/78462297-e7d23200-768d-11ea-9671-5943ec887610.png)

The source of this is these lines in [itkParticleMeshBasedGeneralEntropyGradientFunction.h](https://github.com/SCIInstitute/ShapeWorks/blob/ecc9a174a8d0792e301d1a32de7eeddaee870883/Libs/Optimize/ParticleSystem/itkParticleMeshBasedGeneralEntropyGradientFunction.h#L229):
```cpp
        m_PointsUpdate = new vnl_matrix_type(10,10);
        m_InverseCovMatrix = new vnl_matrix_type(10,10);
        m_points_mean = new vnl_matrix_type(10,10);
```

These are never freed. This was added as part of [this commit](https://github.com/SCIInstitute/ShapeWorks/commit/0c28833afc388021f78929d030b7ad0e6706f975).

Undoing the changes from that commit fixes the problem(tested in this [branch](https://github.com/SCIInstitute/ShapeWorks/tree/leak)), but I'm wondering if I'm missing something.

Alternatively, a smart pointer should work.

@prafulag @akenmorris @sheryjoe

**Comment by akenmorris** [comment]
I haven’t looked through the full diff, but I would recommend a smart pointer.
