### ISSUE TITLE
write script to automatically generate body of Documentation/shapeworks.md

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#467]
Use the script (maybe python) to generate the "API body" of the markdown document that describes our unified executable, something like:
```
command_index = ""
command_detail = ""
for all commands cmd in `shapeworks --help`
    command_index += cmd.name + [#cmd.name] +"\n"
    command_detail += cmd.name + "\n"+cmd.desc+"\n"
    for all params parm in `shapeworks $cmd --help`
        command_detail += "\t"+parm.name+": " + parm.desc + "\n"
```
Then concatenate the result of this script with the overview of the executable that already exists in that file. This will ensure the documentation is updated when command is added, removed, or changed. 

Related to #464 .

**Comment by sheryjoe** [comment]
Addressed with DocumentationUtils package.
