### ISSUE TITLE
Upgrade Qt4 to Qt5

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#47]
[ShapeWorksView2](https://github.com/SCIInstitute/ShapeWorks/tree/master/Post/source/ShapeWorksView2) is the primary application to be updated in order to upgrade Qt.  

This overview of how to transition suggests it's fairly straightforward:   [https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5]()

Related:
https://github.com/SCIInstitute/ShapeWorks/issues/45

**Comment by akenmorris** [comment]
The complication is that VTK has to be upgraded at the same time generally as we have to switch to a version that uses Qt5 instead of Qt4 for the QVTKWidget.

**Comment by cchriste** [comment]
> everything using VTK has to be updated to the new APIs.
Can we list "everything" to give an idea of how much work the VTK upgrade entails?

**Comment by riddhishb** [comment]
This is solved via #60
