### ISSUE TITLE
Rename "Export PCA Loadings" in View2, add to Studio

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#472]
Export PCA Loadings actually exports Raw Component Values in View2.

Also, this seems to be missing entirely in Studio

**Comment by sheryjoe** [comment]
@akenmorris is this added/fixed in Studio? View2 should be deprecated.

**Comment by akenmorris** [comment]
Yes, it's "Export PCA Component Scores".

Should View2 be removed yet?

**Comment by sheryjoe** [comment]
> Should View2 be removed yet?
If we refactored and included all its features into Studio, i think we should remove. It would be double the effort to maintain both Studio-Analyze and View2 especially with the new viz/analyze features that we will add to Studio.

**Comment by akenmorris** [comment]
Well, we don't really really maintain View2 in any way besides making sure it still compiles.

Studio does not have multiple domain support while View2 does.
