### ISSUE TITLE
Studio: Add orientation cube to single viewer mode 

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#474]
Add the orientation cube (from View2) to Studio, but only for single viewer mode (e.g. PCA display)

**Comment by sheryjoe** [comment]
add A-P-L-R view box or XYZ axes

consider a solution when viewing shapes in a grid (multi samples view).

**Comment by akenmorris** [comment]
I'm not sure what to do for the grid view:

<img width="502" alt="Screen Shot 2020-10-01 at 10 45 29 AM" src="https://user-images.githubusercontent.com/1693349/94840060-16c72780-03d5-11eb-9718-e23ee68ced86.png">

**Comment by akenmorris** [comment]
I guess we can shrink it as the grid increases:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/1693349/94841477-51ca5a80-03d7-11eb-8197-bd20766bbcb6.png">

**Comment by sheryjoe** [comment]
Shrinking it seems to work in a grid view.
