### ISSUE TITLE
Double check links on use cases documentation

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#476]
For instance: "The use case is located at: /Examples/Python"  -- link not working

https://github.com/SCIInstitute/ShapeWorks/blob/master/Examples/Python/ellipsoid.py

**Comment by AtefehKashani** [comment]
I have updated the broken links and committed to the documentation branch ready for your review.

**Comment by jadie1** [comment]
Thanks Atefeh, I double checked all the links in the documentation branch and they work now.

**Comment by jadie1** [comment]
The documentation branch is ready to be merged, once it is we can close this issue

**Comment by AtefehKashani** [comment]
This issue is addressed.
