### ISSUE TITLE
Separate recentering and isotropic resampling in groom utils

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#477]

**Comment by cchriste** [comment]
If you are referring to the function `applyIsotropicResampling` in GroomUtils.py, please see the version found in the `executable` branch, which will soon be merged. At least in that version re-centering is optional.

**Comment by jadie1** [comment]
Re-centering is optional in the master version as well but it defaults to true and has caused a lot of confusion. We already have a center function in GroomUtils.py so I am just taking it out of applyIsotropicResampling and having the use cases call the functions separately for clarity.

**Comment by cchriste** [comment]
I feel that way about many of the GroomUtils functions. We’ll simplify and
break it apart more. If you’d like to take a pass please do it on the
executable branch since it will make the merge less painful. Thank you!

**Comment by jadie1** [comment]
I already fixed this particular issue on a branch called "separate_centering_resampling". Should I make a pull request for it branch or remove it and make the fix in the executable branch?

**Comment by jadie1** [comment]
Closing this - it was fixed for now with the separate_centering_resampling branch
