### ISSUE TITLE
Move particle based surface reconstruction from prep to post tools

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#48]
current path: 
https://github.com/SCIInstitute/ShapeWorks/tree/master/Prep/Source/MeshTools/ParticleBasedSurfaceReconstruction/source

**Comment by cchriste** [comment]
@sheryjoe this probably relates to code reorg as well as to the work you've been doing. Can you please clarify this particular issue? I'll add it to the code reorg/libshare milestone.

**Comment by sheryjoe** [comment]
As the reorg will organize tools based on functionality rather than the workflow phase (i.e. prep vs post), this issue is now irrelevant.
