### ISSUE TITLE
Pytorch Install

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#481]
Pytorch needs to be added to the conda installs for the DeepSSM use case via:
conda install pytorch torchvision cudatoolkit=## -c pytorch
Where ## is the version number. 

We need to find a way to either automatically detect which cuda version is compatible with the users GPU or allow them to somehow specify it directly.

**Comment by cchriste** [comment]
Awesome. I'm excited to see how there were installed in the DeepSSM branch. 

On a somewhat related note, we're running into incompatible version issues with conda_installs across platforms (pull requests #701 and #702) and I'm convincing myself we can split the sections into `if (windows) ... else if (mac) ... else ...` and specify versions that way.

**Comment by sheryjoe** [comment]
@jadie1 is this resolved?

**Comment by jadie1** [comment]
@sheryjoe Yes as soon as pull request #709 is merged.
