### ISSUE TITLE
For new `warp` command, landmark files for source and target are needed to verify functionality.

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#486]
Tests are already written and data is found in Testing/data/warp. The small ellipse is currently there along with three tests in Testing/ImageTests. The first test uses all landmark points and the second uses every third landmark. The results can be written directly by running the unit tests (only those tests can be run with the argument `--gtest_filter=ImageTests.warp*` passed to the `ImageTests` executable` and then checked and committed. 

It's all currently in the executable branch and it would be nice to fix those tests before merging with master, but this issue at least clarifies they aren't finished yet and what is needed for their completion. Note the code attempts to provide the same functionality as the original warp function @riddhishb added, but these results should be verified.

**Comment by cchriste** [comment]
Jadie provided some data and Archana and I have been looking into it.

**Comment by cchriste** [comment]
We have verified the new command works with the data we received. The results are the same as the results we received and it’s all been added to the unit test.

Technically this issue is complete, but we may want to provide some documentation as to how this input data is created. @jadie1 ?

**Comment by sheryjoe** [comment]
@jadie1 @riddhishb should we close this issue? documentation?

**Comment by jadie1** [comment]
We can close this. It works and the description makes sense. We don't have any additional documentation for the other image commands so I don't think we need to add any at this point.
