### ISSUE TITLE
ShapeWorksPost - modes of variation not generated from world coordinate space

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#49]
Please add estimation of procrustes transformation from local to world coordinates and apply to template mesh.
It may be useful to write out both template meshes - local mean and world mean

**Comment by cchriste** [comment]
This is a high priority according to Praful because for the upcoming meeting we want to use Post instead of View2 since it looks better in Post.

**Comment by cchriste** [comment]
#623 is to remove post from our repository. Closing this issue.
