### ISSUE TITLE
Add version to Project files, add warning to Studio when newer than current file is loaded

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#506]
facilitates updating old project files when things change

**Comment by akenmorris** [comment]
This is done, but I need to add a warning to the current Studio when it reads a project from a future version.  Something along the lines of "Warning, you are opening a project file from a newer version of ShapeWorks, some settings may not load correctly, etc"

**Comment by akenmorris** [comment]
Done in #524
