### ISSUE TITLE
add yes/no to run the next step for interactive python use cases

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#507]
This will help debug when something fails an hour into the tests by allowing the user to skip running earlier parts of the tests.

**Comment by cchriste** [comment]
There’s still an interactive mode. It just doesn’t allow you to skip the steps.

**Comment by sheryjoe** [comment]
If you skip steps, there should be safeguards to make sure that the input of a specific step is available for a previous run.

**Comment by jadie1** [comment]
As Shireen said, because the pipeline is supposed to be run sequentially there'd be a lot of cases and we'd need a lot of checks to see if a step can be skipped

**Comment by cchriste** [comment]
I respect that such checking would be correct.

In the meantime,  can you please create a draft version that doesn’t do this checking? This will help Archana and I do validate results and clearly identify which commands caused which changes (a slight variation on Shireen’s suggestion by email a couple days ago).

**Comment by jadie1** [comment]
Covered by issue #818
