### ISSUE TITLE
Studio: exporting reconstructed meshes 

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#511]
From Amy (amy.lenz@utah.edu)

When in Studio and visualizing the mode of variation results, I often export the mean and +/- 2SD surface meshes to perform post process visualization comparisons.  I found that using File->Export Surface Mesh, the .vtk file generated only contains the correspondence particle x,y,z locations for that mode of variation and not the reconstructed surface mesh itself.  The export gui says it is exporting as a .vtk, but then there is not a file extension that makes it recognizable as a .vtk file to common softwares.  So I just renamed it adding .vtk file extension but if you open that in a software such as CloudCompare, you'll just see the correspondence particles and not the mesh reconstruction.  I've attached two examples of the mean fibula file, with and without the .vtk extension.  Here is the same mean fibula surface reconstruction as exported by View2 in an old version that successfully exports with the .vtk file format as a mesh (Fibula_mean_smooth.vtk).  

[femur_vtk.zip](https://github.com/SCIInstitute/ShapeWorks/files/4703642/femur_vtk.zip)

**Comment by akenmorris** [comment]
Cloud Compare is choking on this part of the VTK file:

METADATA
INFORMATION 0

If I remove those two lines, it reads the rest of the file (the polygons).

I'm honestly not familiar with this block, it must be new in VTK 8
that we're now using in ShapeWorks.  I will see if I can configure the
writer to write an older version of the format for better
compatibility.

**Comment by akenmorris** [comment]
Completed in #543
