### ISSUE TITLE
Instructions for opening analyze file without running the full pipeline

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#512]
From Amy Lenz:

Can you provide instructions on how to re-visualize the analyze.xml after the initial correspondence model has been executed?  For example, it may take a while to run the model, successful results are achieved

**Comment by akenmorris** [comment]
Yes, agreed.  The Use cases should all end with a line saying something like:

To analyze the results again, run:

ShapeWorksStudio </path/to/xml>


-------------

And then we should document this elsewhere as well.
