### ISSUE TITLE
SW project file (spreadsheet) from previously trained model

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#514]
In case a user has results (groomed distance transforms and particle system) from an old version of ShapeWorks. Can we provide a way to visualize the shape model and groom data within our current Studio?

**Comment by akenmorris** [comment]
Yes, the new Studio still reads the old View2 style XML files with <point_files> and <distance_transform_files> tags.  You can then save these as XLSX if desired.

**Comment by sheryjoe** [comment]
Nice! Chris Butson has shape models (and groomed data) from an old ShapeWorks version (a couple of years ago). Let's see if Studio can load his old results.

**Comment by sheryjoe** [comment]
Should we close this issue? @akenmorris

**Comment by akenmorris** [comment]
Yes, Studio reads the old files.
