### ISSUE TITLE
Fix ellipse -> ellipsoid in Windows_README line 43

### ISSUE THREAD

**Issue by 0leks** [SCIInstitute/ShapeWorks#516]
It is line 43 of this file which I don't know how to edit: [https://raw.githubusercontent.com/SCIInstitute/ShapeWorks/master/Documentation/install/Windows_README.txt](https://raw.githubusercontent.com/SCIInstitute/ShapeWorks/master/Documentation/install/Windows_README.txt)

**Comment by akenmorris** [comment]
You can edit and create a PR

**Comment by akenmorris** [comment]
Done.

**Comment by 0leks** [comment]
Oops I just realized that its in the Doc/install folder. I got thrown off by the githubusercontent thing for some reason
