### ISSUE TITLE
Add MACRO to declare shapeworks subcommand

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#517]
[executable branch]

I'm not a huge fan of macros. But looking at Commands.h it seems that nearly every class definition is the exactly same. Let’s add a macro that lets us do:
NEW_SHAPEWORKS_COMMAND(Image, Threshold)
NEW_SHAPEWORKS_COMMAND(Mesh, CloseHoles)
 ...etc.

(Karthik suggested this and I modified his suggestion slightly to try to declare a macro that includes the command type and class name as its two arguments.)

**Comment by archanasri** [comment]
Done.
