### ISSUE TITLE
Organize Documentation and update GettingStarted 

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#530]
- should be the top level for SSM workflow
- should introduce the three phases with links to their md
- should be in the documentation folder
- fix the link in the readme
- link to use cases

**Comment by sheryjoe** [comment]
Shireen to take the first crack on the getting started.

**Comment by akenmorris** [comment]
Images is already capitalized:

https://github.com/SCIInstitute/ShapeWorks/tree/master/Images

I don't think there is an 'install' folder.  Maybe inside dependencies from build_dependencies.sh?

**Comment by sheryjoe** [comment]
I was referring to Documentation/images and Documentation/install (which is now capitalized).

**Comment by sheryjoe** [comment]
This has been addressed in the org-doc branch. To be merged soon.
