### ISSUE TITLE
Adding batch process mode to the FindreferenceImage function

### ISSUE THREAD

**Issue by AtefehKashani** [SCIInstitute/ShapeWorks#532]

**Comment by akenmorris** [comment]
This issue is just adding it to the Changelog, right?

**Comment by sheryjoe** [comment]
This is about loading and processing samples in chunks (batches) rather than one sample at a time to reduce IO time.

**Comment by AtefehKashani** [comment]
I have tested different strategies to decrease the IO time. For the FindReferenceImage function, since we need to handle different size images for padding, loading in batch will not decrease the running time and will be O(n). So in my opinion the current implementation is good enough to handle this.

**Comment by akenmorris** [comment]
Is it that you would like to overlap IO with computation (e.g. load the next batch in another thread)?  Or do each pair in a multithreaded fashion?

In either case, I think this functionality should be implemented in C++ rather than Python.

**Comment by sheryjoe** [comment]
Agreed.
