### ISSUE TITLE
RunUseCase mesh/image mode

### ISSUE THREAD

**Issue by 0leks** [SCIInstitute/ShapeWorks#534]

**Comment by sheryjoe** [comment]
The use case should be detect whether to use <data>/meshes or the isosurface of distance transforms from groomed <data>/segmentations

**Comment by akenmorris** [comment]
I was suggesting that we provide both paths for each example

**Comment by sheryjoe** [comment]
Agreed.

**Comment by sheryjoe** [comment]
> > The use case should be detect whether to use /meshes or the isosurface of distance transforms from groomed /segmentations
> 
> What do you mean? The isosurface should be extracted by `shapeworks optimize` when running on distance transform data but is configured to mesh mode?

Extracting meshes and maybe decimating them using PreviewCmd can be a grooming step. shapeworks optimize will work on extracted meshes in this case.

**Comment by sheryjoe** [comment]
let's consider this when we restructure running use cases with native python apis.
