### ISSUE TITLE
Documentation PDFs

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#536]
Documentation/PDFs contain documentation for old shell scripts and stand alone commands. These should be replaced incrementally with md-based documentation and updated based on ShapeWorks consolidated commands and python use cases and APIs. Update doc strings in python use cases that refer to these pdfs.

**Comment by iyerkrithika21** [comment]
Summary: all pdfs are outdated. We can delete this folder


PDF Topic | Contents | Comments
-- | -- | --
AlgnmentTools.pdf | 1. Center of mass alignment2. Rigid ICP based image registration3. Rigid ICP based mesh registration | This document can be deleted as we have the commands consolidated.
BinaryToDTFemurs.pdf | Complete pipeline for femur from segmentation use case | This document can be deleted as we have the details in : http://sciinstitute.github.io/ShapeWorks/use-cases/mesh-based/femur.html
FIDS-Theory.pdf | Face index map generation:1. KD-tree2. Potential problems3. choosing the search diameter4. barycentric distance | This doesn’t seem related to ShapeWorks
ImagePrepTools.pdf | Image grooming commands:1. Isotropic resampling2. Padding3. Find largest bounding box and cropping4. Threshold images5. Topology preserving smoothing | This document can be deleted as we have the commands consolidated.
MeshToDTFemurs.pdf | Complete pipeline for femur from meshes. | This document can be deleted as we have the details in : http://sciinstitute.github.io/ShapeWorks/use-cases/mesh-based/femur-mesh.html
ParameterDescription.pdf | Parameter description for optimization | This document can be deleted as we have the details in : http://sciinstitute.github.io/ShapeWorks/workflow/optimize.html
ScriptUsage.pdf | How the bash script can be used for:1, Single scale optimization2. Multi scale optimization | This document can be deleted as we have included the single scale and multi scale options in the xml file and studio
ShapeWorksPost.pdf | 1. How to build shapeworkspost2. How to visualize the models | This document can be deleted as shapeworkspost has been depreciated
SWBackground.pdf | Introduction to particle based shape correspondence1. What is a PDM?2. Correspondence optimization3. Shape modeling pipeline – preprocessing,alignment,correspondence initialization,optimization, visualization | This document can be deleted as we have the details in : http://sciinstitute.github.io/ShapeWorks/getting-started/shapes.html

**Comment by sheryjoe** [comment]
@iyerkrithika21 let's delete it then.

**Comment by iyerkrithika21** [comment]
@akenmorris can you remove the files directly or do we need a PR?
