### ISSUE TITLE
Clarify size paramter meaning for tools

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#542]
Tools such as rasterization use origin, size, and shape inputs. We should clarify to the user what is expected from these. 

Here is feedback from Allen Sanderson: 
When I read size I think measurement, as in the bounding box size (physical units), especially because the other two inputs are in physical units. However, what is wanted the number of rows, cols, slices in the resulting image. So there is a clarity issue.
I think because the other inputs are physical units it would be better to have one supply everything in physical units. It could be either relative:
origin_x, origin_y, origin_z
size_x, size_y, size_z
absolute:
min_x, min_y, min_z
max_x, max_y, max_z

**Comment by jadie1** [comment]
In addition, for the rasterization tool,  we should test and document if the output distance transform can be larger than the mesh. If it can then the user has the ability to subsample a specific area of the mesh which is a nice feature

**Comment by cchriste** [comment]
Thank you, Jadie. Can you please provide concrete examples? And it would be especially helpful for some of these examples to describe such ambiguities in the new api (executable branch). Thanks!

**Comment by jadie1** [comment]
The tool Allen was referring too is: GenerateBinaryAndDTImagesFromMeshes 
I believe that is the same in the master and executable branch currently.
I know that WriteImageInfoToText writes files for origin, size, and spacing. I'm not sure if anything else uses those values

**Comment by sheryjoe** [comment]
@archanasri is this still an issue?

**Comment by archanasri** [comment]
@sheryjoe nope, closing it.
