### ISSUE TITLE
Improve use case tiny tests

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#549]
Improve and note runtime for all use case tiny tests for next release after 5.4

**Comment by sheryjoe** [comment]
Has to be addressed so that we can merge the executable branch @AtefehKashani @cchriste @archanasri

**Comment by AtefehKashani** [comment]
addressed in PL #587

**Comment by sheryjoe** [comment]
@AtefehKashani I am running the left atrium with  --tiny_test and redirecting console output to a log file. It seems that it starts with particle optimization then grooming is done at the end. attached is the log. Any idea what is going on here?
[left_atrium_log.txt](https://github.com/SCIInstitute/ShapeWorks/files/4808417/left_atrium_log.txt)


branch: exec-auto-doc (up to date with master after resolving conflicts)

**Comment by sheryjoe** [comment]
@AtefehKashani  And it also takes some time (may be 10 mins) before printing anything to the console.

**Comment by sheryjoe** [comment]
@AtefehKashani and getting the below error when running --tiny_test with --start_with_image_and_segmentation_data

TypeError: applyCropping() got an unexpected keyword argument 'processRaw'

branch: exec-auto-doc (up to date with master after resolving conflicts)

**Comment by AtefehKashani** [comment]
> exec-auto-doc

There is nothing to do with the tiny test. The use case is not reflected the changes in the GroomUtils in this branch. You will get the same error for the other use cases as well with/out tiny test when start_with_image_and_segmentation_data is on.

**Comment by AtefehKashani** [comment]
> @AtefehKashani I am running the left atrium with --tiny_test and redirecting console output to a log file. It seems that it starts with particle optimization then grooming is done at the end. attached is the log. Any idea what is going on here?
> [left_atrium_log.txt](https://github.com/SCIInstitute/ShapeWorks/files/4808417/left_atrium_log.txt)
> 
> branch: exec-auto-doc (up to date with master after resolving conflicts)

I'm not sure what is happening on your end. Since the optimization can't be run without distance transforms, It first runs the grooming and then the optimization. I guess there is something wrong with printing in the console output.
 I reran the tiny test and it ran in couple of minutes. It started to write out in the console immediately (without 10 mins delay that you mentioned), and also in the order of the pipeline.

**Comment by sheryjoe** [comment]
> > exec-auto-doc
> 
> There is nothing to do with the tiny test. The use case is not reflected the changes in the GroomUtils in this branch. You will get the same error for the other use cases as well with/out tiny test when start_with_image_and_segmentation_data is on.

What changes in GroomUtils? Is there another branch (other than master) that has a fixed GroomUtils?

**Comment by cchriste** [comment]
> What changes in GroomUtils? Is there another branch (other than master) that has a fixed GroomUtils?

We have the same question, and suspected some of the data on girder had recently changed (side question: what if the data is updated but my machine has already downloaded a version? Will the test know to download a fresh version?). 

Just to make sure everything is up to date, I just merged everything from master down to executable and executable_improv (our work branch) into the exec-auto-doc branch and pushed. The only changes not already in there were a pull request related to particle systems and some whitespace. The push will trigger new GitHub actions.

**Comment by cchriste** [comment]
> We suspected some of the data on girder had recently changed (side question: what if the data is updated but my machine has already downloaded a version? Will the test know to download a fresh version?).

side-side question (probably for @0leks): what if the version of the executable trying to run a test uses an old version of the data? Will it know which dataset to download?

**Comment by jadie1** [comment]
Completed in PR #587

**Comment by 0leks** [comment]
> > We suspected some of the data on girder had recently changed (side question: what if the data is updated but my machine has already downloaded a version? Will the test know to download a fresh version?).
> 
> side-side question (probably for @0leks): what if the version of the executable trying to run a test uses an old version of the data? Will it know which dataset to download?

It'll download the version based on the version of DataSetUtils they have installed. So far there are 3 different data stores (UseCaseCollection, use-case-data-v0, use-case-data-v1)
UseCaseCollection and use-case-data-v0 are frozen so that old versions will still run fine.
use-case-data-v1 is getting updated with (hopefully non-breaking) changes to the data.
