### ISSUE TITLE
Create ShapeWorks user documentation (in gh-pages branch)

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#55]
Related to #46, but in this case we are using a separate branch called **gh-pages** so that anyone can update the user documentation at any time without requiring a pull request to master branch.

The gh-pages branch now exists and the documentation is currently built using the Markdown files _in that branch_ interpreted by Jekyll. It can be viewed from http://sciinstitute.github.io/ShapeWorks/, which should be pointed to in the main README.md in master. 

This documentation should be included in the downloadable user deployments, and when we attain a dedicated ShapeWorks domain name it can be hosted there instead. The current Jekyll-based production of this content is not mandatory, and this branch can and should be used for our main website. But at this time the Jekyll interpretation of Markdown files is functional and simple enough for anyone to contribute.

**Comment by sheryjoe** [comment]
@riddhishb @icleen It is worth to checkout MkDocs ...

**Comment by cchriste** [comment]
We're almost there. The remaining part of this issue is to include the docs with the distribution. Currently one would need to go back to the GitHub page and that might mean a mismatch between the downloaded distribution and the documentation seen by the user. 

Is it only possible to use `mkdocs serve` or can the static version of the documentation be included in the downloadable deployment?

**Comment by akenmorris** [comment]
If we generate static docs, they can be included.  We are including the other documentation including the generated docs from the scripts.

**Comment by sheryjoe** [comment]
`mkdocs serve` and `mkdocs build` (preferred) will generate static docs locally in the `site` folder (which is the content of gh-pages branch). This can be copied as part of the packaging to the released distribution.

**Comment by sheryjoe** [comment]
@akenmorris, may be this is already done.  Could we copy the mkdocs build site folder as part of the packaging scripts?

**Comment by akenmorris** [comment]
Sure.  How is that done?

**Comment by sheryjoe** [comment]
Oh, may be I have done it already. See lines 48-50 in package.sh - I think I did the same for the windows package script. Could you please test these?

**Comment by akenmorris** [comment]
I see, yep.  I will check that the deployables have the docs.

**Comment by akenmorris** [comment]
Ok, they are there.  However, there is a problem.  The links on the left side go to directory names, e.g. Documentation/getting-started/examples.

This works fine with a webserver that is configured to look for examples/index.html, however web browsers do no appear to do this when reading from the filesystem.  I just get a directory contents when I click on any link on the left.  I can then click on "index.html"  and I get to where I was trying to go.

**Comment by sheryjoe** [comment]
seems there is a fix based on the below. I am adding it now and please test (#746) it on your side @akenmorris 

https://github.com/mkdocs/mkdocs/issues/1498

**Comment by sheryjoe** [comment]
@akenmorris i think this is resolved already. can we close this issue?

**Comment by akenmorris** [comment]
Confirmed, the deployments have usable documentation.
