### ISSUE TITLE
Python use case for DeepSSM

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#551]
Add complete functional use case to demonstrate DeepSSM.
- Update RunUseCase.py to include it
- Add deep_ssm.py (use case code)
- Add DataAugmentUtils.py (python code for data augmentation)
- Add DeepSSMUtils.py (python code for DeepSSM)
- Add documentation 

For next release after 5.4

**Comment by sheryjoe** [comment]
- TL network for fine-tuning
