### ISSUE TITLE
Update ChangeLog for Release 5.4

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#555]
@akenmorris @AtefehKashani @jadie1 @0leks : please make sure that the changelog includes new/upgraded/fixed features that are included in Release 5.4 (compared to the previous release).

**Comment by akenmorris** [comment]
This is what we have so far.  Is there anything else?

https://github.com/SCIInstitute/ShapeWorks/blob/master/ChangeLog

ShapeWorks 5.4.0 - 2020-05-27
	* Studio: New XLSX based file format.  See Examples/Studio/ellipsoid.xlsx for an example
	* Studio: Improved scalability.  Files now loaded on-demand as necessary.
	* Lower memory footprint and faster optimization: ShapeWorks is now using [OpenVDB](https://www.openvdb.org/), a more memory-efficient data structure, for signed distance transforms. Along with other refactoring and code optimizations, ShapeWorks now uses *85% less memory* (from 57.09GB to 9.67GB in one use case). Additionally, the particles optimizer is now *2X faster*.
	* Lower memory footprint for estimating correspondences for new shapes on existing shape models: For <fixed_domains> usage, only distance transforms for the new shapes will be loaded. 
	* Lower memory footprint for finding the reference image for the rigid alignment.
	* Lower memory footprint and running time for finding representative subset samples of data.

**Comment by sheryjoe** [comment]
Please include the below too: (and add the links accordingly). 

* Documentation: New [Getting started](link?) documentation that goes over shape modeling workflow documentation, different ShapeWorks interfaces with a video illustration for Studio.
* Documentation: Better documentation for the [RunUseCase](doc link) input arguments.
* Documentation: Added [instructions] on how to load a pre-trained shape model without running the full pipeline. 
* @0leks : About dataset portal?
* Studio: Exporting reconstructed meshes? @akenmorris

**Comment by sheryjoe** [comment]
Question: why don't we use md for the changelog?

**Comment by akenmorris** [comment]
I don't know.  I guess it's just traditional.  Emacs even has a ChangeLog mode (when the filename is ChangeLog).

I don't mind if we switch.  Anyone else?  @cchriste

**Comment by sheryjoe** [comment]
We can keep it. It is just not user friendly when it comes to links.

**Comment by akenmorris** [comment]
Let’s make it MD

**Comment by cchriste** [comment]
It's not user friendly, but imo it lets us provide developer level details
that we might otherwise oversimplify.
Users have documentation. :-)

**Comment by cchriste** [comment]
Cool. I love Markdown!

**Comment by sheryjoe** [comment]
Done.
