### ISSUE TITLE
shapeworks optimize <project-file> subcommand

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#567]
- [ ] A shapeworks subcommand that will enable users to run the optimization given a project file.
- [ ] Update use cases to use the shapeworks subcommand

**Comment by sheryjoe** [comment]
@akenmorris where are we on this?

**Comment by akenmorris** [comment]
I haven't started on it yet.  One question, are we removing ShapeWorksRun?  Or are we keeping it as duplicate functionality?

**Comment by sheryjoe** [comment]
This should replace ShapeWorksRun.

**Comment by akenmorris** [comment]
Completed in #711
