### ISSUE TITLE
Optimizing particles directly on meshes

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#570]
This issue includes relevant tasks/issues for mesh-based shapeworks (Oleks' graduation project).
- [x] Mesh-based data structure 
- [x] particle optimization and geodesic walks
- [x] automated tests

**Comment by sheryjoe** [comment]
How about open meshes?

**Comment by medakk** [comment]
@sheryjoe There is already a [test for open meshes](https://github.com/SCIInstitute/ShapeWorks/blob/d2285e8473cfcaec26caa55a3163780bdab27f8c/Testing/OptimizeTests/OptimizeTests.cpp#L83) with "hemisphere". Can this issue be considered resolved, or do we need more tests? (lumps, femur)
