### ISSUE TITLE
Optimize particles on n-D contours

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#571]
This entails implementing a ContourDomain with necessary APIs to interact with the optimizer.

**Comment by akenmorris** [comment]
What is N in this case?  2 and 3?

**Comment by sheryjoe** [comment]
Yes. The dimensionality of the particle.

**Comment by akenmorris** [comment]
Yes, but I’m asking what dimensionality we plan to support. Shapeworks has templates for dimension but realistically only supports 3D.

**Comment by sheryjoe** [comment]
If we don't want to deal with templates, we can support 3D natively and 2D could be handled as 3D with the z-coord being fixed to 1 (or 0).

**Comment by akenmorris** [comment]
That’s what I’ve done in the past. There is a lot beyond even beyond the templates that makes a lot of assumptions. The particle files for example.

**Comment by medakk** [comment]
#1165 assumes contour are 3D. The user must provide contour files where each vertex has 3 dimensions. Filling z with 0s is a grooming step

**Comment by sheryjoe** [comment]
@medakk @akenmorris can this be done in the optimizer when loading contours? if 2d, z-dim is filled by zeros. I think this is too simple to be a grooming step.

**Comment by medakk** [comment]
> I think this is too simple to be a grooming step.

If its a simple grooming step to do, should it not be done as a grooming step?

The end result will always be a 3D shape model, and I prefer the expectation that the user provides a 3D shape and obtains a 3D result. (as opposed to providing a 2D shape and obtaining a 3D shape model)

**Comment by sheryjoe** [comment]
> > I think this is too simple to be a grooming step.
> 
> If its a simple grooming step to do, should it not be done as a grooming step?
> 
> The end result will always be a 3D shape model, and I prefer the expectation that the user provides a 3D shape and obtains a 3D result. (as opposed to providing a 2D shape and obtaining a 3D shape model)

If it is built-in in the optimizer, the output could also be set to 2d by dropping the z-dim. though, i agree that it would be more transparent if set the expectations to be 3d and rely on groom and analyze steps to convert 2d->3d input and 3d>2d output. @akenmorris thoughts?

**Comment by akenmorris** [comment]
Don’t we need 3D contours anyway?

It’d be easy to add a z=0 if it’s not provided and I guess drop it off in the output?  But then we have the problem that all of the analysis tools are expecting 3D. I think the output will have to be 3D anyway. 

Does VTK support 2D?  We may be limited by file formats anyway

**Comment by medakk** [comment]
[vtkPoint](https://vtk.org/doc/nightly/html/classvtkPoints.html) is always 3D
![image](https://user-images.githubusercontent.com/10536745/111933157-82d14100-8a84-11eb-989b-dbd03950e3f2.png)

>  But then we have the problem that all of the analysis tools are expecting 3D
Yes, the analysis tools would break

**Comment by sheryjoe** [comment]
To avoid breaking analysis tools, we can have 2d->3d as a grooming step and the optimizer output 3d (with z dim = 0). We can add documentation (and inline help/tooltips) about supporting 3d contours and using this grooming step to work on 2d contours. We can also add to studio exporting 2d contours, which drops the z dim.

**Comment by medakk** [comment]
As per today's meeting:

* we will document that contour domain only works with 3D input. The user must add an extra dimension if necessary
* we will revisit this once we have a 2D use case. (it'd be a fair amount of work to ensure that the particle reader, analysis tools etc work with 2D)
