### ISSUE TITLE
Visualize shape models for contours

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#573]
Visualize mean and pca modes for a contour model in Studio.

**Comment by sheryjoe** [comment]
I am pushing this back to the 5.6 release to aligned with @medakk work on adding the contour domain.

**Comment by medakk** [comment]
No work was needed for this. Since the result is an array of particles, it works out of the box in Studio. I assume handling display of contours/reconstruction pertains to #578

**Comment by sheryjoe** [comment]
@medakk we need to reconstruct the mean contour and deform it along pca modes.

**Comment by medakk** [comment]
I see. The current PR doesn't handle this. I'll unlink this issue

**Comment by sheryjoe** [comment]
@riddhishb can you check this issue out for 6.1? we can choose the template contour to be the contour of the median shape (similar to meshes) and use TPS warping (in vtk or itk).

**Comment by akenmorris** [comment]
This works, we have a use case demonstrating.
