### ISSUE TITLE
Build geodesic-based RBFs for free-form constraints

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#575]
Building geodesic-based RBFs for free-form constraints which entails:
(a) a point selection strategy to compute geodesics to a subset of surface point, this selection could be quasi-random that assures covering the full surface.
(b) computing geodesics to contours on the surface, TriMesh/MeshFIM classes have this functionality. It might need some refactoring/cleaning up and testing.
(c) implementing and testing the free form constraint as a child class of the Constraint class

**Comment by akenmorris** [comment]
Typo in commit message accidentally closed this.

**Comment by akenmorris** [comment]
Will not implement
