### ISSUE TITLE
Brush and lasso interfaces within Studio for user-defined constraints

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#576]
The brush and lasso interfaces within Studio to provide [*]
(1) a surface mesh with labeled vertices whether in or out the constraint and
(2) constraint boundary (polyline, i.e., ordered points on the surface)
*vtk filters could be used to provide (1) and (2) for lasso and brush interfaces.

**Comment by akenmorris** [comment]
Completed and merged.
