### ISSUE TITLE
Studio: Optimize particles on contours

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#578]
Exposing optimizing particles with life updates on n-D contours in Studio. Related to #571

**Comment by medakk** [comment]
Python implementation is here: https://github.com/sheryjoe/ContourWorks/tree/PythonVersion/Python

**Comment by sheryjoe** [comment]
@akenmorris why is this issue not feasible for 6.1?

**Comment by sheryjoe** [comment]
We have to add grooming steps for contours.

**Comment by akenmorris** [comment]
Works, you can open the resulting spreadsheet from supershapes_1mode_contour and optimize inside Studio
