### ISSUE TITLE
Finalize consolidation for segmentation-based grooming subcommands

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#583]
Most of these might have been done already. This issue is to make sure that we finalize the consolidation efforts for image subcommands. **The deadline to close this issue is July 7th for NIH reporting purposes.**

- image subcommands
- documentation
- document fixed bugs / differences with standalone tools
- update python use cases to use consolidated commands
- unit tests
- merge executable branch (which include other SW members to review and test)

**Comment by archanasri** [comment]
Done with commit e0bcb6b3df1b2c32fbfed61bb31f9f678e4f279c
