### ISSUE TITLE
handle use case data updates

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#595]
> We suspected some of the data on girder had recently changed (side question: what if the data is updated but my machine has already downloaded a version? Will the test know to download a fresh version?).

side-side question (probably for @0leks): what if the version of the executable trying to run a test uses an old version of the data? Will it know which dataset to download?

_Originally posted by @cchriste in https://github.com/SCIInstitute/ShapeWorks/issues/549#issuecomment-647217234_

**Comment by 0leks** [comment]
Currently you have to delete your local dataset .zip file in order for it to download new version.

**Comment by 0leks** [comment]
The version of dataset that will be downloaded is dependent on the version of DatasetUtils installed. At the top of GirderConnector there is a variable that is set to use-case-data-v0 or use-case-data-v1. Old versions of the code will download from the old dataset collection.

**Comment by cchriste** [comment]
> The version of dataset that will be downloaded is dependent on the version of DatasetUtils installed. At the top of GirderConnector there is a variable that is set to use-case-data-v0 or use-case-data-v1. Old versions of the code will download from the old dataset collection.

This seems insufficient. The use case and the girder version are independent.

**Comment by cchriste** [comment]
Related to #608

**Comment by sheryjoe** [comment]
Closing this as we move to a better domain modeling with Girder 4.
