### ISSUE TITLE
add tests for Particle System shapeworks subcommands

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#602]
The following commands need to have tests in Testing/shapeworksTests:
- read-particle-system
- compactness
- generalization
- specificity

**Comment by medakk** [comment]
The operations themselves have tests: https://github.com/SCIInstitute/ShapeWorks/blob/bdd3a84170d06ac668890cb4f1671217c4431a4e/Testing/ParticlesTests/ParticlesTests.cpp

Is this issue about tests for commands that call these operations?

**Comment by sheryjoe** [comment]
@cchriste ?

**Comment by medakk** [comment]
Add a shell script here for particles tests: https://github.com/SCIInstitute/ShapeWorks/tree/master/Testing/shapeworksTests

and a file in Testing/data/shapeworks/ to diff against
