### ISSUE TITLE
add tests for Mesh to both MeshTests and shapeworks subcommands

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#603]
The following Mesh commands need to have tests in Testing/shapeworksTests:
- read-mesh
- write-mesh
- coverage

Mesh read and write unit tests need to be added to MeshTests.

**Comment by sheryjoe** [comment]
@cchriste @archanasri still an issue?

**Comment by archanasri** [comment]
There are shapeworksTests for readmesh, writemesh and coverage so yes it can be closed.
