### ISSUE TITLE
treat use case input data as read only

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#608]
The use cases always unzip the downloaded data and then add/modify data from these directories. 
- It would be cleaner in general to treat downloaded data as read only (and not unreasonable for it to be so).
- The time required to extract the zip files would be saved on successive runs of the tests.

**Comment by cchriste** [comment]
Related to #595

**Comment by AtefehKashani** [comment]
I have changed the permission of LA data and re-upload them.  It is ready to review.

**Comment by sheryjoe** [comment]
@jadie1 is n't that resolved by the new use case structure? Examples/Data and Examples/Output? should we close this? @cchriste

**Comment by jadie1** [comment]
Yes I think we can close this
