### ISSUE TITLE
Add all use cases to unit tests

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#611]
1. Move them from PythonTests to UseCaseTests
2. Add all use cases using tiny_test
3. Add a flag to optionally execute them

**Comment by sheryjoe** [comment]
Related to #423

**Comment by cchriste** [comment]
I think we just need to add these to GitHub actions. @akenmorris ?

**Comment by akenmorris** [comment]
We can now that we have the partial download for all of them.

**Comment by sheryjoe** [comment]
@akenmorris is this feasible for 6.1?

**Comment by akenmorris** [comment]
@sheryjoe , yes it's almost done, see #1254 .  It's not really a 6.1 issue though as the automated tests are not part of the user download.

**Comment by akenmorris** [comment]
Done.
