### ISSUE TITLE
fix ellipsoid.zip on girder

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#612]
<img width="882" alt="Screen Shot 2020-06-29 at 5 23 58 PM" src="https://user-images.githubusercontent.com/1260945/86066594-d485f700-ba2f-11ea-8154-301c7fa6261d.png">
(the picture says it all)
The images directory looks similar.

**Comment by 0leks** [comment]
How did you get to that state? Did you delete ellipsoid.zip and run the ellipsoid use case?

**Comment by cchriste** [comment]
Yes. (only realized later that ellipsoid.zip is actually part of the repo)

**Comment by 0leks** [comment]
Is there anything inside of the seg.ellipsoid_*.nrrd (1) folders?

**Comment by cchriste** [comment]
yes.

**Comment by 0leks** [comment]
What's inside of the seg.ellipsoid_*.nrrd (1) folders?

**Comment by cchriste** [comment]
The images and segmentations have different things, mostly copies of the same images. You can delete the .zip file and run ellipsoid tiny test and it will download it for you.

**Comment by 0leks** [comment]
Yeah I tried that and it worked fine, not seeing the issue you are. Is this a reproducible issue? If you delete your ellipsoid folder and the ellipsoid.zip does it happen again?

**Comment by cchriste** [comment]
Yup.

**Comment by cchriste** [comment]
And the one that's downloaded is 2.2M while the one in the repo is only 1.5M.

**Comment by 0leks** [comment]
Woah thats pretty crazy.
I noticed that your folder structure is Python/ellipsoid
Normally it is Python/TestEllipsoids/ellipsoid
Is there a reason for this difference?

**Comment by cchriste** [comment]
Yes. I just manually unzipped the ellipsoid.zip file after it was downloaded. If I let it run and put it all in the place the same junk is there.

**Comment by sheryjoe** [comment]
<img width="319" alt="image" src="https://user-images.githubusercontent.com/3253036/86161236-32ffb380-baca-11ea-8b13-15610d1475cf.png">

ellispoid does not have images so no need to copy seg files in the images folder.

**Comment by sheryjoe** [comment]
Adding some version control on girder data to avoid not downloading new versions in case users have already downloaded an older version (previous release for example).

**Comment by sheryjoe** [comment]
I assume this has been resolved with -vN versioning.
