### ISSUE TITLE
binpath for RunUseCase.py overrides use path

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#613]
If user explicitly specifies shapeworks_path, use it. Otherwise, let their current path come before any defaults.

**Comment by sheryjoe** [comment]
Related to #478?

**Comment by cchriste** [comment]
I'm going to make an argument the other direction: our script should use whatever is deemed the default locations for binaries. All this means for developers is they'll always have to provide the path to their ShapeWorks bin directory. 
Closing.
