### ISSUE TITLE
for OSX, add ability to execute ShapeWorksStudio from terminal when shapeworks' bin is in PATH

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#615]
OSX creates app bundles for executables, so the path to ShapeWorksStudio is actually $SHAPEWORKS_BIN/ShapeWorksStudio.app/Contents/MacOS. The user can explicitly add both to their own path, but it would be nice to only need SHAPEWORKS_BIN rather than always setting path to include both locations (especially for people with multiple build trees). 

Perhaps an executable shell script in $SHAPEWORKS_BIN?

**Comment by sheryjoe** [comment]
This is related to #478

**Comment by akenmorris** [comment]
How about a symlink?

**Comment by sheryjoe** [comment]
@akenmorris @cchriste what is the status of this issue?

**Comment by akenmorris** [comment]
@sheryjoe https://github.com/SCIInstitute/ShapeWorks/pull/967

**Comment by cchriste** [comment]
No script in result of GitHub action for this pull request, and cannot test locally due to broken make install (#953).

**Comment by akenmorris** [comment]
Completed.
