### ISSUE TITLE
Bad way to find OpenVDB

### ISSUE THREAD

**Issue by 0leks** [SCIInstitute/ShapeWorks#616]
[Line 31 of root CMakeLists.txt](https://github.com/SCIInstitute/ShapeWorks/blob/master/CMakeLists.txt#L31) assumes that CMAKE_PREFIX_PATH only has one directory and it is the dependencies directory.

```
if (NOT DEFINED OpenVDB_DIR OR "${OpenVDB_DIR}" STREQUAL "OpenVDB_DIR-NOTFOUND")
  set(OpenVDB_DIR ${CMAKE_PREFIX_PATH}/lib/cmake/OpenVDB)
endif()
```

**Comment by sheryjoe** [comment]
May be related. FindOpenVDB can't be found if -DCMAKE_PREFIX_PATH is given a relative path for dependencies. It works only for absolute paths.

**Comment by sheryjoe** [comment]
@medakk @akenmorris is this resolved already?

**Comment by medakk** [comment]
No, still haven't found a better way to do it.

**Comment by sheryjoe** [comment]
@medakk any update on this issue?

**Comment by medakk** [comment]
Looks like it was fixed by @akenmorris at some point. Closing
