### ISSUE TITLE
Add help (function) to Python API for Image tools 

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#618]
python offers help(function) which shows the arguments and some description of any given function.
Does pybind have some way to generate this for people to use?

**Comment by cchriste** [comment]
I think this automatically uses the `## description` that precedes a Python function. 
Or does it require the function to be exposed from `__init__.py`?
Test this, and add these to all our Python functions.

**Comment by archanasri** [comment]
E.g:
help(Image.antialias)

Help on instance method in module shapeworks:

antialias(...)
    antialias(self: shapeworks.Image, iterations: int = 50, maxRMSErr: float = 0.009999999776482582, layers: int = 0) -> shapeworks.Image
    
    antialiases binary volumes

**Comment by archanasri** [comment]
Done with commit d19da6f43e3999fd38a3bfd0ec19a543ee34007e
