### ISSUE TITLE
ShapeWorksStudio (and probably commandline) don't support image orientations besides RAI

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#62]
SetImage in itkPSMImageDomain.h currently finds the coordinates of the start and end of the image and assumes these are the lower and upper bounds.  These are then used in many other places in the code.  These values are only correct for RAI orientation.  When an alternate orientation image is used, such as LPI, the values can be inverted and various checks will fail eventually causing a crash.

An example LPI file:

[Segmentation_1.nrrd.zip](https://github.com/SCIInstitute/ShapeWorks/files/3465710/Segmentation_1.nrrd.zip)

**Comment by akenmorris** [comment]
ShapeWorksStudio is now supporting non-RAI

**Comment by cchriste** [comment]
Is there something we can add to the command line / Image / Python api for this?

**Comment by akenmorris** [comment]
itk::OrientImageFilter

I'm just not sure if where this should happen for libImage.

**Comment by akenmorris** [comment]
I'm wondering if we should just add this to the Image class file I/O:

```
  // set orientation to RAI
  using Orienter = itk::OrientImageFilter<ImageType, ImageType>;
  Orienter::Pointer orienter = Orienter::New();
  orienter->UseImageDirectionOn();
  orienter->SetDesiredCoordinateOrientation(
    itk::SpatialOrientation::ITK_COORDINATE_ORIENTATION_RAI);
  orienter->SetInput(image.getITKImage());
  orienter->Update();
  image = Image(orienter->GetOutput());
```

Or it could check the orientation first.

The issue is that images in other orientation basically don't work for almost all operations (e.g. even centering).  Nawazish was running into this today.

**Comment by akenmorris** [comment]
See #1466

**Comment by cchriste** [comment]
> I'm wondering if we should just add this to the Image class file I/O:

From the description of the filter, it may reorder data, but there shouldn't be any resampling, which is the only concern. The most conservative solution would be to only change the orientation (as in the example above) if it's not already correct. But it will probably be fine if we just do it all the time.

https://itk.org/Doxygen/html/classitk_1_1OrientImageFilter.html#a48974f74c5d40539fead341a90ba5f49

**Comment by akenmorris** [comment]
Correct, it only permutes the axes.  I will write it such that it checks the current orientation and only applies the filter if necessary.
