### ISSUE TITLE
Use Case demonstrating data augmentation methods

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#624]
We need a use case showing shape driven as well as shape and image driven datat augmentation with different sampling methods.

**Comment by jadie1** [comment]
This use case will demonstrate the different embedding and sampling choices for data augmentation. The goal is to provide the user with an example of how to decide the best data augmentation method for a given data set. It will require visualization techniques described in issue [687](https://github.com/SCIInstitute/ShapeWorks/issues/687)

**Comment by sheryjoe** [comment]
Related to #737

**Comment by jadie1** [comment]
We decided this would be better demonstrated in a notebook rather than as a use case. The DeepSSM use case provides an example of using data augmentation for a subsequent task. The notebook will demonstrate the effect of using different sampling distributions.
