### ISSUE TITLE
Allow Shapeworks to write Procrustes transformation files

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#626]
Is there a way to expose transformations caused by procrustes in optimization? We'd like to have the rotation, translation, and scale matrix in addition to the world and local particles.

**Comment by sheryjoe** [comment]
When we write world and local, we should be able to also write a plain text file for each sample that has the transformation parameters.

**Comment by sheryjoe** [comment]
This is also related to feeding pre-alignment from grooming.
