### ISSUE TITLE
Update Evaluation use case to use Studio rather than View2

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#628]

**Comment by sheryjoe** [comment]
@medakk @akenmorris is this resolved already?

**Comment by medakk** [comment]
What is this?

**Comment by akenmorris** [comment]
I don’t think anything uses view2.  I don’t know what the “evaluation” use case is.

**Comment by sheryjoe** [comment]
This is Examples/Python/ellipse_evaluate.py 

BTW, it should be ellipsoid !

**Comment by akenmorris** [comment]
Ok, I get it.  It does use View2!
