### ISSUE TITLE
Create virtual MeshType class containing vtkPolyData, vxl, and others

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#629]
- Keeps Mesh class concrete, enabling chained calls like Image.
- enables use of different types of meshes
- probably exists already as described by Oleks in his project defense

**Comment by 0leks** [comment]
Yeah this currently exists in the form of MeshWrapper in the Optimize library.
The public API's of MeshWrapper are the ones used by MeshDomain.
Should definitely discuss how to go about making a MeshType that can be more general purpose
