### ISSUE TITLE
add support for Option &nargs(size_t n) > 1 (see todo in this function in optparse.h)

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#631]
- enables `--pos <x> <y> <z>` instead of `-x <x> -y <y> -z <z>`

**Comment by sheryjoe** [comment]
Is this a duplicate issue? see ##632

**Comment by sheryjoe** [comment]
@archanasri is this still an issue?

**Comment by archanasri** [comment]
@sheryjoe it looks like a duplicate issue of #632. We can either close this or that since this isn't done yet and it would be nice to have this for the command-line interface.

**Comment by cchriste** [comment]
Also, **don't require parameter name for single-parameter commands such as readimage**.

(I don't think we need a separate issue for this since they're very closely related)

**Comment by cchriste** [comment]
Closing as duplicate of #331
