### ISSUE TITLE
add support for multiple parameters of a single option to shapeworks executable

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#632]
- enables `--pos <x> <y> <z>` instead of `-x <x> -y <y> -z <z>`
- `Option &nargs(size_t n) > 1` (see todo in this function in optparse.h)

**Comment by sheryjoe** [comment]
@archanasri is this still an issue?

**Comment by cchriste** [comment]
Yes, and we could add "don't require parameter name for single-parameter commands such as readimage. Both are desirous and feasible, and as much as I argue against the command line interface, we still have it and I tend to use it quite a bit for testing. 

@sheryjoe can we reopen this with the other addition I mentioned it and add it to some "would be nice" category?

**Comment by cchriste** [comment]
Ah. I see #631 is still open. I added the above comment in that.
