### ISSUE TITLE
add ability to require default _first_ argument for shapeworks subcommands

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#633]
ex: `readimage /path/to/img` rather than requiring `--name /path/to/image`
  - this is an OptionParser addition
  - if default 1st argument specified, it will be mandatory, so just take first argument after command when parsing
  -  if first argument after command name starts w/ --, report error

**Comment by sheryjoe** [comment]
shouldn't that be an option? i.e., support both with and without --name?

**Comment by sheryjoe** [comment]
@archanasri is this still an issue?

**Comment by archanasri** [comment]
@sheryjoe yes it is.

Would this be something that will benefit only the read and write commands?

**Comment by cchriste** [comment]
Ah. This is closely related to #631.

**Comment by cchriste** [comment]
> @sheryjoe yes it is.
> 
> Would this be something that will benefit only the read and write commands?

This would be beneficial for any command that only requires a single argument, or even commands that normally take only one arg.

**Comment by cchriste** [comment]
Closing as duplicate of #330.
