### ISSUE TITLE
move shapeworks-postv1 to a separate GitHub repo (and don't include it with shapeworks)

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#634]
Even though Post is due for retirement, it's manually copied libraries are causing include/link conflicts, the workarounds for which are hacky. Let's make Post use the external Eigen library (v3.3.7 installed by conda) and remove it's copy.

**Comment by cchriste** [comment]
I think it's really pretty and that we should keep it around somewhere for posterity, especially if any features are still due for migration to Studio, but can we move Postv1 to a separate repo? Assigning Riddhish and Alan since they have the most to gain/lose by this suggestion. Thanks!

**Comment by cchriste** [comment]
Is this now gone?

**Comment by akenmorris** [comment]
I thought it was.  @riddhishb ?

**Comment by cchriste** [comment]
@riddhishb ?

**Comment by cchriste** [comment]
I notice there's only one file in ShapeWorks/Post/source/ShapeWorksView2/MeshManager.h.
related to #96

**Comment by cchriste** [comment]
<src>/Post/source/ShapeWorksView2/MeshManager.h is not included anywhere. Can we remove it and close this (and the other related) issues?

**Comment by cchriste** [comment]
Removed MeshManager.h and closing this issue.
