### ISSUE TITLE
Consolidation for mesh-based grooming subcommands used in the use cases

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#636]
- mesh subcommands
- documentation
- document fixed bugs/differences with standalone tools
- update python use cases to use consolidated commands
- unit tests
- merge mesh_party branch (which include other SW members to review and test)

**Comment by sheryjoe** [comment]
@archanasri with mesh party being merged, should we close this issue?

**Comment by archanasri** [comment]
@sheryjoe only a subset of mesh commands have been consolidated so this can remain open until all of them have been consolidated.

**Comment by archanasri** [comment]
Following commands have been consolidated from standalone executables:
smooth, decimate, invert normals, reflect, alignment, fill holes, probe volume at mesh vertices, clip, translate, scale, bounding box, quality control, surface to surface distance, to image and to distance transform.
