### ISSUE TITLE
No test output should be written to source tree (treat it as read only)

### ISSUE THREAD

**Issue by 0leks** [SCIInstitute/ShapeWorks#637]
Probably needs some clever .gitignore line.
Already caused Hong to commit bunch of Testing/data/*/output/ folders to his branch

**Comment by cchriste** [comment]
For example, OptimizeTests currently outputs a bunch of stuff that clogs git.

This is as much for clarity during development as it is for ensuring our system works even when things are stored in a read only location (such as /Applications on OSX or many places on AWS, SCI servers, or other remote locations).

**Comment by akenmorris** [comment]
Agree with the title of this issue and comments in #1066

**Comment by cchriste** [comment]
closing as duplicate of #1066 and #1266
