### ISSUE TITLE
Update Optimize.md

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#638]
We need to update the parameters listed in optimize.md for the new multi-scale parameter  (use_shape_statistics_after) and explain how it relates to the old ones (number_of_levels, starting_particles) which should be removed. 
Users in orthopedics have also voiced that a more detailed explanation of parameters would be helpful. Specifically the ones that are not used in the use cases like attribute_scale and narrow_band so they can decide if they need them.

**Comment by sheryjoe** [comment]
Closing it. Related to #648
