### ISSUE TITLE
Docs: Rewrite Groom documentation to illustrate consolidated APIs (command, c++, and python)

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#647]
**Branch:** mkdocs
**File to be edited**: docs/workflow/groom.md

See [gh-pages](http://sciinstitute.github.io/ShapeWorks/) for deployed docs.   
See docs/dev/mkdocs.md for instructions, naming convention, and doc organization.

**Comment by archanasri** [comment]
I have updated the docs/workflow/groom.md file with command-line image grooming tools.

**Comment by sheryjoe** [comment]
Please run `mkdocs gh-deploy` to reflect these changes.

**Comment by cchriste** [comment]
> Please run `mkdocs gh-deploy` to reflect these changes.

Does this need to be run manually after each change to the documentation? Or is it done by the GitHub actions? 
Can you please point us to the documentation explaining what is required? Thanks!

Does mkdocs gh-deploy actually update the docs seen in gh-pages? If so, would we want to do this for a branch or have it done automatically for the GitHub action used for master only?
@akenmorris can you chime in on this? I'm not clear on how we'll keep gh-pages up to date with master and I don't like the idea of having to run it manually or that it might be run by actions that update a branch that isn't master.

**Comment by sheryjoe** [comment]
No, this does not have to be run manually. It is part of the GitHub actions. So I assume it should be updated with every PR merge (@akenmorris?) 

For instructions, please see (and update if needed) docs/dev/mkdocs.md . And yes, this command update the docs seen in gh-pages (build static pages and push to the gh-pages branch).

**Comment by aogs** [comment]
It is easy to run a step from the action only if the branch is master (e.g. merges or direct commits).  See the “Deploy” step for an example. 

Also, in scripts you can check the branch. See package.sh for an example.

**Comment by sheryjoe** [comment]
consolidated APIs have been addressed. I will add to the what is new section to illustrate an example that include c++ chaining. groom.md should include python apis when ready. pushing it to 5.6.

**Comment by archanasri** [comment]
Is this part of the 6.0 Release?

**Comment by archanasri** [comment]
Python API needs to be added.

**Comment by sheryjoe** [comment]
@archanasri did you add the below on the documentation slide? could you give some context?
`argument list for Python interface is sometimes different from command line interface.`

**Comment by archanasri** [comment]
This issue should address how to groom and the thought process behind it. It should link to notebooks (as an example of how grooming can be done) and ShapeWorksCommands (to list out the different grooming tools).
Adding @iyerkrithika21 and @jadie1 to help with this.

**Comment by jadie1** [comment]
@sheryjoe We have taken a stab at this on the fix_docs branch. Could you look it over?

**Comment by sheryjoe** [comment]
@jadie1 @archanasri 

- For the pic illustrating before and after registration, can you add the reference in the same view with a different color? i did a similar illustration in the notebooks videos. for now I added in relevant videos for illustration.

- the pic illustrating reference selection can be improved by displaying all shapes in the cohort and the selected reference.

**Comment by jadie1** [comment]
@sheryjoe I made these updates to fix_docs
