### ISSUE TITLE
Docs: Customize readthedocs theme

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#652]
- [ ] Text justification
- [x] Main sections highlights
- [ ] Different coloring theme

**Comment by sheryjoe** [comment]
@medakk let me know your comments on this.

**Comment by medakk** [comment]
> Text justification

Like instead of left-aligned?
![image](https://user-images.githubusercontent.com/10536745/95702745-6940e900-0c0a-11eb-8787-0156a7b196ee.png)

> Main sections highlights

I don't understand, what do you mean?

> Different coloring theme

[Seems simple enough to change](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/). What color scheme do you have in mind?

**Comment by medakk** [comment]
> Different coloring theme

Oops, I was looking at the docs for "Material for mkdocs". Looks like theme color options need to be exposed by the theme(https://www.mkdocs.org/user-guide/configuration/#theme),

**Comment by sheryjoe** [comment]
> > Text justification
> 
> Like instead of left-aligned?
> ![image](https://user-images.githubusercontent.com/10536745/95702745-6940e900-0c0a-11eb-8787-0156a7b196ee.png)


Yes. 

> > Main sections highlights
> 
> I don't understand, what do you mean?
That is done with the recent PR

**Comment by sheryjoe** [comment]
> > Different coloring theme
> 
> Oops, I was looking at the docs for "Material for mkdocs". Looks like theme color options need to be exposed by the theme(https://www.mkdocs.org/user-guide/configuration/#theme),

We are already using readthedocs theme.

**Comment by cchriste** [comment]
I've been trying to simply make the text enclosed by single backticks appear calmer than bright red, so far to no avail. 

Another part of this issue is #1341.

**Comment by cchriste** [comment]
Examples of various themes that can be used with mkdocs:
https://matusnovak.github.io/doxybook2/

**Comment by cchriste** [comment]
PR #1721 is at least a partial resolution to this. It utilizes the mkdocs Material theme.
Colors can be changed [using this simple method](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-scheme), which even enables selectors for different color sets, as demonstrated on that page.
I don't understand what is meant to be changed by "text justification."

**Comment by akenmorris** [comment]
@sheryjoe , is this complete with the new docs theme?

**Comment by sheryjoe** [comment]
@akenmorris the deployed documentation does not load  (might be a connection issue on my side). could you add a snapshot of the new theme?

**Comment by akenmorris** [comment]
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/1693349/164611672-2dce46b2-c31f-4992-930e-b4ebe8b66d1f.png">

**Comment by cchriste** [comment]
> @akenmorris the deployed documentation does not load (might be a connection issue on my side). could you add a snapshot of the new theme?

It's still loading and working for me, too. *sigh of relief*
Sorry you're having trouble, Shireen.

I would consider this issue complete.

**Comment by akenmorris** [comment]
Done.
