### ISSUE TITLE
applyCropping function in GroomUtils

### ISSUE THREAD

**Issue by AtefehKashani** [SCIInstitute/ShapeWorks#654]
When I am running use cases from master,  I am getting error in the cropping function:
```         cmd = ["shapeworks",
               "boundingbox", "--names"] + glob.glob(path) + ["--", "--padding", str(paddingSize),
               "read-image", "--name", inname,
               "crop",
               "write-image", "--name", outname]```

if you notice in the second line "["--", "--padding", str(paddingSize),"  "--" is not getting any argument. I don't know if the order of commands are correct or not, but I assume after the --name it requires the inname.

**Comment by archanasri** [comment]
@AtefehKashani what is the error that you get?
We need to use "--" because the --names takes in a list of filenames and "--" denotes the end of the files to be read.

**Comment by AtefehKashani** [comment]
@archanasri here is the erroe

``` CMD: shapeworks boundingbox --names -- --padding 10 read-image --name TestEllipsoids/groomed/aligned/segmentations/seg.ellipsoid_00.isores.center.pad.com.aligned.nrrd crop write-image --name TestEllipsoids/groomed/cropped/segmentations/seg.ellipsoid_00.isores.center.pad.com.aligned.cropped.nrrd
Usage: bounding-box [args]...

bounding-box: error: --names option requires an argument
General exception caught.
        Returncode: 2
        Output: None
```

**Comment by AtefehKashani** [comment]
And also, the printing of the rigid alignment is changed and it is not printing the input and output file names, is there any specific reason for that?

**Comment by archanasri** [comment]
@AtefehKashani 
I ran the ellipsoid use case from master. I didn't get any error. Do you have the latest master?

There is no reason for not printing input and output names.

**Comment by AtefehKashani** [comment]
@archanasri yes, I do have the latest master. 
To keep the consistency with other grooming functions, it is better to add those printing line to the rigid alignment function.

**Comment by archanasri** [comment]
@AtefehKashani Have you made any changes to ellipsoid.py or GroomUtils.py?

**Comment by AtefehKashani** [comment]
@archanasri  I fixed the bug on my local directory, thanks!
