### ISSUE TITLE
Move all included dependencies into shared Libs directory and update all CMakeLists.txt files to use them

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#66]
- ParticleBasedSurfaceReconstruction needs to built as part of post and superbuild
- Its CMakeLists being updated to reflect the new repo
- The below dependencies listed in its CMakeLists should be part of Libs. 

  ${COMMON_LIBS_DIR}/Eigen
  ${COMMON_LIBS_DIR}/ITKVTK
  ${COMMON_LIBS_DIR}/Procrustes --> make sure to use the procrustes lib used by ShapeWorksRun
  ${surfworks_SOURCE_DIR}/Transforms
   ${surfworks_SOURCE_DIR}/Utils --> this has utils and vis, can we move this to the libs to be common across all Shapeworks tools?
  )

**Comment by cchriste** [comment]
Including:
- Update ParticleBasedSurfaceReconstruction Cmakelists and its dependencies
- ShapeWorks Studio (also see #45)
- ...
