### ISSUE TITLE
Use Cases should avoid resampling until the last possible time

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#660]
**This will reduce accumulation of errors inherent in that operation.**

This was discussed in detail during ShapeWorks meeting on 8/18, and more details can be found in slide 6 https://docs.google.com/presentation/d/1c5WnpLbfU8FtbDhGu3CWMFchSrsaGQyu7DFA26qKEfA/edit#slide=id.g8a7032bcf8_0_176

Though bounding boxes were the narrow topic of discussion, this more general issue is to simply avoid any resampling until absolutely necessary, likely not until Image::resample is explicitly called (also see issue #659) or until optimization work is completed (in theory optimization doesn't require images with the same dims).

**Comment by cchriste** [comment]
Many of the operations that resample can be found by searching Commands.cpp for `resample` and Image.cpp for `applyTransform`.

After this issue is resolved, the user will have to explicitly call resample before writing an image if that's their intended result, since all the commands that now do this by default (e.g., Image::translate), Image::rotate, etc) will now no longer do so, but instead they will probably set a separate `transform` member of the class which will be applied by applyTransform.

**Comment by sheryjoe** [comment]
Use cases should be updated to enable both scenarios, aligning data or passing pre-alignment transformation to the optimizer. 

Related to #865

@akenmorris please add other issues related to this one.

**Comment by sheryjoe** [comment]
Use cases should be updated to enable passing pre-alignment transformation to the optimizer. We can put together an example use case to demonstrate/visualize intermediate steps. We could also add an optional arugment to the use case to export groomed files in case needed for subsequent steps. For example, DeepSSM use case would need prealigned images and shapes.

@jadie1 @riddhishb we could consider adding a spatial transformer to DeepSSM to handle misalignments in the shape cohort. thoughts?

Related to #865
@akenmorris please add other issues related to this one.

**Comment by akenmorris** [comment]
This is going to require some fairly significant rewriting of the grooming pipelines of the python use cases.  Let's push this to 6.3 since no one is actively working on it.

**Comment by sheryjoe** [comment]
related to #1516

**Comment by archanasri** [comment]
This issue will be closed when use cases are refactored. No change in the back-end is needed.
