### ISSUE TITLE
Windows build/run not possible using current instructions

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#664]
I can't build on Windows. Here are some things that were difficult or impossible to figure out:
- How to run msys shell (git bash) with conda in the path: eventually I was able to add condabin to the path like the path to qmake, then run `conda.bat activate shapeworks` (I ran conda_installs.bat from the anaconda bash shell). Almost none of this is in the BUILD_Windows.md
- that file and another refer to a missing part of getting started to add something to the path, which is now in Paths.md
- it's confusing which shell should be used for what part of the process described in build_windows.md
- the example at the end just doesn't work. As far as I can tell, there is _no_ conda command in windows msys shells, just conda.bat, so if the instructions tell you to use msys (more details about this are needed), and the example shows just running conda, something is missing.

And finally, build_dependencies doesn't work anyway. Very soon after it starts, this error occurs:
```-- Configuring for OpenVDB ABI Version 7
-- ----------------------------------------------------
-- ------------- Configuring OpenVDBCore --------------
-- ----------------------------------------------------
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find IlmBase (missing: IlmBase_INCLUDE_DIR IlmBase_LIB_COMPONENTS
  Half) (Required is at least version "2.2")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindIlmBase.cmake:285 (find_package_handle_standard_args)
  openvdb/CMakeLists.txt:61 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/cam/code/swdeps/install/openvdb/build/CMakeFiles/CMakeOutput.log".
Microsoft (R) Build Engine version 16.3.1+1def00d3d for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: ALL_BUILD.vcxproj
```
👎

**Comment by cchriste** [comment]
Note that debug builds may not be possible at all, see issue #665.

**Comment by sheryjoe** [comment]
@akenmorris @cchriste could you check the below links and let me know what exactly needed to be added to the documentation to resolve this issue? Please send specific instructions.

http://sciinstitute.github.io/ShapeWorks/users/install.html
http://sciinstitute.github.io/ShapeWorks/dev/build.html

**Comment by sheryjoe** [comment]
@cchriste @akenmorris is this still an issue? what needs to be done to address it?
