### ISSUE TITLE
Cannot build Debug ShapeWorks on Windows 

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#665]
It may be that #466 must be resolved for this to be possible, though that seems itself to be an unreasonable requirement.

**Comment by sheryjoe** [comment]
@cchriste @akenmorris are we still looking into this?

**Comment by akenmorris** [comment]
I don’t know of any way to resolve this without building the dependencies outside of conda. But I am not a windows build expert.

**Comment by sheryjoe** [comment]
Just curious, why do we need to support debug build on windows?

**Comment by cchriste** [comment]
> Just curious, why do we need to support debug build on windows?

For Windows development and debugging. It's a reasonable necessity.

Note: this issue is also reflected in #664 and #713.

**Comment by cchriste** [comment]
It is hard to imagine that it would be impossible to link a debug build against an optimized third party library. Imagine if we had a Windows developer (*gasp*). I haven't tried to resolve this, but one idea for a test would be to create a simple new solution (leave cmake out of it for now) and build an openVDB example app.

**Comment by akenmorris** [comment]
I don't believe actual debug builds are possible on windows using library dependencies from conda.
