### ISSUE TITLE
Cannot run use case from Anaconda shell on Windows

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#667]
Running use case from Anaconda shell on Windows fails when Optimize step starts because openvdb.dll isn't found. A window pops up saying that ShapeWorksRun.exe cannot execute because of this, and an exception is reported at the command line. 

As noted in #664 and #666, there seems no way to run use case from msys (i.e., git-bash) shell.

**Comment by akenmorris** [comment]
It looks like the windows build instructions are not synchronized with how the GitHub action builds it.  There are some steps that copy the libraries into place.  I don't know if cmake can be made to perform these steps or if windows developers would just have to do it manually the way the action works.

I tried the most recent windows binary dev build, following the instructions that it opens at the end of the installer and everything seems to work.  I don't believe any of these recent windows issues affect end users.

**Comment by sheryjoe** [comment]
@akenmorris is this already solved?

**Comment by akenmorris** [comment]
@cchriste ?

**Comment by sheryjoe** [comment]
@cchriste is this still a problem on your machine Cameron?

**Comment by cchriste** [comment]
> @cchriste is this still a problem on your machine Cameron?

Yes, and I think #478 should be associated in order to resolve both.

**Comment by akenmorris** [comment]
Can we move this off 6.1?  It does not, to my knowledge, affect user downloads.

**Comment by cchriste** [comment]
> It looks like the windows build instructions are not synchronized with how the GitHub action builds it. 

This problem is noted in both #713 and #664, so this particular issue is otherwise fixed. Closing.
