### ISSUE TITLE
GroomUtils.applyCropping should only compute bounding box once, then crop

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#669]
It's a waste of computation to repeatedly compute the bounding box of a set of images. If the crop command needs to be modified to accept bounds, or the bounding-box command needs to provide them, make these modifications accordingly.

**Comment by sheryjoe** [comment]
@archanasri @cchriste Is this already solved with the current release?

**Comment by archanasri** [comment]
This issue can be solved with Python APIs

**Comment by archanasri** [comment]
Resolved with commit 6bd00fca91e50b23d77f19997d296a1b4ed61e43
