### ISSUE TITLE
ParticleBasedSurfaceReconstruction bugs

### ISSUE THREAD

**Issue by prafulag** [SCIInstitute/ShapeWorks#67]
[copy from email 7/21/19]
WarpToMeanSurface:
1. providing world coordinates (along with local coordinates) results in shape being transformed out of bounding box
2. if using local coordinates only and letting the system compute its own world coordinates generates a bad distance transform, the similar issue faced in fids based distance transform. The BSpline filter output was buggy, I changed it to Linear for my purpose. However, of the two mesh files written from the same distance transform, vtk file does not have any face information. Also, this results in the failure of PreviewQC step.

datapath: /usr/sci/projects/Japanese_dysplasia_shape_analysis/JointModel1-DysplasiaOnly/Experiment_XYZ_Normals_joint_kraken/model_a_i0.001_f100_reg_s1e9_e0.1_r2_proc2_statsInit_0_initIter_3000_optIter_5000/ 

Sampling along the PCA modes: needs debugging [legacy issues, I do not have any more information for this yet.]

**Comment by prafulag** [comment]
Code snippet for 1.

WarpToMeanSurfaceWithPreviewQC - Line 1196 -1210

**Comment by sheryjoe** [comment]
RecontructMeanSurface is tested for femurs and pelvis examples (subset of 5 shapes) with and without world coordinates.

**Comment by sheryjoe** [comment]
move along pca is done and tested on a subset of Praful's data.
