### ISSUE TITLE
Narrow Band Gradient Edge

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#671]
The current use of OpenVDB for the gradient image results in the edge voxel being a very large gradient away from the shape.  Some options:

1) Compute the gradient on the ITK image first and then create the OpenVDB gradient image from this.  That way the final edge should be preserved.

2) Increase the narrow band.

3) Set the background value of the OpenVDB image to -1e8 instead of 1e8.

**Comment by sheryjoe** [comment]
@akenmorris @medakk is this already solved?

**Comment by akenmorris** [comment]
Yes, we did option number 3
