### ISSUE TITLE
Visualize DeepSSM error on the predicted mesh in Studio

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#674]
Make it so user can visualize DeepSSM prediction error as a heat map on predicted meshes.

**Comment by sheryjoe** [comment]
@jadie1 should we close this issue?

**Comment by jadie1** [comment]
Currently the meshes with distance values are generated but the users have to open them in paraview or something to see them. If that is okay then we can close it, but if we want to make it so the meshes can be viewed in Studio or something then we should leave it open.

**Comment by sheryjoe** [comment]
Let's leave it open. We can use Studio to analyze DeepSSM results. At some point, we could also add a DeepSSM tab to Studio to enable training/testing of the model without having the user leave Studio. That will probably be feasible when we add the ability to connect Studio to remote servers (cloud) in case users do not have the computational capacity.

**Comment by jadie1** [comment]
For each sample in the test set, DeepSSM generates the original mesh with scalar distance values to the predicted and predicted meshes with scalar distance values to the original. We need a way to visualize on or both of these.

**Comment by akenmorris** [comment]
Are these distances provided as vertex scalar values in a VTK file?  We just need a way to visualize this in Studio, is that correct?  Can you send me some examples?

**Comment by jadie1** [comment]
Yes exactly. I attached a couple of examples, let me know if you'd like more. If you open these in Paraview and select "Distance" for the coloring option you can see the heat map, that is essentially what we'd like to see in studio. 
[meshes_with_distance.zip](https://github.com/SCIInstitute/ShapeWorks/files/5655104/meshes_with_distance.zip)

**Comment by akenmorris** [comment]
Should we detect and auto show the "distance" scalar, or should we change how they are written out using the default scalars array so that they would autoshow in Paraview (and Studio)?

**Comment by jadie1** [comment]
I think we should just auto show the "distance" scalar. The other metrics
are not vertex-wise they are a single value for the entire mesh.
