### ISSUE TITLE
Image sizes are not the same after rigid alignment

### ISSUE THREAD

**Issue by AtefehKashani** [SCIInstitute/ShapeWorks#675]
(master branch) I have tested this with the RV data, the image sizes don't change after rigid alignment. They are not the same as reference image. This creates problem for cropping function to find the best bounding box and then the groomed data is not proper for optimization.

**Comment by cchriste** [comment]
Please provide more detailed information, including
- exact command to produce this issue
- exact change being used (git hash) so we can be sure to be able to reproduce it
- details of what is produced (ex: `shapeworks read-image --name <img> info` for both input and output of rigid alignment)
- ...and what should be (i.e., tell us what part of the info should be different)
- example images (attach or link)

**Comment by archanasri** [comment]
@AtefehKashani can you share the data that you used to run this? I can work on this issue

**Comment by archanasri** [comment]
@AtefehKashani can you share the python script used to run the use case? There isn't an RV use case python script in the repo.

**Comment by AtefehKashani** [comment]
@archanasri  you're right.We don't have RV use case yet. Here is the script
that I used for running the grooming. It is following the same steps as
other use cases.

**Comment by archanasri** [comment]
@AtefehKashani Can you email me the script?

**Comment by archanasri** [comment]
@AtefehKashani I ran the RV script with the data. I can see that the dimensions and spacing are the same after the rigid alignment step for all images. The origin is different though. Is that causing the problem for cropping for you?

**Comment by AtefehKashani** [comment]
@archanasri It creates problem in cropping and also even if you can crop all the images and get the distance transforms, optimization fails to find a shape model. Please find the attached image. 
one of the points of rigid alignment is that, after alignment  shapes share the same coordinate system(the same as reference image). One other thing that I guess should be checked is verify the center of mass alignment to make sure there is no bug in that step. 
![rv](https://user-images.githubusercontent.com/50889316/93507456-f67a7180-f8da-11ea-9c10-03e161ed6330.png)

**Comment by archanasri** [comment]
@AtefehKashani Can you try running the use case in the image_size branch?

**Comment by AtefehKashani** [comment]
@archanasri I ran it from the image_size branch and I am getting the following error. Did yo get the same message when testing the rigid alignment function?

""""""""""""""""""""""""""""
resample: error: no such option: --sizex
Traceback (most recent call last):
  File "RV.py", line 51, in <module>
    rigidFiles = applyRigidAlignment(parentDir + "aligned", comFiles, None, medianFile)
  File "/scratch/code/ShapeWorks/Examples/Python/GroomUtils.py", line 306, in applyRigidAlignment
    subprocess.check_call(cmd)
  File "/scratch/anaconda3/envs/shapeworks2/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['shapeworks', 'read-image', '--name', './RV_Groom_test/com_aligned/009.Dia-RV-Endo.isores.pad.com.nrrd', 'resample', '--sizex', '479.0', '--sizey', '479.0', '--sizez', '131.0', '--spacex', '1.0', '--spacey', '1.0', '--spacez', '1.0', '--originx', '34.0104', '--originy', '-160.297', '--originz', '253.964', '--interp', 'nearest', 'write-image', '--name', './RV_Groom_test/aligned/009.Dia-RV-Endo.isores.pad.com.aligned.nrrd']' returned non-zero exit status 2.
"""""""""""""""""""""""""""

**Comment by sheryjoe** [comment]
@archanasri where are we on this issue?

**Comment by archanasri** [comment]
@AtefehKashani I am not getting that error.

**Comment by sheryjoe** [comment]
@archanasri @AtefehKashani where are we on this issue?

**Comment by archanasri** [comment]
I am waiting on @AtefehKashani's testing results to see what changes need to be done.

**Comment by sheryjoe** [comment]
@AtefehKashani can you share a subset of the RV shapes where we can reproduce this error? or can you quickly test this on your side.

**Comment by AtefehKashani** [comment]
@archanasri I'll test this as soon as I get time and let you know. @sheryjoe I have already shared the data with archanasari as we discussed before.

**Comment by archanasri** [comment]
@AtefehKashani Sounds good!

**Comment by AtefehKashani** [comment]
@archanasri I have tested with RV data and the problem is fixed. We can close the issue.

**Comment by archanasri** [comment]
Great! I'll create a PR to merge this change to the master.

**Comment by archanasri** [comment]
I just noticed that after merging the pybind branch, we actually fixed the issue with python api. It's the same fix as in this branch.
