### ISSUE TITLE
ellipsoid dataset should not have images

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#677]
In use-case-data-v1, ellipsoid has an images folder that contains segmentations. This use case does not have imaging data and hence this folder should be removed. RunUseCase/ellipsoid.py (and other use cases) should be smart to detect that no images/meshes are given for this use case and act accordingly. For instance, if the user specifies the --start_with_image_and_segmentation_data, a warning should be given that this data set does not come with images.

**Comment by jadie1** [comment]
I updated the dateset in the portal to not have images and to have the groomed and shape_model folders. 
I added a warning to the use case when  --start_with_image_and_segmentation_data is used. 
This change is in pull request #656
