### ISSUE TITLE
Geodesic repulsion for surface sampling

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#681]
- [ ] geodesic distances on meshes 
- [ ] unit tests
- [ ] automated tests
- [ ] scapula use case

- Storing a sparse variant of the distance matrix in memory, based on an upper bound for distances
- Using dimensionality reduction techniques on the distance matrix, and only storing that in memory
- Changes required to ShapeWorks to implement geodesics (in terms of the acceleration structure, sampling algorithms, preprocessing pipeline)
- Going from inter-vertex geodesics to geodesics between arbitrary particle positions

**Comment by medakk** [comment]
Plan for this release is to implement geodesics with gaussian entropy(ie: don't worry about cotan for now), with particle based caching. TODO: implement this for femur_mesh and compare time, speed, results with OpenVDB femur
