### ISSUE TITLE
Use case for multiple domains

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#683]
See [How to Add New Use Cases?](http://sciinstitute.github.io/ShapeWorks/dev/new-use-case.html) for instructions.
See also [Getting Started with Documentation](http://sciinstitute.github.io/ShapeWorks/dev/docs.html)

**Comment by iyerkrithika21** [comment]
Ran ellipsoid_multiple_domain use case for two domains in the splitting_test branch with the meshes generated by scaling vtkSphereSource.
This is the output
![image](https://user-images.githubusercontent.com/11266258/99688863-83f55180-2a43-11eb-9bd9-0072b301f254.png)

**Comment by sheryjoe** [comment]
@akenmorris could we add multi domain support in Studio?

**Comment by iyerkrithika21** [comment]
Tasks:
1. Generate shape model for multiple domains using `ShapeWorks.`
2. Visualize the results in `ShapeWorks View2.`
3. Create a notebook to show the basic use case for ellipsoids with the same radii and different orientations.

**Comment by iyerkrithika21** [comment]
Multiple domains from the use cases perspective will have the following components:

1. Python use case
2. Jupyter Notebook
3. Changes to optimizeUtils to handle the dictionary parameters for XML file
4. Include analyze.xml file generation for multiple domains.

@sheryjoe, do you think we need separate issues?

**Comment by sheryjoe** [comment]
@iyerkrithika21 is this still an issue?

**Comment by iyerkrithika21** [comment]
Use cases have been included in the release.

**Comment by iyerkrithika21** [comment]
Use cases have been included in the release.
