### ISSUE TITLE
Use case for optimizing particles on meshes (femur_mesh, lumps)

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#688]
Please refer to guidelines here
https://sciinstitute.github.io/ShapeWorks/dev/new-use-case/

**Comment by medakk** [comment]
The [current femur use case](https://github.com/SCIInstitute/ShapeWorks/blob/d2285e8473cfcaec26caa55a3163780bdab27f8c/Examples/Python/femur_mesh.py#L52) only uses the first 15 samples. Is this intentional? @sheryjoe

**Comment by akenmorris** [comment]
Looking at the commit history, I have to wonder if @0leks had reduced it while testing.  It should probably go back to the full set.

**Comment by 0leks** [comment]
Yeah this can go back to the full set I think
