### ISSUE TITLE
DeepSSM/DataAugmentation: Function names consistent CamelCase vs camelCase

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#695]
Examples:
DeepSSMUtils.getTrainValLoaders(out_dir, aug_data_csv, batch_size, down_sample)
DeepSSMUtils.getTestLoader(out_dir, test_img_list, down_sample)
DeepSSMUtils.trainDeepSSM(loader_dir, parameters, out_dir)
DeepSSMUtils.testDeepSSM(out_dir, model_path, loader_dir, PCA_scores_path, num_PCA)
vs 
DataAugmentationUtils.VisualizeAugmentation(aug_data_csv)
DeepSSMUtils.AnalyzeResults(out_dir, DT_dir, prediction_dir, mean_prefix)

**Comment by jadie1** [comment]
Thanks for catching this Shireen, I fixed it in the DeepSSM branch.
