### ISSUE TITLE
DeepSSM: visualize reconstructed mesh and particles overlaid on image

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#696]
- Use three.js: Get the three.js viz tool working for visualizing particles for DeepSSM and other Img2SSM functionality we are working on.

It is hard to relate DeepSSM results with the expected shape boundary on the image.

<img width="1319" alt="Screen Shot 2020-09-17 at 12 41 48 PM" src="https://user-images.githubusercontent.com/3253036/93513520-36455700-f8e3-11ea-851a-3daed75420a9.png">

**Comment by jadie1** [comment]
Related to #977, pushing to 6.4

**Comment by akenmorris** [comment]
I believe this is satisfied within studio now:

![image](https://github.com/SCIInstitute/ShapeWorks/assets/1693349/7419123b-a7d2-40e1-9a0e-c242b9393660)
