### ISSUE TITLE
Studio: expose SSM evaluation metrics

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#697]

**Comment by medakk** [comment]
@medakk needs to add documentation and references https://arxiv.org/pdf/2009.02878.pdf
section 4.1.1 (pg 7)

**Comment by akenmorris** [comment]
These should be shown as curves under the metrics panel.  Something like this:

![image](https://user-images.githubusercontent.com/1693349/101952766-689ae380-3bb6-11eb-87fc-f4aa4f27459b.png)

**Comment by akenmorris** [comment]
I'm not sure this will be usable for large shape models.  At about 50 shapes, each value on the X axis takes a minute or more to compute.  Compactness is not a problem since they are all computed at once.  For a model with 588 shapes, it took 16 minutes to compute specificity for 587 modes (one X value).  To generate the full chart will take many days.

@sheryjoe , @medakk

**Comment by medakk** [comment]
Copying my comment from the other issue, sincei ts more relevant here:

Eigen has a [BDCSVD](https://eigen.tuxfamily.org/dox/group__SVD__Module.html) implementation, which claims to be a faster, but less accurate way to compute SVD. Perhaps we can try replacing all instances of JacobiSVD in [ShapeEvaluation.cpp](https://github.com/SCIInstitute/ShapeWorks/blob/76a411824b9225b85a2c97efbdfd735a66f22439/Libs/Particles/ShapeEvaluation.cpp) with BDCSVD and see if it makes a difference

**Comment by sheryjoe** [comment]
> Copying my comment from the other issue, since its more relevant here:
> 
> Eigen has a [BDCSVD](https://eigen.tuxfamily.org/dox/group__SVD__Module.html) implementation, which claims to be a faster, but less accurate way to compute SVD. Perhaps we can try replacing all instances of JacobiSVD in [ShapeEvaluation.cpp](https://github.com/SCIInstitute/ShapeWorks/blob/76a411824b9225b85a2c97efbdfd735a66f22439/Libs/Particles/ShapeEvaluation.cpp) with BDCSVD and see if it makes a difference

Agreed. Worth trying and benchmarking time and metrics differences.

**Comment by akenmorris** [comment]
Done
