### ISSUE TITLE
cleanup duplicated data in various unit tests 

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#699]
Many of our unit tests load/compare the same input/output data, but use copies of this data. 
Reorganize the unit tests' data storage to better handle such duplication.

**Comment by sheryjoe** [comment]
@cchriste @archanasri could we associate this issue to a milestone?

**Comment by sheryjoe** [comment]
Just created a "Deployment" milestone to associate these types of issues to so that they are on our radar. This milestone does not have a specific time. We can move issues to releases milestones when we have a better time estimate of their resolution.

**Comment by archanasri** [comment]
> @cchriste @archanasri could we associate this issue to a milestone?

Yes we can

**Comment by archanasri** [comment]
Done with commit 0541ccefad526eb1e095f4584f0d583ad034b833 and commit ca94a485fc2f274b3332a506480e9efd1c79c473
