### ISSUE TITLE
Docs: instructions for adding videos

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#703]
This should be a dev documentation. It could be added to the "how to add a new use case" or but I think its purpose warrant it to be a general dev doc as videos could be added anywhere in the documentation. 

- Instructions on how to add videos to the documentation (thumbnails that link to youtube)
- Location of the videos on SCI file system.

**Comment by medakk** [comment]
> Instructions on how to add videos to the documentation (thumbnails that link to youtube)

We decided that we would not be using YouTube, right?

> Location of the videos on SCI file system.

[I've added this in the PR](https://github.com/SCIInstitute/ShapeWorks/blob/27ad19896fccb2516e9d0cb9931d88a42d995571/docs/dev/mkdocs.md#inserting-videos-in-documentation)

**Comment by cchriste** [comment]
> > Instructions on how to add videos to the documentation (thumbnails that link to youtube)
> 
> We decided that we would not be using YouTube, right?
> 
> > Location of the videos on SCI file system.
> 
> [This is already covered in the PR](https://github.com/SCIInstitute/ShapeWorks/blob/27ad19896fccb2516e9d0cb9931d88a42d995571/docs/dev/mkdocs.md#inserting-videos-in-documentation)

Clever! And very useful to users wanting to contribute to documentation. But as a developer, I _still_ don't know where to put an uploaded video. Will you please update the _developer_ documentation with these instructions?

**Comment by sheryjoe** [comment]
> > > Instructions on how to add videos to the documentation (thumbnails that link to youtube)
> > 
> > 
> > We decided that we would not be using YouTube, right?
> > > Location of the videos on SCI file system.
> > 
> > 
> > [This is already covered in the PR](https://github.com/SCIInstitute/ShapeWorks/blob/27ad19896fccb2516e9d0cb9931d88a42d995571/docs/dev/mkdocs.md#inserting-videos-in-documentation)
> 
> Clever! And very useful to users wanting to contribute to documentation. But as a developer, I _still_ don't know where to put an uploaded video. Will you please update the _developer_ documentation with these instructions?

I agree. We should include these instructions for the SW developer team.

**Comment by medakk** [comment]
Ah I see! I added that: 72554bcc

Its worth nothing that our docs consider "users contributing to documentation" as developers. All the mkdocs stuff are lumped into "For developers"

**Comment by cchriste** [comment]
Related to #650
