### ISSUE TITLE
shapeworks --version

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#706]
should be the version of the whole shapeworks software and should be consistent with about in Studio.

**Comment by akenmorris** [comment]
I've added this, so we now have:

"ShapeWorks version 5.5.0-dev (executable version 1.0.0)"

One question.  Do we need a separate version number for the executable?  @cchriste @sheryjoe

**Comment by cchriste** [comment]
Please use the same version for the executable.

Thanks,
Cameron

**Comment by cchriste** [comment]
Ah! I think I misunderstood your message. What you wrote sounds just fine. To what branch is it committed? Thanks!

**Comment by akenmorris** [comment]
It's in studio_feature_map since that's the only place the SHAPEWORKS_VERSION is (was added for Studio's about box).

**Comment by sheryjoe** [comment]
Any reason to maintain a separate version for the executable? I think version should be synced with the "ShapeWorks" release version.

**Comment by akenmorris** [comment]
Yes, there is only one version now.
