### ISSUE TITLE
ShapeWorks studio does not display particles on the surface of the shape

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#707]
ShapeWorks built from the master on OpenSUSE Leap 15.2

![image](https://user-images.githubusercontent.com/11266258/94083606-dc500000-fdc0-11ea-9c93-2f6777ac6ef0.png)

[seg.ellipsoid_ nrrd file and particle file.zip](https://github.com/SCIInstitute/ShapeWorks/files/5272502/seg.ellipsoid_.nrrd.file.and.particle.file.zip)

@sheryjoe created an issue as per our discussion

**Comment by medakk** [comment]
Judging by the screenshot, you're remoting into openSUSE from Windows. I've seen this issue when, on my (Ubuntu 18) laptop with NVIDIA GPU, I used SSH with X forwarding to remote into the openSUSE machine. Everything was alright when I switched to the Intel GPU on my laptop.

@iyerkrithika21 if this describes your setup, a workaround maybe to force your laptop to use the Intel GPU for remote windows.

**Comment by akenmorris** [comment]
Yeah, I've only seen this over GLX.  Are you running locally or remotely?

**Comment by iyerkrithika21** [comment]
Yes, I am remoting into openSUSE from Windows.

**Comment by iyerkrithika21** [comment]
I am using NoMachine to access the OpenSUSE system remotely

**Comment by akenmorris** [comment]
Now that we've upgraded to VTK 9, I get now get a blank VTK widget area when running to linux remotely.  @medakk , Does Studio work on a native linux system?

**Comment by medakk** [comment]
Studio works fine on native Linux with commit 862c792687e89c5037f185a735fd22ee05a8a747 (this is post vtk-9, but without the new Studio PR)
I don't see any blank widget areas

**Comment by akenmorris** [comment]
Interesting.  It seems that NoMachine may use GLX in at least some cases.  I see various Qt GLX warnings depending on some settings.  I will see if I can get to the bottom of it.

**Comment by jadie1** [comment]
I am using NoMachine to access the OpenSUSE system remotely from windows as well with VTK 9.0 and studio looks as we expect it to...

**Comment by akenmorris** [comment]
Here's what I get with 9.0 on Linux via NoMachine:

<img width="844" alt="Screen Shot 2020-09-28 at 9 11 14 PM" src="https://user-images.githubusercontent.com/1693349/94508566-6fc56e80-01cf-11eb-9b9b-ea0e67a616e8.png">

This is one of the VTK examples supplied with VTK.

That's the terminal window underneath.  The VTK widgets are just blanking to underneath.

**Comment by akenmorris** [comment]
Ok, so it works fine if the linux host being connected to has a real OpenGL implementation rather than a NoMachine started frame buffer.  Paraview refused to even start in this latter case.

**Comment by iyerkrithika21** [comment]
I had the same issue where Paraview,it can't even be launched on the system.

**Comment by akenmorris** [comment]
Ok, I think we can consider this closed.  I don't think there is any way we can support this configuration while using VTK as I get the same issues with all of the basic VTK examples.  We require a working OpenGL configuration.
