### ISSUE TITLE
Consolidate SurfaceToSurfaceDistance command

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#708]
The mesh tool SurfaceToSurfaceDistance needs to be updated.  Currently it takes in two vtk meshes A and B and outputs those meshes with distance scalars. We should update this so that:
- The input meshes can be in any format we support 
- There are options to output aggregate values such as min, mean, max, and standard deviation of distance.

**Comment by cchriste** [comment]
Hi @jadie, we are working on the consolidated version of this program.
A mesh can have multiple fields, and commands to retrieve fields' values, compute their min, mean, etc, should be added.
Our mesh can now read whatever format is provided (so long as vtk can, and it can). 
The old program writes two new meshes, and we could handle this in a number of different ways (just write two new meshes, add fields to each mesh and keep them both around, etc.

We need to discuss this further to determine the best way to implement the command (and the Mesh api it will use).

**Comment by jadie1** [comment]
Sounds good, I like the idea of generalizing it so meshes can have scalar fields for any value and we can retrieve stats about them.  from the DeepSSM standpoint I don't think it matters if it writes new meshes as it currently does or just adds the fields to the meshes, either way should be fine.

**Comment by akenmorris** [comment]
FYI, the `coverage` command is an example of a command that adds a scalar array to a mesh.

**Comment by cchriste** [comment]
> FYI, the `coverage` command is an example of a command that adds a scalar array to a mesh.

Ahh.... in that case I think coverage is... brooooo... nope. It works. But I have just learned that ply files don't have scalar fields. Or at least when we write them they don't. Should this be an issue? @sheryjoe

**Comment by cchriste** [comment]
This is complete and merged all the way up to the alpha branch. 
Note: 
   //RelativeDistanceAtoB: just call getRange("distance") and take the max
   //RelativeDistanceBtoA: just call getRange("distance") of target and take the max
   //HausdorffDistance:    call getRange("distance") of both this and target and take the max

**Comment by archanasri** [comment]
Merged to master.
