### ISSUE TITLE
shape_model from left_atrium use case is inconsistent

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#710]
The shape model included in the left_atrium zip file is self-inconsistent.  For example, there particle files for CARMA1083, however there is no CARMA1083 in the groomed/distance_transforms folder.

In addition, the set of suffixes between the particle files and distance_transform files are inconsistent.

**Comment by AtefehKashani** [comment]
@akenmorris I have checked the data and I uploaded the groomed/distance_transforms again and this make the all files consistent. Please check it out.

**Comment by akenmorris** [comment]
That fixed it. Thanks!
