### ISSUE TITLE
Windows configure must have `-DVXL_DIR=/path/to/dependencies/install/vxl/build` to the cmake line

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#713]
Configuring works after adding `-DVXL_DIR=/c/Users/cam/code/swdeps/install/vxl/build` to the cmake line, which upon further exploration seems due to the fact that VXL make install doesn't work on Windows (see comment in build_dependencies.sh line 115). 

_Originally posted by @cchriste in https://github.com/SCIInstitute/ShapeWorks/issues/664#issuecomment-678318491_

**Comment by cchriste** [comment]
We should verify this is also necessary in the GitHub actions.

**Comment by akenmorris** [comment]
What needs to be done to close this issue?

**Comment by cchriste** [comment]
If this is still necessary for Windows, the example cmake call in build_dependencies.sh needs to be updated to show that.

**Comment by sheryjoe** [comment]
@akenmorris is this still an issue?

**Comment by akenmorris** [comment]
@cchriste ?

**Comment by cchriste** [comment]
My cmake configure doesn't work without it.

**Comment by sheryjoe** [comment]
@akenmorris @cchriste is there a plan to address this issue?
