### ISSUE TITLE
Replace python VTK cutting plane choser with shapeworks command and python binding

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#715]
This removes the need to install vtk via conda and removes the need to install the VTK bindings.

Is there anything else anyone would want/need VTK in python for?  I don't want to drop it if we end up re-adding it.

**Comment by jadie1** [comment]
After discussion we have decided choosing a cutting plane is part of the data preparing process, not grooming. We will remove this interactivity from the use case (issue #1249) and instead create the ability for the user to select a cutting plane in the "Data" panel of studio (issue #1250).
