### ISSUE TITLE
Replace python ITK usage with ShapeWorks image read

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#716]
After the pybind branch is merged, I think we just need a python api (pybind) call to return an image as a Numpy array.  Then we can probably drop ITK from conda and won't need python bindings for ITK directly.

**Comment by jadie1** [comment]
Pushing to next release because of issue #903 
Currently you can get a numpy array from an image but you can't alter it and write it back to an image, so we need itk for ShapeCohortGen

**Comment by cchriste** [comment]
Because #965 is fixed, we can successfully create the image from a numpy array, thus taking care of ShapeCohortGen. 
Even as of today in master, Image.toArray works fine (it was just going the other way that didn't work). Closing.
