### ISSUE TITLE
All unit tests are not being executed and thereby "succeeding"

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#717]
Seems to be an issue that came from the open meshes branch, but not positive. It started about a month ago.
Assigning it high priority and absolutely imperative for next release. These tests are very important.

**Comment by cchriste** [comment]
It's because GroomFemur.cpp, which contains a `main` function, was added to Libs/Mesh/CMakeLists.txt. This can be modified to have GroomFemur as a standalone executable and get it out of Mesh_sources. If that file contains necessary library contents, it can be split into two different files.

**Comment by sheryjoe** [comment]
@akenmorris @cchriste is this resolved?

**Comment by cchriste** [comment]
I just updated the pull request by disabling the one broken unit test and creating a separate issue for that (#722). Once the actions succeed this can be merged.
