### ISSUE TITLE
Add usecase Conda issue to documentation

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#719]
While testing the #709 PR on windows using the binary builds from the pull request, faced conda error while running conda_installs.bat

CondaError: Cannot link a source that does not exist. C:\Users\...\Anaconda3\Scripts\conda.exe

This was solved by running : 
conda install tqdm -f
https://stackoverflow.com/questions/62227119/conda-error-cannot-link-a-source-that-does-not-exist

Also, should we mention that the anaconda prompt should be run as administrator so that conda has permissions to install packages in C:\ ?

These points could be added to the documentation.

Note: These pointers are not for development build

**Comment by cchriste** [comment]
We shouldn't be running conda as administrator. It's supposed to be installed by a user in their local environment.

**Comment by akenmorris** [comment]
I’ve never had to run it as Administrator.

**Comment by iyerkrithika21** [comment]
Thanks for the comments Alan and Cameron.
I'll close this issue then.
