### ISSUE TITLE
change build_dependencies' install path to $CONDA_PREFIX

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#721]
Amongst many other possible improvements, this enables python to automatically `import vtk` (when its python apis are built) without needing to modify PYTHONPATH*.

* note that other paths may still be necessary, including LD_LIBRARY_PATH on linux, PATH on Windows, and on OSX it may still be necessary to symlink the Qt libs to $CONDA_PREFIX/lib, all as described in #300 and most as implemented in pr #702.

**Comment by akenmorris** [comment]
How will this work for users that download the binary deployments?

**Comment by cchriste** [comment]
Touché. I think I need to step away from this for now.

**Comment by sheryjoe** [comment]
Could be related to #478 ?

**Comment by cchriste** [comment]
The downloadable installations seems to be organized using exactly these paths (except for Qt libs, which are in ShapeWorksStudio.app at least on OS X). Is this correct?

**Comment by akenmorris** [comment]
What paths?  The binary distribution doesn’t rely on having conda installed.

**Comment by akenmorris** [comment]
Is this still an issue?  Can we close it?

**Comment by sheryjoe** [comment]
@cchriste @archanasri ?
