### ISSUE TITLE
Mesh::coverage function is broken

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#722]
The unit test in Testing/MeshTests/MeshTests.cpp has been disabled. 
There was an extensive conversion on Slack the morning of 9/28, and the underlying issue seems to be the upgrade to vtk9.
One proposed solution was to back port new functions from vtk9 that @jadie1 is using. 
#718 is the bug related to the accidentally-disabled unit tests that describes parts of the issue here. The rest is on Slack.

**Comment by jadie1** [comment]
@cchriste I spoke with Shireen and it sounds like we will be going back to VTK 8.2 for this release

**Comment by akenmorris** [comment]
Fixed with the downgrade to VTK 8.2
