### ISSUE TITLE
Upgrade to VTK 9

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#725]
At some point we should upgrade to VTK 9 but we need compatibility for the old ASCII file format.

Some options:

- We can ask Kitware to provide backward compatibility with ASCII
- We can write our own reader and writer to convert between version 4.2 and 5.1. Part of what we would need for a reader is already implemented in FEVTKImport.cpp. 
- We can include the old VTK reader and writer source code in ShapeWorks with different names

**Comment by akenmorris** [comment]
We decided to revert back to VTK 8.2 for now.

**Comment by cchriste** [comment]
Let's resolve #838 and then just upgrade to vtk 9.

**Comment by akenmorris** [comment]
Upgrading to VTK 9 introduces other problems.  For example, our users will be unable to import the VTK files that our tools export with their other tools:

https://discourse.vtk.org/t/can-we-write-out-the-old-vtk-4-2-file-format-with-vtk-9/5066

**Comment by sheryjoe** [comment]
@akenmorris what is the plan for this upgrade?

**Comment by akenmorris** [comment]
I am hoping that Kitware will add the legacy format to a future release (9.1 perhaps) as Steve Pieper suggested:

"I think it would be great of the vtk writers could have a flag to produce earlier version of the formats. Probably it should even be the default to avoid this kind of breaking change (old Bill would not have liked the breaking change)."

**Comment by sheryjoe** [comment]
Let's not upgrade till Kitware adds the legacy format.

**Comment by akenmorris** [comment]
More discussion about it.

https://discourse.vtk.org/t/legacy-polydata-file-compatibility/5354

**Comment by akenmorris** [comment]
9.1 is released as of November 2021.  We should be able to proceed with the upgrade.

**Comment by cchriste** [comment]
> 9.1 is released as of November 2021. We should be able to proceed with the upgrade.

Great! Let's wait until after the 6.3 release to do this in case there are unforeseen complications (e.g., Python bindings, visualizations in Use Cases or Jupyter notebooks, etc).

**Comment by akenmorris** [comment]
Merged
