### ISSUE TITLE
World to local coordinates in data augmentation

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#726]
We need to add functionality to do data aug in the world particle coordinates then map back to local coordinates before generating the corresponding image.

**Comment by riddhishb** [comment]
@jadie1 do you have a script to run this ? We have a ready dataset in IMage2SSM project directory. I will anyways need to run this functionality so I will just do these two things in one shot.

**Comment by jadie1** [comment]
The deep_ssm use case on this branch uses it. You can just copy the data aug step from that and try it

**Comment by jadie1** [comment]
Addressed in PR #807
