### ISSUE TITLE
Missing samples in femurs shape model

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#727]
There are only 17 out of 50 samples in the released shape mode. This is also not consistent with the released correspondenceXX.xml files.

**Comment by jadie1** [comment]
@sheryjoe What data are you looking at? I just had a use case download the "femur-v0.zip" and it has all 50 shape models and the xml.

**Comment by sheryjoe** [comment]
@jadie1 please see the shape_models folder. It only contains 17 samples, although the released correspondence xml files seems to run on all samples. This is very confusing.

**Comment by jadie1** [comment]
This is what is in the zip folders the use cases download:
![image](https://user-images.githubusercontent.com/54382613/94837298-50962f00-03d1-11eb-814b-ea67047ccf17.png)
All 50 of the samples are there:
![image](https://user-images.githubusercontent.com/54382613/94837615-b97da700-03d1-11eb-92c0-d4e10e6533b6.png)
I am not sure which shape_models folder you are referring to but I don't think it is the one used by the use cases.

**Comment by sheryjoe** [comment]
I am refering to use-case-data-v2/femur-v0, isn't this the latest version?

**Comment by jadie1** [comment]
Oh I see... use-case-data-v2/femur-v0 is missing some. Oleks must have copied the data here and some went missing some how. All of the data is correct in  use-case-data-v2/femur-v0, so I will just copy that over. Sorry for the confusion, I didn't realize we were using use-case-data-v2.

**Comment by sheryjoe** [comment]
I think -v2 has all data with hardcoded version as suffix. Please make sure that all use cases in -v2 contain complete shape models. Thanks.

**Comment by jadie1** [comment]
I fixed it for the femur. The same thing seemed to have happened to the LA use case - only 17 of the shape models are there. Should I make a new issue for this? There appears to be some things missing for ellipsoid and ellipsoid_fd as well and I don't see shape models for lump.

**Comment by sheryjoe** [comment]
Yes, please. I also added another issue for the _fd dataset where the correspondence xml is missing the fixed_domains xml tag.

**Comment by jadie1** [comment]
I added issue #738, closing this one.
