### ISSUE TITLE
Improve usability of released shape models and data on the SW portal

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#728]
When downloading a dataset, its shape model can't be visualized off-the-shelf. There is no analyze file or instructions on how to visualize the released shape model. Is there a python script a user should run? Can we release the analyze file (or the spreadsheet file) where a user can just load it in Studio?

We need to rethink how these models are released in a useful way to the user. This is also related to adding some viz-tools to the data portal to allow users to visualize shape models and data without having to wait for 10+ GB download.

Related to #696

**Comment by jadie1** [comment]
@sheryjoe Should we close this or rename it to be more about adding viz-tools to the data portal now that we have analyze.xml's for all use cases on the portal?

**Comment by sheryjoe** [comment]
Let's close it and create a different issue for data portal viz. @jadie1
