### ISSUE TITLE
Studio: Add mesh support

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#730]
- Loading surface meshes
- Option to optimize particles directly on meshes or convert them to DTs (related also to exposing new groom features in Studio)
- Mesh-based reconstruction

**Comment by akenmorris** [comment]
Done

**Comment by sheryjoe** [comment]
@akenmorris could you please upload a video (today) illustrating this?

**Comment by akenmorris** [comment]
I should amend this:

* Option to optimize particles directly on meshes or convert them to DTs (related also to exposing new groom features in Studio)

This was not done.

* Mesh-based reconstruction

This is not done in studio yet as the core functionality is not merged.

**Comment by akenmorris** [comment]
> Option to optimize particles directly on meshes or convert them to DTs (related also to exposing new groom features in Studio)

@jadie1 , @sheryjoe , did we every come up with an algorithm for automatically choosing the spacing for rasterization?  Something based on edge lengths?

**Comment by jadie1** [comment]
@akenmorris No we didn't. In the femur use case we make segs from meshes and we just let the user specify the spacing and default is isotropic.

**Comment by akenmorris** [comment]
Two out of 3 items in the original request are done.  This is not:

Option to optimize particles directly on meshes or convert them to DTs (related also to exposing new groom features in Studio)

**Comment by sheryjoe** [comment]
@akenmorris This issue should be part of the 6 release. I think it is almost resolved with studio loading and optimizing on meshes. Is converting meshes to DT in Studio planned to be part of the release?

**Comment by akenmorris** [comment]
> Is converting meshes to DT in Studio planned to be part of the release?

I think this still requires more thought and design.  How does this work as part of the grooming pipeline?  When you convert meshes to images, do you then open up the rest of the image grooming pipeline?  How is the spacing determined (user must supply?)  What about the opposite (images -> meshes)?

**Comment by sheryjoe** [comment]
Let's give this more thought. Closing this issue and creating a different issue for the DT from meshes. #996
