### ISSUE TITLE
Studio: fix "Optimization Interation"

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#735]

**Comment by akenmorris** [comment]
Can you elaborate on this?

**Comment by sheryjoe** [comment]
<img width="358" alt="params1" src="https://user-images.githubusercontent.com/3253036/94758893-b8aa2e00-035b-11eb-9883-3bf9556e3954.png">

**Comment by akenmorris** [comment]
Ah, yes indeed.
