### ISSUE TITLE
Visualizing Data Augmentation - Parallel & Violin plots

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#737]
Related to #687

We could start with a non-interactive visualization using Python.

Examples:
- (interactive) https://thilospinner.com/towards-an-interpretable-latent-space/
- https://seaborn.pydata.org/generated/seaborn.violinplot.html
- https://www.d3-graph-gallery.com/violin

**Comment by HeavenlyBerserker** [comment]
Why am I here, Shireen?

**Comment by cchriste** [comment]
One of the papers I listened to yesterday explored the ability of people--even experts--to understand various types of plots.
Violin plots definitely didn't "win"--bar graphs with variance lines took the gold even for experienced statisticians--but they can still be useful depending on their context. Then a talk this morning in the best papers session, "Visual Reasoning Strategies for Effect Size Judgements and Decisions," showed that multiple views can reinforce understanding. 
As your links show, there are Python libraries that make it very easy to create different plots, and letting people select different views of data or showing them simultaneously can be useful.
Here are the two papers I mentioned:
[f-info-1187.pdf](https://github.com/SCIInstitute/ShapeWorks/files/5446877/f-info-1187.pdf)
[w-comm-1017.pdf](https://github.com/SCIInstitute/ShapeWorks/files/5446878/w-comm-1017.pdf)
