### ISSUE TITLE
Restructure use case file paths

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#742]
Make it so use cases save data downloaded from the portal in: Examples/Data/<use-case-name>
And save all files output from running the use case to: Examples/Output/<use-case-name>

**Comment by sheryjoe** [comment]
I would also use the use-case-name rather than Test<use-case-name>.

**Comment by sheryjoe** [comment]
@jadie1 is this already addressed? should we close it?

**Comment by jadie1** [comment]
It is closed
