### ISSUE TITLE
Fix Optimize parameters defaults

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#745]
In Optimize.h, 
- m_narrow_band has a default of 0. Shouldn't that be 4?
- use_xyz does not have default, should be true
- use_normals does not have default, should be false
- m_use_shape_statistics_after default is -1, does this mean shape statistics is used starting at the first scale, should not that be 32 or 64?
- debug_projection can't be found, yet it is included in the parameter dictionary. what is the default?

All changes should be reflected in docs/workflow/optimize.md

**Comment by akenmorris** [comment]
> m_narrow_band has a default of 0. Shouldn't that be 4?

It used to be specified as 4 here, but the default value is now dependent on whether <fixed_domains> is active:

```
double Optimize::GetNarrowBand()
{
  if (this->m_narrow_band_set) {
    return this->m_narrow_band;
  }

  if (this->m_fixed_domains_present) {
    return 1e10;
  }
  else {
    return 4.0;
  }
}

```

**Comment by akenmorris** [comment]
> m_use_shape_statistics_after default is -1, does this mean shape statistics is used starting at the first scale, should not that be 32 or 64?

-1 indicates that the parameter has not been set.  In this case, the optimization operates as the old ShapeWorksRun that does not use shape statistics in the init phase at all.

**Comment by akenmorris** [comment]
> debug_projection can't be found, yet it is included in the parameter dictionary. what is the default?

I've never heard of this tag.  I don't see it anywhere but the python scripts.  Who added it?  Am I missing something?

**Comment by akenmorris** [comment]
> use_xyz does not have default, should be true
> use_normals does not have default, should be false

Looks like they are both default to false.  They cannot be defaulted in Optimize.h as they are vectors of size "number of domains per shape".  In `Optimize::SetParameters` it is checked if they have been set from the parameter file.  If they have not, both are set to false.  Are you suggesting that we should change the current behavior to enable XYZ by default?

**Comment by sheryjoe** [comment]
> > use_xyz does not have default, should be true
> > use_normals does not have default, should be false
> 
> Looks like they are both default to false. They cannot be defaulted in Optimize.h as they are vectors of size "number of domains per shape". In `Optimize::SetParameters` it is checked if they have been set from the parameter file. If they have not, both are set to false. Are you suggesting that we should change the current behavior to enable XYZ by default?

Yes, xyz should be default. What if both are given to be false or not given at all, what would be the correspondence term? disabling both does n't make sense.

**Comment by sheryjoe** [comment]
> > debug_projection can't be found, yet it is included in the parameter dictionary. what is the default?
> 
> I've never heard of this tag. I don't see it anywhere but the python scripts. Who added it? Am I missing something?

Praful might have added this for debugging experiments at some point. If it is not any more included in the Optimize library, please remove it from the python examples and modify the corresponding use cases md files. @jadie1

**Comment by akenmorris** [comment]
Merged.
