### ISSUE TITLE
fix acquisition of Python Global Interpreter Lock in pybind_optimize branch

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#747]
See the error in action here: https://github.com/SCIInstitute/ShapeWorks/actions/runs/289850868

I thought I'd fixed this by not linking to pybind11::embed in Libs/Optimize, but it still occurs in the [OSX] GitHub action.
Lots and lots and lots on google that talks about the error. 

I need to move on to other tasks, but my next idea to try to fix it was to call `py::scoped_interpreter guard{};` in some main function somewhere rather than `initialize_interpreter() / finalize_interpreter()` in `Optimize::Run`. But that doesn't make much sense because it's not even executed when you just run python and `import shapeworks`.
See https://pybind11.readthedocs.io/en/stable/advanced/embedding.html#interpreter-lifetime for details on the difference (summary: `initialize_interpreter()` doesn't _quite_ let go of all resources, so `scoped_interpreter` is a little more honest).

**Comment by archanasri** [comment]
pybind_optimze branch builds now.
