### ISSUE TITLE
Fix windows compile bug in pybind_optimize branch

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#748]
D:\a\ShapeWorks\ShapeWorks\ExternalLibs\trimesh2\include\strutil.h(69,9): error C2039: '_vsnprintf': is not a member of 'std' [D:\a\ShapeWorks\build\Libs\Optimize\Optimize.vcxproj]

I have a Windows box and can try a solution if anyone can offer one to me. This presumably compiled in the past so it's completely baffling that this particular branch fails. Also... it might work on my local machine and only fail on GitHub action. I'll make a point to try this today (turning on machine now, because it turns itself off randomly for now apparent reason).

**Comment by cchriste** [comment]
Okay, confirmed: this branch fails to build with the error above. It only took six minutes to get to this error... after re-installing conda, sourcing conda_installs.sh, building dependencies, and running cmake. 🥇

**Comment by archanasri** [comment]
pybind_optimize branch builds now.
