### ISSUE TITLE
Studio glyph coloring bug

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#757]
Please see the attached video. Glyphs turn to blue with one red when we play with glyph properties. 
Branch: master

[studio_glyph_bug.mp4.zip](https://github.com/SCIInstitute/ShapeWorks/files/5344255/studio_glyph_bug.mp4.zip)

**Comment by sheryjoe** [comment]
Same thing when we move from samples view to pca view.

<img width="1651" alt="image" src="https://user-images.githubusercontent.com/3253036/95395403-c01d8a00-08bb-11eb-852b-1fb16dbe2d28.png">

**Comment by akenmorris** [comment]
Fixed in PR #756
