### ISSUE TITLE
Use case for free-form constraints

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#763]
See [How to Add New Use Cases?](http://sciinstitute.github.io/ShapeWorks/dev/new-use-case.html) for instructions.
See also [Getting Started with Documentation](http://sciinstitute.github.io/ShapeWorks/dev/docs.html)

**Comment by cchriste** [comment]
As we add use cases, it becomes more important to provide a summary of what is available (#1103).

**Comment by akenmorris** [comment]
Is this done? @HeavenlyBerserker

**Comment by HeavenlyBerserker** [comment]
Yes
