### ISSUE TITLE
Python APIs for mesh-based grooming consolidated tools

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#767]

**Comment by cchriste** [comment]
#905 resolves a lot of this, but there aren't many details here. Should we keep this issue open since python apis are being added as part of the process of consolidation. Maybe individual executables remaining to be resolved would be a better way to track what needs doing.

**Comment by cchriste** [comment]
@sheryjoe @archanasri Should we add the rest of the new Mesh API to Python before releasing 6.0? Our examples are even more confusing than ever and adding these functions will help them be more transparent. Here's an example from GroomUtils:

```
        # if we have a seg for the non-ref side, reflect it
        if flip_seg != 'None':

# reflect the image using the Python API ( but don't mention anything even  if printCmd is true )
            img_out = rename(image, outImgDir, 'reflect').replace(prefix, flip_prefix)
            imageList.append(img_out)
            img = Image(image)
            img2 = img
            img2.recenter()
            center = img2.origin() - img.origin()
            img.reflect(X).write(img_out)

# reflect the mesh using the command line ( print the command if printCmd is true )
            cmd = ["shapeworks",
                   "read-mesh", "--name", seg,
                   "reflect-mesh", "--axis", "X", "--originx", str(center[0]), "--originy", str(center[1]), "--originz", str(center[2]),
                   "write-mesh", "--name", seg_out]
            if printCmd:
                print("CMD: " + " ".join(cmd))
            seg_out = rename(flip_seg, outSegDir, 'reflect')
            meshList.append(seg_out)
```

It takes more work to create a command than to bind the Python. If we're doing all that work it seems reasonable to go the extra one line of code (plus testing) and bind Mesh::reflect. I know we want to release and Python isn't the _focus_ of this release, but if we have a single Python user they'll want to try all our new Mesh work in Python.

**Comment by archanasri** [comment]
I have started adding the mesh python bindings in the mesh_python branch. I am almost done actually. Need to add tests.

**Comment by cchriste** [comment]
Can we close this issue?

**Comment by archanasri** [comment]
We still have some mesh executables to consolidate.

**Comment by cchriste** [comment]
@archanasri can we close this? I think we have all the mesh executables consolidated.

**Comment by archanasri** [comment]
@cchriste we need to add the geodesic functions (only thing left)

**Comment by nawazishkhan1-nk** [comment]
@cchriste @archanasri 
Issues with createTransform and applyTransform in meshAPI: 
Error : `Unable to convert function return value to a Python type! `

**Comment by cchriste** [comment]
> @cchriste @archanasri
> Issues with createTransform and applyTransform in meshAPI:
> Error : `Unable to convert function return value to a Python type!`

This is the same as #1276. Let's use that issue for related discussion.
