### ISSUE TITLE
Studio/Reconstruction - dynamically load distance transforms

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#769]
Just like the rest of Studio, the surface reconstruction API and Studio's usage of it needs to load the images dynamically rather than loading them all into a big array of ITK images and passing it around.  I assume there is no step in the SurfaceReconstruction that needs all the images?  @sheryjoe ?

**Comment by sheryjoe** [comment]
All images are not needed at one time in memory. Computing the template/mean mesh can be done in a streaming mode by loading one image (distance transform) at a time.  Warping the mean mesh to any target (sample or PCA mode) only needs correspondences and the mean mesh and can be done in a streaming mode (one warp at a time).

**Comment by akenmorris** [comment]
Great!  The solution to this should be combined with #770

**Comment by sheryjoe** [comment]
Yes, it is related. but let's keep both issues.

**Comment by akenmorris** [comment]
Yes, I just mean whoever addresses one should address the other at the same time.

**Comment by akenmorris** [comment]
Done
