### ISSUE TITLE
Studio/Reconstruction - Relax same size constraint on distance transforms

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#770]
Right now you can run the whole pipeline in Studio without force image to be the same size, only the surface reconstruction is requiring this.  @sheryjoe says that this can be relaxed.

**Comment by sheryjoe** [comment]
I think we can relax the same-size assumption for the reconstruction method. The core ingredient is resampling each of the distance transforms to a common coordinate space based on a TPS warp computed using correspondences. This only needs a fixed (common) size for the mean distance transform (not the individual samples/dts). So we could choose a common size (may be the largest possible size) and a voxel spacing and origin from the input samples.
