### ISSUE TITLE
enable passing the itk::Image<float. 3> (our Image::ImageType) to Python

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#780]
We've tried four ways so far and none of them work. Here is what we've tried. The first two compile and Python cannot convert the returned value to a Python class, and the second two won't compile:
``` 
  .def("toITKImage",            &Image::operator Image::ImageType::Pointer) // cannot convert to itk::SmartPointer<itk::Image...
  .def("toITKImage",            &Image::getITKImage) // can't convert return value to a Python type! itk::Image<float, 3u>
  .def("toITKImage",            [](Image& I) { return *(static_cast<Image::ImageType::Pointer>(I); }) // ugly template errors
  .def("toITKImage",            [](Image& I) { return *(I.operator Image::ImageType::Pointer()); })   // same errors
```
The Image::getITKImage function is just this, and works fine when used in C++:
```
  ImageType& getITKImage() { return *image; }
```

When using ITK in python, the type of their image is this:
```
import itk
itkimg = itk.imread("/tmp/test-works.png")
type(itkimg)
itk.itkImagePython.itkImageRGBUC2
```

In summary, we're not sure how to pass the itk Image pointer to Python. The ITK python module is implemented using swig.

**Comment by cchriste** [comment]
We need this for many important reasons, including using more specific itk functions to manipulate sw images in python and interactive visualization of sw images (see Examples/Python/notebooks/itk_image_from_swimg.ipynb).

**Comment by cchriste** [comment]
Similarly, we'd like to be able to construct a sw image from an itk image:

**Comment by cchriste** [comment]
Asked ITK devs: https://discourse.itk.org/t/how-to-pass-c-itk-image-to-python/3547

**Comment by cchriste** [comment]
Their devs suggested simply copying internal data back and forth using numpy. That way if a user wants to manipulate the itk image directly they can do so and simply copy the results back to their shapeworks image. It's less than ideal, but would at least suffice to quickly view an image in a Jupyter notebook, so it is worth demonstrating in our python module documentation (and demonstration notebook(s).

Updated task:
- demonstrate copying from sw image to numpy array in module docs
- demonstrate instantiating itk image from numpy array in module docs
- demonstrate using this in a Jupyter notebook to view an image (using view imported from itkwidgets)

The thread on itk devs provides details on how to do all this.

**Comment by cchriste** [comment]
In summary, we want to be able to convert between ShapeWorks Image to itk image and back.
- We can already go from sw to numpy ✅ 
- We have to fix #965 to go from numpy array to sw image.
- We already have sw2vtkImage, and can probably do something similar to go to itk image (these docs probably have the answer to go from numpy to itk: https://itkpythonpackage.readthedocs.io/en/master/Quick_start_guide.html).
- `sw2vtkImage`:
```python
# a helper function that converts shapeworks Image object to vtk image
def sw2vtkImage(swImg, verbose = False):
            
    # get the numpy array of the shapeworks image
    array  = swImg.toArray()
    
    # the numpy array needs to be permuted to match the shapeworks image dimensions
    array = np.transpose(array,(2,1,0))
    
    # converting a numpy array to a vtk image using pyvista's wrap function
    vtkImg = pv.wrap(array)
    
    if verbose:
        print('shapeworks image header information: ')
        print(swImg)

        print('\nvtk image header information: ')
        print(vtkImg) 
    
    return vtkImg
```

**Comment by cchriste** [comment]
`itk_np_copy = itk.image_from_array(np_copy)`

**Comment by cchriste** [comment]
different ways to do this, but we should at least provide a pymodule function

**Comment by cchriste** [comment]
@sheryjoe @archanasri @jadie1 @iyerkrithika21 
Should we provide this function? Are we still using itk anywhere else? 
It would be exactly the same as the sw2vtkImage above, just using the itk.image_from_array function instead (and calling the set_origin/spacing as presumably the vtk version does now). 
The main issue seems to be our notebook-crashing conflicts with itk python modules.

If not needed, we can close this issue.

**Comment by sheryjoe** [comment]
@jadie1 @iyerkrithika21 do we still need this function for our notebooks?

**Comment by jadie1** [comment]
No we are no longer using ITK widgets in the notebooks so we don't need this.
