### ISSUE TITLE
Dataset metadata field for image_use_cases

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#786]
Whether a use case has images or not should be a metadata field and the script can query this field without downloading the full dataset. 

Related to PR #784

**Comment by iyerkrithika21** [comment]
Include check in `sw.data` module

**Comment by jadie1** [comment]
Pushing to 6.3 because it will be addressed with the new portal

**Comment by iyerkrithika21** [comment]
Related #1384

**Comment by akenmorris** [comment]
This should be handled by the python library from the data portal
