### ISSUE TITLE
Implement gradient of normals for image domain

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#803]
Use [ITK's Hessian filter](https://itk.org/Doxygen/html/classitk_1_1HessianRecursiveGaussianImageFilter.html) to get hessians instead of implementing it via multiple DerivativeImageFilters in ParticleImageDomainWithHessians.h

(also look into adding a custom type to openvdb to store hessians directly, then we'd have to sample only once to get hessians instead of 6 times https://github.com/AcademySoftwareFoundation/openvdb/issues/696 )

**Comment by medakk** [comment]
using the Hessian filter will(might?) increase peak memory usage, need to make sure that is not too high

**Comment by sheryjoe** [comment]
It should be gradient of normals rather than hessian. Using openvdb for image domain.

**Comment by sheryjoe** [comment]
opening for more testing.
