### ISSUE TITLE
Update OptimizeUtils.py to handle multiple domains

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#804]
Make OptimizeUtils.py more general so that it can handle any number of domains.

Part 1: Change handling of parameters-

- [x] Number of particles 

- [x] Use normals

- [x] Attribute scales 

- [x] Use xyz

Part 2: Change the way constraints are handled

**Comment by iyerkrithika21** [comment]
#683

**Comment by iyerkrithika21** [comment]
[https://github.com/SCIInstitute/ShapeWorks/blob/multidomain/Examples/Python/OptimizeUtils.py](url)

Added functions to handle parameter values based on domains per shape

**Comment by iyerkrithika21** [comment]
In the function **runShapeWorksOptimize**, the xml file is created as follows: 

``numP = parameterDictionary['number_of_particles']
outDir = parentDir + '/' + str(numP) + '/'
if not os.path.exists(outDir):
    os.makedirs(outDir)
parameterFile = parentDir + "correspondence_" + str(numP) + ".xml"```

Now since the number_of_particles parameter is an array the XML created is **correspondence_[128, 128]** and the folder **[128,128]** are created. This might have to be changed.

**Comment by iyerkrithika21** [comment]
Changed the parameter file name format to : correspondence_128_128.xml

**Comment by sheryjoe** [comment]
@iyerkrithika21 is this still an issue?

**Comment by iyerkrithika21** [comment]
> 
> 
> @iyerkrithika21 is this still an issue?

Part 2 has not been addressed yet.

**Comment by HeavenlyBerserker** [comment]
I think we should create another issue for Part 2, since we're still not sure how constraints are ultimately gonna be handled in Python. I y'all agree, we can close this.

**Comment by sheryjoe** [comment]
Created another issue for handling constraints. #982 . Closing this one.
