### ISSUE TITLE
more accurately compute distance transforms from meshes

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#810]
Currently to get a distance transform from meshes we rasterize the mesh into a binary segmentation and then create a distance transforms from that. We want to directly convert meshes to distance transforms, this can be done using this trimesh function: [https://trimsh.org/trimesh.proximity.html?highlight=distance]( https://trimsh.org/trimesh.proximity.html?highlight=distance)

**Comment by jadie1** [comment]
Related to issue #529

**Comment by medakk** [comment]
There's a python library that does this https://pypi.org/project/mesh-to-sdf/

It uses python trimesh:

```python
from mesh_to_sdf import mesh_to_voxels

import trimesh
import skimage

mesh = trimesh.load('chair.obj')
voxels = mesh_to_voxels(mesh, 64, pad=True)
```



There's a VTK function to find mesh->point distance: [vtkDistancePolyDataFilter](https://vtk.org/doc/nightly/html/classvtkDistancePolyDataFilter.html), and another one to compute signed distance fields from vtkPolyData:[vtkSignedDistance](https://vtk.org/doc/nightly/html/classvtkSignedDistance.html)(but unfortunately treats it as a point cloud and not a mesh O.o). I'm not sure if there's a way to put the two together

**Comment by cchriste** [comment]
> There's a VTK function to find mesh->point distance: [vtkDistancePolyDataFilter](https://vtk.org/doc/nightly/html/classvtkDistancePolyDataFilter.html), and another one to compute signed distance fields from vtkPolyData:[vtkSignedDistance](https://vtk.org/doc/nightly/html/classvtkSignedDistance.html)(but unfortunately treats it as a point cloud and not a mesh O.o). I'm not sure if there's a way to put the two together

I wrestled with this for quite awhile last weekend. So annoyingly almost what we want!

**Comment by medakk** [comment]
> I wrestled with this for quite awhile last weekend. So annoyingly almost what we want!

Ah :(

There's a library called [Discregrid](https://github.com/InteractiveComputerGraphics/Discregrid), they have an example to [convert an OBJ file to a signed distance field](https://github.com/InteractiveComputerGraphics/Discregrid/blob/master/cmd/generate_sdf/main.cpp).

**Comment by cchriste** [comment]
Note: Libs/Mesh/GenerateBinaryAndDTImagesFromMeshes.cxx is an executable that both creates a volume from a mesh and computes distance transform. The distance transform isn't used and it's costly to compute.  
We now have `Mesh::toImage` to compute the volume and this issue is to add a function to compute the dt. 
In the meantime, dts can be computed by first calling Mesh.toImage, then Image.computeDT.

**Comment by sheryjoe** [comment]
Addressing this issue will make #1010 and #1011 irrelevant. See my comments there.

**Comment by cchriste** [comment]
> There's a library called [Discregrid](https://github.com/InteractiveComputerGraphics/Discregrid), they have an example to [convert an OBJ file to a signed distance field](https://github.com/InteractiveComputerGraphics/Discregrid/blob/master/cmd/generate_sdf/main.cpp).

This is what we're planning to try. We need some challenging tests cases. @medakk can you please share a scapula example? We'll compare both time and accuracy.

**Comment by sheryjoe** [comment]
to evaluate accuracy, given a mesh, compute a distance transform from trimesh2 or discregrid, then extract isosurface and compute surface2surface distance. What is the distribution of this error relative to voxel size used in conversion to distance transform?

this is important to deprecate fids.

**Comment by cchriste** [comment]
Solution: 
use `[classvtkImplicitPolyDataDistance](https://vtk.org/doc/nightly/html/classvtkImplicitPolyDataDistance.html)::FunctionValue(input, output)`, where `input` and `output` are `vtkDataArrays`, (which will be wrapped by our upcoming `Field` class), and `input` is initialized to the center of every voxel in the image.

**Comment by cchriste** [comment]
@archanasri This is basically the same as #1016, maybe just a duplicate, so I think we have it working in essence from what we did yesterday. Lots of good ideas for testing. I don't know that we need to use the other suggested libraries, but they're worth considering if it's slow or (for no apparent reason) inaccurate.

**Comment by cchriste** [comment]
If this is really high priority for 6.2, we should talk about it. It's been a minute (inverse hyperbole, not sarcasm), but it seems like we were really close to being done with this.

**Comment by cchriste** [comment]
NOTE: we want to try `vtkStaticCellLocator` instead of only `vtkCellLocator` since it claims to be multithreaded in the vtk docs. But this is not available until vtk version 9 (#725). It makes for a frustrating comparison since it might not only be faster, but more accurate. And it would be simpler to just use that rather than another library, though we will still compare with the other libs' methods.

**Comment by cchriste** [comment]
Note: the resolution of this issue will also address #935, #1515, #1420, #1408, #1504.

**Comment by cchriste** [comment]
> Note: the resolution of this issue will also address #935, #1515, #1420, #1408, #1504.

#935: Field class created (using vtkDataArray), but needs to be used everywhere
#1515: done
#1420: simple addition to command line (parameter of `get-field` or additional command to dump sharedData.field)
#1408: open
#1504: open
