### ISSUE TITLE
meshFIM::GetFeatureDerivative returns incorrect gradients

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#811]
Color: x coordinate of the normal at each vertex
Arrows: feature gradient returned by meshFIM
![image](https://user-images.githubusercontent.com/10536745/98997482-ce317c80-24f1-11eb-83f1-0130b4fe40c7.png)

in contrast, this is what libigl returns:
![image](https://user-images.githubusercontent.com/10536745/98997519-d984a800-24f1-11eb-95a4-660233729440.png)

We'll use libigl for now, and revisit this later if required.

**Comment by sheryjoe** [comment]
@medakk is this still an issue?

**Comment by medakk** [comment]
Yes, `meshFIM::GetFeatureDerivative` returns incorrect results. I don't see any point in fixing it however, the libigl gradient works fine.

**Comment by sheryjoe** [comment]
Closing this as we now rely on libigl for gradient computation.
@medakk
