### ISSUE TITLE
Data Portal Viz

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#815]
We'd like to add some viz-tools to the data portal to allow users to visualize shape models and data without having to wait for 10+ GB download.
Related to issue #696

**Comment by sheryjoe** [comment]
@jadie1 @riddhishb @akenmorris 
Can we add sub-issues for Wasim to work on? We can use this issue as the parent one.

**Comment by jadie1** [comment]
Can we close this issue here now that kitware is working on it?
