### ISSUE TITLE
Toy Data Python Module

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#816]
We want to add a Python module for generating parameterized toy data (meshes, segmentation, and images). This data will be useful for testing and debugging. 
This will include:
- Ellipsoids 
- SuperShapes

**Comment by iyerkrithika21** [comment]
Tutorial notebook added: https://github.com/SCIInstitute/ShapeWorks/blob/generate_shape/Examples/Python/notebooks/tutorials/getting-started-with-ShapeGenerator.ipynb
