### ISSUE TITLE
Redesign Groom Utils

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#818]
Redesign groom utils so it can be run interactively rather than batch wise. 
This will make it so intermediate grooming files don't have to be saved (issue #598) and steps can be skipped (issue #507)

**Comment by sheryjoe** [comment]
Pushing this to the next release. Use cases and their documentation need to be restructured around shapeworks python library.

**Comment by sheryjoe** [comment]
Related to #818
