### ISSUE TITLE
migrate existing Matlab code to ShapeWorks to reduce number of particles on a mesh

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#82]
Praful has some code to do this and it will dramatically reduce our memory usage in ShapeWorks for the same task. 

He will introduce us to the code and we will make a plan (asap) to port this to C++.

**Comment by cchriste** [comment]
@sheryjoe ?

**Comment by sheryjoe** [comment]
I don't recall details about this issue. @prafulag, is this related to removing redundant vertices in the output mesh of PreviewCmd?

**Comment by cchriste** [comment]
@akenmorris @sheryjoe @prafulag @AtefehKashani Anyone have any ideas what this is about? Are there too many particles on a mesh? If not, can we close it?

**Comment by akenmorris** [comment]
No idea from me.

**Comment by sheryjoe** [comment]
ShapeWorks for meshes is the optimization of particles directly on meshes that we developed originally by Praful (matlab) and migrated to c++ by Oleks and further improved by Karthik. 

I recall the "migrate" part of the issue but not "to reduce number of particles on a mesh".  I think we can close this issue.
