### ISSUE TITLE
Summary values for sw image

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#824]
import shapeworks as sw
swImg = sw.Image(filename)

the following apis are not supported - a quick work around is to convert to numpy array and provide these summarized values for image data.

minvalue = swImg.min()
maxvalue = swImg.max()
meanvalue = swImg.mean()
stdvalue = swImg.std()

**Comment by sheryjoe** [comment]
@archanasri @cchriste is this still an issue?

**Comment by archanasri** [comment]
@sheryjoe yes it is

**Comment by cchriste** [comment]
I suggest we create a python function to include with our module that does just this.
