### ISSUE TITLE
Update shapeworks.sw2vtkMesh to export mesh vertices, edges, and polys rather than read/write to disk

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#825]
Similar to shapeworks.Image, we want to convert a shapeworks mesh to itk or vtk data structure to be visualized by itkwidgets, which supports both itk:Mesh and vtk::PolyData

This also will be very handy when visualizing multiple samples in a grid view using pyvista.

For now, a workaround would be saving the mesh/image and re-reading it for visualization.

**Comment by sheryjoe** [comment]
Update for sw.Image: 
- Converting to itk image can be done by extracting a numpy array from a sw image and use itk.GetImageFromArray
- Converting to vtk image can be done by extracting a numpy array from a sw image and use pyvista.wrap 

These helper functions will be soon demonstrated in our notebook tutorials. These helper functions can be included in shapeworks __init__.py 

I will provide more updates on sw.Mesh later.

**Comment by sheryjoe** [comment]
For sw.Mesh, we need access to mesh vertices and faces to construct itkMesh and vtkPolyData in python.

**Comment by sheryjoe** [comment]
pyvista wrap function can wrap vtkPolyData and trimesh (python) objects. If we can get the vertices and faces as arrays from sw.Mesh, we can construct vtkPolydata in python and use pv.wrap for visualization.

**Comment by sheryjoe** [comment]
Please, update notebooks to replace sw2vtk sw2itk helper functions.

**Comment by cchriste** [comment]
This may simply not be possible from c++, but these helpers should be in the pymodule.
For now, they will be moved into pymodule (by @jadie1 and @iyerkrithika21)

**Comment by sheryjoe** [comment]
@jadie1 @iyerkrithika21 please address this issue as you resolve #1173 and #865.

**Comment by archanasri** [comment]
I don't think we need toItk anymore since we are not going to use itkwidgets.

**Comment by sheryjoe** [comment]
@archanasri is this still an issue?

**Comment by archanasri** [comment]
> pyvista wrap function can wrap vtkPolyData and trimesh (python) objects. If we can get the vertices and faces as arrays from sw.Mesh, we can construct vtkPolydata in python and use pv.wrap for visualization.

In order to construct the mesh after obtaining the two arrays, we need to import vtk or import trimesh. Is this something we want to do?
importing itk always led to more issues

**Comment by cchriste** [comment]
> > pyvista wrap function can wrap vtkPolyData and trimesh (python) objects. If we can get the vertices and faces as arrays from sw.Mesh, we can construct vtkPolydata in python and use pv.wrap for visualization.
> 
> In order to construct the mesh after obtaining the two arrays, we need to import vtk or import trimesh. Is this something we want to do?
> importing itk always leads to more issues

Agreed. And we essentially already have these functions in our module (we can add sw2itk if we want, but since our "resolution" to so many itk issues is to simply not include it, this would go against that). Implementing them on the C++ side--they already are, just not provided as part of our module--would provide no benefit.

**Comment by archanasri** [comment]
So should we just leave sw2vtk as it is? It currently writes out the sw mesh and loads the same mesh using pyvista.read

**Comment by cchriste** [comment]
> So should we just leave sw2vtk as it is? It currently writes out the sw mesh and loads the same mesh using pyvista.read

This works fine, but should probably not use the disk.
I changed the name of the issue to address this remaining item specifically (formerly "Add toItk / toVtk to python sw.Mesh and shapeworks.Image).

I don't think resolving this is necessary for 6.1, and possibly not at all, though similarly to #903, sharing memory will be more efficient than copying.

**Comment by cchriste** [comment]
These functions exist in shapeworks python module as `shapeworks.sw2VtkImage` and `sw2vtkMesh`.
Their names should be changed to be simply `toVtk` (maybe `toVtkImage`/`toVtkMesh`, or use Python overloading module; we do utilize overloading for the C++ bindings, so it's a reasonable expectation).

#903 will automatically improve performance (note: this should be used as a test and performance comparison for that issue).

**Comment by cchriste** [comment]
> Their names should be changed to be simply `toVtk` (maybe `toVtkImage`/`toVtkMesh`

I no longer agree with myself about renaming: `sw2vtk[Image|Mesh]` seems fine.

> #903 will automatically improve performance

This now works efficiently and even the internal data pointer in the wrapped image points directly back to the image.
No copies were made in the wrapping of the Image for pyvista visualization. 👍

**Comment by archanasri** [comment]
@cchriste It looks like this issue can be closed. Do you want to discuss this offline?

**Comment by cchriste** [comment]
From our discussion yesterday, the best way to convert a shapeworks.Mesh to a vtkImage (wrapped by pyvista) will be to retrieve the vertices, faces, [and any fields], using the example here: https://docs.pyvista.org/examples/00-load/create-poly.html#sphx-glr-examples-00-load-create-poly-py

All of these can be fetched without copying similar to Images. The quantity of data is significant and unlikely to be re-allocated with every filter.  Therefore sharing without copying should also increase efficiency.
