### ISSUE TITLE
print header information for shapeworks Mesh

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#828]
for a shapeworks Image class, print(swImage) prints image header information that includes image dimensions (rows, columns and slices), physical origin, physical size, and voxel spacing (in physical units).

We need a similar functionality for shapeworks Mesh class so print(swMesh) should print number of faces, number of vertices, and min and max of x-, y-, and z- coordinates.

**Comment by archanasri** [comment]
![image](https://user-images.githubusercontent.com/31980477/101536565-68e97380-3957-11eb-827d-79f1c5381501.png)

**Comment by archanasri** [comment]
Done with commit 31734b4
