### ISSUE TITLE
resampling adds a slice of zeros

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#833]
shapeSeg.resample(sw.Vector(isoSpacing,isoSpacing,isoSpacing), sw.InterpolationType.Linear ) adds a slice of zeros

Below is ellipsoid_00 in ellispoid-v1

<img width="960" alt="image" src="https://user-images.githubusercontent.com/3253036/100529197-0b5c6680-31a2-11eb-8124-8ea106dcf7ff.png">

isosurface 

<img width="952" alt="image" src="https://user-images.githubusercontent.com/3253036/100529199-2038fa00-31a2-11eb-95cb-110c54a3cdc0.png">

**Comment by archanasri** [comment]
It seems to be working for us. Were any other functions used before this?
<img width="1000" alt="Screen Shot 2021-01-16 at 3 40 21 PM" src="https://user-images.githubusercontent.com/31980477/104824697-49c0ea00-5811-11eb-9577-35ade0e5cc3c.png">

**Comment by cchriste** [comment]
@cchriste @archanasri Please run the "getting started with segmentations" notebook to verify this is working. It mentions this issue at the line that produces the incorrect result.

**Comment by cchriste** [comment]
Also, the passing-then-resampling #831 to verify the resampling since it also illustrates the extra slice of zeros (look closely at the red box in one of the Paraview images)

**Comment by cchriste** [comment]
Fixed by dc000af2db62a9ba390061d374205d324496ed11
Will be merged with #905 
<img width="849" alt="Screen Shot 2021-01-20 at 6 00 25 PM" src="https://user-images.githubusercontent.com/1260945/105260344-e0134980-5b4a-11eb-9aa1-c9fdacfc51af.png">

**Comment by archanasri** [comment]
Fix merged to master.
