### ISSUE TITLE
DeepSSM looking for femur shape_model in wrong folder

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#834]
I tried `python RunUseCase.py --use_case deep_ssm --shapeworks_path ../../build/cmake-build-release/bin/` on master but it crashed saying:

```
Step 1. Get Data
Unzipping Data/femur-v0.zip into Output/deep_ssm/
Traceback (most recent call last):
  File "RunUseCase.py", line 72, in <module>
    module.Run_Pipeline(args)
  File "/scratch/karthik/projects/ShapeWorks/Examples/Python/deep_ssm.py", line 39, in Run_Pipeline
    for file in os.listdir(model_dir):
FileNotFoundError: [Errno 2] No such file or directory: 'Output/deep_ssm/femur-v0/shape_models/femur/1024/'
```

this is likely because the particle files are now in multi_scale/1024

**Comment by jadie1** [comment]
@medakk I am not sure why you are seeing a multi-scale folder. Here is what is on the portal: 
![image](https://user-images.githubusercontent.com/54382613/100653557-d832e800-3305-11eb-8ca8-6157a6f7f1a8.png)
'use-case-data-v2/femur-v0/' should get unzipped to 'Output/deep_ssm/femur-v0/' so the path looks right to me.

**Comment by sheryjoe** [comment]
Please remove Data/femur-v0.zip and rerun the use case.

**Comment by jadie1** [comment]
I have verified that this is not an issue when using the current femur-v0.zip
