### ISSUE TITLE
update ellispoid-v1/segmentations to have different image sizes

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#835]
This is a very nice toy example that demonstrates the grooming pipeline. Can we change the segmentations so that they have different image sizes? I would resize the images rather than padding them to maintain some of these shapes touching the image boundaries.

**Comment by iyerkrithika21** [comment]
5/6 pixel std in each dimension

**Comment by iyerkrithika21** [comment]
Added to ShapeCohortGen package
@sheryjoe can we close this issue?

**Comment by sheryjoe** [comment]
> Added to ShapeCohortGen package
> @sheryjoe can we close this issue?

Yes. Please add here the link for the commit or PR that has addresses this issue.

**Comment by iyerkrithika21** [comment]
Done with commit generate_shapes@0098d649b62a04e5b954748963228ae4babf9743
