### ISSUE TITLE
Update FEVTKimport::Load to just binary vtk files

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#838]
Currently this function painstakingly reads by hand lines of the ASCII "legacy" vtk files.
It should instead just read the binary vtk polydata and pick whatever data it needs out of it.
(which means if we have other stuff that manually writes ascii vtk files, it will also have to write binary versions) 

Because...
In vtk 9, they changed how ascii vtk files are written, which makes them unable to be read by our class as well as any other products that use vtk < 9 (such as ParaView). 

We need to upgrade to vtk 9 since our inability to do so now (however not okay it was for them to change the format of their own "legacy" file format) is blocking other items, such as merging pybind (#798) in order to use our Python API.

**Comment by cchriste** [comment]
From our discussion during our 11/30 meeting it seems it might be more appropriate to write the old vtk ascii files when we export them since they need to be imported by other apps that don't know about the change to the ascii format either.

**Comment by cchriste** [comment]
Is this still an issue?

**Comment by sheryjoe** [comment]
We might not need this once we deprecate the FEMesh lib.

**Comment by akenmorris** [comment]
Not needed.
