### ISSUE TITLE
Upgrade to python 3.9

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#839]

**Comment by sheryjoe** [comment]
@akenmorris @cchriste 

Upgrading to 3.8 results in lots of packages conflicts. Was this the argument for not to upgrade? thoughts?


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting pip
  Downloading pip-20.3-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 2.3 MB/s 
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
Successfully installed pip-20.3
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                                                                     /  

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - scikit-learn=0.21.3 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8.6

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package zlib conflicts for:
vtk=8.2.0 -> zlib[version='>=1.2.11,<1.3.0a0']
cmake=3.18.2 -> zlib[version='>=1.2.11,<1.3.0a0']
requests=2.24.0 -> python -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8|1.2.11.*']
vtk=8.2.0 -> python[version='>=3.6,<3.7.0a0'] -> zlib[version='1.2.*|1.2.11|1.2.8|1.2.11.*']
colorama=0.4.3 -> python -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8|1.2.11.*']
notebook=6.1.5 -> python[version='>=3.8,<3.9.0a0'] -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8']
boost=1.72.0 -> boost-cpp=1.72.0 -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8|1.2.11.*']
geotiff=1.6.0 -> zlib[version='>=1.2.11,<1.3.0a0']
pybind11=2.5.0 -> python[version='>=3.6,<3.7.0a0'] -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8']
scikit-learn=0.21.3 -> python[version='>=3.6,<3.7.0a0'] -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8']
graphviz=2.38.0 -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8']
openexr=2.5.3 -> zlib[version='>=1.2.11,<1.3.0a0']
python=3.8.6 -> zlib[version='>=1.2.11,<1.3.0a0']
numpy=1.19.1 -> python[version='>=3.7,<3.8.0a0'] -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8']

Package expat conflicts for:
notebook=6.1.5 -> pypy3.6[version='>=7.3.2'] -> expat[version='>=2.2.9,<2.3.0a0']
cmake=3.18.2 -> expat[version='>=2.2.9,<2.3.0a0|>=2.2.9,<3.0a0']
numpy=1.19.1 -> pypy3.6[version='>=7.3.1'] -> expat[version='>=2.2.9,<2.3.0a0']
pybind11=2.5.0 -> pypy3.6[version='>=7.3.2'] -> expat[version='>=2.2.9,<2.3.0a0']
vtk=8.2.0 -> expat[version='>=2.2.5,<2.3.0a0|>=2.2.9,<2.3.0a0|>=2.2.6,<3.0a0']

Package libcxx conflicts for:
doxygen=1.8.20 -> libcxx[version='>=10.0.1|>=11.0.0']
colorama=0.4.3 -> python -> libcxx[version='>=10.0.0|>=10.0.1|>=11.0.0|>=9.0.1|>=9.0.0|>=4.0.1']
tbb=2019.9 -> libcxx[version='>=9.0.0']
geotiff=1.6.0 -> libtiff[version='>=4.1.0,<5.0a0'] -> libcxx[version='>=4.0.1|>=9.0.0']
graphviz=2.38.0 -> libtiff[version='>=4.0.9,<5.0a0'] -> libcxx[version='>=10.0.0|>=10.0.1|>=9.0.1|>=9.0.0']
pybind11=2.5.0 -> libcxx[version='>=10.0.0|>=10.0.1|>=9.0.1']
notebook=6.1.5 -> python[version='>=3.8,<3.9.0a0'] -> libcxx[version='>=10.0.0|>=10.0.1|>=11.0.0|>=9.0.1|>=9.0.0|>=4.0.1']
openexr=2.5.3 -> libcxx[version='>=10.0.1']
gtest=1.10.0 -> libcxx[version='>=10.0.1|>=11.0.0|>=9.0.1|>=9.0.0']
boost=1.72.0 -> boost-cpp=1.72.0 -> libcxx[version='>=10.0.0|>=11.0.0|>=9.0.0|>=4.0.1']
vtk=8.2.0 -> expat[version='>=2.2.9,<2.3.0a0'] -> libcxx[version='>=10.0.0|>=10.0.1|>=11.0.0']
scikit-learn=0.21.3 -> libcxx[version='>=4.0.1']
scikit-learn=0.21.3 -> python[version='>=3.6,<3.7.0a0'] -> libcxx[version='>=10.0.0|>=10.0.1|>=11.0.0|>=9.0.1|>=9.0.0']
cmake=3.18.2 -> libcxx[version='>=10.0.0|>=10.0.1']
vtk=8.2.0 -> libcxx[version='>=4.0.1|>=9.0.0|>=9.0.1']
pybind11=2.5.0 -> python[version='>=3.6,<3.7.0a0'] -> libcxx[version='>=11.0.0|>=9.0.0|>=4.0.1']
geotiff=1.6.0 -> libcxx[version='>=10.0.0|>=10.0.1|>=9.0.1']
python=3.8.6 -> libcxx[version='>=10.0.1|>=11.0.0']
python=3.8.6 -> libffi[version='>=3.3,<3.4.0a0'] -> libcxx[version='>=10.0.0|>=4.0.1|>=9.0.1']
cmake=3.18.2 -> expat[version='>=2.2.9,<2.3.0a0'] -> libcxx[version='>=4.0.1|>=9.0.1']
numpy=1.19.1 -> python[version='>=3.7,<3.8.0a0'] -> libcxx[version='>=10.0.0|>=10.0.1|>=11.0.0|>=9.0.1|>=9.0.0|>=4.0.1']
graphviz=2.38.0 -> libcxx[version='>=4.0.1']
requests=2.24.0 -> python -> libcxx[version='>=10.0.0|>=10.0.1|>=11.0.0|>=9.0.1|>=9.0.0|>=4.0.1']
boost=1.72.0 -> libcxx[version='>=10.0.1|>=9.0.1']
tbb-devel=2019.9 -> libcxx[version='>=9.0.0']

Package bzip2 conflicts for:
pybind11=2.5.0 -> python[version='>=3.6,<3.7.0a0'] -> bzip2[version='>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']
colorama=0.4.3 -> python -> bzip2[version='>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']
notebook=6.1.5 -> python[version='>=3.8,<3.9.0a0'] -> bzip2[version='>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']
requests=2.24.0 -> python -> bzip2[version='>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']
cmake=3.18.2 -> bzip2[version='>=1.0.8,<2.0a0']
numpy=1.19.1 -> python[version='>=3.7,<3.8.0a0'] -> bzip2[version='>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']
scikit-learn=0.21.3 -> python[version='>=3.6,<3.7.0a0'] -> bzip2[version='>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']
vtk=8.2.0 -> libnetcdf[version='>=4.7.4,<4.7.5.0a0'] -> bzip2[version='>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']
boost=1.72.0 -> boost-cpp=1.72.0 -> bzip2[version='>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']

Package xz conflicts for:
scikit-learn=0.21.3 -> python[version='>=3.6,<3.7.0a0'] -> xz[version='5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
requests=2.24.0 -> python -> xz[version='5.0.*|5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
boost=1.72.0 -> boost-cpp=1.72.0 -> xz[version='5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
pybind11=2.5.0 -> python[version='>=3.6,<3.7.0a0'] -> xz[version='5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
vtk=8.2.0 -> libtiff[version='>=4.1.0,<5.0a0'] -> xz[version='5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
geotiff=1.6.0 -> libtiff[version='>=4.1.0,<5.0a0'] -> xz[version='>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0']
colorama=0.4.3 -> python -> xz[version='5.0.*|5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
notebook=6.1.5 -> python[version='>=3.8,<3.9.0a0'] -> xz[version='5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
cmake=3.18.2 -> xz[version='>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0']
graphviz=2.38.0 -> libtiff[version='>=4.0.9,<5.0a0'] -> xz[version='5.0.*|5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
numpy=1.19.1 -> python[version='>=3.7,<3.8.0a0'] -> xz[version='5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
python=3.8.6 -> xz[version='>=5.2.5,<5.3.0a0']

Package pypy3.6 conflicts for:
vtk=8.2.0 -> future -> pypy3.6[version='7.3.0.*|7.3.1.*|7.3.2.*|>=7.3.2']
pybind11=2.5.0 -> pypy3.6[version='>=7.3.2']
pybind11=2.5.0 -> python[version='>=3.6,<3.7.0a0'] -> pypy3.6[version='7.3.*|7.3.0.*|7.3.1.*|7.3.2.*']
colorama=0.4.3 -> python -> pypy3.6[version='7.3.0.*|7.3.1.*|7.3.2.*']
boost=1.72.0 -> numpy[version='>=1.16.5,<2.0a0'] -> pypy3.6[version='7.3.0.*|7.3.1.*|7.3.2.*|>=7.3.1|>=7.3.2']
notebook=6.1.5 -> argon2-cffi -> pypy3.6[version='7.3.*|7.3.0.*|7.3.1.*|7.3.2.*|>=7.3.1']
requests=2.24.0 -> certifi[version='>=2017.4.17'] -> pypy3.6[version='7.3.0.*|7.3.1.*|7.3.2.*|>=7.3.1|>=7.3.2']
numpy=1.19.1 -> python[version='>=3.6,<3.7.0a0'] -> pypy3.6[version='7.3.*|7.3.0.*|7.3.1.*|7.3.2.*']
notebook=6.1.5 -> pypy3.6[version='>=7.3.2']
scikit-learn=0.21.3 -> numpy[version='>=1.14.6,<2.0a0'] -> pypy3.6[version='7.3.0.*|7.3.1.*|7.3.2.*|>=7.3.1|>=7.3.2']
numpy=1.19.1 -> pypy3.6[version='>=7.3.1']

Package libgfortran conflicts for:
scikit-learn=0.21.3 -> libcblas[version='>=3.8.0,<4.0a0'] -> libgfortran[version='4.*|5.*|>=4.0.0,<5.0.0.a0|>=3.0.1,<4.0.0.a0|>=3.0,<4.0.0.a0|>=3.0.1']
openblas=0.3.6 -> libgfortran[version='>=3.0.1,<4.0.0.a0|>=4.0.0,<5.0.0.a0']
numpy=1.19.1 -> libblas[version='>=3.8.0,<4.0a0'] -> libgfortran[version='4.*|5.*|>=4.0.0,<5.0.0.a0|>=3.0.1,<4.0.0.a0|>=3.0.1']
vtk=8.2.0 -> hdf5[version='>=1.10.6,<1.10.7.0a0'] -> libgfortran[version='4.*|5.*|>=4.0.0,<5.0.0.a0|>=3.0.1,<4.0.0.a0|>=3.0.1']
boost=1.72.0 -> numpy[version='>=1.16.5,<2.0a0'] -> libgfortran[version='>=3.0,<4.0.0.a0|>=3.0.1,<4.0.0.a0|>=3.0.1']

Package ncurses conflicts for:
python=3.8.6 -> readline[version='>=8.0,<9.0a0'] -> ncurses[version='>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.1,<7.0a0|>=6.2,<7.0a0']
notebook=6.1.5 -> python[version='>=3.8,<3.9.0a0'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0|>=6.2,<6.3.0a0']
requests=2.24.0 -> python -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']
pybind11=2.5.0 -> python[version='>=3.6,<3.7.0a0'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']
numpy=1.19.1 -> python[version='>=3.7,<3.8.0a0'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.1,<7.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0']
scikit-learn=0.21.3 -> python[version='>=3.6,<3.7.0a0'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']
vtk=8.2.0 -> python[version='>=3.7,<3.8.0a0'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.1,<7.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0']
cmake=3.18.2 -> ncurses[version='>=6.2,<6.3.0a0|>=6.2,<7.0a0']
colorama=0.4.3 -> python -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']
boost=1.72.0 -> python[version='>=3.7,<3.8.0a0'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.1,<7.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0']

Package gdbm conflicts for:
numpy=1.19.1 -> pypy3.6[version='>=7.3.1'] -> gdbm[version='>=1.18,<1.19.0a0']
pybind11=2.5.0 -> pypy3.6[version='>=7.3.2'] -> gdbm[version='>=1.18,<1.19.0a0']
notebook=6.1.5 -> pypy3.6[version='>=7.3.2'] -> gdbm[version='>=1.18,<1.19.0a0']

Package sqlite conflicts for:
requests=2.24.0 -> python -> sqlite[version='3.13.*|3.20.*|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|3.9.*|>=3.31.1,<4.0a0|>=3.30.0,<4.0a0|>=3.29.0,<4.0a0|>=3.27.2,<4.0a0|>=3.23.1,<4.0a0|>=3.22.0,<4.0a0|>=3.20.1,<4.0a0']
colorama=0.4.3 -> python -> sqlite[version='3.13.*|3.20.*|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|3.9.*|>=3.31.1,<4.0a0|>=3.30.0,<4.0a0|>=3.29.0,<4.0a0|>=3.27.2,<4.0a0|>=3.23.1,<4.0a0|>=3.22.0,<4.0a0|>=3.20.1,<4.0a0']
pybind11=2.5.0 -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='3.13.*|3.20.*|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.23.1,<4.0a0|>=3.22.0,<4.0a0|>=3.20.1,<4.0a0|>=3.25.1,<4.0a0|>=3.27.2,<4.0a0|>=3.30.0,<4.0a0']
python=3.8.6 -> sqlite[version='>=3.33.0,<4.0a0']
vtk=8.2.0 -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='3.13.*|3.20.*|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.27.2,<4.0a0|>=3.30.0,<4.0a0|>=3.23.1,<4.0a0|>=3.22.0,<4.0a0|>=3.20.1,<4.0a0']
numpy=1.19.1 -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='3.13.*|3.20.*|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.27.2,<4.0a0|>=3.23.1,<4.0a0|>=3.22.0,<4.0a0|>=3.20.1,<4.0a0|>=3.30.0,<4.0a0']
scikit-learn=0.21.3 -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='3.13.*|3.20.*|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.23.1,<4.0a0|>=3.22.0,<4.0a0|>=3.20.1,<4.0a0|>=3.25.1,<4.0a0|>=3.27.2,<4.0a0']
boost=1.72.0 -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='3.13.*|3.20.*|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.27.2,<4.0a0|>=3.23.1,<4.0a0|>=3.22.0,<4.0a0|>=3.20.1,<4.0a0|>=3.30.0,<4.0a0']
notebook=6.1.5 -> python[version='>=3.8,<3.9.0a0'] -> sqlite[version='3.13.*|3.20.*|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.23.1,<4.0a0|>=3.22.0,<4.0a0|>=3.20.1,<4.0a0|>=3.25.1,<4.0a0|>=3.27.2,<4.0a0']
geotiff=1.6.0 -> proj[version='>=7.2.0,<7.2.1.0a0'] -> sqlite[version='>=3.30.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|>=3.31.1,<4.0a0']

Package setuptools conflicts for:
python=3.8.6 -> pip -> setuptools
scikit-learn=0.21.3 -> joblib[version='>=0.11'] -> setuptools
notebook=6.1.5 -> jinja2 -> setuptools

Package tbb conflicts for:
vtk=8.2.0 -> tbb[version='>=2019.1|>=2019.4|>=2019.7|>=2019.9']
tbb-devel=2019.9 -> tbb==2019.9[build='ha1b3eb9_1|ha1b3eb9_0']

Package zstd conflicts for:
boost=1.72.0 -> boost-cpp=1.72.0 -> zstd[version='>=1.4.4,<1.5.0.0a0|>=1.4.5,<1.5.0a0']
cmake=3.18.2 -> zstd[version='>=1.4.5,<1.4.6.0a0']
vtk=8.2.0 -> libtiff[version='>=4.1.0,<5.0a0'] -> zstd[version='>=1.3.3,<1.3.4.0a0|>=1.3.7,<1.3.8.0a0|>=1.4.4,<1.4.5.0a0|>=1.4|>=1.4.3,<1.5.0.0a0|>=1.4.4,<1.5.0.0a0|>=1.4.5,<1.5.0a0|>=1.4.4,<1.5.0a0|>=1.4.0,<1.5.0.0a0']
geotiff=1.6.0 -> libtiff[version='>=4.1.0,<5.0a0'] -> zstd[version='>=1.3.7,<1.3.8.0a0|>=1.4.4,<1.4.5.0a0|>=1.4|>=1.4.3,<1.5.0.0a0|>=1.4.4,<1.5.0.0a0|>=1.4.5,<1.5.0a0|>=1.4.4,<1.5.0a0']
graphviz=2.38.0 -> libtiff[version='>=4.0.9,<5.0a0'] -> zstd[version='>=1.3.3,<1.3.4.0a0|>=1.4.0,<1.5.0.0a0|>=1.4.3,<1.5.0.0a0|>=1.4.4,<1.5.0.0a0|>=1.4.5,<1.5.0a0|>=1.4|>=1.4.4,<1.4.5.0a0|>=1.3.7,<1.3.8.0a0|>=1.4.4,<1.5.0a0']

Package ca-certificates conflicts for:
colorama=0.4.3 -> python -> ca-certificates
python=3.8.6 -> openssl[version='>=1.1.1h,<1.1.2a'] -> ca-certificates
boost=1.72.0 -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
requests=2.24.0 -> python -> ca-certificates
vtk=8.2.0 -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates

Package libcurl conflicts for:
cmake=3.18.2 -> libcurl[version='>=7.71.1,<8.0a0']
vtk=8.2.0 -> hdf5[version='>=1.10.6,<1.10.7.0a0'] -> libcurl[version='>=7.59.0,<8.0a0|>=7.61.0,<8.0a0|>=7.61.1,<8.0a0|>=7.63.0,<8.0a0|>=7.68.0,<8.0a0|>=7.71.1,<8.0a0']
geotiff=1.6.0 -> proj[version='>=7.2.0,<7.2.1.0a0'] -> libcurl[version='>=7.64.1,<8.0a0|>=7.69.1,<8.0a0|>=7.71.0,<8.0a0|>=7.71.1,<8.0a0']

Package tzdata conflicts for:
pybind11=2.5.0 -> python[version='>=3.9,<3.10.0a0'] -> tzdata
boost=1.72.0 -> python[version='>=3.9,<3.10.0a0'] -> tzdata
requests=2.24.0 -> python -> tzdata
notebook=6.1.5 -> python[version='>=3.9,<3.10.0a0'] -> tzdata
colorama=0.4.3 -> python -> tzdata

Package llvm-openmp conflicts for:
scikit-learn=0.21.3 -> mkl[version='>=2019.4,<2020.0a0'] -> llvm-openmp[version='>=10.0.0|>=10.0.1|>=11.0.0|>=9.0.1|>=9.0.0']
numpy=1.19.1 -> mkl[version='>=2019.4,<2020.0a0'] -> llvm-openmp[version='>=10.0.0|>=10.0.1|>=11.0.0|>=9.0.1|>=9.0.0']
scikit-learn=0.21.3 -> llvm-openmp
openblas=0.3.6 -> libgfortran[version='>=4.0.0,<5.0.0.a0'] -> llvm-openmp[version='>=8.0.0|>=8.0.1']

Package freetype conflicts for:
graphviz=2.38.0 -> freetype[version='2.5.*|2.6.*|2.7|2.7.*|2.7|2.8.1|>=2.8.1,<2.9.0a0|>=2.9.1,<3.0a0']
vtk=8.2.0 -> freetype[version='>=2.9.1,<3.0a0']

Package icu conflicts for:
boost=1.72.0 -> boost-cpp=1.72.0 -> icu[version='>=64.2,<65.0a0|>=67.1,<68.0a0|>=68.1,<69.0a0']
vtk=8.2.0 -> libxml2[version='>=2.9.10,<2.10.0a0'] -> icu[version='>=58.2,<59.0a0|>=64.2,<65.0a0|>=67.1,<68.0a0']

Package lz4-c conflicts for:
cmake=3.18.2 -> zstd[version='>=1.4.5,<1.4.6.0a0'] -> lz4-c[version='>=1.9.2,<1.10.0a0|>=1.9.2,<1.9.3.0a0']
vtk=8.2.0 -> lz4-c[version='>=1.8.1.2,<1.8.2.0a0|>=1.8.3,<1.8.4.0a0|>=1.9.2,<1.9.3.0a0|>=1.8.1.2,<1.9.0a0']

Package libcxxabi conflicts for:
scikit-learn=0.21.3 -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='1|2|4|0|3|hcfea43d_1|hebd6815_0']
graphviz=2.38.0 -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='1|2|4|0|3|hcfea43d_1|hebd6815_0']
vtk=8.2.0 -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='1|2|4|0|3|hcfea43d_1|hebd6815_0']

Package six conflicts for:
numpy=1.19.1 -> mkl-service[version='>=2,<3.0a0'] -> six
scikit-learn=0.21.3 -> mkl-service[version='>=2,<3.0a0'] -> six
notebook=6.1.5 -> argon2-cffi -> six

Package python_abi conflicts for:
boost=1.72.0 -> python_abi[version='3.6.*|3.7.*|3.9.*|3.8.*',build='*_cp38|*_cp36m|*_cp37m|*_cp39']
boost=1.72.0 -> numpy[version='>=1.16.5,<2.0a0'] -> python_abi==3.6[build=*_pypy36_pp73]

Package numpy conflicts for:
boost=1.72.0 -> numpy[version='>=1.14.6,<2.0a0|>=1.16.5,<2.0a0|>=1.19.2,<2.0a0']
scikit-learn=0.21.3 -> numpy[version='>=1.11.3,<2.0a0|>=1.14.6,<2.0a0']
scikit-learn=0.21.3 -> scipy -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11|>=1.16.5,<2.0a0|>=1.18.5,<2.0a0|>=1.19.2,<2.0a0|>=1.18.1,<2.0a0|>=1.9.3,<2.0a0|>=1.9|>=1.16.6,<2.0a0|>=1.15.1,<2.0a0']

Package libgfortran4 conflicts for:
openblas=0.3.6 -> libgfortran[version='>=4.0.0,<5.0.0.a0'] -> libgfortran4
scikit-learn=0.21.3 -> libcblas[version='>=3.8.0,<4.0a0'] -> libgfortran4[version='>=7.5.0']
vtk=8.2.0 -> hdf5[version='>=1.10.6,<1.10.7.0a0'] -> libgfortran4[version='>=7.5.0']
numpy=1.19.1 -> libblas[version='>=3.8.0,<4.0a0'] -> libgfortran4[version='>=7.5.0']

Package libpng conflicts for:
vtk=8.2.0 -> libpng[version='>=1.6.35,<1.7.0a0|>=1.6.37,<1.7.0a0|>=1.6.36,<1.7.0a0']
vtk=8.2.0 -> freetype[version='>=2.9.1,<3.0a0'] -> libpng[version='>=1.6.23,<1.7|>=1.6.34,<1.7.0a0']

Package libgfortran5 conflicts for:
scikit-learn=0.21.3 -> libcblas[version='>=3.8.0,<4.0a0'] -> libgfortran5[version='>=9.3.0']
numpy=1.19.1 -> libblas[version='>=3.8.0,<4.0a0'] -> libgfortran5[version='>=9.3.0']
vtk=8.2.0 -> hdf5[version='>=1.10.6,<1.10.7.0a0'] -> libgfortran5[version='>=9.3.0']

Package libwebp conflicts for:
vtk=8.2.0 -> libtiff[version='>=4.1.0,<5.0a0'] -> libwebp
graphviz=2.38.0 -> libtiff[version='>=4.0.9,<5.0a0'] -> libwebp
geotiff=1.6.0 -> libtiff[version='>=4.1.0,<5.0a0'] -> libwebp

Package libiconv conflicts for:
doxygen=1.8.20 -> libiconv[version='>=1.16,<1.17.0a0']
vtk=8.2.0 -> libxml2[version='>=2.9.10,<2.10.0a0'] -> libiconv[version='>=1.15,<1.17.0a0|>=1.16,<1.17.0a0|>=1.16,<2.0a0|>=1.15,<2.0a0']

Package openblas conflicts for:
scikit-learn=0.21.3 -> numpy[version='>=1.14.6,<2.0a0'] -> openblas[version='0.2.18.*|0.2.18|0.2.18.*|0.2.19|0.2.19.*|0.2.20|0.2.20.*|>=0.2.20,<0.2.21.0a0|>=0.3.3,<0.3.4.0a0|>=0.2.15']
boost=1.72.0 -> numpy[version='>=1.14.6,<2.0a0'] -> openblas[version='>=0.2.20,<0.2.21.0a0|>=0.3.3,<0.3.4.0a0']

Package liblapacke conflicts for:
scikit-learn=0.21.3 -> blas=[build=openblas] -> liblapacke[version='3.8.0|3.9.0|3.9.0',build='3_openblas|5_openblas|6_openblas|8_openblas|12_openblas|14_openblas|17_openblas|16_openblas|15_openblas|13_openblas|11_openblas|10_openblas|9_openblas|7_openblas|4_openblas|2_openblas']
numpy=1.19.1 -> blas=[build=openblas] -> liblapacke[version='3.8.0|3.9.0|3.9.0',build='3_openblas|5_openblas|6_openblas|8_openblas|12_openblas|14_openblas|17_openblas|16_openblas|15_openblas|13_openblas|11_openblas|10_openblas|9_openblas|7_openblas|4_openblas|2_openblas']

Problem encountered creating/updating shapeworks conda environment.

**Comment by cchriste** [comment]
It's slightly dated, but this pull request's branch provides updated versions for many of this packages. It could save some time even if only to merge the conda_installs.
https://github.com/SCIInstitute/ShapeWorks/pull/702

**Comment by cchriste** [comment]
Has anyone tried to upgrade Python recently?

I'm mostly thinking about this for #1220.

**Comment by akenmorris** [comment]
Merged
