### ISSUE TITLE
Retire ShapeWorks Post after adding standalone tool for mesh warping

### ISSUE THREAD

**Issue by riddhishb** [SCIInstitute/ShapeWorks#845]
Post is deprecated after we remove the mesh warping functionality.

**Comment by akenmorris** [comment]
I assume we should wait to retire it until there is a new command for `shapeworks`?  @sheryjoe @riddhishb

**Comment by sheryjoe** [comment]
Agreed.

**Comment by sheryjoe** [comment]
@riddhishb is this still an issue?
