### ISSUE TITLE
use_shape_statistics_after can potentially create more particles than number_of_particles

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#846]
If use_shape_statistics_after > number_of_particles, the total number of particles is increased to use_shape_statistics_after. The fix is probably just a `use_shape_statistics_after = std::min(use_shape_statistics_after, number_of_particles)` somewhere

**Comment by sheryjoe** [comment]
@medakk @akenmorris is this still an issue?

**Comment by akenmorris** [comment]
Yes, fix is in #1260
