### ISSUE TITLE
Mesh Consolidation: ReflectMesh

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#851]
Needed for issue #529

Current command is ReflectMesh:

> Usage: ReflectMesh [OPTION]
> 
> A command line tool that reflect meshes with respect to a specified center and
> specific axis....
> 
> Options:
>   -h, --help            show this help message and exit
>   --version             show program's version number and exit
>   --inFilename=STRING   Mesh file to be reflected.
>   --outFilename=STRING  The filename of the output reflection mesh.
>   --reflectCenterFilename=STRING
>                         The filename for origin about which reflection occurs.
>   --inputDirection=INT  Direction along which it needs to be reflected
>   --meshFormat=STRING   The IO mesh format

With Pybind it would be ideal if we could pass the center as an array for the three coordinates instead of having that saved to a file for --reflectCenterFilename.

**Comment by archanasri** [comment]
It has been implemented in the mesh_party branch.
