### ISSUE TITLE
Mesh Consolidation: Clip

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#855]
Needed for issue #529

We need a tool for clipping meshes using a cutting plane defined by three points similar to Image.clip().
I believe this is is done here: https://github.com/SCIInstitute/ShapeWorks/blob/master/Libs/Mesh/GroomFemur.cpp#L137

**Comment by archanasri** [comment]
It has been implemented in the mesh_party branch.
