### ISSUE TITLE
Studio should not let us set the PCA mode to greater than number of samples - 2

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#856]
![image](https://user-images.githubusercontent.com/10536745/101828108-5b1a2680-3aee-11eb-9df1-fb18ea4d6514.png)

**Comment by sheryjoe** [comment]
This should be number of samples - 1

**Comment by akenmorris** [comment]
@sheryjoe , are you sure?  We are using 0 based numbering for PCA modes.  A model with only two shapes has only mode 0 (n-2).

**Comment by sheryjoe** [comment]
I think 1-based is more intuitive for users (first mode, second mode ... etc). Let's change it to 1-based then, thanks.

**Comment by akenmorris** [comment]
Using 1-based now.
