### ISSUE TITLE
Mesh grooming: invert normals

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#858]
We need a mesh grooming feature to invert mesh normals(ie: turn it inside out)

Before inverting normals:
![image](https://user-images.githubusercontent.com/10536745/101830480-ca454a00-3af1-11eb-96cd-7d6179638002.png)

After inverting normals:
![image](https://user-images.githubusercontent.com/10536745/101830165-55721000-3af1-11eb-9a49-956a0900acb1.png)

**Comment by akenmorris** [comment]
Is this what you want?

https://vtk.org/doc/nightly/html/classvtkReverseSense.html

**Comment by medakk** [comment]
Yes, looks like it

**Comment by archanasri** [comment]
> Yes, looks like it

Then Mesh::reflect() can be used.

**Comment by medakk** [comment]
This one?

```cpp
  /// reflect meshes with respect to a specified center and specific axis
  Mesh& reflect(const Axis &axis, const Vector3 &origin = makeVector({ 0.0, 0.0, 0.0 }));
```

it's not quite the same thing. it may be flipping normals buts its also reflecting(/mirroring/scaling) the mesh. I had a dataset where the samples only needed flipping of normals, and not reflection

**Comment by medakk** [comment]
something like:

```cpp
  // flip normals
  vtkSmartPointer<vtkReverseSense> reverseSense = vtkSmartPointer<vtkReverseSense>::New();
  reverseSense->SetInputData(this->mesh);
  reverseSense->ReverseNormalsOff();
  reverseSense->ReverseCellsOn();
  reverseSense->Update();
  this->mesh = reverseSense->GetOutput();
```

without any of the other transform code in `reflect()`

**Comment by archanasri** [comment]
Merged to master.
