### ISSUE TITLE
ReconstructMeanSurface will no longer build in Xcode

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#866]
Once the Python bindings were added for this executable, it fails to build in Xcode.
<img width="259" alt="Screen Shot 2020-12-14 at 2 26 31 PM" src="https://user-images.githubusercontent.com/1260945/102137663-6932b480-3e18-11eb-932f-6d1332cc0177.png">

This prevents developers using Xcode from debugging, and could still be a problem when this executable is consolidated into our standalone executable's particle system commands. If this executable isn't used by anyone maybe it can simply be removed?

May have some relation to #440.

**Comment by akenmorris** [comment]
@cchriste Please try with the latest commit to pybind branch.

**Comment by cchriste** [comment]
It worked. I'm impressed and am not sure how you surmised the reason was the Analyze library's dependencies on Optimize when the executable that failed was in Mesh and didn't mention either. 
```
add_executable(ComputeMeanNormals ComputeMeanNormals.cxx)
TARGET_LINK_LIBRARIES(ComputeMeanNormals ${ITK_LIBRARIES} tinyxml Utils)
```

**Comment by akenmorris** [comment]
It was ReconstructMeanSurface (see your image above), and it links to Analyze (which was linking to Optimize).

I don't know why this is only a problem for Xcode.  If I had to guess, it's a bug in CMake's XCode generator that injected a dependency where one was unnecessary (even if asked for).
