### ISSUE TITLE
Mac binary deployment doesn't work

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#868]
Our instructions say:

1. Install the ShapeWorks pkg file.
2. Open a terminal, change directory to /Applications/ShapeWorks
3. type "source conda_installs.sh"

Since the user does not have write permission here, this results in:

```
Warning: Failed to create the file ./Miniconda3-latest-MacOSX-x86_64.sh:
Warning: Permission denied
  0 54.4M    0   785    0     0   1299      0 12:12:46 --:--:-- 12:12:46  1297
curl: (23) Failed writing body (0 != 785)
bash: ./Miniconda3-latest-MacOSX-x86_64.sh: No such file or directory
rm: ./Miniconda3-latest-MacOSX-x86_64.sh: No such file or directory
```

Additionally, the shapeworks python module does not have rpath stuff set up correctly.
Is anyone opposed to changing the path for the save/run/delete of miniconda to /tmp?

**Comment by iyerkrithika21** [comment]
Can this be an issue in Windows as well? We ask the users to run conda_installs.bat from "C:\Program Files\ShapeWorks"

**Comment by akenmorris** [comment]
It's not a problem for windows since the bat file doesn't download miniconda.  We ask the user to install it on their own.

**Comment by akenmorris** [comment]
After manually installing miniconda and trying to use the notebooks, I found that I can't load the shapeworks module.  First, I got:

```
ImportError: dlopen(/Applications/ShapeWorks/bin/shapeworks.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libvgl_algo.dylib
  Referenced from: /Applications/ShapeWorks/bin/shapeworks.cpython-37m-darwin.so
  Reason: image not found
```

I set LD_LIBRARY_PATH=/Applications/ShapeWorks/lib

and now I get:

```
ImportError: dlopen(/Applications/ShapeWorks/bin/shapeworks.cpython-37m-darwin.so, 2): Library not loaded: @rpath/QtSql.framework/Versions/5/QtSql
  Referenced from: /Applications/ShapeWorks/bin/shapeworks.cpython-37m-darwin.so
  Reason: image not found
```

Why is this dependent on qt?

**Comment by sheryjoe** [comment]
@akenmorris I am not sure. This is related to the shapeworks python lib, not the notebooks? (which need itkwidgets and pyvista). @archanasri any thoughts?

**Comment by akenmorris** [comment]
Right, it's nothing to do with notebooks.

**Comment by akenmorris** [comment]
> Why is this dependent on qt?

To answer my own question, this stems from the dependency on VTK, which was built against Qt.

**Comment by akenmorris** [comment]
The mac binary deployment works now.
