### ISSUE TITLE
Use cases in the master branch need to be fixed

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#869]
Tasks:
- [x] ellipsoid_cut - replace `applyRigidAlignment` with `applyResampling'
- [x] femur_cut - replace `applyRigidAlignment` with `applyResampling'
- [x] femur_cut - In the cropping step, region returned by `ImageUtils.boundingBox` is large and causes error
- [x] femur-In the cropping step, region returned by `ImageUtils.boundingBox` is large and causes error
- [x] GroomUtils - change the format of the clipping plane points used in the `ClipBinaryVolumes` function

**Comment by sheryjoe** [comment]
@iyerkrithika21  can you add more details about what fails exactly in each use case?

**Comment by iyerkrithika21** [comment]
Femur and femur cut errors : 
```
Invalid region specified.
Traceback (most recent call last):
  File "RunUseCase.py", line 79, in <module>
    module.Run_Pipeline(args)
  File "/home/sci/iyerkrithika/ShapeWorks/Examples/Python/femur.py", line 315, in Run_Pipeline
    croppedFiles_segmentations = applyCropping(groomDir + "cropped/segmentations", clippedFiles_segmentations, groomDir + "clipped_segmentations/*.nrrd")
  File "/home/sci/iyerkrithika/ShapeWorks/Examples/Python/GroomUtils.py", line 218, in applyCropping
    img.crop(region).write(outname)
RuntimeError: /home/sci/iyerkrithika/ShapeWorks/dependencies/install/include/ITK-5.0/itkImportImageContainer.hxx:199:
Failed to allocate memory for image.
```

**Comment by jadie1** [comment]
The femur error when isotropic spacing is used is caused by center of mass alignment which is causing the segmentations to just be 0. This is fixed if the order of subtraction is switched, i.e. T = img.center() - img.centerOfMass() instead of T = img.centerOfMass() - img.center().

**Comment by jadie1** [comment]
I have added fixes for:
- issue when non-isotropic spacing is used in the femur use case
- COM order issue which was effecting the bounding box step in femur and femur_cut
All of the fixes are on the use_case_fix branch. 
@iyerkrithika21 can you double check that all of the use cases are functioning now and then we can make a pull request?
