### ISSUE TITLE
Identify subset of dependencies needed for user installations

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#884]
Users don't need to run the full conda_installs since it brings things like cmake in which are not necessary for using a prebuilt ShapeWorks installation. We should identify the subset of dependencies needed for users. This will make user installations faster and less prone to conflicts (though combining conda and pip still renders this more likely).

In addition, this will enable partitioning the [e.g., conda] installation between shapeworks-core, shapeworks-python, and shapeworks-studio, since presumably Qt/Vtk OpenGL libraries aren't needed for command line tools (though they may be needed for the Python module since it provides helper functions that use itkwidgets, pyvista, and vtk; unless we further partition the module).

**Comment by akenmorris** [comment]
My suggestion is that we add a "--developer" option to the script rather than split it into two scripts (one for developers and one for us).  Then with the --developer argument, the additional packages will be installed.

**Comment by akenmorris** [comment]
Hey, maybe a better idea is to just detect if you're sitting in a git repo (e.g. is .git a folder?) and if so, do the developer stuff.  Then we don't run into the problem that someone on the team forgets --developer and is confused why stuff isn't working.

**Comment by cchriste** [comment]
As I await conda_installs.sh for testing the 6.1 release, it begins to install cmake and ctest, obviously unnecessary to users.
This is a huge time sink for users. 
I also wonder if we need should be including things like our test executables for users.

**Comment by cchriste** [comment]
> I also wonder if we need should be including things like our test executables for users.

Actually, we're not packaging test executables, but on Windows all the test .pdb files are being included, and on all platforms libTesting is added (maybe it's still needed).

**Comment by cchriste** [comment]
Overall proposal for installation:
- create and package install_shapeworks.sh/bat that only includes libraries necessary for users
- create and **do not package** developer_installs.sh that includes all libraries necessary for dev
