### ISSUE TITLE
Fixed domain optimization doesn't work on meshes

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#887]
When I run fixed domain optimization on meshes I get a segmentation fault in the intialization step.

To test:

- Unzip this: [fd_mesh_test.zip](https://github.com/SCIInstitute/ShapeWorks/files/5804750/fd_mesh_test.zip)
- Change the paths in `fd_mesh_test/correspondece_128.xml` to be correct for you
- Run `shapeworks optimize --name=fd_mesh_test/correspondence_128.xml`
- Note that if you remove the fixed domain tag in the xml it runs fine

**Comment by akenmorris** [comment]
Confirmed.

**Comment by akenmorris** [comment]
Thanks for putting together a small test case.  I've used this as the basis for an automated test.
