### ISSUE TITLE
upgrade to latest trimesh2 library using conda

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#89]
This external library should (probably) be updated and moved to our external libs directory.

Used by fim_v4.
Original source found here: https://gfx.cs.princeton.edu/proj/trimesh2/

**Comment by cchriste** [comment]
Instead of moving to ExternalLibs, this library should be added using cmake's ExternalProject_Add command like vtk, ITK, etc.

**Comment by sheryjoe** [comment]
Agreed. But we need to extract our changes/additions to this lib to a class (i.e. internal lib). This also entails ensuring that this internal lib is compatible with the latent trimesh lib. @prafulag can help/advise on this.

**Comment by cchriste** [comment]
> Agreed. But we need to extract our changes/additions to this lib to a class (i.e. internal lib). This also entails ensuring that this internal lib is compatible with the latent trimesh lib. @prafulag can help/advise on this.

Yes, this is already mentioned in the comment from Aug 26.

**Comment by cchriste** [comment]
If the map/reduce classes are our creation vs a presumably upgraded part of trimesh, here are instructions on how to update threading with ITK 5: https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/ITK5MigrationGuide.md

**Comment by cchriste** [comment]
Instead of providing a copy of the library, we should install the conda version:
`https://anaconda.org/conda-forge/trimesh`

(title updated accordingly)

**Comment by 0leks** [comment]
[trimesh](https://github.com/mikedh/trimesh) is different from [trimesh2](https://gfx.cs.princeton.edu/proj/trimesh2/)
I don't think trimesh2 can be installed via conda. I don't even know if there is a git repo for it... (I haven't found one)

**Comment by cchriste** [comment]
Ah. Okay then, return to upgrade.

**Comment by cchriste** [comment]
This version might be the best. It's updated regularly and contains Windows support:
https://github.com/Forceflow/trimesh2

**Comment by 0leks** [comment]
That looks nice, I'll  check it out

**Comment by cchriste** [comment]
What is in ExternalLibs/Trimesh2? 
If this is a clone of the Forceflow repo, can we add a README and close this issue? 
Or are there ShapeWorks-specific modifications? 
Do we still have another version (I don't see one)?
Are the changes from our originally-modified version still here, or were they moved to another library?
Thanks!

**Comment by 0leks** [comment]
I believe it is currently the latest version from the main website: https://gfx.cs.princeton.edu/proj/trimesh2/
Plan is to change this to clone the forceflow version in the build_dependencies script.
The changes from the originally-modified version were all moved to meshFIM

**Comment by cchriste** [comment]
Is this issue now resolved? Having latest version of Trimesh2 in ExternalLibs seems okay. So as long as the modified version has been eliminated I'd call it complete.

**Comment by medakk** [comment]
Closing this because we are deprecating all trimesh usage
