### ISSUE TITLE
Studio should append ".xlsx" 

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#892]
If I save a project in studio without the name ending in .xlsx:
![image](https://user-images.githubusercontent.com/10536745/104410981-b6449c00-5526-11eb-807f-df043c7bb42c.png)

and later try to open it:
![image](https://user-images.githubusercontent.com/10536745/104411009-cb212f80-5526-11eb-8584-bef6ad0f498c.png)

it doesn't work. I think the convention followed by most applications is to add the extension (".xlsx" in this case) to the filename in "save as" even if the user doesn't specify it

**Comment by akenmorris** [comment]
I agree.  It already does this on OSX.  I figured it worked elsewhere as well.  I will check Windows and Linux.

**Comment by akenmorris** [comment]
Looks like it was just Linux.  OSX and Windows use native file widgets that already do this.

Should be fixed for linux in #891
