### ISSUE TITLE
Mesh and particles disappear in studio after optimization

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#914]
* open Studio, add a single mesh
* "Skip" grooming
* run optimize
* everything is fine during optimization, but at the end everything disappears:
![image](https://user-images.githubusercontent.com/10536745/105560535-44f8ac00-5cd1-11eb-8a04-ad125fbb67e4.png)
* switch to "groom" tab, everything is back to normal again
![image](https://user-images.githubusercontent.com/10536745/105560573-60fc4d80-5cd1-11eb-9d63-1e25bdf4cdf9.png)
* can switch back to optimize now if needed

In the console I see "Error: asked for groomed mesh when none is present!"

**Comment by akenmorris** [comment]
Done in #927
