### ISSUE TITLE
Include joint ellipsoid generation in cohort package

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#919]
User options for joint generation :
1. Size 
2. Alignment
3. Distance between the ellipsoids

**Comment by iyerkrithika21** [comment]
@sheryjoe 
1. Right now the user can specify if the centers have to be randomized, and the randomized center will be used for all the joints in the cohort. Should each joint have its own center? Also, radii are the same for all joints in the cohort.
2. The user can also specify the distance between two ellipsoids in the joint.
3. The rotation is not randomized. The rotation is calculated as  `shape_index*(180/num_samples_in_cohort)`  where `shape_index is in [0,....,num_samples_in_cohort-1]` 
Any other alignment options to be included?

**Comment by sheryjoe** [comment]
@iyerkrithika21 
> 1. Right now the user can specify if the centers have to be randomized, and the randomized center will be used for all the joints in the cohort. Should each joint have its own center? Also, radii are the same for all joints in the cohort.

Does this mean that each sample (joint) will have a randomized center? i.e., reflecting translation misalignment? or each ellipsoid in each joint will have a randomized center?

> 2. The user can also specify the distance between two ellipsoids in the joint.
> 3. The rotation is not randomized. The rotation is calculated as  `shape_index*(180/num_samples_in_cohort)`  where `shape_index is in [0,....,num_samples_in_cohort-1]`

I think the user should also indicate which axes to rotate about.

>    Any other alignment options to be included?

 I think that ellipsoid centers for each joint should be tied together and parameterized by the distance between the two ellipsoids (surfaces) and their radii.

**Comment by iyerkrithika21** [comment]
> > 1. Right now the user can specify if the centers have to be randomized, and the randomized center will be used for all the joints in the cohort. Should each joint have its own center? Also, radii are the same for all joints in the cohort.
> 
> Does this mean that each sample (joint) will have a randomized center? i.e., reflecting translation misalignment? or each ellipsoid in each joint will have a randomized center?

Each sample(joint) will have a randomized center.

**Comment by sheryjoe** [comment]
@iyerkrithika21 we also want a dataset that has another mode of variation to reflect the distance between the two ellipsoids. This will enable us to demonstrate the different alignment methods to be used in the analysis phase.

**Comment by iyerkrithika21** [comment]
Distances could follow a distribution

**Comment by iyerkrithika21** [comment]
complete with PR #1255
