### ISSUE TITLE
SW discussion forum

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#921]
- [x] Update the [contact](http://sciinstitute.github.io/ShapeWorks/about/contact.html) to reflect the discourse discussion forum instead of gitter.
- [x] Update team page

**Comment by sheryjoe** [comment]
@jadie1 Please update the documentation to refer to the discussion forum instead of gitter.

**Comment by jadie1** [comment]
> @jadie1 Please update the documentation to refer to the discussion forum instead of gitter.

Done on the mkdocs branch

**Comment by sheryjoe** [comment]
Addressed in PR #968
