### ISSUE TITLE
Adding Landmark Registration to Studio

### ISSUE THREAD

**Issue by elevendavis** [SCIInstitute/ShapeWorks#922]
As discussed in the weekly meeting, we have generated landmarks for the scapula use case (~19 per bone) and would like to use these landmarks as one means of model registration in Studio. I believe this feature was available in the line script version of ShapeWorks, but it would be nice to have some means to do it in Studio. We envision this as being able to select a STL and then select a CSV or plaintext file containing landmark identifiers and XYZ coordinates. Studio would then use these coordinates to line up the models. 

- Evan & Tanner

**Comment by akenmorris** [comment]
Completed in #1639
