### ISSUE TITLE
Replace trimesh2 with VTK or other mesh library

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#926]
The trimesh2 library we are using is unsupported and uses very questionable code constructs (e.g. **goto**s) and may be a source of bugs (see #925).  It also has support for only one file format, PLY and has no support for scalar values.

I propose replacing it with VTK or some other mesh library.

**Comment by medakk** [comment]
@akenmorris a thought I had:

after geodesic walk, we know exactly which triangle the particle is located on. it makes sense to immediately update the `particle2tri_` cache at the end of geodesic walk instead of (potentially) doing a kdtree lookup the next iteration.

**Comment by akenmorris** [comment]
Correct, I’m doing this in the replace_trimesh branch.  There were a few other caching opportunities as well.

**Comment by sheryjoe** [comment]
Based on the related issue #925, I think this should be considered before the 6 release. @akenmorris @medakk ?
