### ISSUE TITLE
[Mesh] Create independent class for mesh fields

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#935]
Getting and setting values associated with fields of a Mesh would likely be better when separated from the Mesh API itself.

Note: fields can have more than one component. For example, normals at each vertex.

**Comment by cchriste** [comment]
vtkPolyData has (inherits) three (at least) types of data array holders, accessed via the following functions:
->GetPointData()
->GetCellData()
->GetFieldData()

Our Field class will ideally make access/creation of these simpler, for example by providing a Field::Type enum which can then be used by access/modification functions in Mesh, rather than having a dozen+ different functions that all do essentially the same thing.

**Comment by cchriste** [comment]
We might use this to include a dictionary of heterogenous data with a mesh (proposed in our meeting on 2021.02.01).
If this is generically feasible with vtkPolyData, it could even be savable with a mesh.
Similarly, the results of commands that perform costly computations could be cached using such a mechanism.

**Comment by cchriste** [comment]
This will be able to replace the handful of Mesh functions that perform some computation on fields (mean, range, etc).

**Comment by cchriste** [comment]
> We might use this to include a dictionary of heterogenous data with a mesh (proposed in our meeting on 2021.02.01).
> If this is generically feasible with vtkPolyData, it could even be savable with a mesh.

vtkPolyData can have multiple fields, all saved with the mesh (simple).
It's also possible to have AoS and SoA (arrays of structs and structs of arrays), but these might be unnecessarily complicated for ShapeWorks. 

> Similarly, the results of commands that perform costly computations could be cached using such a mechanism.

MeshWrapper has some facilities which might be emulated to cache such computations. But let's not prematurely optimize.

**Comment by cchriste** [comment]
> vtkPolyData has (inherits) three (at least) types of data array holders, accessed via the following functions:
> ->GetPointData()
> ->GetCellData()
> ->GetFieldData()
> 
> Our Field class will ideally make access/creation of these simpler, for example by providing a Field::Type enum which can then be used by access/modification functions in Mesh, rather than having a dozen+ different functions that all do essentially the same thing.

The argument for separate functions is specialization and security based on how many values are in a field. For ShapeWorks Meshes, just a simple Field class with an arbitrary number of values should be fine, and if we want to specialize/validate number of values we can add parameters to Mesh::[get|set]Field, but it seems unnecessary at this point.

**Comment by cchriste** [comment]
Input would be appreciated. 
1. Are we okay with only a handful of Field classes?
2. Are we okay with multiple functions to return the different field types (by name).

**First:**
For our Field class, we want to simplify this while maintaining its efficiency. 
Identifying our specific field types is the first step to deciding what we need. 
Currently, this include (in Mesh and MeshWrapper):
- **ScalarField, VectorField, MatrixField, consisting of 1-, 3-, and 9-component tuples respectively.**

We could also include 2-component tuples for spherical coordinates and 4-components vectors for homogenous 3-component Vectors (the former are used during some computations, not sure about the latter). And ultimately we could be completely generic, but that obviates the reason to create a shapeworks field class.

**Second:**
To _access_ fields from a Mesh we could return pointers to a base Field class.
_Or_ we could provide multiple `GetField` functions that return the specific type of field (scalar, vector, matrix). 
- these fields would provide concrete `GetValue` functions while the others would require `static_cast` somewhere.
- note: a single SetField function would still be sufficient for that operation.

This page provides lots of information about vtk's current vtkDataArray class and derivations thereof: https://vtk.org/doc/nightly/html/VTK-7-1-ArrayDispatch.html.

**Comment by cchriste** [comment]
Related to #903, which is half complete, but makes use of underlying `vtkDataArray::GetVoidPointer()` that itself intermixes with our decision of how general of a class we want to use for mesh fields. It's probably sufficient to provide simple fields (in vtk we'll call these `GenericDataArrays`, or "Arrays of Structs," the traditional way of storing data. An example is that an array of `Vectors` would be stored as V1.x V1.y V1.z V2.z V2.y V2.z ..., whereas a more complicated method of storages, known as "Structs of Arrays" would for example vectorize input data such that all the x's are together (V1.x V2.x ...), etc. Also relates to #1408, which was discussed at our meeting last week. 

The implementations in Python are half complete as well as C++, but some presumptions, for example that our data is stored in traditional vtk "Array of Struct" order, have been made and feedback would be appreciated.

**Comment by sheryjoe** [comment]
@sheryjoe @akenmorris @riddhishb please go over @cchriste questions on this issue and let's brainstorm.

**Comment by HeavenlyBerserker** [comment]
I think accessing mesh fields is not difficult or confusing through the mesh API. I like the idea of having a single vtkpolydata store all fields. This way we do not have redundant meshes stored.

I don't see why a specific fields class is required. We can just write methods to set and get any kind of field on a vtkpolydata, right? The fields also have names already.

**Comment by akenmorris** [comment]
I think it might help to list out the potential use cases.  I see how the current GetFieldValue is limiting (only doubles)

When discussing a merge of Mesh and MeshWrapper/VtkMeshWrapper, it's important to note that a lot of those data structures would most likely only be used internally.  There really isn't a need to provide external API access to them.  For example, the 3x3 gradient at each vertex is generated to support the "SampleNormalAtPoint".  I don't see any particular reason to expose the gradient as "Field" for anything else to use (nor to save it to a mesh file).  I would try to avoid over-engineering it unless there are real anticipated uses.

**Comment by cchriste** [comment]
> I think it might help to list out the potential use cases. I see how the current GetFieldValue is limiting (only doubles)

Correct. And we need to be able to pass the fields themselves, which can be really be anything, but the way they will be used should help dictate the level of simplicity. Just passing raw vtkDataArrays pushes an undue level of complexity onto users of this data if the only probable field types are scalars and vectors/points.

> When discussing a merge of Mesh and MeshWrapper/VtkMeshWrapper, it's important to note that a lot of those data structures would most likely only be used internally. There really isn't a need to provide external API access to them. For example, the 3x3 gradient at each vertex is generated to support the "SampleNormalAtPoint". I don't see any particular reason to expose the gradient as "Field" for anything else to use (nor to save it to a mesh file). I would try to avoid over-engineering it unless there are real anticipated uses.

This is very helpful to know! Similar to our dance with polar coordinates internal to a couple of distance calculation functions, if the user doesn't need to see this outside of there respective functions, there's no need to complicate the API.

**Comment by cchriste** [comment]
Based on the input we've received so far, it seems simply wrapping `vtkDataArray` and insulating the user from its fairly confusing usages (e.g., operating on a generic base class pointer using a case statement based on its reported type (`vtkAbstractArray::GetDataType()`) will be the best way to keep things simple, avoid storing fields in a mesh when it doesn't make sense (ex: `MeshUtils::computeMeanNormals(vector of input meshes)`, and allow for use of fields (i.e., data arrays) independent of Meshes (e.g., getting/setting values simply using a [] operator, computing statistics, and other purposes). 

This doesn't bar storing data as "structs of arrays," but a simple implementation means copying to get one. The probable use cases for something like this are GPU computations, and the way to enable something like this efficiently would still be to provide a transparent user wrapper of the underlying vtk data array classes. Right now vtk copies data between arrays of structs (typical) and structs of arrays (i.e., for three-component vectors a, b, c: a0a1a2b0b1b2c0c1c2 vs a0b0c0a1b1c2a2b2c32) when needed, and we would have the same ability. But we can save that for if/when such a use case arises. And to reiterate: the user would never have to think about it with our insulated API.

**Comment by archanasri** [comment]
@cchriste @sheryjoe Can we move this to 6.3?

**Comment by HeavenlyBerserker** [comment]
Thus far, I've seen only one good argument for creating this mesh fields class being the fact that the Python equivalent class might need more precise data structures. How does our python code handle vtk objects? Can c++ vtk structures be easily handled with vtk python? If not, then I fully support this mesh fields' class.

**Comment by cchriste** [comment]
> Thus far, I've seen only one good argument for creating this mesh fields class being the fact that the Python equivalent class might need more precise data structures. How does our python code handle vtk objects? Can c++ vtk structures be easily handled with vtk python? If not, then I fully support this mesh fields' class.
> 
> On the other hand, having fields in the vtkpolydata mesh is helpful to easily debug the mesh fields by writing the mesh into a vtk file and visualizing the fields in paraview. Maybe GPU processing is also an issue? IDK
> 
> These are, after all, just QoL improvements for developers. Personally, I've been okay with using the current implementation, but I'd be down to structure everything better if anybody else plans to develop on top of it or if it's necessary for Python.

It's necessary for Python. And it's use is completely different in vtkMeshWrapper as in Mesh.

**Comment by cchriste** [comment]
One challenge that already come out of vtk's field-per-internal-collection design is more than one field with the same name. The first example is normals, and when vtk computes them for whatever you ask, it gives them the same name. We've been discussing ways to address this, such as renaming the fields after such a computation (e.g., by `computeMeanNormals`).

**Comment by cchriste** [comment]
This function should compare fields, not be a member of Mesh:
```
  /// compare field of meshes to be (eps)equal (same field for both if only one specified)
  bool compareField(const Mesh& other_mesh, const std::string& name1, const std::string& name2="", const double eps=-1.0) const;
```

**Comment by akenmorris** [comment]
Not needed, vtk scalar fields are fine.
