### ISSUE TITLE
TriMeshWrapper::ComputeBarycentricCoordinates

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#936]
TriMeshWrapper::ComputeBarycentricCoordinates does not handle degenerate triangles.  One of the femur groom meshes and the clipped boundary ends up having a face with two vertices in the same location.  This is likely due to the low precision of the vertex positions in the PLY file.

When given a triangle with shared vertices, this function returns a bunch of NaNs which end up breaking many other things in the optimizer.  This results in either crashing (see potentially #925) or hanging/infinite loop.

This function either has to be fixed to handle degenerate triangles, or we need to ensure that these triangles to not get passed to it.

Also related: #910

**Comment by medakk** [comment]
@akenmorris Does vtkCleanPolyData let us close this?

**Comment by akenmorris** [comment]
Yep
