### ISSUE TITLE
[Mesh] fix Mesh::fix w/ parameters test (MeshTests::fixTest2)

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#938]
Here is the function signature:
```
  /// quality control mesh
  Mesh& fix(bool wind = true, bool smoothBefore = true, bool smoothAfter = true, double lambda = 0.5, int iterations = 1, bool decimate = true, double percentage = 0.5);
```

See `TEST(MeshTests, fixTest2)` in MeshTests.cpp (in alpha branch):
```
  Mesh femur(std::string(TEST_DATA_DIR) + "/m03.vtk");
  femur.fix(true, true, true, 1.0, 10, true, 1.0);
  Mesh ground_truth(std::string(TEST_DATA_DIR) + "/fix2.vtk");
  ASSERT_TRUE(femur == ground_truth);
```

For some reason results are not consistent so strictly comparing against ground truth isn't working.

**Comment by archanasri** [comment]
```
TEST(MeshTests, fixTest1)
{
  Mesh femur(std::string(TEST_DATA_DIR) + "/m03.vtk");
  femur.fix();
  Mesh ground_truth(std::string(TEST_DATA_DIR) + "/fix1.vtk");
  ASSERT_TRUE(femur == ground_truth);
}
// https://github.com/SCIInstitute/ShapeWorks/issues/938
TEST(MeshTests, fixTest2)
{
  Mesh femur(std::string(TEST_DATA_DIR) + "/m03.vtk");
  femur.fix(true, true, true, 0.5, 1, true, 0.5);
  Mesh ground_truth(std::string(TEST_DATA_DIR) + "/fix1.vtk");
  ASSERT_TRUE(femur == ground_truth);
}
```
`Mesh& fix(bool wind = true, bool smoothBefore = true, bool smoothAfter = true, double lambda = 0.5, int iterations = 1, bool decimate = true, double percentage = 0.5);`

fixTest1 and fixTest2 are essentially the same but fixTest1 passes and fixTest2 fails. When the order of the tests is exchanged, the first test passes and the second test fails. The problem could be the FEMesh pointer.

**Comment by cchriste** [comment]
The other issue that came up is that some combinations of the (too many) parameters to this function cause crashes altogether. @archanasri can provide examples.

**Comment by cchriste** [comment]
The command line version of this test is also failing on Linux, but not on OSX (Windows is still unknown). 
The error is that the centers of mass differ, which could be precision related.
```
2021-02-03T23:16:51.0173765Z 7: [ RUN      ] shapeworksTests.meshfixTest
2021-02-03T23:16:51.7519497Z 7: coms differ!
2021-02-03T23:16:51.7520063Z 7: compare failure
2021-02-03T23:16:51.7563994Z 7: /home/runner/work/ShapeWorks/ShapeWorks/Testing/shapeworksTests/shapeworksTests.cpp:330: Failure
```
It only compares down to three significant digits, shown in this line of Mesh::compare. That seems ample...
```
  if (!epsEqualN(centerOfMass(), other.centerOfMass(), 3)) { std::cout << "coms differ!\n"; return false; }
```

**Comment by cchriste** [comment]
Just to be even more clear, calling `Mesh::fix` repeatedly produces notably different results, parameters are not.
```
Mesh mesh1 = Mesh("/path/to/mesh");
mesh1.fix();
Mesh mesh2 = Mesh("/path/to/mesh");
mesh2.fix();
// mesh1 != mesh2 
```

This is the same no matter if run in c++ or from the command line (haven't tried python yet). If you run the command once, it produces the same result every single time (the first one shown here), but if you run it twice the second result is different even single time (and the same as the second result every single time). Seems like some global somewhere? A random number generator seeded the same each time? 

```$ ./bin/shapeworks readmesh --name ../Testing/data/m03.vtk meshinfo meshfix meshinfo readmesh --name ../Testing/data/m03.vtk meshinfo meshfix meshinfo
number of points:      15002
number of faces:       30000
center:                [90.7541, -160.557, -673.572]
center of mass (0,1]:  [92.6201, -157.662, -666.611]
bounding box:          {
	min: [46, -193, -738],
	max: [136, -128, -609]
}
field names: 
number of points:      7431
number of faces:       14858
center:                [90.777, -160.578, -673.534]
center of mass (0,1]:  [92.9194, -157.559, -666.84]
bounding box:          {
	min: [46, -193, -738],
	max: [135, -128, -609]
}
field names: 
number of points:      15002
number of faces:       30000
center:                [90.7541, -160.557, -673.572]
center of mass (0,1]:  [92.6201, -157.662, -666.611]
bounding box:          {
	min: [46, -193, -738],
	max: [136, -128, -609]
}
field names: 
number of points:      7437
number of faces:       14870
center:                [90.773, -160.585, -673.546]
center of mass (0,1]:  [92.6307, -157.521, -667.317]
bounding box:          {
	min: [46, -193, -738],
	max: [135, -128, -609]
}
field names: 
```

**Comment by cchriste** [comment]
None of these tests pass on Linux. Here are the results:

**Comment by cchriste** [comment]
I don't know what else I can contribute to this aside from brute force debugging. Just going to comment out all these tests until these issues can be addressed.

**Comment by cchriste** [comment]
Frozen until re-meshing feature added to Studio, after which desired APIs will be noted here and/or in #938.

**Comment by akenmorris** [comment]
> For some reason results are not consistent so strictly comparing against ground truth isn't working.

PreviewQC appears to be using a random number generator:

https://github.com/SCIInstitute/ShapeWorks/blob/4f30da74dc67cb533fa0f07162f20450859b51fd/Libs/Mesh/PreviewMeshQC/FECVDDecimationModifier.cpp#L25

```
static unsigned int nseed = 47856987;
nseed = 789789812*nseed + 38569741 + rand();
return (int)(nseed%nmax);
```

I recommend we replace this with std::mt19937 and additionally re-seed it for each execution in order to get consistent results.

Additionally, FECVDDecimationModifier::Apply method has many places where it can return 0/NULL and Mesh::cvdDecimate does not check for this and blindly goes to convert it to VTK, which will cause crashes in some cases.
