### ISSUE TITLE
[Mesh] Image::toMesh creates Mesh with different fieldnames than after it's saved then loaded

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#939]
Please see `TEST(ImageTests, toMeshTest1)` in ImageTests.cpp (in alpha branch). 
Note that Mesh comparison fails due to different field names.

```
[ RUN      ] ImageTests.toMeshTest1
mesh: {
	number of points: 36233,
	number of faces: 72464,
	center: [70, 121.252, 47.5],
	center or mass: [79.4799, 118.602, 50.7752],
	fieldnames: 
		default
		default

comp: {
	number of points: 36233,
	number of faces: 72464,
	center: [70, 121.252, 47.5],
	center or mass: [79.4799, 118.602, 50.7752],
	fieldnames: 
		scalars
		normals
```

**Comment by cchriste** [comment]
Same operation from command line:
```(shapeworks) $ ./bin/shapeworks readimage --name ../Testing/data/la-bin.nrrd imagetomesh fieldnames
default
default
```

**Comment by cchriste** [comment]
Same operation using Python (in Jupyter notebook) provides _almost_ correct field names (note "Normals" is capitalized):
<img width="755" alt="Screen Shot 2021-02-03 at 8 53 28 AM" src="https://user-images.githubusercontent.com/1260945/106772689-80fb0d80-65fd-11eb-943a-1234622e122a.png">

**Comment by cchriste** [comment]
this has now been fixed in meshtest branch

**Comment by archanasri** [comment]
Fix merged to master.
