### ISSUE TITLE
ShapeWorks Portal: use-case-data-v2/left_atrium-v0 image and segmentations misalignment

### ISSUE THREAD

**Issue by wasim92007** [SCIInstitute/ShapeWorks#943]
Hi,

I have checked the first 15 datasets of the use-case-data-v2/left_atrium-v0 images and corresponding  segmentation in the ParaView 5.9.0 tool and it appears to me that for few of the datasets the image and the segmentation are misaligned.

I am attaching the below screenshots for quick reference.

### 
**List of misaligned datasets -**
![misaligned_datasets](https://user-images.githubusercontent.com/3947801/106856094-37e99e80-667b-11eb-8f95-dc537818d3ec.png)

**### Individual screenshots -**

1. ![misaligned_CARMA0046](https://user-images.githubusercontent.com/3947801/106856081-35874480-667b-11eb-8730-48a50cff24f1.png)

2. ![misaligned_CARMA0072](https://user-images.githubusercontent.com/3947801/106856084-361fdb00-667b-11eb-85e5-d3751f47f6c3.png)

3. ![misaligned_CARMA0254](https://user-images.githubusercontent.com/3947801/106856085-36b87180-667b-11eb-882e-21fa0fef5a52.png)

4. ![misaligned_CARMA0291](https://user-images.githubusercontent.com/3947801/106856086-36b87180-667b-11eb-85c5-1f545307df70.png)

5. ![misaligned_CARMA0301](https://user-images.githubusercontent.com/3947801/106856087-36b87180-667b-11eb-9817-b25d2ef4aa31.png)

6. ![misaligned_CARMA0415](https://user-images.githubusercontent.com/3947801/106856088-37510800-667b-11eb-99cc-031acf7ceb3f.png)

7. ![misaligned_CARMA0440](https://user-images.githubusercontent.com/3947801/106856089-37510800-667b-11eb-996a-9d3c52164df0.png)

8. ![misaligned_CARMA0468](https://user-images.githubusercontent.com/3947801/106856090-37e99e80-667b-11eb-93a7-9ba82ce0048d.png)

9. ![misaligned_CARMA0606](https://user-images.githubusercontent.com/3947801/106856092-37e99e80-667b-11eb-9a31-75314d57cdc6.png)

**Comment by akenmorris** [comment]
Have the segmentations been "recentered" to 0 origin or something?

**Comment by jadie1** [comment]
Strange they look aligned when I open them in Paraview 5.7.0
![image](https://user-images.githubusercontent.com/54382613/106954763-7c178600-66f1-11eb-9ed9-9e373857fba7.png)

They look aligned in ITK snap as well

**Comment by iyerkrithika21** [comment]
They look aligned in itksnap for me too!

**Comment by wasim92007** [comment]
They are showing misaligned in my Paraview 5.9.0 setup.
Do you think there might be something wrong with my setup?
Can we have a look?

**Comment by wasim92007** [comment]
I had a quick discussion with @jadie1 and we looked into the issue in my setup.
Looks like the ones which are showing misaligned do not have "**space origin**" metadata in the image file.

I am attaching the below screenshots for reference -
For misaligned datasets, _only the segmentation has_ "**space origin**" metadata-
![Screenshot_1](https://user-images.githubusercontent.com/3947801/106965797-2e8b2f80-676a-11eb-890b-5598698507b4.png)
![Screenshot_2](https://user-images.githubusercontent.com/3947801/106965798-2f23c600-676a-11eb-9f52-4fa94fc217bc.png)

For Aligned ones, _both the Image and Segmentation has_ "**space origin**" metadata.
![Screenshot_3](https://user-images.githubusercontent.com/3947801/106965912-64301880-676a-11eb-8d7b-8437f0c92a4d.png)
![Screenshot_4](https://user-images.githubusercontent.com/3947801/106965913-64301880-676a-11eb-818c-124a9ae2b394.png)

**Comment by jadie1** [comment]
I just read and wrote again all of the images in shapeworks and now they have the origin in the header. I will replace the ones on the portal with these and let you know when they are done uploading @wasim92007

**Comment by jadie1** [comment]
Okay they are on the portal, let me know if they still look unaligned

**Comment by akenmorris** [comment]
Yeah, if you look on the first line, some files were NRRD0001 and some were NRRD0004
