### ISSUE TITLE
Particle splitting no longer allows for differing numbers of particles per domain

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#945]
The old splitting allowed for the differing number of particles in <number_of_particles> to work.  We had:

```
 for (int i = 0; i < n; i++) {
      int d = i % m_domains_per_shape;
      if (m_sampler->GetParticleSystem()->GetNumberOfParticles(i) < m_number_of_particles[d]) {
        m_sampler->GetParticleSystem()->SplitAllParticlesInDomain(random, i, 0);
      }
    }
```

This would only split for domains that had not exceeded their particle count.  The new particle splitting does not check this and splits no matter what.

Sample file, the input nrrds don't really matter:

<output_dir>
  output
</output_dir>

<number_of_particles>
  32
  64
</number_of_particles>

<domains_per_shape>
  2
</domains_per_shape>

<inputs>
  1.nrrd
  2.nrrd
  3.nrrd
  4.nrrd
</inputs>

**Comment by sheryjoe** [comment]
@HeavenlyBerserker please prioritize this issue to help us finalize the multiple domains in Studio.

**Comment by HeavenlyBerserker** [comment]
@sheryjoe I implemented a fix for this in the allow_diff_particle branch, which I handed off to @akenmorris on Th, February 25th, through Slack. I didn't PR since I could not visualize the results due to Studio not being able to display it, but the particle files do contain the right number of particles now.

**Comment by sheryjoe** [comment]
@akenmorris did you have a chance to test Hong's fix?

**Comment by akenmorris** [comment]
No, are we changing this to include in the 6.0 release?

**Comment by sheryjoe** [comment]
> No, are we changing this to include in the 6.0 release?
No. This is still for 6.1 release. it would be nice to see the multiple domains support a different number of particles per domain.
