### ISSUE TITLE
Mesh grooming consolidation: command for remeshing

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#952]
I recently had to run a remesh operation on a (poor quality) mesh:

![image](https://user-images.githubusercontent.com/10536745/107466672-af0eaf00-6b21-11eb-8996-0a69f69f2c5e.png)

It'd be useful to have a command to do this in the consolidated mesh commands.  According to @sheryjoe this is implemented in the PreviewCmd tool

**Comment by cchriste** [comment]
This is a duplicate of Mesh::fix and can be closed.
