### ISSUE TITLE
Installation using `make install` fails

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#953]
This is a problem across OSes. It's great that GitHub actions create working installations, but make installs should do the same. 

On Linux, after `make install` to a given path:
```
(shapeworks) ~/code/ShapeWorks/build$ ~/tools/ShapeWorks/bin/shapeworks
/scratch/cam/tools/ShapeWorks/bin/shapeworks: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory
```

On Windows, I can't currently run even from the build directory. Here is the error I get there since it is similar:
```
(shapeworks)
MINGW64 ~/code/ShapeWorks/build (alpha)
$ ./bin/RelWithDebInfo/shapeworks
C:/Users/cam/code/ShapeWorks/build/bin/RelWithDebInfo/shapeworks.exe: error while loading shared libraries: a
pi-ms-win-crt-locale-l1-1-0.dll: cannot open shared object file: No such file or directory
```

On OSX, make install fails while trying to install Studio, but after disabling that here is the error when running:
```
(shapeworks) ~/code/ShapeWorks/ShapeWorks/build_debug$ ~/tools/ShapeWorks/bin/shapeworks
dyld: Library not loaded: @rpath/libvgl_algo.dylib
  Referenced from: /Users/cam/tools/ShapeWorks/bin/shapeworks
  Reason: image not found
Abort trap: 6
```

**Comment by cchriste** [comment]
Confirmed `make install` still doesn't work. Maybe close this as "won't fix"?

**Comment by akenmorris** [comment]
`make install` now works, we have tested this on all 3 platforms with the new support for using ShapeWorks as a library (e.g. ITK CMake example)
