### ISSUE TITLE
Fix Python Image copy-from-numpy constructor

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#965]
Our current attempt to _copy_ a numpy array into an image is broken.
`.def(py::init([](py::array_t<long> np_array) {`

This relates to #903 and #716

**Comment by cchriste** [comment]
This is now working from the pybind pull request

**Comment by sheryjoe** [comment]
@cchriste should we close this?

**Comment by cchriste** [comment]
pybind merged with added tests, closing issue
