### ISSUE TITLE
Use case for multi-type domains (mesh/image and contours)

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#974]
Related to #973.

**Comment by cchriste** [comment]
As we add use cases, it becomes more important to provide a summary of what is available (#1103).

**Comment by iyerkrithika21** [comment]
@akenmorris, the shared boundary use case has meshes and contours. Can we close this, or do we need a use case with all three domain types (mesh, images, and contours)?

**Comment by akenmorris** [comment]
We support all three, but I really don't think we need do demonstrate it.
