### ISSUE TITLE
Optimize shape model on multiple domains with shared boundaries

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#975]

**Comment by cchriste** [comment]
Can we do this already and only need a notebook and/or use case to demonstrate?

**Comment by cchriste** [comment]
> Can we do this already and only need a notebook and/or use case to demonstrate?

Looks like #976 is the use case, and this is the functionality.

**Comment by iyerkrithika21** [comment]
@akenmorris, can we consider this resolved?

**Comment by akenmorris** [comment]
Yep
