### ISSUE TITLE
DeepSSM in Studio

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#977]
Parent issue for including DeepSSM in Studio. 

- [x] Phase 1: Similar to current python deep_ssm use case, images are assumed to be pre-groomed, test shapes are optimized with training.

> - [x] #1371
> - [x] #1372
> - [x] #1373
> - [x] #1374
> - [x] #1375

- [x] Phase 1b: #1881 Integrating variants and loss that were worked on for the journal extension.

- [x] Phase 2: #1887 Image grooming within studio, test shapes are held out from optimization and optimized separately in a fixed domain model

- [x] Phase 3: True inference, new images are registered against groomed image model

**Comment by akenmorris** [comment]
Phase 1 is complete. Moving this issue to 6.3 for phase 2.

**Comment by jadie1** [comment]
Just updating the use case in 6.3, moving the next phase of DeepSSM in Studio to 6.4

**Comment by akenmorris** [comment]
Done #2181
