### ISSUE TITLE
Add mesh grooming to Studio

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#984]
Parent issue for adding mesh grooming tools to Studio.

Children issues thus far:
#922

**Comment by sheryjoe** [comment]
- Mesh fixes from FEMesh lib, expose individual ops, e.g. smoothing, decimation, fix winding
- remeshing from mmgtools (scale functions? for adaptive meshing especially with high curvature regions)
- fill holes
- center of mass alignment
- ICP alignment

**Comment by akenmorris** [comment]
@sheryjoe , what parameters to FEFixMesh should we expose in Studio?  Right now I just have a checkbox called "Quality Control" that uses whatever the defaults for Mesh::fix are:

  Mesh& fix(bool smoothBefore = true, bool smoothAfter = true, double lambda = 0.5, int iterations = 1, bool decimate = true, double percentage = 0.5);

**Comment by akenmorris** [comment]
See https://github.com/SCIInstitute/ShapeWorks/blob/c42e24ee262eda1af1c196f2b37ff7b76f48c3f6/Libs/Mesh/Mesh.cpp#L508

**Comment by akenmorris** [comment]
@sheryjoe , should these steps from PreviewQC be broken up into separate steps?  I'm not sure where this combined "fix" call came from.

**Comment by sheryjoe** [comment]
> @sheryjoe , should these steps from PreviewQC be broken up into separate steps? 

Yes.

> I'm not sure where this combined "fix" call came from.

I think this is the consolidation of the PreviewCmd command.

**Comment by akenmorris** [comment]
Ok, do we want to support smoothing both before and after decimation?

**Comment by sheryjoe** [comment]
@akenmorris should we push this issue to 6.2 as it is partially resolved?

**Comment by akenmorris** [comment]
Yes

**Comment by akenmorris** [comment]
Completed.
