### ISSUE TITLE
Docs: Illustration (flow chart) on how initialization and optimization is performed and related to params

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#987]

**Comment by sheryjoe** [comment]
@akenmorris @jadie1 We will need this for the workshop.

**Comment by sheryjoe** [comment]
@jadie1 is this resolved?

**Comment by jadie1** [comment]
Yes it has been added to optimize.md. There are some errors that have been fixed on the fix_docs branch which will be merged soon.
