### ISSUE TITLE
Docs: Intuition behind modes of variation

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#990]
Based on users comment: Develop intuition behind the parameters, modes of variation (tutorials on pca).

**Comment by sheryjoe** [comment]
@jadie1 is this resolved?

**Comment by jadie1** [comment]
@sheryjoe Can we push this one to the next release? There is already some info on this in worflows/analyze.md and I am not sure I'll have time.

**Comment by sheryjoe** [comment]
@jadie1 sounds good.

**Comment by jadie1** [comment]
@sheryjoe Could you give more detail on what we should add to the documentation for this?
