### ISSUE TITLE
Meshes in Studio: Option to convert segmentations to meshes for optimization

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#996]
Option to optimize particles directly on meshes or convert them to DTs (related also to exposing new groom features in Studio)

Bifurcated from #730

Alan:
I think this still requires more thought and design. How does this work as part of the grooming pipeline? When you convert meshes to images, do you then open up the rest of the image grooming pipeline? How is the spacing determined (user must supply?) What about the opposite (images -> meshes)?

**Comment by akenmorris** [comment]
Yes, so whether the user provides images or meshes, they could be given the option to run the optimizer in either mode.  The complexity is in the grooming pipeline.  Where do you switch?  If given images, you probably want to do hole filling and other operations before creating a mesh, but there is no reason to pad the image or create a distance transform.  You could smooth in either domain.

**Comment by sheryjoe** [comment]
As we discussed in an earlier dev meeting, it would be tricky grooming-wise to provide the flexibility of running the optimizer in either mode given meshes. This flexibility can be provided by python scripts and notebooks. One caveat would be if the user has segmentations and would like to run the optimizer on meshes in Studio. We could keep Studio simpler by sticking to user's input type (segmentations or meshes) and provide groom-optimize workflows accordingly. 

@akenmorris @jadie1 @riddhishb thoughts?

**Comment by sheryjoe** [comment]
- Given segmentations, add a final grooming step to allow optimization on meshes and expose relevant parameters for decimation ... etc
- Given meshes, add a final grooming step to convert to DT and expose relevant parameters
