### ISSUE TITLE
Check/tune mesh use case parameters based on rescaling the update vector

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#998]
Rescale update vector to original magnitude after projection to surface tangent #601
- [x] update parameters
- [x] update optimization model on the data portal

**Comment by akenmorris** [comment]
> update optimization model on the data portal

Are we making a new version or do we replace the one that's there?  @sheryjoe

**Comment by akenmorris** [comment]
femur parameters have been updated.  Ellipsoid_mesh and lumps look fine as is, no need to update.

**Comment by sheryjoe** [comment]
I would replace the models after QCing them.

**Comment by sheryjoe** [comment]
> femur parameters have been updated. Ellipsoid_mesh and lumps look fine as is, no need to update.

Although the parameters don't have to change, the models are changed due to this fix, right?

**Comment by akenmorris** [comment]
> Although the parameters don't have to change, the models are changed due to this fix, right?

Correct, they will be slightly different.

**Comment by sheryjoe** [comment]
> > Although the parameters don't have to change, the models are changed due to this fix, right?
> 
> Correct, they will be slightly different.

I would also upload the updated models for these datasets.

**Comment by sheryjoe** [comment]
Where are we on this issue?

**Comment by akenmorris** [comment]
Still need to re-run and upload the changed results.

**Comment by akenmorris** [comment]
New results are updated on the data portal.
